### ISSUE TITLE
When writing to a OCI dist-spec registry, shouldn't Content-Type=application/octet-stream be set?

### ISSUE THREAD

**Issue by rchincha** [google/go-containerregistry#1018]
https://github.com/google/go-containerregistry/blob/4cdd086967d44da4546642e5d81799c22e3dea0c/pkg/v1/remote/write.go#L353

https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-a-blob-in-chunks

**Comment by jonjohnsonjr** [comment]
Everything seems to work fine _without_ it, and there's no language that we _MUST_ include that header in the spec, it's just included in the examples. Registries generally just ignore the content-type, I think.

**Comment by rchincha** [comment]
Just FYI, this is different from what containers/image code does.
https://github.com/containers/image/blob/master/docker/docker_image_dest.go#L171

**Comment by jonjohnsonjr** [comment]
Thanks for the heads up. I think it would be reasonable to "fix", but I haven't encountered any problems with it personally. If we want to do something interesting with the `Content-Type` header, I can imagine updating the spec to include it, but there doesn't seem to be any utility in just verifying that it's set to `application/octet-stream`.
