### ISSUE TITLE
Make --insecure flag's behavior equal to  docker --insecure-registry flag.

### ISSUE THREAD

**Issue by ninehills** [google/go-containerregistry#1024]
Docker `--insecure-registry` flag can ignore TLS certificate validate error. 

This will be compatible with a private docker registry with a self sign certificate.

Dirty workaroud: https://github.com/ninehills/go-containerregistry/commit/c2d589a1f9b722149e552c8ea8caefd11e32ee3b

**Comment by jonjohnsonjr** [comment]
This is easy enough for the `crane` CLI -- we can just add a `crane.WithTransport` option based on the flag, around [here](https://github.com/google/go-containerregistry/blob/0233fcda5d536d4548d66e24829000e64a3e6059/cmd/crane/cmd/root.go#L72).

**Comment by Omar007** [comment]
Reference for the behaviour Docker implements can be found here: https://docs.docker.com/registry/insecure/

> With insecure registries enabled, Docker goes through the following steps:
> - First, try using HTTPS.
> - If HTTPS is available but the certificate is invalid, ignore the error about the certificate.
> - If HTTPS is not available, fall back to HTTP.
