### ISSUE TITLE
Just  verify if the layer  need push  to registry

### ISSUE THREAD

**Issue by hhstu** [google/go-containerregistry#1034]
there is no need to verify that the file in that layer exists in the tar file when  a layer in remote registry is exists.  

example: 
  An   java  image that include base image jre   and  a jar file ,  jre image has been exists in remote registry,. 
   I just  want to build a  tar file which manifest has all layers but  without jre  layer files , then push  to  the remote registry,

**Comment by imjasonh** [comment]
I'm not sure I understand the question or the request being made here. Can you give me more information about what you're trying to accomplish?

Pushing a `tarball.Image` to a remote registry with `remote.Write` is already pretty optimized to avoid pushing layers that are already present in the registry. If you're seeing unnecessary pushes, that could be a bug.

**Comment by jonjohnsonjr** [comment]
Do you need to have the tarball at all? What are you trying to do? With a lot of operations, we can skip any work that isn't necessary.

For example, with `crane copy`, we do existence checks on blobs in a destination registry before even downloading them from the source registry. If you're serializing an image to a tarball, we don't know what which layers you'll need later, so we can't skip downloading any of them.

We _have_ talked about adding some mechanism for writing "sparse" tarballs that omit certain layers, e.g. https://github.com/google/go-containerregistry/pull/559/files#diff-69edbea8617f01694b09c8e0a51e75dd806ba9aaad93d72dbc6d16fd9a92636a

This issue has some involved discussion that's somewhat related: https://github.com/google/go-containerregistry/issues/651

I'm ok with adding some way to check if a blob exists (I want to implement this for something like `crane stat`), but I'm not sure if it would be the best solution to your problem.
