### ISSUE TITLE
crane copy hangs indefinitely/does not copy tags with Azure Container Registry

### ISSUE THREAD

**Issue by michaelperel** [google/go-containerregistry#1053]
When using `crane copy` with a Dockerhub account, it succeeds quickly as in:

`crane copy node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 mydockerhubaccount/node:14`

or 

`crane copy node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 mydockerhubaccount/node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523`

However, when using Azure Container Registry (ACR) for some images `crane copy` hangs indefinitely:

`crane copy node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 myaccount.azurecr.io/node:14`

And if using the full digest in the destination image, if it succeeds, does not push the tag:

`crane copy node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 myaccount.azurecr.io/node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523`

Any thoughts as to why it may behave this way?

I am trying to use `crane.Copy` to implement [this feature](https://github.com/safe-waters/docker-lock/issues/104) in one of my projects, but am unsure if other registries may behave similarly.

**Comment by jonjohnsonjr** [comment]
> Any thoughts as to why it may behave this way?

The hanging indefinitely is really bizarre. I would not expect that at all. You can do `crane cp -v ...` to dump a bunch of debug information about the requests, which would certainly be helpful for debugging. I don't have an azure account or I would try to debug this myself.

Two unlikely ideas:
1. Something to do with [tag locking](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock#lock-an-image-by-tag)?
2. Something with auth is sending us in a re-auth loop?

> does not push the tag

This one I'd maybe consider a bug/FR on our side: https://github.com/google/go-containerregistry/issues/702

**Comment by michaelperel** [comment]
@jonjohnsonjr I am not sure I can post the entire logs, as I don't know if it contains any secrets. But when using ACR, the last line that indefinitely hangs (for any image), is a PATCH that roughly looks like:

```
2021/06/16 16:57:26 --> PATCH <I OBSCURED THIS OUTPUT>
2021/06/16 16:57:26 PATCH /v2/erlang/blobs/uploads/<I OBSCURED THIS OUTPUT>
Host: <MYACCOUNT>.azurecr.io
User-Agent: crane/v0.5.1 go-containerregistry/v0.5.1
Transfer-Encoding: chunked
Authorization: <redacted>
Accept-Encoding: gzip
```

Let me know if you need more output, or it is safe to post it.

This is the command that generated this particular output, but I tried many different variations (including the digest, not including the digest, etc.):

`crane copy -v erlang:latest@sha256:42111b334dd1d2c885706bc2ed3574a2364a982dd04b7ba211907d288c3909d1 myaccount.azurecr.io/erlang:latest`

As for:
> 1. Something to do with tag locking?

I am not using tag locking.

> 2. Something with auth is sending us in a re-auth loop?

Nothing in the logs seems to indicate this, but I have not dug into crane's code to investigate it further.

Would you be open to making a free trial of an Azure account and giving it a try?

**Comment by jonjohnsonjr** [comment]
> Would you be open to making a free trial of an Azure account and giving it a try?

Seems to work for me:

```
$ time crane copy node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab83
34b0657f923092523 <redacted>.azurecr.io/node:14
2021/06/16 14:41:39 Copying from node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 to <redacted>.azurecr.io/node:14
2021/06/16 14:41:42 pushed blob: sha256:787f5e2f10471c11a2064774062aeeb400f76e9eef1ca768156a23678f005f3e
2021/06/16 14:41:42 pushed blob: sha256:7b6173a10eb81a318ed53df74c8b80d29656f68194682e51f46f9b7b24c6ba03
2021/06/16 14:41:43 pushed blob: sha256:bd821d20ef8c23c1c474d4b014889cfd2fcffb063a86dea8769347a630d0d558
2021/06/16 14:41:44 pushed blob: sha256:bfde2ec33fbca3c74c6e91bca3fbcb22ed2972671d49a1accb7089c9473cac12
2021/06/16 14:41:44 pushed blob: sha256:809893a7b9acd18499eb54db93a0e5f3732032150a9fc530409ac50bd65a8a50
2021/06/16 14:41:44 pushed blob: sha256:dc05be471d511acb4574f2f3630582527220c59d0abf0b8b905769916b550da7
2021/06/16 14:41:45 pushed blob: sha256:9e84a31df1a67fa41d74870e848e07fc5ebb02438edc5ce134ab602825239140
2021/06/16 14:41:45 pushed blob: sha256:fb63ab1f1488054c8a6840616c740ec865a48e0a2b3e197bfc2cadbea8ae75b4
2021/06/16 14:41:54 pushed blob: sha256:55fab5cadd3cc0fb680b701177abf2c36dde0de9f1e3f3b233aab8ba622c4d48
2021/06/16 14:41:55 pushed blob: sha256:c47df8afdb4a38dc29d187c4ed2def96ef46a01a650a767c5aa927a5b9a8f3b9
2021/06/16 14:41:55 <redacted>.azurecr.io/node@sha256:2472a3ceccbab5dfee5b6dc50db0be9fb53b0d035864a66f920488227c45cec4: digest: sha256:2472a3ceccbab5dfee5b6dc50db0be9fb53b0d035864a66f920488227c45cec4 size: 2215
2021/06/16 14:41:57 pushed blob: sha256:6ba756a0ca8996787a145d62543ecf7cec523a638705be132f442d2013655149
2021/06/16 14:41:57 pushed blob: sha256:c61945aef6a8fee06fbe4dccead7cbad9da46ba174cee1eae1f813541ddb76b3
2021/06/16 14:41:57 pushed blob: sha256:a31433848e31af05adc5d08b320578e9a0f2fbcc8d1b9ab67c326ef2e7211d2d
2021/06/16 14:41:59 pushed blob: sha256:7c0fb436eb37d865367986469e3988dc05d2363e227f4a87a733cd9c8bac9d02
2021/06/16 14:41:59 pushed blob: sha256:55b9a6b6b2552c5b2eac0a316e75a7bc18092819ee25c4f1d4d54700bcc1d3dc
2021/06/16 14:42:00 pushed blob: sha256:162a8647c8edf7ff80c3708fa5c46d2fad67bad6a2af29e47f2803d048ce142f
2021/06/16 14:42:00 pushed blob: sha256:996fa2ea3ee24e2c8795432a6a96563f170c367d41c428e06fa4f6735e25c35a
2021/06/16 14:42:01 pushed blob: sha256:0ad0df1f1fa0c631401a3729be99927a3afcaa022e4dd89e0acc026805d6fd2d
2021/06/16 14:42:06 pushed blob: sha256:6ffd0715a9f0618d8a935a052bf0586f2cb1f1455811d818f4a1dd805cd36660
2021/06/16 14:42:06 pushed blob: sha256:4c7a89c22b7204c6844b6bbae31081aec44858bcbc55842b35f7c227f19c7ccb
2021/06/16 14:42:06 <redacted>.azurecr.io/node@sha256:907d755170b7cbe9143d10510481629467821f2598a4ba015f4c17ae1da9b8da: digest: sha256:907d755170b7cbe9143d10510481629467821f2598a4ba015f4c17ae1da9b8da size: 2214
2021/06/16 14:42:08 pushed blob: sha256:b7c0a158e8c10a9879f2c775b2d7a4483d25019616d9391af775249d584b41e8
2021/06/16 14:42:09 pushed blob: sha256:41f38ce3010a5142300d74e5e19db4dea7694f4771471c330fff27c633f8ba32
2021/06/16 14:42:10 pushed blob: sha256:d82fbf846f6fdcc504df83891d0f286583888d4c91c733ee2395a16ff234988d
2021/06/16 14:42:10 pushed blob: sha256:ce440adabe2a1239387777b4e56ce06814fe9b17d519fc476a46594611db4f32
2021/06/16 14:42:10 pushed blob: sha256:1ce0b6aec0ac54a348a544e907fb5ad05379872104ad82cdbb3ffac5af27ce3b
2021/06/16 14:42:10 pushed blob: sha256:4c12508c6bbd70d5ad25a4b072cda7dd714d91d928406523c4d995aaa176778c
2021/06/16 14:42:10 pushed blob: sha256:0b7ba67728992b93a372d6ca58c67dbf79cbbb7d3c9a510835edeb9fcec609b3
2021/06/16 14:42:15 pushed blob: sha256:6f6e6a02baabe0cbf32c994495d1577fc0193f69c3df1c9657367f0f2e365dd7
2021/06/16 14:42:18 pushed blob: sha256:c190b75eb2b4877064de73bec4c24d0c1a4763b176409eb5121609793112ba9b
2021/06/16 14:42:18 pushed blob: sha256:6ce0ac4e4700143a2bc2a43d61af9585771d30ad9a7957fcab513436941b0778
2021/06/16 14:42:19 <redacted>.azurecr.io/node@sha256:d7f0825bc32d49c1c61c8666f1cd0d366e45e94045f2c3db0af58d56d040c62f: digest: sha256:d7f0825bc32d49c1c61c8666f1cd0d366e45e94045f2c3db0af58d56d040c62f size: 2215
2021/06/16 14:42:19 <redacted>.azurecr.io/node:14: digest: sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 size: 776

real    0m39.444s
user    0m12.539s
sys     0m8.459s
```

**Comment by jonjohnsonjr** [comment]
Possibly something to do with service tiers rate limiting you?

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus#service-tier-features-and-limits

```
$ crane manifest node:14@sha256:52fe2e3604ca3d7d0bc017c0d60df5baaf54c3e261bab8334b0657f923092523 | jq .manifests[].digest -r | xargs -I{} crane manifest node@{} | jq .layers[].size | awk '{sum+=$0} END{print sum}'
1039717465
```

Copying all those images is ~1GB...

For basic tier:
1 GB / 10 Mbps = 13 minutes 20s

How long is "indefinitely"?

You might also be limited based on Write Ops per minute? Each of those has 10 layers, so I could see possibly hitting that if you count each "write" request as a separate Write Op, but probably not...

**Comment by michaelperel** [comment]
Thank you so much for trying it out.

For the issue of hanging indefinitely, I am really sorry to send you down that rabbit hole. I am on vacation and realized that after ~500mb of upload to one registry, my ISP throttled me (despite not throttling uploads to other sites as running a speedtest shows fast upload speeds).

Testing it on a VM, it works perfectly.

As for tags not pushing, to be clear:

`crane copy busybox:stable@sha256:930490f97e5b921535c153e0e7110d251134cc4b72bbb8133c6a5065cc68580d myaccount.azurecr.io/busybox:stable`

works.

`crane copy busybox:stable@sha256:930490f97e5b921535c153e0e7110d251134cc4b72bbb8133c6a5065cc68580d myaccount.azurecr.io/busybox:stable@sha256:930490f97e5b921535c153e0e7110d251134cc4b72bbb8133c6a5065cc68580d`

does not push the tag. It does still allow you to pull the image by digest, just not by tag.

You have referenced this in another issue, so I am not reporting anything you are unaware of.

Since the first command works, that is good enough for me. I think it would be appropriate to close the issue, and I really appreciate your time.

**Comment by jonjohnsonjr** [comment]
> I am really sorry to send you down that rabbit hole

No problem at all, I certainly learned a few things.

> You have referenced this in another issue, so I am not reporting anything you are unaware of.
>
> Since the first command works, that is good enough for me. I think it would be appropriate to close the issue, and I really appreciate your time.

Sounds good to me! If you think the tag thing is a blocker for https://github.com/safe-waters/docker-lock/issues/104, feel free to pile onto that issue. If a bug on our side is blocking my feature request, I feel obligated to fix it :P
