### ISSUE TITLE
Unable to Login / push tar to https private registry

### ISSUE THREAD

**Issue by SanadhyaLakshya** [google/go-containerregistry#1064]
I am Beginner to the crane can someone give me the command how to use the --insecure command to use to push a tar file to insecure docker registry, or what will be the basic command

1.  While pushing the tar to the registry the error comes
     400 Bad Request: The plain HTTP request was sent to HTTPS port
     sample command used : crane push  '/root/alpine.tar'  '10.31.20.4:9444/alpine'
     Is there is any way to use like this -> 'https://10.31.20.4:9444/alpine' pls suggest

or how to use the --insecure flag with push command to skip the ssl certificate 

2. Same in case of crane auth login , how to authenticate the https registry.
    Sample used : crane auth login https://10.31.20.4:9444 -u user -p pass
    Error comes : Error: registries must be valid RFC 3986 URI authorities

**Comment by jonjohnsonjr** [comment]
> the error comes 400 Bad Request

Can you use `crane push -v ...` and figure out which request is failing with 400?

For the second question, does this work?

```
crane auth login 10.31.20.4:9444 -u user -p pass
```
