### ISSUE TITLE
How to set SSL_CERT_DIR and  SSL_CERT_FILE  with crane command in crane push.

### ISSUE THREAD

**Issue by SanadhyaLakshya** [google/go-containerregistry#1066]

**Comment by imjasonh** [comment]
Based on [these docs](https://golang.org/pkg/crypto/x509/#SystemCertPool), it sounds like you can set these environment variables directly, though I've never tested it. What behavior are you seeing when you try it?

```
SSL_CERT_DIR=/path/to/certs crane push some.tar some/image
```

**Comment by SanadhyaLakshya** [comment]
Yeah thanks the above command worked for me..
