### ISSUE TITLE
Documentation: Add published images in README

### ISSUE THREAD

**Issue by zhouhaibing089** [google/go-containerregistry#1068]
I was looking at how to build crane as a tekton task, and it took me a while to figure out whether there is an officially published image for crane. I find a pointer from this thread - https://github.com/google/go-containerregistry/issues/598#issuecomment-547075025, and then tried to search `gcr.io/go-containerregistry` in this repo, and realized there is a [cloudbuild.yaml][1].

My suggestion is, if this image can be explicitly documented in README or on each release page, that would make it more discoverable. I'd be happy to help, by the way. Thanks~

[1]: https://github.com/google/go-containerregistry/blob/main/cloudbuild.yaml

**Comment by imjasonh** [comment]
We have https://github.com/google/go-containerregistry/tree/main/cmd/crane#images today, but I agree we could probably advertise this (and `crane`/`gcrane` in general) better in the top-level README.md

**Comment by zhouhaibing089** [comment]
Oh, I missed the link you pasted. Do you think release page is a better place - something like [kubernetes/git-sync releases][1] ?

[1]: https://github.com/kubernetes/git-sync/releases/tag/v3.3.3

**Comment by imjasonh** [comment]
Yeah, we could link the image from our [releases](https://github.com/google/go-containerregistry/releases/tag/v0.5.1) too, possibly even [built using goreleaser](https://goreleaser.com/customization/docker/), though that requires a Dockerfile, and `crane`'s image is currently built using [`ko`](https://github.com/google/ko).

It looks like we can also [configure goreleaser to add links to the image in the release notes](https://goreleaser.com/customization/release/), which could be nice.
