### ISSUE TITLE
install crane on ubuntu

### ISSUE THREAD

**Issue by vickeyrihal1** [google/go-containerregistry#1071]
We are looking to install crane on an ubuntu docker container. Could you help us with the steps to install the particular binary only? 

"go get" is not working out for me due to its building time and other hassles. We just want a binary that either be get using "apt-get install" or downloadable from some public storage.

Appreciate your help.

**Comment by imjasonh** [comment]
You can find pre-built binaries for Linux in the releases: https://github.com/google/go-containerregistry/releases
