### ISSUE TITLE
cannot fetch go registry in bazel repo

### ISSUE THREAD

**Issue by kunal-rp** [google/go-containerregistry#1074]
Suddenly unable to build repo due  to Http Exception when fetching for go registry images : 

 `WARNING: Download from https://api.github.com/repos/google/go-containerregistry/tarball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 44ab9b4a959950922ca11f9fe511010f649c2af034dace12da37a33a4fae3ded but wanted 3a5f9ff61b48b928ce37e9d227a581571957b3b3ad5d45d148bce5433f9c9a6c
ERROR: An error occurred during the fetch of repository 'com_github_google_go_containerregistry':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/bazel_gazelle/internal/go_repository.bzl", line 31, column 33, in _go_repository_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://api.github.com/repos/google/go-containerregistry/tarball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb] to /private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/com_github_google_go_containerregistry/temp1878119429892939480/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.tar.gz: Checksum was 44ab9b4a959950922ca11f9fe511010f649c2af034dace12da37a33a4fae3ded but wanted 3a5f9ff61b48b928ce37e9d227a581571957b3b3ad5d45d148bce5433f9c9a6c
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/bazel_gazelle/internal/go_repository.bzl", line 31, column 33, in _go_repository_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://api.github.com/repos/google/go-containerregistry/tarball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb] to /private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/com_github_google_go_containerregistry/temp1878119429892939480/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.tar.gz: Checksum was 44ab9b4a959950922ca11f9fe511010f649c2af034dace12da37a33a4fae3ded but wanted 3a5f9ff61b48b928ce37e9d227a581571957b3b3ad5d45d148bce5433f9c9a6c
ERROR: /private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/io_bazel_rules_docker/container/go/pkg/oci/BUILD:18:11: @io_bazel_rules_docker//container/go/pkg/oci:go_default_library depends on @com_github_google_go_containerregistry//pkg/v1/layout:go_default_library in repository @com_github_google_go_containerregistry which failed to fetch. no such package '@com_github_google_go_containerregistry//pkg/v1/layout': java.io.IOException: Error downloading [https://api.github.com/repos/google/go-containerregistry/tarball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb] to /private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/com_github_google_go_containerregistry/temp1878119429892939480/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.tar.gz: Checksum was 44ab9b4a959950922ca11f9fe511010f649c2af034dace12da37a33a4fae3ded but wanted 3a5f9ff61b48b928ce37e9d227a581571957b3b3ad5d45d148bce5433f9c9a6c
DEBUG: Rule 'nginx_base' indicated that a canonical reproducible form can be obtained by modifying arguments digest = "sha256:2e76f4d4e21bae1d012267cff67e032bb006a2cff5c00afa5d4ad011c1855128"
DEBUG: Repository nginx_base instantiated at:
  /Users/kunal/Desktop/Coding/slot/WORKSPACE:171:15: in <toplevel>
Repository rule container_pull defined at:
  /private/var/tmp/_bazel_kunal/7f05ac5fbb332b788011f82724633b02/external/io_bazel_rules_docker/container/pull.bzl:225:33: in <toplevel>
ERROR: Analysis of target '//frontend/app:prod_image' failed; build aborted: Analysis failed
`

**Comment by kunal-rp** [comment]
Docker workspace setup : 

`http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "1698624e878b0607052ae6131aa216d45ebb63871ec497f26c67455b34119c80",
    strip_prefix = "rules_docker-0.15.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.15.0/rules_docker-v0.15.0.tar.gz"],
)
load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps()

load(
    "@io_bazel_rules_docker//java:image.bzl",
    _java_image_repos = "repositories",
)
_java_image_repos()

load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure="toolchain_configure"
)`

**Comment by imjasonh** [comment]
I'm pretty sure this will be fixed by upgrading to the latest rules_docker.

More info: https://github.com/google/go-containerregistry/issues/997
