### ISSUE TITLE
Question about resolving the default keychain

### ISSUE THREAD

**Issue by yaelharel** [google/go-containerregistry#1078]
Our project was reported that we have the following bug: https://github.com/buildpacks/lifecycle/issues/651.
We think that while resolving the `defaultKeychain` https://github.com/google/go-containerregistry/blob/b448abac9a7021605f2142ed6e04daa61c769324/pkg/authn/keychain.go#L62 either the `Username` or the `Password` are set to an empty string in some scenarios although they were set to something else as part of the following command:
```
export TOKEN=$(az acr login --name project --expose-token --output tsv --query accessToken --resource-group ProjectNameRG)
docker login reponame.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password $TOKEN
```
Can such thing happen?
Does it make sense that `00000000-0000-0000-0000-000000000000` is being translated to an empty string?
Or maybe the value of the token is set to be the `IdentityToken` (that we’re currently not checking in our code https://github.com/buildpacks/lifecycle/blob/f15f80c6731ca9b01545eb8234281a105d3f4577/auth/env_keychain.go#L143-L159)?

**Comment by jonjohnsonjr** [comment]
This feels weird to me...

```
docker login reponame.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password $TOKEN
```

Usually an IdentityToken uses the `<token>` username:
* https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/config/credentials/native_store.go#L11
* https://github.com/Azure/acr-docker-credential-helper/blob/a79b541f3ee761f6cc4511863ed41fb038c19464/src/docker-credential-acr/program.go#L24

However, depending on what their docker config file looks like, there might be a credential helper doing something fishy, e.g. maybe ACR knows how to interpret that username in a special way to translate the password to an identity token?

Using an identity token drops you into the oauth flow: https://github.com/google/go-containerregistry/blob/03f1bf46bab527b80f3b32fba78b7a7ac0b0bc42/pkg/v1/remote/transport/bearer.go#L138-L147

Not sure if this is helpful, but it's hard for me to really trace what's going on.

**Comment by yaelharel** [comment]
@jonjohnsonjr, thank you for your response!
We found https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#az-acr-login-with---expose-token that describes the flow of the `docker login` scenario.
Does it help in any way?

**Comment by jonjohnsonjr** [comment]
I'm still not entirely sure how this works from the buildpacks side (why do you pull headers+creds from the env?), but I've traced the docker code to figure out what's going on. It's pretty complex, but the interesting bit:

The `docker login` code hits the registry with basic creds to make sure they work.

Usually, this returns an `{"access_token":"..."}` object, and the creds are persisted in the config file as basic.

However, it seems like when you `docker login` with this magic username, it also returns a `refresh_token`, e.g. `{"access_token":"...","refresh_token":"<long identity token>"}`.

This gets "stored" as a refresh token, which is persisted as an `identitytoken` in the config file, which tells us to drop into the oauth flow: https://github.com/google/go-containerregistry/blob/main/pkg/authn/README.md#oauth-2

Hope that helps.

**Comment by jonjohnsonjr** [comment]
I drew some stuff.

Here's normal login flow:

![image](https://user-images.githubusercontent.com/17863526/125677422-d3204261-e67e-449d-a20e-3a79581acafe.png)

Here's the oauth login flow you're hitting:

![image](https://user-images.githubusercontent.com/17863526/125677478-2178e437-0a2a-4c09-9fd4-edaa8f8179df.png)

**Comment by yaelharel** [comment]
@jonjohnsonjr, this helps a lot! Thank you very much!
