### ISSUE TITLE
Not able to use with AWS Public ECR

### ISSUE THREAD

**Issue by ngoyal16** [google/go-containerregistry#1085]
not able to use with AWS Public ECR

we are tring to copy contect from one debug ecr repo to main ecr repo but while doing ls on public.ecr.aws images it giving 404

**Comment by jonjohnsonjr** [comment]
Looks like public ECR doesn't implement tag listing: https://github.com/aws/containers-roadmap/issues/1262

**Comment by smoke** [comment]
I believe this is still an issue, regardless it depends on other party.
