### ISSUE TITLE
Pulling GCR images (using Golang) using service account credentials

### ISSUE THREAD

**Issue by arnav1408** [google/go-containerregistry#1087]
Can someone help me in establishing this task?
I am looking to use gcrane to pull GCR images via Golang using Gcloud service account credentials.

**Comment by jonjohnsonjr** [comment]
There are a handful of ways to do this. What do you need to do with the image after you've pulled it?

In the [google](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/google) package, there are a bunch of authentication mechanisms. I need to document this better, but a brief description:

`google.Keychain` will first attempt to find [application default credentials](https://cloud.google.com/docs/authentication/production#automatically) (ADC), and fall back to shelling out to `gcloud` to get an access token if it can't find any ADC. You would use that like this:

```
func main() {
        ref := "gcr.io/<my-project>/<my-image>:<tag>"
	img, err := crane.Pull(ref, crane.WithAuthFromKeychain(google.Keychain))
	if err != nil {
		panic(err)
	}
        if err := crane.Save(img, ref, "/some-path/image.tar); err != nil {
		panic(err)
        }
}
```

If you have a JSON key, you can use [`google.NewJSONKeyAuthenticator`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/google#NewJSONKeyAuthenticator):

```
img, err := crane.Pull(ref, crane.WithAuth(google.NewJSONKeyAuthenticator(key)))
```

But that's generally not the best option if you don't want to transmit keys over the internet. I'd recommend using [`google.NewTokenSourceAuthenticator`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/google#NewTokenSourceAuthenticator) and pairing that with an `oauth2.TokenSource` that you construct yourself.

```
ts : getTokenSource()
img, err := crane.Pull(ref, crane.WithAuth(google.NewTokenSourceAuthenticator(ts)))
```

There are a handful of ways to obtain a TokenSource: https://pkg.go.dev/golang.org/x/oauth2/google

If you want to impersonate a service account, look at this package for another way to get a TokenSource: https://pkg.go.dev/google.golang.org/api@v0.51.0/impersonate

**Comment by arnav1408** [comment]
Thanks for the response.
I need to tag it and push it back to GCR.
Could you specifically elaborate on the way where we can use service account credentials to accomplish this task and what would be the golang code for that?

**Comment by jonjohnsonjr** [comment]
How are you accessing the service account credentials? Did you download a JSON key or do you want to impersonate them using some other credentials? Are you running this in an environment where you can control the application default credentials?

**Comment by arnav1408** [comment]
I'm working in a company which is providing me these credentials.

**Comment by jonjohnsonjr** [comment]
Assuming you have the service account credentials in JSON key form, this should work:

```go
func main() {
        ref := "gcr.io/my-project/my-image:v7"
        newTag := "v8"
        jsonKey := "{...}"

	img, err := crane.Tag(ref, newTag, crane.WithAuth(google.NewJSONKeyAuthenticator(jsonKey)))
	if err != nil {
		log.Fatal(err)
	}
}
```

However, you don't want to just embed credentials in your code. There are a number of ways to avoid doing that:
* https://cloud.google.com/docs/authentication/production#best_practices
* https://cloud.google.com/iam/docs/best-practices-for-using-and-managing-service-accounts#using_service_accounts
* https://cloud.google.com/iam/docs/best-practices-for-securing-service-accounts#service-account-keys
* https://cloud.google.com/iam/docs/impersonating-service-accounts#attaching-new-resource

Without knowing more about the environment this code will be running or how you generally manage credentials, it's hard to recommend a specific course of action.

**Comment by arnav1408** [comment]
Thanks for responding
