### ISSUE TITLE
User-Agent is still set to "go-containerregistry" in override transport

### ISSUE THREAD

**Issue by dlegs** [google/go-containerregistry#1107]
I have a use-case where a custom, predefined user-agent header has to be used when pulling container images, and it looks like the user-agent string is still set to "go-containerregistry" after using `options.WithTransport()` to override the default `http.RoundTripper` transport.

It looks like unless the override transport [can be cast](https://github.com/google/go-containerregistry/blob/f9a1886f3df0e2b00d6c62715114fe1093ab1ad7/pkg/v1/remote/transport/transport.go#L58-L61) to `transport.userAgentTransport`, [a new wrapped transport is created](https://github.com/google/go-containerregistry/blob/f9a1886f3df0e2b00d6c62715114fe1093ab1ad7/pkg/v1/remote/transport/useragent.go#L80) with the "go-containerregistry" user-agent.

I solved this issue by copying the private `transport.userAgentTransport` struct and wrapping my override transport and user-agent in that so it can be cast, but others could find themselves with the same issue!

**Comment by imjasonh** [comment]
Can you use `remote.WithUserAgent` instead? https://pkg.go.dev/github.com/google/go-containerregistry@v0.6.0/pkg/v1/remote#WithUserAgent

We could probably do a better job of documenting who wins when WithTransport sets useragent.

**Comment by jonjohnsonjr** [comment]
This is one reason I would like to revisit the transport wrapping stuff: https://github.com/google/go-containerregistry/pull/1122#issuecomment-916220715
