### ISSUE TITLE
Support crane push tarBall contains more than one image?

### ISSUE THREAD

**Issue by dashjay** [google/go-containerregistry#1109]
when I push a tarball with only one image in it, crane works very well, but when I push a tarball contains more than one image,
error throw out.
```
crane push /tmp/bundle.tar docker-registry.com
Error: loading /tmp/bundle.tar as tarball: tarball must contain only a single image to be used with tarball.Image
exit status 1
```
Instead, pull can work for more than one image with `crane pull image:tag image2:tag ... /tmp/bundle.tar`

I don't know if there is any other considerations that block this.

**Comment by jonjohnsonjr** [comment]
We're missing some library functionality that would make this a lot easier to implement.

Right now we have [`tarball.Write`](https://github.com/google/go-containerregistry/blob/de8aff85c9090d37ed6fe436d696f3a820e5c767/pkg/v1/tarball/write.go#L68) and its dual [`tarball.Image`](https://github.com/google/go-containerregistry/blob/de8aff85c9090d37ed6fe436d696f3a820e5c767/pkg/v1/tarball/image.go#L90).

We also have [`tarball.MultiWrite`](https://github.com/google/go-containerregistry/blob/de8aff85c9090d37ed6fe436d696f3a820e5c767/pkg/v1/tarball/write.go#L77) that writes multiple images into a tarball, but we _don't_ have anything that reads multiple images from a tarball.

I think I'd like to see something like `tarball.Images` that returns a `map[name.Reference]v1.Image`.

You _can_ hack around this with [`tarball.LoadManifest`](https://github.com/google/go-containerregistry/blob/de8aff85c9090d37ed6fe436d696f3a820e5c767/pkg/v1/tarball/image.go#L74) but that's not nearly as nice.

**Comment by dashjay** [comment]
Due to urgent needs, I wrote one version with registry v2 http last week 😄 . Now I am trying to rewrite it with internal pkg and struct, maybe I will make pr soon if I made it.

**Comment by afbjorklund** [comment]
We had a lot of historical problems, when using `podman` to load tarballs wtih multiple images.

These should all be solved now (podman3), but decided to stick with one image per tarball....
(the workaround was to pre-load all the images, and then save the entire `/var` as a snapshot)

If I recall correctly, there was no support in OCI for having multiple images per archive ?

**Comment by jonjohnsonjr** [comment]
> If I recall correctly, there was no support in OCI for having multiple images per archive ?

The [OCI Image Layout](https://github.com/opencontainers/image-spec/blob/main/image-layout.md) can support multiple images in a single archive. The `index.json` file contains an index pointing to each one.

**Comment by afbjorklund** [comment]
Maybe it was just the implementation of it then... (in podman, that was)

**Comment by dashjay** [comment]
I don't understand that why function [remote.MultiWrite](https://github.com/google/go-containerregistry/blob/de8aff85c9090d37ed6fe436d696f3a820e5c767/pkg/v1/remote/multi_write.go#L44) says that all refs must share the same repository. I can not understand it...

**Comment by jonjohnsonjr** [comment]
> I don't understand that why function remote.MultiWrite says that all refs must share the same repository. I can not understand it...

It's a limitation of the current implementation. Currently, we assume all the operations happen within a single repository because authentication is scoped to a single repository. We don't have any way to track requests and auth across multiple repositories (currently). This could easily be fixed.

**Comment by weakpixel** [comment]
Example to push a multi image tar file to a repository: [push-docker-multi-image-tar.go](https://gist.github.com/weakpixel/b9d3ddf25e52e88ed5608a1f30bd87db)

```
docker save alpine busybox > ./images.tar 
go run push-docker-multi-image-tar.go ./images.tar https://localhost:5000
```

Works for me with tars created with docker version 20.10.17
