### ISSUE TITLE
Crane operations on Windows containers

### ISSUE THREAD

**Issue by imjasonh** [google/go-containerregistry#1111]
Layers in Windows containers have an...odd... format, as discovered when [building Windows support for `ko`](https://github.com/google/ko/pull/374). It might be helpful to package this knowledge into ggcr and/or `crane`, so fewer folks have to deal with it.

For example: layers must have a `Hives/` top-level directory (which can be empty), and all file contents must be in the `Files/` top-level directory. `/` is still accepted as a file separator. There's a mysterious `PAXHeader` value that's needed for any tar entries that need to be executable.

Off the top of my head, `crane append` could Windows-ify the layer contents if `--platform=windows/*`. We might want to make Windowsification some kind of ggcr/`crane` method or option.

**Comment by jonjohnsonjr** [comment]
> We might want to make Windowsification some kind of ggcr/crane method or option.

I like this idea a lot.

**Comment by imjasonh** [comment]
`func Windowsify(in v1.Layer) v1.Layer` returns a layer that reads from the `in` layer and inserts and entry for `Hives/`, and prepends `Files/` to all other paths, and sets the `PAXHeader` value.

If `Digest`/`DiffID`/`Size` are called on it, it could generate and buffer the layer contents instead of failing like `stream.Layer` does.

**Comment by jonjohnsonjr** [comment]
> If Digest/DiffID/Size are called on it, it could generate and buffer the layer contents instead of failing like stream.Layer does.

I think we'd want both?

**Comment by adamrehn** [comment]
@imjasonh would you like any assistance with this? Now that the OS version selection support added by @phillipsj in #1173 has been merged, this appears to be the biggest remaining blocker standing in the way of using `crane append` and `crane mutate` to act as an equivalent to `ko publish` for non-Go applications in automation pipelines running under Kubernetes.

(Motivating example: being able to build a Windows executable and package it into a container image inside a Tekton task, without needing to resort to using a [Windows HostProcess container](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/) so hcsshim can communicate with the underlying host node's HCS.)

**Comment by phillipsj** [comment]
I have been working on doing this very thing already following along with what KO is doing. Happy to assist with this too.

**Comment by imjasonh** [comment]
> (Motivating example: being able to build a Windows executable and package it into a container image inside a Tekton task, without needing to resort to using a [Windows HostProcess container](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/) so hcsshim can communicate with the underlying host node's HCS.)

I am _very_ interested in this. I could use this to make a multi-OS [`deno-image`](https://github.com/imjasonh/deno-image) demo. Let's do this.

If either of you want to take a stab at `mutate.Windowsify` (naming tbd but don't let it block you) that could be useful as a start. A goal there could be having `ko` not have a bunch of `if platform == "windows"` checks everywhere, and just have one.

Let me know if you'd like any help, or if you'd like to meet to talk through what it'll take. Simplifying `ko` and codifying this behavior in one place would be great.

Other questions:
- I wonder whether we want `crane export` to detect that it's pulling a Windows image from a non-Windows environment, and un-Windowsify it by default. Maybe this could be a flag? Is that something anybody would want?

**Comment by imjasonh** [comment]
Also, there might be some overlap with https://github.com/google/go-containerregistry/issues/1168 if we want this to be lazy and only windowsify on its way to being read.

The `func(tar.Header) (tar.Header, error)` paradigm could be useful for prepending `Files/` to directories and setting the `PAXHeader`, but we'd need something else to be able to inject the empty `Hives/` directory.

**Comment by phillipsj** [comment]
I am up for meeting at discuss it. We are currently using crane to pull and
export windows images on a Linux build agent to create airgap packages so I
would definitely want any behavior change there to be opt-in.

If this was added to crane then our reliance on anything other than crane
for creating containers would be greatly reduced.

**Comment by adamrehn** [comment]
@imjasonh @phillipsj I'm in a pretty different timezone to you (Australia vs. the US) so if you're keen for a meeting then it might be simpler for the two of you to schedule a chat together without me and then post some notes here with the actionables for going forward?

**Comment by imjasonh** [comment]
Fixed by #1179 

Further improvements happening in #1194 FYI
