### ISSUE TITLE
Change logic around whether an error is 'Temporary'

### ISSUE THREAD

**Issue by DennisDenuto** [google/go-containerregistry#1113]
Currently, if an [actionable error](https://github.com/distribution/distribution/blob/main/docs/spec/api.md#errors)  is returned by the registry, that will determine whether to retry (and takes precedence over the http status code returned). See https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/transport/error.go#L91 for the code logic i’m talking about.

We have encountered a scenario where a registry (flakey) sometimes returns a `500` status code error, *and* also returns an actionable error of `UNKNOWN`

```
{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
```

This results in gcr *not* retrying. (However, retrying in this case *would* have succeeded)

Reading the [distribution spec](https://github.com/distribution/distribution/blob/main/docs/spec/api.md#errors), it sounds like actionable errors should be produced by status codes of `4xx`. 

If the above is true, what are your thoughts on instead retrying based on the http status code (even if an actionable error was provided) if the http status code is *not* `4xx`?

i.e. change the condition to be this:

```
 if (e.StatusCode < http.StatusBadRequest || e.StatusCode >= http.StatusInternalServerError) || len(e.Errors) == 0
```

Or, allowing the consumer of the library the ability to configure the conditions which mark whether an error is ‘Temporary’?

**Comment by jonjohnsonjr** [comment]
> We have encountered a scenario where a registry (flakey) sometimes returns a 500 status code error, and also returns an actionable error of UNKNOWN
> 
> `{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}`

Ahh, now I understand your point, sorry I was confused.

Yes, this is a problem. Let's add `UNKNOWN` to [this list](https://github.com/google/go-containerregistry/blob/7e0ed51a7bb1930bfb6859f319975b578ed04de2/pkg/v1/remote/transport/error.go#L138-L157) as well.

We could just consider all `UNKNOWN` to be a `temporaryErrorCodes`, but we could also move [this check](https://github.com/google/go-containerregistry/blob/7e0ed51a7bb1930bfb6859f319975b578ed04de2/pkg/v1/remote/transport/error.go#L91-L94) to be after [this check](https://github.com/google/go-containerregistry/blob/7e0ed51a7bb1930bfb6859f319975b578ed04de2/pkg/v1/remote/transport/error.go#L95-L99) and just remove the `if len(e.Errors) == 0` bit? That way, if there's a non-temporary error in the response, we won't retry, but if the only errors are temporary, we retry based on the HTTP status code.

> `StatusCode < http.StatusBadRequest`

I'm not sure if I understand this bit. Under what situations would we want to retry < 400?

> `.StatusCode >= http.StatusInternalServerError`

This would also drop `http.StatusRequestTimeout`, which feels reasonable to retry.

Looking at https://datatracker.ietf.org/doc/html/rfc7231#section-6.6 it seems like for retries:
* 500 might succeed.
* 501 will fail.
* 502 might suceed.
* 503 might suceed, and suggests we should respect `Retry-After` headers.
* 504 might succeed.
* 505+ will fail.

I'd say we should maybe add `StatusGatewayTimeout` to [this this](https://github.com/google/go-containerregistry/blob/7e0ed51a7bb1930bfb6859f319975b578ed04de2/pkg/v1/remote/transport/error.go#L165-L170) and possibly have some way to propagate `Retry-After` headers to our backoff logic.

> Or, allowing the consumer of the library the ability to configure the conditions which mark whether an error is ‘Temporary’?

Another option is for library consumers to pass a custom transport that implements their desired retry behavior, but that's not a great solution.

**Comment by DennisDenuto** [comment]
> Let's add UNKNOWN to this list as well.

+1

> but we could also move this check to be after this check

I'm kinda worried that change will result in retrying less `http status code` and `error` combinations. Although, for my specific example this change in addition to the above adding `UNKNOWN` would work well. 

My concern I think is stemming from the lack of clear understanding/specification on how different registries express whether an error is temp or not. So in the wild i'm worried we will run into strange combinations of a temp `error` returned with a non-temp `http status code` where retrying would have 'worked'.

I might be over-correcting here, but I was thinking of being *more* permissive when considering whether an error is temp or not.

i.e.
If the `http status code` is temp or `error` is temp, then retry. 

> This would also drop http.StatusRequestTimeout, which feels reasonable to retry.

Yeah, this if statement is gnarly and hurts my head when I try to parse it (sorry)... but theres the `|| len(e.Errors) == 0` at the end of it. So if the status is `http.StatusRequestTimeout` it *would* get retried assuming theres no `error` returned too.

This if statement is me trying to code-ify the [distribution spec](https://github.com/distribution/distribution/blob/main/docs/spec/api.md#errors). Specifically this line `Actionable failure conditions, covered in detail in their relevant sections, are reported as part of 4xx responses `

I'll go and create a PR to at least add UNKNOWN to this list as well. Based on your thoughts I can further incorporate changes to that PR too :-)

**Comment by jonjohnsonjr** [comment]
> So if the status is http.StatusRequestTimeout it would get retried assuming theres no error returned too.

Ah, makes sense.

> I might be over-correcting here, but I was thinking of being more permissive when considering whether an error is temp or not.

Yeah, that's my intention as well, but I think it's a little weird that we don't consider http status codes _at all_ if there are structured errors present (i.e. [this](https://github.com/google/go-containerregistry/blob/7e0ed51a7bb1930bfb6859f319975b578ed04de2/pkg/v1/remote/transport/error.go#L100) should not return true, probably). It doesn't make sense to retry a basically ever 405, even if the registry returns the wrong Error code (e.g. `UNKNOWN` instead of `UNSUPPORTED`).

I think with all my suggested changes, we end up both retrying in more situations where we should and _not_ retrying in situations where we _shouldn't_.

https://github.com/google/go-containerregistry/pull/1115 is a good place to start, at least.
