### ISSUE TITLE
Allow configuring the retry attempts

### ISSUE THREAD

**Issue by DennisDenuto** [google/go-containerregistry#1114]
Currently the number of retries gcr attempts is hardcoded to `3`. See https://github.com/vmware-tanzu/carvel-imgpkg/blob/15b20e52873608cd5d3699d2c4e2ca61d04b3511/vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go#L423-L428

In environments where the network is super flakey, this number is too low. 

It would be great if the consumer of this library can configure the `backoff` values

Assuming the above seems reasonable, I'd be happy to submit a PR.

**Comment by tkrishtop** [comment]
Hi @DennisDenuto could you please provide an example of how to use your code to configure the retries? 

I'm trying to do this: https://go.dev/play/p/kyxdXxCAxyN

but have the undefined errors
```
$ go run main.go 
# command-line-arguments
./main.go:10:31: undefined: crane.Backoff
./main.go:18:9: undefined: crane.WithRetryBackoff
``` 

But it seems like both `Backoff` and `WithRetryBackoff` are supposed to be exposed

https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/options.go#L278-L292

```
// Backoff is an alias of retry.Backoff to expose this configuration option to consumers of this lib
type Backoff = retry.Backoff

...

// WithRetryPredicate sets the predicate for retry HTTP operations.
func WithRetryPredicate(predicate retry.Predicate) Option {
	return func(o *options) error {
		o.retryPredicate = predicate
		return nil
	}
}
```

**Comment by imjasonh** [comment]
[`WithRetryPredicate`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote#WithRetryBackoff) is in `pkg/v1/remote`, not `pkg/crane`.

You can set this as a crane option using:

```
	options := []crane.Option{
		Remote: []remote.Option{
			remote.WithRetryBackoff(customRetryBackoff),
		},
	}
```

**Comment by tkrishtop** [comment]
Thank you @imjasonh worked like a magic!

```
package main

import (
	"log"
	"time"

	"github.com/google/go-containerregistry/pkg/crane"
	"github.com/google/go-containerregistry/pkg/v1/remote"
)

func withRemoteOption(ro remote.Option) crane.Option {
	return func(o *crane.Options) {
		o.Remote = append(o.Remote, ro)
	}
}

func main() {
	customRetryBackoff := &remote.Backoff{
		Duration: 1.0 * time.Second,
		Factor:   5.0,
		Jitter:   0.1,
		Steps:    3,
	}

	options := []crane.Option{
		withRemoteOption(remote.WithRetryBackoff(*customRetryBackoff)),
	}

	image := "gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c"
	_, err := crane.Pull(image, options...)

	if err != nil {
		log.Println("[error] failed to pull remote container", err)
	} else {
		log.Println("[ok] pull finished fine")
	}
}
```

```
$ go run main.go 
2022/09/21 17:42:02 [ok] pull finished fine
```
