### ISSUE TITLE
Consider adding support Vault provider for k8schain

### ISSUE THREAD

**Issue by Dentrax** [google/go-containerregistry#1117]
Currently, _crane_ only supports [three KMS providers](https://github.com/google/go-containerregistry/tree/main/pkg/authn/k8schain), as follows:
- gcp
- aws
- azure

Adding [vault](https://github.com/hashicorp/vault) as a k8schain provider would be great. By legacy design, I think we need to implement necessary parts in another dependency project called [k8s-pkg-credentialprovider](https://github.com/vdemeester/k8s-pkg-credentialprovider). At the end of the day, it will look like this: 

```golang
package k8schain

import (
	// vault credential provider
	_ "github.com/vdemeester/k8s-pkg-credentialprovider/vault"
)
```

**P.S:** _I'm not so sure if that repository is still actively maintained. Which brings me a question: Any plans to move that implementation into _crane_? That said, we can get rid of dependency, and we will be able to manage these easily here. Just thinking..._

Is it makes sense to implement `vault` provider? We can give a hand for this. @developer-guy 😇

**Comment by imjasonh** [comment]
I think the long-term plan is for k8schain to be deprecated and removed entirely. It'll take some time. We'd probably like to replace it with a [docker-credential-magic](https://github.com/docker-credential-magic/docker-credential-magic) helper that bundles as many cloud-specific credential helpers as we can. I'm not sure if there's a vault cred helper; if there is, we should bundle it.

cc @jonjohnsonjr

**Comment by jonjohnsonjr** [comment]
So `crane` doesn't link `k8schain` by default, and as Jason said, I'd like to get rid of it eventually.

How/where are you using this? It should be possible to implement a vault-based `Keychain` and use it with crane, but if you're trying to use it with the `crane` _binary_, I would recommend implementing a credential helper instead. We can make that easy to distribute with docker-credential-magic, but in general I'd like to push these dependencies out of this repository.

If that's not a workable solution, I'd be interested in why. Maybe we could come up with another option.

**Comment by Dentrax** [comment]
Thanks for the clarification. Actually, I do not have any special use case for this. Just interested in how to implement different `keychain` providers, and learn more about how _credential helpers_ are working; so I ended up here to discuss further this. I think [docker-credential-magic](https://github.com/docker-credential-magic/docker-credential-magic) is quite new project. I'll take a look at that. Thanks. 👍
