### ISSUE TITLE
How do we set the manifest platform."os.version" property?

### ISSUE THREAD

**Issue by rgl** [google/go-containerregistry#1137]
How do we set the manifest `platform."os.version"` property like the `golang:1.17.1` image?

```console
PS C:\Users\vagrant\Desktop\example-docker-buildx-go> .\crane.exe manifest golang:1.17.1 | jq
{
  "manifests": [
    ...
    {
      "digest": "sha256:203c24bdb4c98895e3425bce051aa6c43b55f20daaf339cc628d9b6cd20d7d58",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "windows",
        "os.version": "10.0.14393.4651"
      },
      "size": 3402
    }
  ],
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2
}
```

**Comment by imjasonh** [comment]
Using [`pkg/v1/mutate.AppendManifests`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/mutate#AppendManifests):

```
idx := mutate.AppendManifests(empty.Index, mutate.IndexAddendum{
  Add: img,
  Descriptor: v1.Descriptor{
    Platform: v1.Platform{
      Architecture: "amd64",
      OS: "windows",
      OSVersion: "10.0.14393.4651",
    },
  },
})
```

**Comment by jonjohnsonjr** [comment]
Also note that this field can be present in the config file, so you may also need to set it in the underlying image:

* https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/mutate#ConfigFile
* https://github.com/google/go-containerregistry/blob/2459de30539a35c9514d29b582dea19dbb3330ea/pkg/v1/config.go#L39

**Comment by rgl** [comment]
By any chance, can that be done from the crane application (e.g. without writing a custom go app)?

Or even, just let us modify the manifest json, and somehow use crane to upload it?

**Comment by imjasonh** [comment]
> By any chance, can that be done from the crane application (e.g. without writing a custom go app)?

Nope, `crane` doesn't include much functionality for modifying indexes or manifest lists, sorry. :( 

I wrote https://github.com/imjasonh/combine to combine two manifest lists, if that happens to be what you're after.

**Comment by rgl** [comment]
@imjasonh, I think `combine` almost is what I'm looking for!

To explain a bit more, at https://github.com/rgl/example-docker-buildx-go/blob/add-windows/.github/workflows/build.yml I'm using `docker buildx` to produce a multi-arch image (published at https://hub.docker.com/layers/ruilopes/example-docker-buildx-go/staging--v1.3.0-test12-linux).

And then I use `docker build` (not buildx) to create a non-multi-arch windows 2019 image (published at https://hub.docker.com/layers/169706351/ruilopes/example-docker-buildx-go/staging--v1.3.0-test12-windowsnanoserver-1809).

And, in the near future, I want to also add a windows 2022 image.

So, I'm looking for a tool that can take an arbitrary number of manifests or images and merge them all into a single manifest.

But for doing this, I believe I first need to include a proper `platform."os.version"` property in the windows images, which I don't known how to do with an existing tool.

So, I'm kinda stuck and would appreciate any help you could provide :-)

**Comment by jonjohnsonjr** [comment]
> Or even, just let us modify the manifest json, and somehow use crane to upload it?

If you're willing to do this manually, I have a fork of crane with an `edit` command that I use for experiments (I'd need to rewrite a bunch of k8s dependencies to make it mergeable): https://github.com/jonjohnsonjr/go-containerregistry/tree/editor

This will pop open an editor for you to do whatever you need:
```
crane edit manifest $IMAGE
```

> So, I'm looking for a tool that can take an arbitrary number of manifests or images and merge them all into a single manifest.

I'm interested in this and there have been some attempts (https://github.com/google/go-containerregistry/pull/891) but I wasn't ever really happy with the UX. I'm thinking we should just have something similar to `crane append`  called `crane amend` that only works on manifest lists and call it a day.

cc @tianon
