### ISSUE TITLE
What filtering and sorting options are there for ls? I want to sort by modified date.

### ISSUE THREAD

**Issue by red8888** [google/go-containerregistry#1142]
My expectation was there would be more options than using gcloud but looks like there are less? I want to sort tags by modified date.

This is what I do now:
```
gcloud container images list-tags \
	'gcr.io/myproject/myimage' \
	--flatten='tags[]' \
	--format='value(tags)' \
	'--limit=10' \
	'--format=json'
```

I see zero sorting or filtering options for gcrane ls and the tags appear to be sorted alphabetically by default:
`gcrane ls gcr.io/myproject/myimage --json | jq .tags`

**Comment by jonjohnsonjr** [comment]
Implementing useful filtering would require me to either invent or take a dependency on some kind of DSL for comparing timestamps and such, which I've been too lazy to do given that I've been able to use `jq` to accomplish anything I've needed to do with this.

Generally, I've biased towards small and composable interfaces for [g]crane, so I'd be reluctant to add (and maintain) any powerful filtering support, but I'm open to the idea if there's a compelling argument for it, e.g. some use case where `jq` is insufficient or a really nice UX that I hadn't considered.
