### ISSUE TITLE
crane: how to copy a sub-set of a image platforms?

### ISSUE THREAD

**Issue by rgl** [google/go-containerregistry#1143]
How can we copy the images of a manifest list that match a given platform list?

Using `crane --all` we can copy all the images from a manifest list.

Using `crane --platform` we can can copy a single image that matches the given singular platform, but how about a sub-set? Something like `crane --platform linux/amd64,linux/arm64`?

This would be useful for copying a sub-set of the [`debian:bullseye-slim`](https://hub.docker.com/_/debian) images (e.g. just the `linux/amd64` and `linux/arm64` platform images).

**Comment by rgl** [comment]
> Do you want to copy both images separately to the destination? Or do you want to take the existing manifest list, filter out all the platforms you don't care about, and push a _new_ manifest list with just those two platforms?

The second one :-)

**Comment by jonjohnsonjr** [comment]
X-ref: https://github.com/containers/skopeo/pull/1511

**Comment by gpsmit** [comment]
I would love to have this feature as well.
Today I pushed 5GB worth of windows images when im only interested in linux arm & and images
