### ISSUE TITLE
authn: Also consult ~/.config/containers/auth.json for auth config

### ISSUE THREAD

**Issue by imjasonh** [google/go-containerregistry#1145]
See https://github.com/containers/podman/issues/11923 and https://github.com/tektoncd/operator/issues/448

Currently [`auth.DefaultKeychain`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/authn#DefaultKeychain) only consults ~/.docker/config.json, and fails if it's not present.

Podman and other tools also consult ~/.config/containers/auth.json (mainly to avoid the "docker" name, AFAICT), so Podman users won't be able to easily use tools built using go-containerregistry.

`DefaultKeychain` could consult ~/.config/containers/auth.json if ~/.docker/config.json is not found. AFAIK they have the same expected structure.

**Comment by rhatdan** [comment]
Any movement on this?

**Comment by imjasonh** [comment]
Thanks for the ping.

We should definitely be able to fix this. I want to make sure we do it right, for both Docker and Podman users -- and probably even for people who have both configured, whether they realize it or not. 😵‍💫 

As I'm looking at this, it seems this won't be quite as straightforward as I'd originally thought -- Docker's `config.Load` that we use today doesn't return an error if the config file isn't found, it just creates one and returns it in that case. So we can't easily detect that case and fallback to looking for Podman's config.

Reading [Podman's docs](https://docs.podman.io/en/latest/markdown/podman-login.1.html), it seems like their solution is to always prefer to look for Podman's auth config first, then fallback to Docker's if that's not found. We could do that too, but I'm a bit worried that this would be a confusing breaking change for users who have both `~/.docker/config.json` and `~/.config/containers/auth.json` configured, who before such a change would use the former and after would use the latter.

That might be a small enough disruption to a small enough set of people that we should just make the change and document it in release notes.

In that case, is there an easy package in Podman's codebase we could ~~steal~~ reuse to perform this fallback parsing logic? I have some code that passes tests (https://github.com/google/go-containerregistry/compare/main...imjasonh:auth-podman) but I'd feel a lot more comfortable repurposing throughly tested code for this rather than write my own. I'm sure there have been lots of edge cases found and fixed and I'd love not to rediscover those landmines myself.

cc @jonjohnsonjr
