### ISSUE TITLE
Question: remote.Catalog lists all repos from all GCR projects and organizations

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [google/go-containerregistry#1180]
I am using the following code to list my `docker` repositories that are available in GCR

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/google/go-containerregistry/pkg/authn"
	gcr "github.com/google/go-containerregistry/pkg/name"
	"github.com/google/go-containerregistry/pkg/v1/google"
	"github.com/google/go-containerregistry/pkg/v1/remote"
)

func main() {

	auth, err := google.NewGcloudAuthenticator()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(auth)
	registry, err := gcr.NewRegistry("gcr.io")
	if err != nil {
		log.Fatal(err)
	}
	ctx := context.Background()
	repos, err := remote.Catalog(ctx, registry, remote.WithAuthFromKeychain(authn.DefaultKeychain))
	if err != nil {
		log.Fatal(err)
	}
	for _, repoName := range repos {
		fmt.Println(repoName)
	}
}

```

The problem is that despite the fact that I have performed an explicit `gcloud config set project` to a specific project, invocation of the above program will list **ALL** repos of **ALL** organizations and **ALL** projects my `gcloud` has access to.

Is there a way to limit the code above so that it lists the gcr repos of a specific org/project?

**Comment by jonjohnsonjr** [comment]
> The problem is that despite the fact that I have performed an explicit gcloud config set project to a specific project, invocation of the above program will list ALL repos of ALL organizations and ALL projects my gcloud has access to.

Yeah this is awful and a problem with how the `catalog` API is implemented.

> Is there a way to limit the code above so that it lists the gcr repos of a specific org/project?

`google.List` and `google.Walk` expose the response that GCR returns, which includes some extensions to the distribution API.

The `google.Tags` response contains `Children`, which are basically subdirectories for your repository.

I'd use `gcrane ls` as an example for how you might want to use this: https://github.com/google/go-containerregistry/blob/c90c44474acce673c0719a67e0f45a85f3dff157/cmd/gcrane/cmd/list.go#L57-L94
