### ISSUE TITLE
Crane Login auth failing

### ISSUE THREAD

**Issue by tbuchier** [google/go-containerregistry#1183]
Hello,

Since today crane login using `latest` image is failing:

`crane auth login -u _json_key -p "${GCR_SA_KEY}" ${GCR_HOST}`

```
2021/11/17 07:59:15 No matching credentials were found for "gcr.io"
Error: failed to copy image: GET https://gcr.io/v2/token?scope=repository......=gcr.io: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

If we try crane login with the same json_key using `v0.7.0` it works fine. 

Thanks

**Comment by rlapond** [comment]
We also have an auth issue in our git-ci connecting to harbor since yesterday after 18:00 with: 
`crane auth login REGISTRY_URL -u "REGISTRY_AUTOMATION_USERNAME" -p "REGISTRY_AUTOMATION_PASSWORD"` 

Probably because of #1181

**Comment by WanzenBug** [comment]
@tbuchier Why did you close the issue? Do you have a solution?

I also ran into this issue in CI. We are using gitlab with the `gcr.io/go-containerregistry/crane:debug` image, and run
```
mkdir -p $HOME/.docker
ln -snf $DOCKER_PUBLISH_AUTH_CONFIG_FILE $HOME/.docker/config.json
crane copy ....
```

which worked fine up to now. Since #1181, it seems the file is no longer picked up. Looking at the code, it seems fallbacks for the environment variables is missing. I.e. `DOCKER_CONFIG` should default to `$HOME/.docker` and `XDG_RUNTIME_DIR` to `$HOME/.config`. Manually setting `export DOCKER_CONFIG=$HOME/.docker` fixes my pipeline

**Comment by max-wittig** [comment]
We see the same problem within our environment. Sadly we have no fixed tags for the debug image to`downgrade`.

@fh1ch

**Comment by tbuchier** [comment]
@WanzenBug My bad when I opened this issue at first I was suspecting #1181 then I found out our common CI image is using a fixed version so I closed. But eventually our failing pipeline is different and directly use crane:latest as executor image so... here we are haha

**Comment by PatrickSpies** [comment]
> We see the same problem within our environment. Sadly we have no fixed tags for the debug image to `downgrade`.
> 
> @fh1ch

See https://github.com/google/go-containerregistry/tree/main/cmd/crane#images
> Tagged debug images are available at gcr.io/go-containerregistry/crane/debug:[tag].

Using `gcr.io/go-containerregistry/crane/debug:v0.7.0` as executor image fixed our failing pipelines...

**Comment by dlouzan** [comment]
@PatrickSpies Hah, we have just discovered that debug images are actually tagged, we always thought that there was only latest. The funny naming scheme tripped us, wonder if this is also a surprise for more people 🤔

**Comment by imjasonh** [comment]
Sorry for the disruption everyone, I'm reverting in #1184 which should fix it.

This issue also highlights a need for better tagging for `:debug` images, so debug users can downgrade. I'll open a separate issue for that.
