### ISSUE TITLE
daemon.Image doesn't return an error if the image isn't in the daemon

### ISSUE THREAD

**Issue by sharifelgamal** [google/go-containerregistry#1186]
Previously, if someone called daemon.Image with a nonexistent image, it would a return an error since `tarball.Image` would rightfully fail. Now the daemon retrieval code is lazier about writing tarballs, which has the unfortunate side-effect of suppressing that error, which is an unexpected change in behavior.

**Comment by jonjohnsonjr** [comment]
Well that's annoying. Maybe we should send a cheap request to make sure it exists (e.g. access the image ID)?

**Comment by sharifelgamal** [comment]
That would be plenty fine for our purposes.

**Comment by jonjohnsonjr** [comment]
@knqyf263 any concern?

**Comment by sharifelgamal** [comment]
This is blocking minikube from upgrading to a newer version of go-containerregistry, so we're stuck at v0.6.

**Comment by medyagh** [comment]
the issue still exists at v0.0.8 too
https://github.com/kubernetes/minikube/runs/4972650332?check_suite_focus=true

```
[
  "TestFunctional/serial/CacheCmd/cache/add_remote",
  "TestFunctional/serial/CacheCmd/cache/delete_k8s.gcr.io/pause:3.3",
  "TestFunctional/serial/CacheCmd/cache/list",
  "TestFunctional/serial/CacheCmd/cache/verify_cache_inside_node",
  "TestFunctional/serial/CacheCmd/cache/cache_reload",
  "TestFunctional/serial/CacheCmd/cache/delete"
]
```

**Comment by jonjohnsonjr** [comment]
Can you test with https://github.com/google/go-containerregistry/pull/1272?

**Comment by sharifelgamal** [comment]
> Can you test with #1272?

Works like a charm :)

**Comment by knqyf263** [comment]
@jonjohnsonjr Sorry I missed your message. 

>Maybe we should send a cheap request to make sure it exists (e.g. access the image ID)?

Sounds good.

**Comment by jonjohnsonjr** [comment]
Thanks all.
