### ISSUE TITLE
Support Manifest Lists

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#119]
We should add support for manifest lists, if only to avoid needing this non-Fatal workaround for DockerHub:
```
2018/04/29 07:27:03 manifest digest: "sha256:90f24abe180424046a5d53f6fc6f9fdb8f79b835cb2fd7d1a782e4c30dfb5dcc" does not match Docker-Content-Digest: "sha256:d2518289e66fd3892c2dae5003218117abeeed2edbb470cba544aef480fb6b3a" for "index.docker.io/library/ubuntu:latest"
```

Jon, you're easily the best person for the job :)

**Comment by jonjohnsonjr** [comment]
This will be a lot of work to make it compose well with everything.

As a starting point, we can just stash the manifest list and resolve it to the amd64/llinux linux it points to. Making this work transparently for e.g. `crane copy` will take some effort (i.e. we will need to teach each sink about manifest lists).

**Comment by listx** [comment]
ping?

**Comment by bbrowning** [comment]
Because Knative uses go-containerregistry, this bug prevents Knative from working with quay.io and likely several other registries. You'll see the manifest digest error message which is fatal for non-DockerHub repositories.

**Comment by jonjohnsonjr** [comment]
@bbrowning I believe quay has a different issue, but your point is generally correct :) working on this now.

**Comment by bbrowning** [comment]
@jonjohnsonjr Yes, the issue is probably a bit different after a conversation on the Knative Slack. It manifests in a similar error message around digests not matching, but it was pointed out to me that quay.io isn't on schema 2 yet.
