### ISSUE TITLE
Pushing an image with existing tag

### ISSUE THREAD

**Issue by ueoeae** [google/go-containerregistry#1191]
How do you handle a crane push of an image if the tag already exists in the registry? The push still happens if the tag exists, and overwrites previous push/tag.

**Comment by imjasonh** [comment]
In this case the push should still succeed and the tag should point to the newly pushed image.

This matches the behavior of `docker push`, etc.

Depending on the registry, the previous image may still be available by digest, or by any other tags it still has pointing to it.

**Comment by ueoeae** [comment]
> In this case the push should still succeed and the tag should point to the newly pushed image.
> 
> This matches the behavior of `docker push`, etc.
> 
> Depending on the registry, the previous image may still be available by digest, or by any other tags it still has pointing to it.

Would you know of a possibility to check if the used tag already exists so that a push does not take place unless the tag is unique?

**Comment by imjasonh** [comment]
You can check for the existence of an image at a tag with [`crane digest`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_digest.md), which will fail if the tag doesn't exist. Something like:

```
crane digest registry.com/my/image:tag && echo "tag exists" && exit 1
crane push image.tar registry.com/my/image:tag
```

If `registry.com/my/image:tag` exists then it won't be pushed to.

Beware there's a possible race condition, if you check for the existence of a tag then push to it; another process can push to that tag in the meantime. At this time there isn't a "push to this tag only if it doesn't exist yet" option, though enabling this across registries is being discussed in OCI: https://github.com/opencontainers/distribution-spec/issues/250

**Comment by imjasonh** [comment]
Closing this, please reply if this didn't answer your question.
