### ISSUE TITLE
crane append: cross repo mount causes "UNAUTHORIZED" error on Dockerhub

### ISSUE THREAD

**Issue by sclevine** [google/go-containerregistry#123]
I've identified a potential bug with `crane append` on both macOS 10.13.4 and Linux (docker4mac).

Crane version: `48dcc10b3aad9a760316aba5c88138bcc60dbcd1`
Go version (mac): `go version go1.10 darwin/amd64`
Go version (linux): `go version go1.10 darwin/amd64` (`GOOS=linux`)

When the source is a Dockerhub repo and the destination is a different Dockerhub repo, I get the following error:
```
 opal:test stephen$ crane append packs/cflinuxfs2:run sclevine/some-app:latest ./layer.tgz
2018/05/06 16:58:34 UNAUTHORIZED: "authentication required"
```
I get the same error if I have write access to both repos:
```
 opal:test stephen$ crane append sclevine/cflinuxfs2:run sclevine/some-app:latest ./layer.tgz
2018/05/06 16:59:45 UNAUTHORIZED: "authentication required"
```
Using the same repo for both the image source and image destination succeeds.

The authorization error is coming from this call:
https://github.com/google/go-containerregistry/blob/48dcc10b3aad9a760316aba5c88138bcc60dbcd1/cmd/crane/append.go#L94

I was able to fix this by removing these lines (which create a cross-repo mount):
https://github.com/google/go-containerregistry/blob/48dcc10b3aad9a760316aba5c88138bcc60dbcd1/cmd/crane/append.go#L85-L87
This is very slow, presumably because the base layers are copied to the host and back to the registry.

**Comment by sclevine** [comment]
More data from a failed attempt:

Request:
```
POST https://index.docker.io/v2/sclevine/some-app/blobs/uploads/?from=packs%2Fcflinuxfs2&mount=sha256%3A9535de6d506e0e353a9378d14ad3fe8f2d44bf7f1e8e7dd5b58c01a053878d37 application/json
(no body)
```

Response:
```
&{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Type:[application/json; charset=utf-8] Docker-Distribution-Api-Version:[registry/2.0] Www-Authenticate:[Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:sclevine/some-app:pull,push repository:packs/cflinuxfs2:pull",error="insufficient_scope"] Date:[Mon, 07 May 2018 02:28:29 GMT] Content-Length:[311] Strict-Transport-Security:[max-age=31536000]] 0xc420172c00 311 [] false false map[] 0xc4202c0200 0xc42028c2c0}
```
Response Body:
```
{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "authentication required",
      "detail": [
        {
          "Type": "repository",
          "Class": "",
          "Name": "sclevine\/some-app",
          "Action": "pull"
        },
        {
          "Type": "repository",
          "Class": "",
          "Name": "sclevine\/some-app",
          "Action": "push"
        },
        {
          "Type": "repository",
          "Class": "",
          "Name": "packs\/cflinuxfs2",
          "Action": "pull"
        }
      ]
    }
  ]
}
```

**Comment by sclevine** [comment]
It seems like the requested scopes here:
https://github.com/google/go-containerregistry/blob/48dcc10b3aad9a760316aba5c88138bcc60dbcd1/v1/remote/transport/transport.go#L75
would only include the destination `ref` from here:
https://github.com/google/go-containerregistry/blob/48dcc10b3aad9a760316aba5c88138bcc60dbcd1/v1/remote/write.go#L42
via `dstTag` in append:
https://github.com/google/go-containerregistry/blob/48dcc10b3aad9a760316aba5c88138bcc60dbcd1/cmd/crane/append.go#L94

Testing this theory out now.

**Comment by sclevine** [comment]
@dprotaso @bsnchan @ImJasonH @mattmoor FYI, this means `packs/cf:export` doesn't work with Docker Hub right now.

**Comment by sclevine** [comment]
Confirmed that the scopes are the issue.

Note that the `scope` query param must be passed for each value:
```
scope=repository%3Asclevine%2Fsome-app%3Apush%2Cpull&scope=repository%3Apacks%2Fcflinuxfs2%3Apull&service=registry.docker.io
```
Even though the API docs sort of suggest that space-delimited values are okay:
https://docs.docker.com/registry/spec/auth/token/#requesting-a-token

I'm happy to PR a fix, but I'm not sure how we'd like to refactor `transport.New` to support this. Perhaps it could take full-qualified scopes? And then maybe `WriteOptions` could include a list of repos that we need `pull` access to?

**Comment by sclevine** [comment]
Opened #124 with a suggestion for a fix.

**Comment by ImJasonH** [comment]
Did #124 fully resolve this for you?

**Comment by sclevine** [comment]
Yep, sorry, forgot to close this one.
