### ISSUE TITLE
crane: copy container images from oci layout extracted by google/ko

### ISSUE THREAD

**Issue by developer-guy** [google/go-containerregistry#1232]
We've (@dentrax @csantanapr) just tried to copy container image from OCI directory extracted by the google/ko project and got an error because the crane couldn't detect that this is a directory, then it considered this as an image and looked up to the registry to copy.

To reproduce issue:

```shell
$ mkdir -p hello-world
$ cd hello-world
$ go mod init github.com/<username>/hello-world
$ cat << EOF | tee main.go
package main
import "fmt"
func main() {
  fmt.Println("Hello World!")
}
EOF

$ KO_DOCKER_REPO=docker.io/<username> ko build --push=false --bare -B --platform=linux/amd64 --tags latest --oci-layout-path hello-world-oci github.com/<username>/hello-world
$ crane copy hello-world-oci docker.io/<username>/hello-world
 crane copy hello-world-oci docker.io/devopps/hello-world
2022/01/06 17:16:56 Copying from hello-world-oci to docker.io/devopps/hello-world
Error: fetching "hello-world-oci": GET https://index.docker.io/v2/library/hello-world-oci/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/hello-world-oci Type:repository]]
```

**Comment by developer-guy** [comment]
we're willing to work on it btw, please feel free to assign it to me 🙋🏻‍♂️

**Comment by Dentrax** [comment]
I'm not sure how the CLI will look like but how about:

```
$ crane copy file://foo/bar <DEST>
```

vs.

```
$ crane copy foo/bar <DEST>
```

If we use something like the following above, what I understand from this UX is that we're trying to copy `foo/bar` image from the _default_ registry, i.e. docker.io. Thoughts?

**Comment by imjasonh** [comment]
I think you want [`crane push`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_push.md), which as of v0.8.0 can push directories in layout format.

**Comment by jonjohnsonjr** [comment]
We may want to implement something for `crane push` that knows how to "reroot" images onto the target registry and/or auto-derive the target ref based on annotations in `index.json`.

What's are you trying to accomplish?

**Comment by developer-guy** [comment]
> I think you want [`crane push`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_push.md?rgh-link-date=2022-01-06T15%3A40%3A55Z), which as of v0.8.0 can push directories in layout format.

yes, works like a charm, so, I'm closing this one, thanks for the help folks
