### ISSUE TITLE
Create release tags for k8schain

### ISSUE THREAD

**Issue by scothis** [google/go-containerregistry#1233]
Nested go modules should have their own tags in order for a consumer to be able to require the module based on a version. Currently we have to consume k8schain as a specific commit (`v0.0.0-20220105220605-d9bfbcb99e52`) rather than as a version (`v0.8.0`). Tools like Dependabot will update versioned dependences, but will not update commit based dependencies.

Trying to consume as a version will result in a error from go:
```
        github.com/google/go-containerregistry/pkg/authn/k8schain: reading github.com/google/go-containerregistry/pkg/authn/k8schain/pkg/authn/k8schain/go.mod at revision pkg/authn/k8schain/v0.8.0: unknown revision pkg/authn/k8schain/v0.8.0
```

This can be solved by creating an additional tag for each release of the nested module, like `pkg/authn/k8schain/v0.8.0`.

**Comment by imjasonh** [comment]
If we do this, we should do it generally for every sub-Go-module in the repo ([and there might be more coming soon](https://github.com/google/go-containerregistry/pull/1231)!), and automate it as best we can.

Docs here: https://go.dev/ref/mod#module-path
