### ISSUE TITLE
Fill out `mediaType` for OCI

### ISSUE THREAD

**Issue by maisem** [google/go-containerregistry#1235]
Currently when I create an OCI using the mutate pkg, the `mediaType` field is not set.
https://github.com/google/go-containerregistry/blob/d9bfbcb99e526b2a9417160e209b816e1b1fb6bd/pkg/v1/mutate/index.go#L134-L142

OCI spec recently added support for `mediaType` (https://github.com/opencontainers/image-spec/commit/5b82148fa647734a2c6095b2eab9b502fbca227e) when it was previously not allowed as per https://github.com/opencontainers/image-spec/pull/795.

Now that it is in spec, the field should be set.

/cc @jonjohnsonjr

**Comment by jonjohnsonjr** [comment]
Thanks!
