### ISSUE TITLE
question: does crane pull handle manifest conversion

### ISSUE THREAD

**Issue by thesayyn** [google/go-containerregistry#1245]
I have been playing around with crane pull OCI format. upon inspection of the OCI contents of the image, I realized that crane does not make image config/manifest OCI compliant.  mediaType is still `application/vnd.docker.distribution.manifest.v2+json`/ `application/vnd.docker.container.image.v1+json`

On the other hand, tools such as skopeo handle the conversion automatically and give you OCI with the original manifest stripped down that conforms to OCI spec. 

Perhaps this is the intended behavior, though I want to better understand why would one want to have docker manifests laid out as OCI layout.

If this is not the intended behavior, is there intent to handle this conversion? perhaps I could help.

**Comment by thesayyn** [comment]
this quirk is only present when the source image is in docker v2 format.

**Comment by jonjohnsonjr** [comment]
> Perhaps this is the intended behavior, 

This is intended behavior, as we want to be able to roundtrip images through the OCI Layout. For example, you should be able to `crane pull` an image into a layout, then `crane push` that image to another registry, and the digests should be identical. If we did conversion between OCI and Docker media types, we'd lose the original payload, and the digests would no longer match.

> though I want to better understand why would one want to have docker manifests laid out as OCI layout.

It's a generally useful mechanism for storing content-addressable things on disk. If you look at [the example layout](https://github.com/opencontainers/image-spec/blob/main/image-layout.md#index-example), there's even an [appstream](https://www.freedesktop.org/wiki/Distributions/AppStream/) artifact referenced.

What's your use case for converting to the OCI spec? I could imagine that being something we support, but maybe it would live in [`crane mutate`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_mutate.md)?

**Comment by thesayyn** [comment]
@jonjohnsonjr sorry for pinging. I have been working on a patch to add `--manifest_type` to force conversion when specified. I was able to do it using `mutate.MediaType`,  `mutate.ConfigMediaType`, `mutate.IndexMediaType` and introducing `mutate.Config` and a conversion func (similar to CreatedAt and Canonical) to drop properties that are only present in DockerV2 images.

Would you be interested to see the patch? with this patch, we can use crane to pull-push images with conversion.

**Comment by jonjohnsonjr** [comment]
How frustrating that we already use the flag that `skopeo` uses: https://github.com/google/go-containerregistry/blob/80d1a2f06b8de00fc1becc254ab9008d7c7b471e/cmd/crane/cmd/pull.go#L108

I think I'd be okay with adding something like `--convert oci` to push/pull but it feels a little pointless to just change the mediaType strings.

OTOH, I do actually find myself wanting to do this sometimes... so maybe it's fine.

@imjasonh would you be opposed to this?

**Comment by thesayyn** [comment]
> How frustrating that we already use the flag that skopeo uses:

This flag is a bit misleading IMHO. could be renamed to something like `--output_format`

> I think I'd be okay with adding something like `--convert oci` to push/pull but it feels a little pointless to just change the mediaType strings.

Actually, it doesn't just change the media types. it strips some of the properties in the config file that are not standardized by the spec.  I believe adding this flag to the pull command would be enough as one could do `pull --convert oci` and `push ./oci-dir`

> OTOH, I do actually find myself wanting to do this sometimes... so maybe it's fine.

from my point of view, this is a perfectly valid use case. Also, major registries support OCI media types including docker hub. I have tried to convert Debian image and push it to docker hub.  See: [thesayyn/oci-image:latest](https://hub.docker.com/layers/192576407/thesayyn/oci-image/latest/images/sha256-9ccfb72ac06562d1c3b2df2a357aa7a674bdf54dc4e0b22afa2d9ade3e991335?context=repo&tab=vulnerabilities)

**Comment by jonjohnsonjr** [comment]
> Would you be interested to see the patch? with this patch, we can use crane to pull-push images with conversion.

Yeah I'd love to take a look.

> it strips some of the properties in the config file that are not standardized by the spec

I have some reservations about doing this because if any fields get added to the spec, the tool becomes broken (without rebuilding the tool). Maybe that's fine, it's just a little added friction to making any changes.

**Comment by thesayyn** [comment]
> I have some reservations about doing this because if any fields get added to the spec, the tool becomes broken (without rebuilding the tool). Maybe that's fine, it's just a little added friction to making any changes.

I totally agree with this. in fact I saw that `os.features` prop was missing in the `ConfigFile` struct.  it is always gonna be a case ig.
