### ISSUE TITLE
question: passing registry certificates to crane while doing crane push

### ISSUE THREAD

**Issue by tanmay-db** [google/go-containerregistry#1246]
Hi, 

I was trying to push some docker images using crane to some of our registries which requires certificates but I am not able to pass those (couldn't find any flag / documentation).

The command I am using is:
`crane push /path/to/docker/image.tar /link/to/registry` and I received the message "400 No required SSL certificate was sent".

Is there some way to pass the certificates (if they are present in `/path/to/cert` on my machine)? Thank you

PS: Since crane pushes tarballs (on doing `crane push image-id`, I received `Error: loading image-id as tarball`), I created the tar ball using: `docker save image-id > /path/to/docker/image.tar`. Is it possible to directly push the image using it's image-id or without having to explicitly convert image to a tarball?

**Comment by jonjohnsonjr** [comment]
The SSL_CERT_FILE or SSL_CERT_DIR environment variables might work for you?

See https://pkg.go.dev/crypto/x509#SystemCertPool

**Comment by tanmay-db** [comment]
Hi @jonjohnsonjr, thanks for the response. I am using apple machine and unfortunately that doesn't seem to work on macOS.

> On Unix systems other than macOS the environment variables SSL_CERT_FILE and SSL_CERT_DIR can be used to override the system.

**Comment by tanmay-db** [comment]
Also, I saw your comment here: https://github.com/google/containerregistry/issues/162#issuecomment-788186923, I tried but with by just upgrading to python3, it didn't work (pushing docker images > 2GB still failed). Are you aware if go implementation has any such constraint like the 2GB one in the original python implementation?

**Comment by tanmay-db** [comment]
@jonjohnsonjr Hi, sorry for another ping. Just wanted to ask about the above questions in case they got missed.

**Comment by imjasonh** [comment]
This library should have no problem pushing images over 2GB. If you observe any problems please file a bug.

**Comment by jonjohnsonjr** [comment]
>  I am using an apple machine and unfortunately that doesn't seem to work on macOS.

Ah, you should be able to just [add the certs to your keychain](https://support.apple.com/guide/keychain-access/add-certificates-to-a-keychain-kyca2431/mac)?

> Is it possible to directly push the image using it's image-id or without having to explicitly convert image to a tarball?

Unfortunately, not with `crane` directly because we avoid linking the [`daemon` package](https://github.com/google/go-containerregistry/tree/main/pkg/v1/daemon) into `crane` (on purpose, due to its size).

**Comment by tanmay-db** [comment]
Thank you for the response @imjasonh and @jonjohnsonjr, I tried adding the certificates to the keychain in mac but it didn't work. I received the same "400 No required SSL certificate was sent" error.

Since going further our work would involve using linux so I have checked the usage of the `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variables that you have mentioned earlier but they doesn't seem to work, so I want to ask if there is any specific way to use them?

The strange thing is that if I use any one of them then I receive - "_400 No required SSL certificate was sent_" but if I use both of them and then even if both the variables are set to wrong values (for example: _path/to/cert/abc_ where abc doesn't exists) then the error is different - "_x509: certificate signed by unknown authority_"

The names of the certificates have been renamed to the registry hostname in case that might be required but it didn't work as well. 

The certificates should be correct because when the same certificates are passed to the `curl` command to query the registry, it works as opposed to not sending certificate in which case the response is "_400 No required SSL certificate was sent_". Hence the thought was that maybe go implemented or used the variables differently but the variables defined here in the repo: https://github.com/golang/go/blob/master/src/crypto/x509/root_unix.go#:~:text=certFileEnv%20%3D%20%22SSL_CERT_FILE%22  do take the values of `SSL_CERT_FILE` and `SSL_CERT_DIR` so I am not sure why it isn't working. 

Could you please tell what would be the correct way to use these variables or if something else is missing?

**Comment by jonjohnsonjr** [comment]
On unix it just appends any PEM-encoded files under `SSL_CERT_DIR` to the system certs: https://github.com/golang/go/blob/77eff30ec0bc63df61ea742bb8278f92e2c133dc/src/crypto/x509/root_unix.go#L72

For usage, this seems to have worked for other folks: https://github.com/google/go-containerregistry/issues/1066#issuecomment-871385691

**Comment by tanmay-db** [comment]
Hi @jonjohnsonjr, thanks for the response, I tried that and also tried putting all those environment variables in a script to push the image but it didn't work. I am still getting the same previous error message - 400 no certificate sent. I have been trying to test out few other things in the past few days but no luck so far.
