### ISSUE TITLE
Add shell to krane:debug

### ISSUE THREAD

**Issue by ChrisSamo632** [google/go-containerregistry#1262]
Adding a SHELL to `krane:debug` (similar to `crane:debug` in https://github.com/google/go-containerregistry/issues/605) would allow for use of the image in GitLab CI.

The `krane` image allows for authentication against ECR repositories by default, whereas `crane` does not because the `ecr-login` helper login isn't included within the Image and there's seemingly no way to `crane auth` with AWS Key details provided to the image.

`krane:debug` currently doesn't work in GitLab CI due to the lack of a SHELL, which is a requirement of using an image within a GitLab CI Pipeline.

**Comment by imjasonh** [comment]
I thought we'd already done this, in

https://github.com/google/go-containerregistry/blob/03d4ad10d1d6b8ee5f11bfddf71b983f88fc75df/cloudbuild.yaml#L41

Maybe the relative `KO_CONFIG_PATH` and the `cd cmd/krane` is confusing it. I'll fix it and send a PR. 👍
