### ISSUE TITLE
Add tag resolution library function

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#127]
This comes up all the time. We should expose a method to do this:

```go
func Resolve(tag name.Tag, kc authn.Keychain) (name.Digest, error)
```

`kc` could be [`authn.DefaultKeychain`](https://github.com/google/go-containerregistry/blob/0ff1db03aaaabc9820e8a13353f61d8474814abd/authn/keychain.go#L38) (uses docker creds) or @mattmoor's [`k8schain`](https://github.com/mattmoor/k8schain) (uses kubelet creds).

**Comment by mattmoor** [comment]
See [here](https://github.com/mattmoor/warm-image/blob/master/pkg/controller/warmimage/controller.go#L257-L283)

**Comment by jonjohnsonjr** [comment]
IMO, this PR implemented a better option via `remote.Get`: https://github.com/google/go-containerregistry/pull/408

You could implement the originally proposed `Resolve` as:

```go
func Resolve(tag name.Tag, kc authn.Keychain) (name.Digest, error) {
  desc, err := remote.Get(tag, remote.WithAuthFromKeychain(kc))
  if err != nil {
    return name.Digest{}, err
  }
  digest := fmt.Sprintf("%s@%s", tag.Repository.Name(), desc.Digest)
  return name.NewDigest(digest, name.StrictValidation)
}
