### ISSUE TITLE
question: Can crane get config for oras artifact on GitHub packages?

### ISSUE THREAD

**Issue by vsoch** [google/go-containerregistry#1275]
This isn't urgent because (at least for now) I don't need a config for this particular container! But I was playing around, and trying to
get the config for this package: https://github.com/singularityhub/github-ci/pkgs/container/github-ci 

using this endpoint: https://crane.ggcr.dev/config/ghcr.io/singularityhub/github-ci:latest

And it's totally empty. I'm guessing there is some kind of bug on GitHub's side returning some format of response that isn't correct? This is an oras artifact so that might be it. 

I was able to get the tags and manifest successfully! But wanted to report the issue in case others run into something similar with an oras config here. Please feel free to disregard if it's not important, or close if someone else has reported. Thank you!

**Comment by imjasonh** [comment]
It looks like that image has an empty config blob:

```
$ crane manifest ghcr.io/singularityhub/github-ci:latest
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.sylabs.sif.config.v1",
    "digest": "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "size": 0
  },
...
$ crane blob ghcr.io/signularityhub/github-ci@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
...
DENIED: requested access to the resource is denied
$ echo -n "" | sha256sum -
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

So the config is empty. I'm not sure what we should do in that case.

**Comment by vsoch** [comment]
Hmm... maybe the web UI could show an empty dict (or struct) to indicate to the viewer that the config is empty (and it's not some kind of hidden server error?)

**Comment by imjasonh** [comment]
(sorry I originally missed that you expected the config to be empty, my bad!)

That might be misleading because an empty `{}` might mean something else.

Maybe the UI or CLI could print something more clearly not a config like `<no config found>`.

In the CLI the error returns what ghcr responded with, which is somewhat confusingly an auth denial error and not a "not found" errorz

**Comment by vsoch** [comment]
No worries! I wonder if it might be possible for the server to see the user agent is a browser (or some other easy way to know how the page is requested) and then to print something in the body for the reader?  I definitely think the cli would be okay with the error - the case I'm thinking of is getting an all white window when I ask for the URL and not knowing what that means.

**Comment by vsoch** [comment]
> In the CLI the error returns what ghcr responded with, which is somewhat confusingly an auth denial error and not a "not found" error.

This would be useful too! This is probably something I could figure out if you want a PR, I enjoyed messing around with this tool before and would be happy to do that (probably can make some time in an evening this week!)

**Comment by vsoch** [comment]
Oh I just found this endpoint too - love this one!!! https://crane.ggcr.dev/digest/ghcr.io/singularityhub/github-ci:latest (sorry just got really happy about it lol)
