### ISSUE TITLE
Feature Request: Consider add concurrency and verbosity for `remote.Catalog`

### ISSUE THREAD

**Issue by Dentrax** [google/go-containerregistry#1278]
I've just tried `$ crane catalog` [command](https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/catalog.go) and it took so long that didn't even complete after several hours of run.

I think it would be great to add some _concurrency_ model and some _verbosity_ logs to check the current status of scan progress.

What do you think?

**Comment by imjasonh** [comment]
I wonder if `crane catalog` should print each page as it's returned, instead of calling `remote.Catalog` which loads all pages into memory before returning.

**Comment by jonjohnsonjr** [comment]
My gut reaction is "please please don't ever use catalog" :)

You can throw a `-v` flag to print verbose logs.

**Comment by jonjohnsonjr** [comment]
> I wonder if crane catalog should print each page as it's returned, instead of calling remote.Catalog which loads all pages into memory before returning.

We had some discussion around this originally but I think we just gave up.

https://github.com/google/go-containerregistry/pull/548
