### ISSUE TITLE
question: how to remove a label or annotation with crane

### ISSUE THREAD

**Issue by zhouhaibing089** [google/go-containerregistry#1288]
I'd always like to start with appreciation to the awesome tools like crane! We use this tool to push tarball as well as mutate image with new labels or annotations.

When I tried with:

```console
$ crane mutate <myimage> --annotation foo=bar
```

And I'm able to see the added annotation in:

```console
$ crane manifest <myimage> | jq '.'
```

However, when I try to think of removing this dummy annotation, it seems that there is no such option for me to do that, I'd hope something like below should work:

```console
$ crane mutate <myimage> --annotation foo-
```

(This syntax is similar to how kubectl removes labels or annotations).

**Comment by imjasonh** [comment]
There isn't currently a way to do this, though you should be able to set it to an empty string if that's acceptable.

We've tried adding it in #1063, maybe we just need to resurrect that work.

I'm curious what you're using annotations for that you'd like to be able to set and unset them -- most of the time I see annotations used, it's either to set the value if already unset, or to update its value if set. I don't think I've ever practically wanted to update an existing image to remove an annotation, honestly.

**Comment by zhouhaibing089** [comment]
@imjasonh: I'm still new to image annotations, so honestly, I don't know whether there will be a case of removing an annotation. My use case describe above is just an experimentation (or trying and then removing).

**Comment by zhouhaibing089** [comment]
I'd assume scenarios like:

1. made a mistake, and want to undo the change.
2. wanted to do a rename.
