### ISSUE TITLE
crane: mutate doesn't support setting the user

### ISSUE THREAD

**Issue by matthewrobertson** [google/go-containerregistry#1309]
From the [crane mutate docs](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_mutate.md), it seems that is it is not currently possible to set an Image's `config.user`. Is this an intentional omission or just waiting for someone to add it? If folks are open to it, I would be happy to submit a PR to add something like:

```
crane mutate my.image/foo:bar --user="33:33"
```

**Comment by imjasonh** [comment]
> s this an intentional omission or just waiting for someone to add it? If folks are open to it, I would be happy to submit a PR to add something like:

Not an intentional omission, just something we haven't had a strong need for yet. If you'd like to add this, I'd be happy to review your PR 😄

**Comment by matthewrobertson** [comment]
OK I will take a crack at this as it would be useful for a project I am working on. I will send a PR soon.
