### ISSUE TITLE
the number of image IDs and sizes obtained through remote.Image is incorrect

### ISSUE THREAD

**Issue by fengshunli** [google/go-containerregistry#1311]
![image](https://user-images.githubusercontent.com/18587688/156290868-cc2b9c51-c12a-46e0-87d2-f4a159aaa255.png)

id as follows
![image](https://user-images.githubusercontent.com/18587688/156290983-36b93e7d-69cb-4184-803e-d4be1c129b19.png)

size 
![image](https://user-images.githubusercontent.com/18587688/156291110-66d21497-ffe6-4e46-81a1-739a2880b186.png)

The size added by the layer will be biased

![image](https://user-images.githubusercontent.com/18587688/156291200-5cb43894-5461-45f7-9267-fc7c1abac90e.png)

**Comment by jonjohnsonjr** [comment]
Are you sure you're looking at the same image? Do the digests match?

**Comment by fengshunli** [comment]
close
