### ISSUE TITLE
authn: setting "Auth" field to Access Token throws `malformed HTTP Authorization header` error

### ISSUE THREAD

**Issue by Dentrax** [google/go-containerregistry#1314]
I was trying to use "Access Token" instead of "Bearer Token" that I generated the access token on the Docker Hub: https://hub.docker.com/settings/security

```golang
cfg := authn.FromConfig(authn.AuthConfig{
	Auth: my_docker_access_token,
})
remote.WithAuth(cfg)
```

But I got the following error while getting the digest:
```
GET https://auth.docker.io/token?scope=repository%3Afurkanturkal%2Fbusybox%3Apull&service=registry.docker.io: unexpected status code 400 Bad Request: {"details":"malformed HTTP Authorization header"}
```

If I set `IdentityToken` to my access token, I get:
```
POST https://auth.docker.io/token: unexpected status code 401 Unauthorized: {"details":"refresh_token grants not allowed"}
```

What about adding a new `AccessToken` support as we did for `RegistryToken`?
```golang
package authn

// AccessToken implements Authenticator for access token authentication.
type AccessToken struct {
	Token string
}

// Authorization implements Authenticator.
func (a *AccessToken) Authorization() (*AuthConfig, error) {
	return &AuthConfig{
		AccessToken: a.Token,
	}, nil
}
```
What I'm missing here? 🤔

**Comment by jonjohnsonjr** [comment]
Have you tried using it as an IdentityToken?

**Comment by Dentrax** [comment]
> Have you tried using it as an IdentityToken?

I tried and it threw: `refresh_token grants not allowed`.

**Comment by jonjohnsonjr** [comment]
It looks like you can just use it as a password with your username. Have
you tried that?

**Comment by Dentrax** [comment]
Combining `Username` with `IdentityToken` resulted: `{"details":"refresh_token grants not allowed"}`
But `Username` + `Password` (set Access Token) seems worked! Thanks.

It is makes sense to add a new field called `AccessToken` in `AuthConfig{}` and then using this in a new `type AccessToken struct {}` that implements `Authenticator` interface, as I proposed in the issue:

```golang
type AccessToken struct {
	Username string
	Token    string
}
```

By doing so, we can get rid of the following workaround:
```golang
cfg := authn.FromConfig(authn.AuthConfig{
		Username: "foo",
		Password: "bar", // notice that actually we're passing access token, not password
	})
	
	
remote.WithAuth(&authn.AccessToken{Username: "foo", Token: "bar"})
```

I can submit a PR for this, if you liked.

**Comment by jonjohnsonjr** [comment]
> By doing so, we can get rid of the following workaround:

This doesn't really seem like a workaround to me. From [DockerHub's docs](https://docs.docker.com/docker-hub/access-tokens/#use-an-access-token) on using access tokens, it seems like you're supposed to just use it as a password with your normal username, so I'd say that's working as intended? I might be missing something.

This is kind of confusing though. I'd definitely be open to documenting this better.

**Comment by Dentrax** [comment]
As you mentioned in [DockerHub's docs](https://docs.docker.com/docker-hub/access-tokens/#use-an-access-token), I think setting `username` and `password` is the right way we have to. So closing this one. Thanks!
