### ISSUE TITLE
[crane] "stream error: stream ID x; INTERNAL_ERROR"

### ISSUE THREAD

**Issue by AndolsiZied** [google/go-containerregistry#1318]
We are using kaniko to build a docker image and then push it to a private registry (scaleway) using crane. Sometimes crane returns the following error :
`+ crane push image.tar rg.fr-par.scw.cloud/ubuntu_18.04:2022-03-15_14-40-21
2022/03/15 14:41:03 existing blob: sha256:cf06a7c3161117888114e7e91dbd21915efae33c2dbfb086380f7b21946d6e59
2022/03/15 14:41:09 pushed blob: sha256:78ece0df92d6d52ab69ca4d0ced76e1d03200e4455d759dc5ca5aca199acb3c4
2022/03/15 14:41:09 retrying PUT https://rg.fr-par.scw.cloud/v2/ubuntu_18.04/blobs/uploads/8099cc20-8853-429d-b5fd-220c99f11393?_state=REDACTED&digest=sha256%3Abc085033e936eaf12354d53bd2b9ab308527ec35be00a99c5134d51512df40ff: UNKNOWN: unknown error; map[DriverName:s3aws Enclosed:map[RequestFailure:map[]]]
2022/03/15 14:41:37 pushed blob: sha256:bc085033e936eaf12354d53bd2b9ab308527ec35be00a99c5134d51512df40ff
Error: Patch "https://rg.fr-par.scw.cloud/v2/ubuntu_18.04/blobs/uploads/829952a7-55de-42dc-a5b7-574ae049d5d0": http2: Transport: cannot retry err [stream error: stream ID 25; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error`

It seems to be related to a [go issue](https://github.com/golang/go/issues/20985).
Which version of go is used in crane:debug image ? How we can build a new image with a new version of go ?

**Comment by imjasonh** [comment]
`gcr.io/go-containerregistry/crane:debug` was built using `go 1.17.8`

```
$ ko deps gcr.io/go-containerregistry/crane:debug --sbom=go.version-m
/ko-app/crane: go1.17.8
...
```
