### ISSUE TITLE
feature request: explore usage of sha256-simd

### ISSUE THREAD

**Issue by howardjohn** [google/go-containerregistry#1330]
https://github.com/minio/sha256-simd#drop-in-replacement

Currently when profiling building images, almost 95%+ of cpu time (and the CPU time is ~= wall time) is on sha256 operations. sha256-simd claims to make this much faster, which in turn could make image building faster.

I haven't proven it will actually have real impacts. Opening this to track + get some early feedback on if this is something that would be an acceptable dependency.

**Comment by imjasonh** [comment]
Seems worth experimenting with at least!

This should be the one place we create a sha256 hasher: https://github.com/google/go-containerregistry/blob/7e30746dde2f5a19b609f885dfef4e7b1d1503ad/pkg/v1/hash.go#L78

There also this, which should probably use `v1.Hasher()`: https://github.com/google/go-containerregistry/blob/e7cd6afc43c1dd7f1c5cb4e2dbab3836d9110b24/pkg/registry/manifest.go#L113

We might want to make a new experiment triggered on the presence of an env var, so folks can opt in to it for now. If it's promising we can make it opt-out.
