### ISSUE TITLE
v1/remote: `WithAuth` and `WithAuthFromKeychain` conflict

### ISSUE THREAD

**Issue by estroz** [google/go-containerregistry#1332]
### Describe the bug

Setting `WithAuthFromKeychain` and `WithAuth` will cause the explicitly-set `auth.Authenticator` from the latter to be overwritten.

### To Reproduce

```go
myAuth := remote.WithAuth(authn.FromConfig(authn.AuthConfig{
	Username: "estroz",
	Password: "password",
}))
// Assuming you have no local config or config does not contain myAuth's creds,
// this keychain's Resolve() will return authn.Anonymous.
myKeychain := remote.WithAuthFromKeychain(authn.DefaultKeychain)

const srcImage = `docker.io/library/nginx:latest`
srcRef, err := name.ParseReference(srcImage)
if err != nil {
	panic(err)
}

img, err := remote.Image(srcRef, myAuth)
if err != nil {
	panic(err)
}

const dstImage = `docker.io/estroz/nginx:testtag1`
dstRef, err := name.ParseReference(dstImage)
if err != nil {
	panic(err)
}

badOpts := []remote.Option{myKeychain, myAuth}
if err := remote.Write(dstRef, img, badOpts...); err != nil {
	fmt.Println("badopts:", err) // this prints
}

goodOpts := []remote.Option{myAuth}
if err := remote.Write(dstRef, img, goodOpts...); err != nil {
	fmt.Println("goodopts:", err) // this does not print
}
```

### Expected behavior

If auth is explicitly set, use it and either ignore keychain or return an error that both cannot be set.

### Additional context

Relates to #156

- Version: v0.8.0
- Registry: DockerHub (but I image this would result from any authenticated registry usage)

**Comment by estroz** [comment]
I can fix this if accepted.

**Comment by imjasonh** [comment]
Agree this is an issue. At the very least we should document it, and probably validate and raise an error if both are provided, instead of silently choosing one over the other.

If you're interested in sending a PR I'd be happy to review it. If you need any help let me know 👍

**Comment by estroz** [comment]
I'll send a PR, thanks for verifying!
