### ISSUE TITLE
2 CVEs detected in go library @ 0.8.0 (latest)

### ISSUE THREAD

**Issue by mipnw** [google/go-containerregistry#1345]
### Describe the bug
scanning the go library @ v0.8.0 (latest) for known CVEs finds the following issues
```
Total: 2 (UNKNOWN: 2, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

+--------------------------------------+------------------+----------+--------------------------------------+---------------+--------------------------------+
|               LIBRARY                | VULNERABILITY ID | SEVERITY |          INSTALLED VERSION           | FIXED VERSION |             TITLE              |
+--------------------------------------+------------------+----------+--------------------------------------+---------------+--------------------------------+
| github.com/docker/distribution       | GMS-2022-20      | UNKNOWN  | v2.7.1+incompatible                  | v2.8.0        | OCI Manifest Type Confusion    |
|                                      |                  |          |                                      |               | Issue                          |
+--------------------------------------+------------------+          +--------------------------------------+---------------+--------------------------------+
| github.com/opencontainers/image-spec | GMS-2021-101     |          | v1.0.2-0.20211117181255-693428a734f5 | 1.0.2         | Clarify `mediaType` handling   |
+--------------------------------------+------------------+----------+--------------------------------------+---------------+--------------------------------+
```

The first CVE appears to have already been handled, go.mod in master references github.com/docker/distribution @ v2.8.0 already, but that change is after your latest release.

The second CVE also appears to have been handled, go.mod in master references github.com/opencontainers/image-spec v1.0.3-0.20220114050600-8b9d41f48198.

It would be nice to create a new release with those updates so a dependent project can reference this library without introducing known CVEs into that project.

### To Reproduce
reference this go library in a go.mod, build any executable, `COPY` that executable to an alpine:latest docker image, run `trivy image` on that docker image to scan it.

### Expected behavior

No CVEs.

**Comment by imjasonh** [comment]
This library wasn't affected by either of those CVEs, though I understand this still leads to noise and churn among downstream users regardless.

I think we could probably do with a new release anyway, there've been a few improvements we should "officially" get out the door. When a few of the in-flight PRs land I'll see about cutting a v0.9.0.

**Comment by MaggotMouth** [comment]
Hi @imjasonh 
Are there any particular in-flight PRs you're waiting for that we can follow progress on?

**Comment by M1cha** [comment]
You can simply depend on the main branch or a specific revision instead of the tag to solve this issue.
That being said, we're at 0.11.0 now so your particular issue should be fixed.
