### ISSUE TITLE
gcrane: (feature request) allow gcrane copy --recursive to use non-standard ports

### ISSUE THREAD

**Issue by neoakris** [google/go-containerregistry#1354]
### Description of Desire Feature
I wish the following command would work:  
`gcrane copy --recursive 127.0.0.1:5000 https://myregistry.mydomain.tld`

It gives the following error
```console
Error: parsing repo "127.0.0.1:5000": repository can only contain the 
runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: 127.0.0.1:5000
```
`:` is the specific thing it doesn't like, and the very thing used to denote a non-standard port serving https. (`https://some.name:5000`)

### Additional context
I wrote some internet disconnected container registry image import logic that's intended to work like this:  

**Summary:  
Use an "ephemeral transport registry" & gcrane to deliver initial payload for env bootstrapping (assume no pre-existing infra) + updates to internet disconnected registry.**  

**Details:**  
1. Pull from internet into registry:2 based registry, mounted on local file system
2. Stop the registry:2 and tar up the contents that got mounted on the local file system
3. Transfer the tar'd contents of registry:2 over an air gap boundary
4. untar the contents on an internet disconnected computer, import registry:2 container image, and load registry:2 on the internet disconnected computer using the pre-populated files. (It's like an air gap import of a pre-populated registry, that respects the space saving efficiencies of layered images since it's the registry instead of a docker save based export)
5. The last step I wanted to do was: 
I intended to have a long lived container registry exist in the internet disconnected environment, accessible via https://myregistry.mydomain.tld:443, I loaded my ephemeral transport registry on the same host where the long lived registry was hosted so port 443 was already taken, at which point I decided to use port 5000 (I didn't want to introduce a temporary machine with an unused port 443 as a hard requirement for image imports.)   

I wanted to use gcrane to do a copy from 127.0.0.1:5000 --> https://myregistry.mydomain.tld:443 over localhost.

Leveraging the --recursive flag would import 100% of images from the ephemeral transport registry into the long lived registry. After the transfer was done I planned to stop the ephemeral transport registry's container / close port 5000, and delete the temporarily imported untar'd contents.

(I wanted to use it as a streamlined method of delivering container image updates to the long lived internet disconnected registry)

But when I got to the final step, I unexpected ran into the error message and discovered that gcrane can only use port 443 :( 

**I wanted to ask if my feature request is possible to implement?** 
(In the mean time I plan to look into rancher's hauler.)

- Output of `crane version` = 0.8.0
- Registry used (e.g., GCR, ECR, Quay) = registry:2 (both source and destination registry)

**Comment by neoakris** [comment]
Maybe this is a bug and not a feature request?

`gcrane copy 127.0.0.1:5000/ironbank/big-bang/base:1.0.0 registry.bigbang.dev/ironbank/big-bang/base:1.0.0`

^-- The above works

So since copy without --recursive works with non-standard port
copy with --recursive should also work with non-standard port

**Comment by jonjohnsonjr** [comment]
Does your registry happen to implement GCR's extensions to the registry API?

`gcrane cp -r` only really works with GCR or Artifact Registry because there isn't actually a suitable API for doing this (see https://github.com/opencontainers/distribution-spec/issues/222 for some fun filibustering).

The closest you can really get is using catalog and tag listing:

```bash
for repo in $(crane catalog localhost:5000); do
  for tag in $(crane ls "localhost:5000/$repo"); do
    crane cp "locahost:5000/$repo:$tag" "myregistry.mydomain.tld/$repo:$tag"
  done
done
```

**Comment by neoakris** [comment]
Thanks I ended up doing something very similar only difference was I used some loop to generate a declarative sync.yaml config file, for a tool called regsync, and then used that to syn the 2 repos. It worked with non-standard ports and had smart logic where if nothing needed to be done on a 2nd run, the second run would go quickly.

The registry I used was just the registry:2 docker image. Based on the error message though it didn't even try once it saw I was hosting it on port :5000, it doesn't error when the --recursive flag isn't used, which is why I suspect it could be a bug.

**Comment by jonjohnsonjr** [comment]
> untar the contents on an internet disconnected computer, import registry:2 container image, and load registry:2 on the internet disconnected computer using the pre-populated files. (It's like an air gap import of a pre-populated registry, that respects the space saving efficiencies of layered images since it's the registry instead of a docker save based export)

We're not quite there yet (https://github.com/google/go-containerregistry/pull/1211), but we want to make it straightforward to use an [OCI layout](https://github.com/opencontainers/image-spec/blob/main/image-layout.md) for this purpose. IMO that would be a little bit conceptually cleaner than shipping a whole registry around (in fact you're not the first person I know to do this), but I haven't gotten around to making it easy.

@sudo-bmitch might have something for this already, though?

**Comment by sudo-bmitch** [comment]
@jonjohnsonjr indeed, regsync (and other regclient tools) will support OCI Layout using `ocidir://path/to/dir` which avoids the need to run a registry for the air-gapped transports.

**Comment by jonjohnsonjr** [comment]
Going to close this out because I think you found a good solution 👍
