### ISSUE TITLE
feature request: (g)crane copy tags

### ISSUE THREAD

**Issue by iuadastra** [google/go-containerregistry#1355]
Would be great to have the possibility to copy tags of an image. Something like this to copy tags to the destination with the image:
`gcrane copy --preserve-tags repo.com/myimage:1.0.0 dest-repo.com`

or to add tags while copying:

`gcrane copy --preserve-tags --tag latest --tag 1.0 --tag 1 repo.com/myimage:1.0.0 dest-repo.com`

**Comment by jonjohnsonjr** [comment]
`gcrane cp -r` will preserve tags, but also copies the entire repository. I agree it would be nice to have a flag to do this for a single image.

There's a flag in `docker` when pushing (`--all-tags` or `-a`) that does something similar enough to this that I wouldn't mind stealing that.

**Comment by iuadastra** [comment]
Not stale
