### ISSUE TITLE
question: Include jq in debug container?

### ISSUE THREAD

**Issue by DarwinJS** [google/go-containerregistry#1356]
While I love minimal containers, ones that leave the package manager off make it difficult to work inside the container.

The GitLab example (thank you for that!) is an example where the job run inside the container - and with the package manager not present, it is challenging to add jq.

Since all the output of crane is json, would it be possible to install jq on the debug tag - or at least the os package manager so one can pull on their desired additional utils?

Thanks for any thoughts!

**Comment by imjasonh** [comment]
I'd be willing to consider it. `jq` is pretty small and generally pretty well trusted.

To do it, we'd have to build that base image to include `jq`, and I think if we were going to do that I'd probably want to use [apko](https://github.com/chainguard-dev/apko) to do it declaratively, and build that every time the `crane` image is built and published.

**Comment by DarwinJS** [comment]
That would be fantastic - if apk was in there I could also pull git which is another frequent need - for git ops flows I have to commit updated manifests back.

**Comment by developer-guy** [comment]
Kindly ping @imjasonh, it looks like a fantastic issue that can help to learn _apko & melange_ projects to build an OCI image with the given packages, but can you give me a bit more context about what needs to be done? Where should we start?

**Comment by imjasonh** [comment]
> Kindly ping @imjasonh, it looks like a fantastic issue that can help to learn _apko & melange_ projects to build an OCI image with the given packages, but can you give me a bit more context about what needs to be done? Where should we start?

Sure thing. There's already a `jq` package for Wolfi ([here](https://github.com/chainguard-dev/wolfi-os/blob/main/jq.yaml)), so it should be pretty easy to build a base image for it.

We can have the image release process build and push the base before building the crane container on top of it.

What else do we want in the debug base image? busybox, git, jq, anything else?

**Comment by developer-guy** [comment]
>Sure thing. There's already a jq package for Wolfi ([here](https://github.com/chainguard-dev/wolfi-os/blob/main/jq.yaml?rgh-link-date=2022-09-28T12%3A40%3A59Z)), so it should be pretty easy to build a base image for it.

So, you mean that, instead of searching _jq_ tool in the upstream alpine package repositories, we can look at the _Wolfi OS_ repo to download it while using _apko_? Something like the following:

```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - build-base
    - busybox
    - git
    - jq
...
```

**Comment by imjasonh** [comment]
Yep, basically that! 👍

**Comment by developer-guy** [comment]
So here is the plan, wdyt?

* Create a _melange.yaml_ file inside the crane repo.
* Add the packages above
* Add necessary GitHub Actions workflow to build the base package
  *   - '@local /github/workspace/packages'
  * - crane-base@local
* Add _apko.yaml_ file inside the crane repo
* Add _crane-base@local_ package to the list
* Follow the example here to build the crane project
  * https://github.com/chainguard-dev/hello-melange-apko/tree/main/go

**Comment by imjasonh** [comment]
I don't think we even need to involve melange.

- add debug-base.yaml that includes the debug packages listed above
- during release, `apko publish debug-base.yaml $REPO/debug-base`
- update `.ko/debug/.ko.yaml` to specify `defaultBaseImage: $REPO/debug-base`
- still build and tag the debug image using `ko`, and `KO_CONFIG_PATH=.ko/debug/.ko.yaml`, like we do today.

**Comment by robross0606** [comment]
While I love containers being light weight, the fact that no package manager is available in these containers _really_ hinders their further usage.  I need both `jq` and `curl` in my GitLab pipeline to do some tagging and API notifications.  I'd love to use the `gcr.io/go-containerregistry/crane:debug` image, but it is stripped of anything but busybox and `dpkg` which makes it night impossible to extend slightly and use.
