### ISSUE TITLE
ggcr: bearer transport for OAuth 2.0: sets always: service

### ISSUE THREAD

**Issue by Andrei-Stepanov** [google/go-containerregistry#1359]
### Describe the bug

bearer transport OAuth 2.0: sets always: service

This has impact on kaniko tool too.

### To Reproduce

crane -v pull registry-proxy.domain.com/rh-osbs/marked:latest test.tar 

```
2022/05/06 14:37:04 <-- 401 https://registry-proxy.domain.com/v2/ (483.912621ms)
2022/05/06 14:37:04 HTTP/2.0 401 Unauthorized
Content-Length: 4
Content-Type: text/html; charset=utf-8
Date: Fri, 06 May 2022 12:37:03 GMT
Docker-Distribution-Api-Version: registry/2.0
Server: nginx/1.18.0
Set-Cookie: e78173cf68a07c2689cf2c5497bbc335=dcd6a5197e32af8bab373f164c2693d5; path=/; HttpOnly; Secure; SameSite=None
Www-Authenticate: Bearer realm="https://registry-proxy.domain.com/v2/auth" <--------------- challenge doesn't ask to add service!!!!!

BUG service is set: 2022/05/06 14:37:04 <-- 200 https://registry-proxy.domain.com/v2/auth?scope=repository%3Arh-osbs%2Fmarked%3Apull&service=registry-proxy.domain.com (215.331066ms) [body redacted: basic token response contains credentials]
2022/05/06 14:37:04 HTTP/2.0 200 OK
Content-Length: 1089
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Date: Fri, 06 May 2022 12:37:04 GMT
Server: nginx/1.18.0
Set-Cookie: e78173cf68a07c2689cf2c5497bbc335=0d2d688f655a467012bdb10de835afe2; path=/; HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=63072000; preload
X-Frame-Options: DENY
```

Error that it adds: `service=registry-proxy.domain.com`

### Expected behavior

Do not add `service` param in token request, if challenge doesn't ask it.

### Additional context

Docker - works, podman - works. google/go-containerregistry -- fails

It fails at:

https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/transport/bearer.go#L236

Compare with docker implementation:

https://github.com/containers/common/blob/main/vendor/github.com/containers/image/v5/docker/docker_client.go#L643

it add `service` ONLY if  challenge requires it.

More links:

https://docs.docker.com/registry/spec/auth/token/#how-to-authenticate
https://docs.docker.com/registry/spec/auth/oauth/

Thank you!

Kaniko fails with:

```
unexpected status code 401 Unauthorized: {"error": "Invalid audience"}
```

**Comment by imjasonh** [comment]
Seems like this will also need to be changed:

https://github.com/google/go-containerregistry/blob/9d1ceb8c5d43571c8883eadcd2722226ed124350/pkg/v1/remote/transport/transport.go#L79-L84

I'm not totally sure of the context for this, this code was present in the [initial dump of code from the internal monorepo, four years ago](https://github.com/google/go-containerregistry/commit/35881749c720afef926963dbb76bebfca188c2c1). Perhaps @jonjohnsonjr remembers why this is. I think it's likely this was just what GCR required, and we should relax it.
