### ISSUE TITLE
crane ls should use catalog to list directories

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#137]
Right now it only shows tags :-/

**Comment by jonjohnsonjr** [comment]
this is high effort low impact

**Comment by sding3** [comment]
If the argument parses out to be just a hostname rather than hostname/path, would it be reasonable for crane ls to instead list repos instead listing tags? If this is fine, then it doesn't seem too difficult.

**Comment by imjasonh** [comment]
`crane catalog` does what you want today, and lists repos. I think it's best that `crane ls` and `crane.List` remain clear about which API they call, and don't try to detect and fallback to call the catalog API.
