### ISSUE TITLE
[crane]is there any limitation for the copy command?

### ISSUE THREAD

**Issue by jinhli** [google/go-containerregistry#1392]
When I tried to copy the remote image to our project registry, we have seen the error:
[root@localhost ~]# crane copy quay.io/jinhli0/ubi8-test:v1.01 scan.connect.redhat.com/ospid-62414b36b5917300d77420d3/ubi8-test:v1.05
2022/06/22 11:21:02 Copying from quay.io/jinhli0/ubi8-test:v1.01 to scan.connect.redhat.com/ospid-62414b36b5917300d77420d3/ubi8-test:v1.05
2022/06/22 11:21:09 existing blob: sha256:1e138cc587efeb444984d95818b13909f87b533ec332e4a5a3c3509033b02676
2022/06/22 11:21:09 existing blob: sha256:54f0477c3969cf4cc0ae16c93e0d7852e4b15b17fa403d632f8cfec908fa9ce1
2022/06/22 11:21:09 existing blob: sha256:573049177a7d6b5c1034ee9e00243321f398c5dca2c5bdf396b759dcca9b0d7b
2022/06/22 11:21:09 existing blob: sha256:316cc4daa01c624d4c36121a64cb49e364e8dedb1718fb821d20995e5bc783ba
2022/06/22 11:21:10 existing blob: sha256:54183f4a56792b5ec75ef38ba9e7d6404a2e0ec89e3b9a7117949baf7e2a690c
2022/06/22 11:23:48 failed to copy image: Patch "https://scan.connect.redhat.com/v2/ospid-62414b36b5917300d77420d3/ubi8-test/blobs/uploads/d06bfb21-caa2-495f-ac68-5a78221e74ba?_state=WachxhOFj83ZdKgCjXVq5nFkLpyO8bge8RWxVCHf7Nx7Ik5hbWUiOiJvc3BpZC02MjQxNGIzNmI1OTE3MzAwZDc3NDIwZDMvdWJpOC10ZXN0IiwiVVVJRCI6ImQwNmJmYjIxLWNhYTItNDk1Zi1hYzY4LTVhNzgyMjFlNzRiYSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0wNi0yMlQwMzoxOTo0MS4yMzU4NzEzMjNaIn0%3D": stream error: stream ID 19; INTERNAL_ERROR

**Comment by imjasonh** [comment]
This error sounds like a transient error pushing to the destination registry. It's possible `crane` could detect and retry that error, but I'm not sure without knowing more about the error.

In any case, I'd recommend retrying the copy until it works. If this happens regularly, you may want to file a ticket with the destination registry service.

**Comment by jonjohnsonjr** [comment]
Possibly related to https://github.com/golang/go/issues/36759
