### ISSUE TITLE
ggcr: name.NewDigest allows invalid SHAs

### ISSUE THREAD

**Issue by wlynch** [google/go-containerregistry#1394]
### Describe the bug

[`name.NewDigest`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/name#NewDigest) validation will consider any digest that contains the right # of characters with any characters in the [character set](https://github.com/google/go-containerregistry/blob/0c40ec8ad2226e1d374f1f1c01d5694f505ff946/pkg/name/digest.go#L24) as valid.

This means that something like `repo@sha256:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::` will be considered a "valid" digest

### To Reproduce

https://go.dev/play/p/VXkHg7T_BQY

### Expected behavior

NewDigest rejects invalid SHAs.

### Additional context

There's a TODO to replace the digest implementation - https://github.com/google/go-containerregistry/blob/0c40ec8ad2226e1d374f1f1c01d5694f505ff946/pkg/name/digest.go#L23 maybe this is a reason to make the change? 🤔

**Comment by jonjohnsonjr** [comment]
PR definitely welcome 😅
