### ISSUE TITLE
400 The plain HTTP request was sent to HTTPS portquestion:

### ISSUE THREAD

**Issue by testwill** [google/go-containerregistry#1405]
crane.Pull function failed, err : GET http://192.168.0.105:443/v2/: unexpected status code 400 Bad Request: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

**Comment by maoyangLiu** [comment]
@testwill  I met the same question, Have you solved this problem now

**Comment by testwill** [comment]
http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}

**Comment by apolovov** [comment]
@testwill @maoyangLiu we faced the same crash using the library. And @yalosev figured out that there are weird conditions in code:
https://github.com/google/go-containerregistry/blob/main/pkg/name/registry.go#L25

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/pull/1521 should improve this, hopefully.
