### ISSUE TITLE
question: are there symlinks in images?

### ISSUE THREAD

**Issue by abitrolly** [google/go-containerregistry#1428]
I found that `tarball.image` for some reason processes symlinks.

https://github.com/google/go-containerregistry/blob/7196cf3dc436a7633687b0c83ba76318f70e26f2/pkg/v1/tarball/image.go#L237-L239

However, in description of the image structure, I don't see how symlinks can be useful. Are they really used in wild at this level of image parsing?

https://github.com/google/go-containerregistry/blob/main/pkg/v1/tarball/README.md#structure

**Comment by imjasonh** [comment]
I think this is a case of [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle), where `tarball.Image` should be liberal in what it accepts from images it may be asked to process, but conservative in what it produces itself.

We can't necessarily assume a tarball that `crane push` is being given for example came from a previous `crane pull`, so we should handle the case where the tar includes a symlink even if we ourselves would never produce such a tar.
