### ISSUE TITLE
FR: Support OCI reference types

### ISSUE THREAD

**Issue by developer-guy** [google/go-containerregistry#1434]
Once I run `crane copy,` it'll (at the time of writing this) copy only the image itself, but the image may have other materials attached to it such as SBOMs, attestations, signatures, etc. `cosign copy` command supports that, but in crane, we do not have support for this, so, it'd be better copying these materials (if any) with the image itself optionally.

cc: @dentrax @imjasonh

**Comment by imjasonh** [comment]
To put this in crane we'll need to rely on the new APIs and conventions proposed by the OCI reference types working group:

- proposed image-spec changes: https://github.com/opencontainers/image-spec/pull/934
- proposed distribution-spec changes: https://github.com/opencontainers/distribution-spec/pull/335

We expect these spec changes to be merged in soon 🤞, then for these changes to start trickling out to registry implementations over the next few years. The fallback behavior described in those changes relies on tag naming conventions, for compatibility with registries that haven't adopted the new specs yet.

@jdolitsky has been hacking on changes to go-containerregistry and crane to add support for these APIs here: https://github.com/google/go-containerregistry/compare/main...oci-playground:main

When these APIs and conventions are adopted and the changes above are merged into ggcr, the idea is you'll be able to `crane cp -R <src> <dst>` (`-R` for `--recursive`) and not only copy the source image, but all artifacts that reference it, SBOMs, signatures, attestations, cat pictures, whatever.

**Comment by developer-guy** [comment]
It looks like these PRs are merged, so shall we start working on this issue?

**Comment by imjasonh** [comment]
> It looks like these PRs are merged, so shall we start working on this issue?

See https://github.com/google/go-containerregistry/pull/1455
