### ISSUE TITLE
Cache repo cannot contain a port

### ISSUE THREAD

**Issue by iamkhalidbashir** [google/go-containerregistry#1441]
### Describe the bug

When using the --cache-repo flag, passing a private repo URL containing a port in the URL throws an error
```
WARN[0452] error uploading layer to cache: getting a tag for destination: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: host.docker.internal:6000 
```

### To Reproduce

Use the --cache-repo flag, passing a private repo URL containing a port in the URL

### Expected behavior

Should allow url

**Comment by imjasonh** [comment]
This sounds like a Kaniko bug, not a go-containerregistry bug.

The code Kaniko uses to handle the `--cache-repo` flag is around here: 
https://github.com/GoogleContainerTools/kaniko/blob/986121553be04f5cd23f96e0d0443cd6212cfb25/pkg/cache/cache.go#L97

go-containerregistry's `pkg/name.NewRepository`, `NewTag`, etc., all support parsing registry URLs that specify ports: https://go.dev/play/p/ItiHcL5swnV
