### ISSUE TITLE
crane: Add ability to pass in registry credentials part of crane mutation commands (like copy, pull, push, delete, etc) 

### ISSUE THREAD

**Issue by hariohmprasath** [google/go-containerregistry#1445]
### Describe the bug

Add ability to pass in registry credentials part of crane mutation commands (like copy, pull, push, delete, etc) instead of first performing `crane auth` and then running these commands. Sample commands:

```
crane pull <repository> --username <user> --password <password>
crane push <repository> --username <user> --password <password>
```

### To Reproduce

Only way to push or pull images from registries that requires authentication is to first run `crane auth <credentials>` then execute `crane <copy, pull, push, delete, etc>` commands

### Expected behavior

I would like to use AWS Lambda or Google cloud run to perform image pull and push across various repositories in different customer accounts. Since these serverless computes only accepts one IAM role per function. Only way to do this securely is to pass in the container registries credentials to the serverless function as input parameters, use them as part of `crane auth` command, then run the actual command like `crane pull or push or copy`. But `crane auth` will create a `config.yaml` and store the auth token as plain text which is not secure and making it not suitable to be used on a shared compute. So if crane commands can accept optional registry credentials part of `crane copy, pull, push, delete` commands and use it while performing these registry actions without storing the auth token in temporary location, we could run crane on computers that gets shared across different executions.

### Additional context

Even though crane supports multiple credentials helpers like `osxkeychain`, `pass`, `ecr` and `gcp` because of limitations associated with the file system access and ability to attach just one IAM role per serverless computes (like AWS Lambda and Google cloud run) makes it impossible to use these credential helpers store auth tokens.

- Output of `crane version` - 0.11.0
- Registry used (e.g., GCR, ECR, Quay) - GCR, ECR, dockerhub

**Comment by imjasonh** [comment]
Unfortunately I don't think this would be a good fit for `crane`, since it encourages using hard-coded, and often long-lived, credentials.

If you're comfortable writing some Go you can build this yourself using e.g., [`crane.Pull`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/crane#Pull), [`crane.WithAuth`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/crane#WithAuth) and [`authn.Basic`](https://pkg.go.dev/github.com/google/go-containerregistry@v0.11.0/pkg/authn#Basic).

**Comment by hariohmprasath** [comment]
Thanks for letting me know
