### ISSUE TITLE
crane: multi-arch images copied and pushed, but one of them doesn't work with some commands.

### ISSUE THREAD

**Issue by ozbillwang** [google/go-containerregistry#1460]
### Describe the bug

regarding this issue https://github.com/alpine-docker/git/issues/49

I maintain multi-arch images for public hub docker image `alpine/git`, with below code, I do the local build (multi-arch build with `docker buildx`), push the image to hub.docker.com, then use **crone** to copy and generate two new tags on hub.docker.com as well.

The build runs on Travis CI , a reference pipeline log can be reviewed at here: https://app.travis-ci.com/github/alpine-docker/git/builds/256286326

```
  DOCKER_PUSH="docker buildx build --no-cache --push --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/ppc64le,linux/s390x"

  ${DOCKER_PUSH} -t ${image}:v${VERSION} .
  ./crane copy ${image}:v${VERSION} ${image}:latest
  ./crane copy ${image}:v${VERSION} ${image}:${VERSION}
```
One user reports several arch (**aarch64** and **arm64**) works with v2.36.2 (that's local build and pushed via `docker buildx`), but doesn't work with tag `2.36.2` and `latest` (they are copied and pushed by crane)

no problem in other arch  (Or no tests to other arch, except of amd64, I can test `amd64` on my laptop)

### To Reproduce

```
FROM alpine/git:latest
RUN apk add --no-cache patch
````
get error 
```
------
error: failed to solve: executor failed running [/bin/sh -c apk add --no-cache patch]: exit code: 1`
```
but with tag v2.36.2, it is fine.

```
FROM alpine/git:v2.36.2
RUN apk add --no-cache patch
```

**EXTRA NOTES:** I don't have `amd64` environment to run the test. 

### Expected behavior

should get same result with same images.

### Additional context

the digest are same for these tags

![image](https://user-images.githubusercontent.com/8954908/194441643-3dc50ce5-4bd2-4d32-9c19-7c17404a40d2.png)

- Output of `crane version`

should be **v0.11.0** (you can confirm from the pipeline's logs (https://app.travis-ci.com/github/alpine-docker/git/builds/256286326)
```
+curl -LO https://github.com/google/go-containerregistry/releases/download/v0.11.0/go-containerregistry_Linux_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6690k  100 6690k    0     0  17.5M      0 --:--:-- --:--:-- --:--:-- 17.5M
```
- Registry used (e.g., GCR, ECR, Quay)
hub.docker.com

**Comment by jonjohnsonjr** [comment]
> the digest are same for these tags

If all the tags have the same digest, I don't think there's an issue with `crane`. Is it possible that their docker client had cached an older tag value that was broken?

**Comment by ozbillwang** [comment]
I stand up with your side.

For this issue, I have no environment to verify the problem, will check with the reporter.
