### ISSUE TITLE
ggcr: Write functions don't close progress channel when an early error is encountered

### ISSUE THREAD

**Issue by ibuildthecloud** [google/go-containerregistry#1461]
### Describe the bug

On write functions progress channel is not always closed when there is an early error. For example here: https://github.com/google/go-containerregistry/blob/7268da01c46ecfb72a3ef6f44d0393f650879663/pkg/v1/remote/write.go#L654.  This makes it difficult for the caller of the function to know if they should close the channel or not when an error is returned.

### To Reproduce

Call remote.WriteIndex with a bad password

### Expected behavior

The methods that take a progress opt always close the progress channel on error and send the method error in the channel

### Additional context

- Version of the module v0.11.0

**Comment by imjasonh** [comment]
Good catch. I agree it should close the channel in this case. 👍
