### ISSUE TITLE
ggcr: Allow path in registry URIs

### ISSUE THREAD

**Issue by nivbend** [google/go-containerregistry#1464]
### Describe the bug

This was already raised in #1089, but it seems that working with registries that contain a path part before the repositories' names isn't well supported. This is because it's assumed (and enforced) that the registry's name is only the `host[:port]` part of the URI but some registries, for example JFrog Artifactory, provide the Docker V2 endpoint at a certain path.

The suggested solution in #1089 doesn't seem to work when dealing with the `remote` package.

### To Reproduce

```go
reference, _ := name.ParseReference("example.jfrog.io/artifactory/api/docker/my-repository/my-image:latest")
_, err := remote.Image(reference)
fmt.Println(err.Error())
```

Would give:
```
GET https://example.jfrog.io/v2/artifactory/api/docker/my-repository/my-image/manifests/latest: : Not Found
```

But if we move the `/v2` to the correct place it'll work (commands and output shortened for brevity):
```sh
$ curl https://example.jfrog.io/artifactory/api/docker/my-repository/v2/_catalog
{
  "repositories" : [ "my-image" ]
}
$ curl -v https://example.jfrog.io/artifactory/api/docker/my-repository/v2/my-image/manifests/latest
...
< HTTP/1.1 200 OK
...
```

### Expected behavior

First, the ability to construct a `Registry` with a path part should be provided. Second, that path should be honored when constructing the resources' URLs.

### Additional context

- Version: All up to the latest (`v0.11.0` and current `main`).
- Registry used: JFrog Artifactory, but it's not unlikely that others exist.

**Comment by imjasonh** [comment]
I don't think this behavior is well specified by OCI distribution-spec. The URLs in the spec are all described as, e.g., `/v2/<name>/blobs/<digest>` ([src](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-blobs)), which can be ambiguously interpreted to mean they must be rooted at the hostname, and not include any preceding path elements.

We should try to update distribution-spec to clarify this expectation, one way or another.

Does `docker push` accept Artifactory URLs like you describe? I assume it does. That would be a strong point in favor of modifying the spec to allow them.

**Comment by nivbend** [comment]
> Does docker push accept Artifactory URLs like you describe? I assume it does. That would be a strong point in favor of modifying the spec to allow them.

Actually it doesn't because it also assumes the `v2/` should be right after the hostname... Or at least I didn't get it to work.

`docker login` works, but that's because `example.jfrog.io/v2` returns 200 OK. Access to a specific image is by prefixing it with the repository (again, in the Artifactory sense): `example.jfrog.io/v2/my-repository/my-image/tags/list`.

I think I now understand my initial thinking was somewhat off, I should've considered the _Artifactory_ repository name as part of the _Docker_ repository name (i.e., `my-repository/my-image` as opposed to `my-image` in a "my-repository" sub-registry thing).

A remaining issue is that the way JFrog works is that `example.jfrog.io/v2/_catalog` doesn't return anything, not even a `{}`, you need to add the repository (in the JFrog Artifactory sense, not the Docker one) name, i.e., `example.jfrog.io/v2/my-repository/_catalog`. So if we want to list all the (Docker) repositories in Artifactory, as a whole or in a specific Artifactory repository, we can't do that with `remote.Catalog` or `remote.CatalogPage` because the `/v2/_catalog` is hardcoded.

So on my end I'll close #1465 for now since that seems unnecessary and I'll refactor my code to handle these issues without changes to `go-containerregistry`.

Regarding the `v2/my-repository/_catalog` issue, would you be open to handling this idiosyncrasy in `remote`? Maybe adding a `PrefixPath("my-repository")` kind of `Option` that'll modify that currently hard-coded `/v2/_catalog` path?

Hope I made this as clear as possible with the "repository" term collision between Artifactory and Docker.

**Comment by imjasonh** [comment]
I might consider a prefixing option for `remote.Catalog` specifically. That's a weird one in general because the `_catalog` endpoint isn't specified by OCI, it just happens to be the convention that Docker invented and others continued. Even [Docker's description of `_catalog`](https://docs.docker.com/registry/spec/api/#listing-repositories) seems to indicate it should be at the root, so Artifactory may be out of "spec" there (such as it is).

**Comment by dfreilich** [comment]
+1 on all this! I encountered this while trying to get `crane catalog example.jfrog.io` to work
