### ISSUE TITLE
k8schain: does not ignore missing pull secrets like Kubernetes does

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#1471]
### Describe the bug

If an `imagePullSecrets` is missing the `kubernetes` keychain returns the error:
https://github.com/google/go-containerregistry/blob/02f47e132cf562183cfd7cf272c0605e6183ba53/pkg/authn/kubernetes/keychain.go#L67-L70

However, in kubernetes these are logged and ignored (TIL!):
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/2442466/197318356-04c20a8f-e77c-4cb7-9c81-54e30a91f663.png">

For **necessary** pull secrets, the behavior here is arguably desirable because you get a clear error message to surface to users.

However, if the goal is blind compatibility with Kubernetes semantics, then this manifests errors for **unnecessary** pull secrets where Kubernetes deploys things just fine!

### To Reproduce

1. Create a pod that deploys just fine, and add a non-existent pull secret.
2. Enable `sigstore/policy-controller` on the namespace and try again
3. 💥 

### Additional context

I believe that this would affect Knative (cc @dprotaso @evankanderson), Tekton (cc @imjasonh, @vdemeester), I know it affects `sigstore/policy-controller` (cc @vaikas @hectorj2f).  cc @sudo-bmitch @jonjohnsonjr @dlorenc FYI

I could go either way on this, so I figured I'd tag some stakeholders and solicit opinions. 🍿

**Comment by dprotaso** [comment]
Just as an FYI to others - k8schain is static. So if secrets are missing the resulting chain is a noop and you need to recreate the chain when retrying.

**Comment by imjasonh** [comment]
> Just as an FYI to others - k8schain is static. So if secrets are missing the resulting chain is a noop and you need to recreate the chain when retrying in order to refetch

This is true. If this is a problem for anybody we can definitely rework it so the secrets are refetched from a lister, or updated after some expiration. Open to ideas based on usage and needs.
