### ISSUE TITLE
crane: cp doesn't work for docker.io -- `invalid character 'c' looking for beginning of value`

### ISSUE THREAD

**Issue by jsoref** [google/go-containerregistry#1477]
### Describe the bug

`invalid character 'c' looking for beginning of value` from docker.io

### To Reproduce

```
% crane cp busybox:alpine gcr.io/test/case
2022/10/24 18:46:52 Copying from busybox:alpine to gcr.io/test/case
Error: fetching "busybox:alpine": invalid character 'c' looking for beginning of value
```

### Expected behavior

Possibly an error complaining that I don't have permissions to write to `gcr.io/test/case`, but practically, I'd give it a registry to which I have write permission, and it should just work

### Additional context

This used to work, and a number of tools are failing which indicates that the docker registry changed its API behavior recently. https://github.com/estesp/manifest-tool/issues/189

- Output of `crane version` 0.12.0
- Registry used (e.g., GCR, ECR, Quay) Docker

**Comment by jonjohnsonjr** [comment]
That looks like an error parsing JSON. You could add `--verbose` to figure out exactly what request is failing with the response body.

I would guess either bad credentials or a proxy getting in the way?

FWIW I don't think `busybox:alpine` exists, do you mean `busybox:musl`?

**Comment by jsoref** [comment]
It doesn't really matter:
```
% crane cp --verbose busybox gcr.io/test/case
2022/10/24 23:12:40 Copying from busybox to gcr.io/test/case
Error: fetching "busybox": invalid character 'c' looking for beginning of value
```

**Comment by jsoref** [comment]
hmm, I'm using ~/.rd/bin/docker-credential-none from rancher desktop 1.6.0, switching to ~/.rd/bin/docker-credential-osxkeychain "fixes" the behavior. 

ok, turns out that the `none` credential helper is yielding the wrong exit code:
```
% echo -n https://index.docker.io/v1/| ~/.rd/bin/docker-credential-none get; echo $?
credentials not found in native keychain
0
% echo -n https://index.docker.io/v1/| ~/.rd/bin/docker-credential-osxkeychain get; echo $?
credentials not found in native keychain
1
```

**Comment by jsoref** [comment]
(In case anyone runs into this, this was fixed by https://github.com/rancher-sandbox/rancher-desktop/pull/3134)
