### ISSUE TITLE
cp doesnt work for github container regestry

### ISSUE THREAD

**Issue by Alexander-ac** [google/go-containerregistry#1479]
Hi all,
if I try to copy any images from github container regestry I get following error message:

Error: fetching "ghcr.io/external-secrets/kubernetes-external-secrets:7.2.0": Get "https://ghcr.io/v2/": dial tcp xxx.xx.xxx.33:443: i/o timeout

For any other container regestry it works.

Here is the command I am trying to run:

gcrane cp ghcr.io/external-secrets/kubernetes-external-secrets:7.2.0 myrepository/3rdparty/kubernetes-external-secrets:7.2.0

Any ideas why it's not working.

Thanks in advance

**Comment by imjasonh** [comment]
This error generally means the service is unavailable, or unreachable from your machine somehow.

I don't see any ongoing or recent outages for GHCR here: https://www.githubstatus.com/history

But I'm able to copy that image out of ghcr just fine, so this may be a flaky networking issue.
