### ISSUE TITLE
Do not force user agent when providing a custom transport

### ISSUE THREAD

**Issue by hasheddan** [google/go-containerregistry#1483]
If a user [provides their own transport](https://github.com/google/go-containerregistry/blob/1711cefd7eec057d3892d0bbce1bcd3f8c46d606/pkg/v1/remote/options.go#L137), ggcr will not add its user agent header. However, the user agent will still be injected because in order for the previously mentioned insertion to be skipped, the user must call [`transport.NewWithContext()`](https://github.com/google/go-containerregistry/blob/1711cefd7eec057d3892d0bbce1bcd3f8c46d606/pkg/v1/remote/transport/transport.go#L41) to get a `*transport.Wrapper`, and `transport.NewWithContext()` will [inject the user agent](https://github.com/google/go-containerregistry/blob/1711cefd7eec057d3892d0bbce1bcd3f8c46d606/pkg/v1/remote/transport/transport.go#L68) unless the transport is  already a `*userAgentTransport`, which would mean the user agent was already injected. If a user is supplying their own transport, they should be given full control over its headers.

**Comment by jonjohnsonjr** [comment]
If you're supplying your own transport, you are the innermost transport, so I think you do have full control over its headers.

**Comment by hasheddan** [comment]
@jonjohnsonjr ah you are correct 👍🏻 it does appear that in order to get the `*transport.Wrapper` we essentially have to perform duplicate operations (i.e. call `transport.NewWithContext()`, pass the returned transport with `WithTransport()`, then operations like `remote.Image` will call `transport.NewWithContext()` again). Or am I missing a more optimal pattern?

**Comment by jonjohnsonjr** [comment]
I think it's suboptimal mostly because it's clunky, but the second `transport.NewWithContext` is a no-op: https://github.com/google/go-containerregistry/blob/1711cefd7eec057d3892d0bbce1bcd3f8c46d606/pkg/v1/remote/transport/transport.go#L42-L46

**Comment by hasheddan** [comment]
@jonjohnsonjr ah we are on a version older than https://github.com/google/go-containerregistry/commit/2b1087abc076a6e82339480ea191b7245962932c :)
