### ISSUE TITLE
missing year / author information in license

### ISSUE THREAD

**Issue by dmccaffery** [google/go-containerregistry#1484]
https://github.com/google/go-containerregistry/blob/1711cefd7eec057d3892d0bbce1bcd3f8c46d606/LICENSE#L190

**Comment by imjasonh** [comment]
This is expected. This part of the license text describes how to apply the license to your own work, and includes `Copyright [yyyy] [name of owner]` as example text that should be placed in boilerplate on the work, as is done throughout this repo.
