### ISSUE TITLE
ggcr: `estargz` with TOC first

### ISSUE THREAD

**Issue by abitrolly** [google/go-containerregistry#1494]
### Describe the bug

When I need to inspect files in a streamed `.tar.gz` I still need to download everything to read the TOC at the end. An alternative is to decompress everything, which is also non carbon friendly. 

![image](https://user-images.githubusercontent.com/8781107/203315446-12041ae7-6cfe-4606-9426-3da658fd9e80.png)

### Expected behavior

Is it possible to modify `estargz` format to place TOC first?

**Comment by imjasonh** [comment]
This would have to be decided by the [estargz project](https://github.com/containerd/stargz-snapshotter/), not by go-containerregistry. We just import their packages to optimize existing images.

I seem to recall there's a reason the TOC comes last, but I admit I don't remember details.

There's also recent work by AWS on [SOCI](https://aws.amazon.com/about-aws/whats-new/2022/09/introducing-seekable-oci-lazy-loading-container-images/), which might solve some of these issues, I don't know.
