### ISSUE TITLE
ggcr: retry on unexpected EOF

### ISSUE THREAD

**Issue by imjasonh** [google/go-containerregistry#1500]
### Describe the bug

We're seeing quite a lot of `unexpected EOF` errors coming from GHCR, both when fetching manifests and blobs. This generally means the `Content-Length` header is set to something, but the body responds with fewer than that many bytes, possibly due to a reset connection.

### To Reproduce

Pull from GHCR, eventually see an `unexpected EOF`.

### Expected behavior

GGCR should retry in this case, when pulling manifests and blobs.

### Additional context

I think we can put it here: https://github.com/google/go-containerregistry/blob/c7270c2c2395ecae7d7ffe39d92fc0c572a33cf6/internal/retry/retry.go#L38-L47

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/blob/c7270c2c2395ecae7d7ffe39d92fc0c572a33cf6/pkg/v1/remote/options.go#L62

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/go-containerregistry/pull/1502
