### ISSUE TITLE
ggcr: DefaultKeychain selects unrelated credentials

### ISSUE THREAD

**Issue by lcarva** [google/go-containerregistry#1510]
### Describe the bug

When using `DefaultKeychain.Resolve`, if my docker config contains an auth value for a specific repository, e.g. `quay.io/lucarval/hello`, that auth value is selected when resolving an unrelated repository on the same registry `quay.io/foobar`.

### To Reproduce

Unit test to replicate the issue:

```diff
diff --git a/pkg/authn/keychain_test.go b/pkg/authn/keychain_test.go
index 425aba84..491dd3fb 100644
--- a/pkg/authn/keychain_test.go
+++ b/pkg/authn/keychain_test.go
@@ -264,6 +264,15 @@ func TestVariousPaths(t *testing.T) {
 			Username: "foo",
 			Password: "bar",
 		},
+	}, {
+		desc:   "valid config file; ignores unrelated repo",
+		target: testRepo,
+		content: fmt.Sprintf(`{
+  "auths": {
+    "test.io/another-repo": {"auth": %q}
+  }
+}`, encode("bar", "baz")),
+		cfg: &AuthConfig{},
 	}}
 
 	for _, test := range tests {

```

* `testRepo` is `"test.io/my-repo"`.

The test fails as such:
```
--- FAIL: TestVariousPaths (0.00s)
    --- FAIL: TestVariousPaths/valid_config_file;_ignores_unrelated_repo (0.00s)
        keychain_test.go:65: DOCKER_CONFIG=/tmp/keychain_test3637006557/11
        keychain_test.go:302: got &{Username:bar Password:baz Auth: IdentityToken: RegistryToken:}, want &{Username: Password: Auth: IdentityToken: RegistryToken:}
```

### Expected behavior

The auth value for a specific repo should only be used for that repo, and it should **not** be used for any other repo on the same registry. 

### Additional context

- Version of the module: Any recent version, including `main` at 23d895d080358cd0cdb0698f2e530b17953795ca.
- Registry used (e.g., GCR, ECR, Quay): quay.io but it applies to any registry.

The issue may have been introduced in https://github.com/google/go-containerregistry/pull/1280.

The problem seems to be caused by a conversion that strips off the repository name: https://github.com/google/go-containerregistry/blob/23d895d080358cd0cdb0698f2e530b17953795ca/vendor/github.com/docker/cli/cli/config/credentials/file_store.go#L39-L40

**Comment by lcarva** [comment]
cc @imjasonh

**Comment by lcarva** [comment]
The root cause seems to be deep into the docker library, and unlikely to be fixed. I found a workaround though. Add an dummy entry for the registry without any repos by using an empty auth value. Updated unit test (which now passes):

```diff
diff --git a/pkg/authn/keychain_test.go b/pkg/authn/keychain_test.go
index 425aba84..d8d6ac1b 100644
--- a/pkg/authn/keychain_test.go
+++ b/pkg/authn/keychain_test.go
@@ -264,6 +264,16 @@ func TestVariousPaths(t *testing.T) {
 			Username: "foo",
 			Password: "bar",
 		},
+	}, {
+		desc:   "valid config file; ignores unrelated repo",
+		target: testRepo,
+		content: fmt.Sprintf(`{
+  "auths": {
+    "test.io/another-repo": {"auth": %q},
+    "test.io": {"auth": ""}
+  }
+}`, encode("bar", "baz")),
+		cfg: &AuthConfig{},
 	}}
 
 	for _, test := range tests {

```

I can't think of a downside of this workaround. If others agree, it might be a good idea to document it somewhere and to also add the unit test to the code base.

**Comment by lcarva** [comment]
The previous workaround doesn't actually work when using `multiKeychain` That's because the docker cli library injects the `ServerAddress` into the cfg.

This means an empty config is not really returned [here](https://github.com/tektoncd/chains/blob/516e4926e6cb125dac1dc72475d5cc835076b363/vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go#L126), and the Anonymous authenticator is not returned [here](https://github.com/tektoncd/chains/blob/516e4926e6cb125dac1dc72475d5cc835076b363/vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go#L135), which, of course, causes `multiKeychain` to not proceed to the next keychain.

The confusing part is that the `serveraddress` is [discarded later on](https://github.com/tektoncd/chains/blob/516e4926e6cb125dac1dc72475d5cc835076b363/vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go#L138-L144). So, `<Authenticator>.Authorization()` does return an empty config which explains why the unit test from my previous comment passes.

A potential fix could be to ignore `serveraddress` earlier in the process.

**Comment by jonjohnsonjr** [comment]
> That's because the docker cli library injects the ServerAddress into the cfg.
> 
> This means an empty config is not really returned [here](https://github.com/tektoncd/chains/blob/516e4926e6cb125dac1dc72475d5cc835076b363/vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go#L126)

Ah that's annoying. Yeah perhaps we should strip out ServerAddress before the empty comparison?
