### ISSUE TITLE
question: using crane with Cloud Build requires "cloudbuild_cache" tag?

### ISSUE THREAD

**Issue by nlrussell** [google/go-containerregistry#1535]
When using crane to pull public images in a build config for Cloud Build, I've found that pulling from `gcr.io/go-containerregistry/crane` does not work, but `gcr.io/go-containerregistry/crane:cloudbuild_cache` does. What is this tag, and why is it necessary for integration with Cloud Build? Thanks!

**Comment by imjasonh** [comment]
What error do you see when you pull `gcr.io/go-containerregistry/crane` from Cloud Build? 

There doesn't appear to be an image tagged `:cloudbuild_cache`:

```
$ crane manifest gcr.io/go-containerregistry/crane:cloudbuild_cache
Error: fetching manifest gcr.io/go-containerregistry/crane:cloudbuild_cache: GET https://gcr.io/v2/go-containerregistry/crane/manifests/cloudbuild_cache: MANIFEST_UNKNOWN: Failed to fetch "cloudbuild_cache"
```

**Comment by imjasonh** [comment]
I think GCB pre-caches some images locally, tagged with :cloudbuild_cache, including apparently crane.

I'm not sure why you wouldn't be able to pull :latest, possibly some VPC constraint?

**Comment by nlrussell** [comment]
Hi @imjasonh, here are the various cases we've tried:
- It was time out error using crane without tag,  gcr.io/go-containerregistry/crane
- Also same error if we use latest, gcr.io/go-containerregistry/crane:latest
- But works if we use cloudbuild_cache, gcr.io/go-containerregistry/crane:cloudbuild_cache

I suspect you're right that Cloud Build is set up for certain crane images, but I'm wondering if there's any way to know if I should keep using cloudbuild_cache from the crane perspective?

**Comment by jonjohnsonjr** [comment]
> I suspect you're right that Cloud Build is set up for certain crane images, but I'm wondering if there's any way to know if I should keep using cloudbuild_cache from the crane perspective?

We don't have any control over that tag, since it appears to only exist in the Cloud Build local cache (or something). I would say that it's probably not safe to depend on it because it seems like an internal implementation detail of Cloud Build. If you want to safely depend on `crane` from within your restricted environment, you could always copy a `crane` image into a registry that you control and is within your perimeter.

**Comment by nlrussell** [comment]
Understood!! Thanks for your input, much appreciated @jonjohnsonjr
