### ISSUE TITLE
question: When is the next release planned?

### ISSUE THREAD

**Issue by vaikas** [google/go-containerregistry#1536]
There's been some changes that would be nice to be picked up in a formal release, so just wondering when the next release might get cut so we can do some planning for that. Looks like @jonjohnsonjr @imjasonh did the last few so just curious if this is something that's planned or waiting or something?

Thanks!

**Comment by imjasonh** [comment]
Seems like a good number of fixes worth releasing: https://github.com/google/go-containerregistry/compare/v0.12.1...main

@jonjohnsonjr anything else you want to see in here?

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/releases/tag/v0.13.0
