### ISSUE TITLE
SLSA provenance verification broken for 0.13.0

### ISSUE THREAD

**Issue by imjasonh** [google/go-containerregistry#1539]
https://github.com/google/go-containerregistry/releases/tag/v0.13.0 was cut earlier, and the `verification` phase of the release failed: https://github.com/google/go-containerregistry/actions/runs/3998908027/jobs/6862265563

```
Download assets
  gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "*.tar.gz"
  gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "attestation.intoto.jsonl"
no assets match the file pattern
```

And indeed, there isn't any `attestation.intoto.jsonl` in the release, there's only [`multiple.intoto.jsonl`](https://github.com/google/go-containerregistry/releases/download/v0.13.0/multiple.intoto.jsonl).

The provenance generation and verification steps of the 0.12.0 and 0.12.1 and 0.11.0 releases also had breakages:
- https://github.com/google/go-containerregistry/pull/1468
- https://github.com/google/go-containerregistry/pull/1489
- https://github.com/google/go-containerregistry/pull/1444

Unless we can be sure that provenance is generated and can be verified correctly, I'm sort of inclined to remove the attestation until they can be made more reliable. It's worse to me to have misleading or broken or unverifiable provenance than to have no provenance at all.

@asraa @laurentsimon

**Comment by laurentsimon** [comment]
/cc @ianlewis 
The`attestation.intoto.jsonl` was renamed to `multiple.intoto.jsonl` and the semver of the builder did not reflect that change.
Let me send a PR to update the file name in the verification part. Sorry about this. Nothing is broken, the attestation still exists and verification will work.
