### ISSUE TITLE
ko should fallback onto default GOPATH if unset

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#154]
See: https://github.com/google/go-containerregistry/blob/d5ac5fa9d1f8fc3180a674089995116f9308dd2a/ko/build/gobuild.go#L61-L64

GOPATH if unset should default to `$HOME/go`

**Comment by jonjohnsonjr** [comment]
Just curious, why? I'd expect GOPATH to be set for anybody trying to use ko.

**Comment by dprotaso** [comment]
I would disagree since starting with Go 1.8 you don't need to set GOPATH anymore
https://golang.org/doc/go1.8#gopath

**Comment by dprotaso** [comment]
Curious why you think ko needs an explicit GOPATH

**Comment by dprotaso** [comment]
`go env GOPATH` will print your target GOPATH
