### ISSUE TITLE
question: targz instead of plain gzip in streaming layer

### ISSUE THREAD

**Issue by Skarlso** [google/go-containerregistry#1549]
Hello. :) 

I'm a noob when it comes to OCI layers so I have a quick question. I would like to use tar WITH gzip as compressed layer for streaming layers. Right now, it's just using plain gzip. Is there a reason for that ( I mean there obviously is, but what is it :D )?

Or is that already possible with that weird, pipe tarball to stream layer thing in the steam tests.

Thank you! :)

**Comment by jonjohnsonjr** [comment]
Hello! 👋 

So the main problem that `stream.Layer` solves is orthogonal to the actual contents of the layers. When we upload an image, we need to calculate a few things about each of its layers:

1. The digest of the layer.
2. The size of the layer.
3. The diffid.

The diffid is the sha256 of the _uncompressed_ layer contents. Some diagrams [here](https://github.com/google/go-containerregistry/tree/main/pkg/v1/remote#background) if it helps.

The only way to do this in one pass requires hashing the uncompressed input, compressing it, and hashing/counting the compressed output, all while we upload it to the registry (shown [here](https://github.com/google/go-containerregistry/tree/main/pkg/v1/stream#structure)).

You are right that the vast majority of users will just be piping a tar stream into this, but given that it doesn't have to be a tar stream to compute the digest, size, and diffid, operating on just an `io.ReadCloser` gives the `stream` package flexibility to be used for other non-tarball things. E.g. you could just give it a file. That file might be a tarball, but it doesn't matter to `stream`.

> Or is that already possible with that weird, pipe tarball to stream layer thing in the steam tests.

Yep, it's already possible! Given the way that you usually interact with `tar.Writer` to produce a tar stream in go, there might be a more ergonomic interface for `stream.Layer` (e.g. returning an `io.Writer`), but nobody has asked for that so far. It might be a good contribution.

Hopefully that answers some of your questions.

**Comment by Skarlso** [comment]
Hello @jonjohnsonjr! Thanks, that is a super interesting and awesome explanation of the state of things. I sort of thought about something like this, but wasn't entirely confident in my assumptions. :)

>Yep, it's already possible! Given the way that you usually interact with tar.Writer to produce a tar stream in go, there might be a more ergonomic interface for stream.Layer (e.g. returning an io.Writer), but nobody has asked for that so far. It might be a good contribution.

Interesting! I have a think about this and give it a go when I can. :D Thanks for the suggestion! :)

I consider this one closed though as you perfectly summed up things. Cheers! :)
