### ISSUE TITLE
crane:debug behavior different from crane:latest with respect to docker auth

### ISSUE THREAD

**Issue by harisund** [google/go-containerregistry#1555]
I am trying to push using the following command:

`docker run --volume /home/harisund/.docker:/root/.docker:ro --volume `pwd`:/workdir:ro --workdir /workdir --rm  gcr.io/go-containerregistry/crane:debug /workdir/foo.tar personal_registry/foo:v1`

While that works, the following does not

`docker run --volume /home/harisund/.docker:/root/.docker:ro --volume `pwd`:/workdir:ro --workdir /workdir --rm  gcr.io/go-containerregistry/crane /workdir/foo.tar personal_registry/foo:v1`

When using the latter, it keeps telling me I am not authorized to push. 

To debug, I ran the busybox-sh from debug, and it worked. So I tried replacing the image in docker-run and it worked with :debug but not with :latest

Am I missing something, or did something change?

**Comment by imjasonh** [comment]
The regular `crane` image runs as a `nonroot` user (UID 65532), while `crane:debug` runs as `root`. Their homedirs are different accordingly, so mounting the docker config into `/root/.docker` will not work for the nonroot image.

It might be confusing that `crane` is built with `ko` that uses `cgr.dev/chainguard/static` as its base (nonroot by default), and [`crane:debug` uses `gcr.io/distroless/base:debug` (root)](https://github.com/google/go-containerregistry/blob/main/.ko/debug/.ko.yaml#L1). https://github.com/google/go-containerregistry/pull/1454 makes `:debug` nonroot by default, using a custom base image built with apko.

**Comment by harisund** [comment]
Cool, thank you.
