### ISSUE TITLE
question: how can I copy image between registries for multiple OS/arch ?

### ISSUE THREAD

**Issue by developer-guy** [google/go-containerregistry#1557]
I noticed that the platform flag in copy command only accepts a single value, and if you specify multiple platform flags, the last one will win. So, it'd be good to support taking multiple values for the platform flag to be able to specify the exact platforms that people care about.

```shell
# will copy an image built for linux/amd64
$ crane copy --platform linux/amd64

# will copy an image built for linux/arm64
$ crane copy --platform linux/arm64

# will copy an image built for linux/amd64, it ignores linux/arm64, but it'd be copy this image for each platform.
$ crane copy --platform linux/arm64 --platform linux/amd64
```

**Comment by jonjohnsonjr** [comment]
If you copy the whole multi-arch image, you get everything, but I assume you only want to copy things you care about?

I can interpret this three ways:
1. Copy linux/arm64 and linux/amd64 images separately, do not push a multi-platform image.
2. Synthesize a new multi-platform image that only contains linux/arm64 and linux/amd64.
3. Copy only the linux/arm64 and linux/amd64 child images, then attempt to push the multi-platform image as-is, hoping that the registry supports [sparse indexes](https://github.com/opencontainers/distribution-spec/pull/310).

The first one would be straightforward to implement.

The second one I would hesitate to add to `copy` but maybe we can have a flag for the behavior. This was requested in https://github.com/google/go-containerregistry/issues/1143 already.

The third one would make sense, but probably wouldn't work with almost all existing registries.

Any of those seem like what you want?

**Comment by jonjohnsonjr** [comment]
FWIW you could hack around this a bit with `crane edit manifest`, but it's certainly not elegant.

```
$ crane manifest ubuntu | jq '.manifests = ([.manifests | .[] | select (.platform.os == "linux" and (.platform.architecture == "amd64" or .platform.architecture == "arm64"))])'
{
  "manifests": [
    {
      "digest": "sha256:c985bc3f77946b8e92c9a3648c6f31751a7dd972e06604785e47303f4ad47c4c",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 424
    },
    {
      "digest": "sha256:61bd0b97000996232eb07b8d0e9375d14197f78aa850c2506417ef995a7199a7",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "arm64",
        "os": "linux",
        "variant": "v8"
      },
      "size": 424
    }
  ],
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2
}
```

Piping that into `crane edit manifest <your destination image>` would attempt to write the filtered index, but it would fail unless you copied each sub-image first, which would be easy if we implemented option 1, but is possible with a little shell scripting.
