### ISSUE TITLE
ggcr: authn should also read secrets from ServiceAccount's .secrets

### ISSUE THREAD

**Issue by lcarva** [google/go-containerregistry#1558]
### Feature Request

The authn/kubenertes keychain reads Secrets associated with a ServiceAccount from its `.imagePullSecrets` attribute. However, Secrets can also be associated with a ServiceAccount via its '.secrets` attribute. The first is usually used at the Node level for pulling images for a Pod, while the second is mounted on Pods and used directly by Containers.

The keychain should read Secrets from both locations.

### Use Case

The [Tekton Chains](https://github.com/tektoncd/chains/) controller uses this library to determine the authentication required to push content to the user provided registry. Since users are instructed to using only `.secrets` in other parts of the ecosystem, they must do something different when using Tekton Chains. Further context in https://github.com/tektoncd/chains/issues/700

**Comment by lcarva** [comment]
Are there any objections to taking this approach? If not, I would be happy to submit a patch.

**Comment by imjasonh** [comment]
Yeah I think we'd be open to accepting this. Do you want to send a PR and we can discuss specifics there?

**Comment by lcarva** [comment]
Sounds good! PR submitted: https://github.com/google/go-containerregistry/pull/1560/
