### ISSUE TITLE
`crane http`

### ISSUE THREAD

**Issue by imjasonh** [google/go-containerregistry#1564]
```
crane http -X POST -H "If-Match: abc" https://gcr.io/v2/blah/blah/manifests/latest latest.json
```

Like curl, but with a token exchange. Useful for testing APIs at a lower level, prototyping future crane commands, other tomfoolery.

I don't think we should even copy curl exactly, maybe just `crane http [verb] [url] [body-file]`

**Comment by jonjohnsonjr** [comment]
I think I prefer https://github.com/google/go-containerregistry/issues/1470 for this kind of hacking.

Another idea I just had would be to add a `--curl` flag

```
$ crane manifest ubuntu --curl
curl -H "Authorization: Bearer $(curl "https://auth.docker.io/token?scope=repository:library/ubuntu:pull&service=registry.docker.io" | jq -r .token)" "https://index.docker.io/v2/library/ubuntu/manifests/latest"
```

Then you can take that and add whatever headers you want. This would be kinda tricky to pull off for multi-request things like blob uploads, though.

**Comment by imjasonh** [comment]
Yeah, this probably just belongs in a recipe.
