### ISSUE TITLE
question: are 429 errors handled?

### ISSUE THREAD

**Issue by lcarva** [google/go-containerregistry#1569]
[429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) should be retried. Is this being done by the library?

I just received this error being reported by the library when interacting with images in quay.io. It's unclear to me if a retry actually took place. 

The only place where 429 is explicitly handled is in `pkg/gcrane/copy.go`, but that seems very isolated to just the copy command and not used by the library.

**Comment by imjasonh** [comment]
https://github.com/google/go-containerregistry/blob/4a0e0af4bf958c0bfb17bdfac71c38204b930623/pkg/v1/remote/transport/error.go#L133-L138

If the error response incidicates `TOOMANYREQUESTS` then the request is retried. The HTTP status code 429 is not considered.

The unit test as well:

https://github.com/google/go-containerregistry/blob/4a0e0af4bf958c0bfb17bdfac71c38204b930623/pkg/v1/remote/transport/error_test.go#L52-L57

**Comment by jonjohnsonjr** [comment]
I think it would be reasonable to retry 429 after some delay, but I don't want to just add it to a list of things to retry without also adding support for the `Retry-After` header somewhere.

**Comment by imjasonh** [comment]
Yeah, if we retry on 429 we should try to do it intelligently or else we just end up making more requests.

Docker's ratelimit response headers could be useful: https://docs.docker.com/docker-hub/download-rate-limit/
