### ISSUE TITLE
Latest Debug Image does not have a shell.

### ISSUE THREAD

**Issue by jacobosborne1** [google/go-containerregistry#1575]
The top image which is the latest debug image as of writing does not work in Gitlab CI. Changing to the previously tagged image resolves the issue. 

In our gitlab ci file, the only change we made was changing from crane:debug to crane/debug:<tag>

https://console.cloud.google.com/artifacts/docker/go-containerregistry/us/gcr.io/crane%2Fdebug/sha256:3a2d6f157a3ea512b81df8042d295e1c322113de71770b7e5490d431ba11cc9f

https://console.cloud.google.com/artifacts/docker/go-containerregistry/us/gcr.io/crane%2Fdebug/sha256:90b4a413861ae63e01ce6669f54161515eac8f04e202b9c9b92b48452eaaf20f
![Screenshot 2023-02-21 at 12 12 51](https://user-images.githubusercontent.com/39770158/220341923-1d7a5170-04b5-4ed8-8ce6-843ed3960ee7.png)

**Comment by imjasonh** [comment]
@jonjohnsonjr do you have an idea what might cause this? I don't have much visibility into the GCB build process that pushes these images.

I don't think I even knew that `gcr.io/go-containerregistry/crane/debug:latest` existed, I've always used `crane:debug`.

**Comment by jonjohnsonjr** [comment]
They have the same digest, so there might be something else going on?

```
$ crane digest gcr.io/go-containerregistry/crane/debug
sha256:3a2d6f157a3ea512b81df8042d295e1c322113de71770b7e5490d431ba11cc9f
$ crane digest gcr.io/go-containerregistry/crane:debug
sha256:3a2d6f157a3ea512b81df8042d295e1c322113de71770b7e5490d431ba11cc9f
```
