### ISSUE TITLE
question: How do I delete a tag? `crane delete` doesn't really remove anything and returns for tags DIGEST_INVALID

### ISSUE THREAD

**Issue by Skarlso** [google/go-containerregistry#1578]
Okay, so I've seen a bunch of issues regarding this, but I can't wrap my head around it.

In https://github.com/google/go-containerregistry/issues/999 it is said that `crane delete <image>:<tag>` should work.

But when I try I get 
```
crane delete 127.0.0.1:5000/sha-15465795360511977555:latest
Error: DELETE http://127.0.0.1:5000/v2/sha-15465795360511977555/manifests/latest: DIGEST_INVALID: provided digest did not match uploaded content
```

So then I try something like:
```
crane delete 127.0.0.1:5000/sha-15465795360511977555:latest@sha256:714e389a135f82997869ed7366d07c580f7c6110a70a1b6e4640a780db2e20ba
```

Which does work indeed, at least it returns 202. Which is a success.

But then further calls like `blob` and `manifest` all still show the tag and the blob can be retrieved fine. I know there is supposed to be a GC at some point, but I thought that `delete` would do at least SOMETHING. But it doesn't do anything? How can I check if a tag is deleted or something like that at least. Since everything literally returns that the tag or the SHA exists fine and there is nothing wrong with them.

_Edit_:

Running `gcrane` doesn't show any untagged images:

```
gcrane gc 127.0.0.1:5000/sha-15465795360511977555
➜  temp
```

Another run:

```
gcrane delete 127.0.0.1:5000/sha-15465795360511977555:latest@sha256:714e389a135f82997869ed7366d07c580f7c6110a70a1b6e4640a780db2e20ba
Error: DELETE http://127.0.0.1:5000/v2/sha-15465795360511977555/manifests/sha256:714e389a135f82997869ed7366d07c580f7c6110a70a1b6e4640a780db2e20ba: MANIFEST_UNKNOWN: manifest unknown
➜  temp gcrane gc 127.0.0.1:5000/sha-15465795360511977555
```

This show delete fails because not there, but gc doesn't show anything.

**Comment by imjasonh** [comment]
What registry implementation are you using? Tag deletion, though [specified in distribution-spec](https://github.com/google/go-containerregistry/issues/999#issuecomment-828701797), doesn't seem to be widespread across every registry implementation.

When you delete a ref by tag-and-digest (e.g., `/sha-1546:latest@sha256:714e`), the tag portion is ignored by clients and the request deletes the digest, which is supported by more/most(/all?) registries. You can test this by deleting `:something-made-up@sha256:714e...` -- the tag is ignored completely.

How the registry implements deletion is also registry-specific. Some may delete the manifest by digest right away then only delete blobs later. It would be weird, but in theory a registry could also not delete the manifest right away, but only schedule it for deletion later.

`gcrane gc` is a specific implementation against GCR, and should probably return an error if it detects it's being run against a non-GCR registry.

**Comment by Skarlso** [comment]
Hmm, hmmm, interesting. I'm running a docker registry.

this one:
```
docker.io/library/registry@sha256:3f71055ad7c41728e381190fee5c4cf9b8f7725839dcf5c0fe3e5e20dc5db1fa
```

I'm looking at this doc: https://docs.docker.com/registry/spec/api/#deleting-an-image

So this _should_ work. :/ But I guess, there is nothing from your side then that could be done? :/

**Comment by Skarlso** [comment]
Oras did the trick. crane deletes image while the docker registry is deleting manifests.

```
oras manifest delete 127.0.0.1:5000/sha-15465795360511977555:latest --plain-http
Are you sure you want to delete the manifest "sha256:06ac21b354778064062ba0ec1bd1334d2db9272e1b66c6e103297dd8fe35b460" and all tags associated with it? [y/N] y
Deleted 127.0.0.1:5000/sha-15465795360511977555:latest
➜  go-containerregistry git:(main) crane ls 127.0.0.1:5000/sha-15465795360511977555
```

Thanks. :)

**Comment by imjasonh** [comment]
To be clear, you're deleting the manifest by digest, which happens to have a tag applied to it, which is also deleted.

If you'd wanted to delete only the tag, but ensure the manifest was still available by digest, it doesn't sound like `oras` handles this, as it asks if you're sure you want to delete the digest.

Deleting a tag, but not deleting the manifest by digest at the same time, seems to not be supported by Docker's registry implementation.

The Docker API docs you linked also say:

> For deletes, `reference` must be a digest or the delete will fail. If the image exists and has been successfully deleted, the following response will be issued:

**Comment by Skarlso** [comment]
@imjasonh thanks for confirming. Indeed, I did some reading and talked to some peeps on slack and yes. This seems to be the case. And I have a better understanding now of the manifest tag relationship. Thank you for your answer!
