### ISSUE TITLE
FR: implement crane serve

### ISSUE THREAD

**Issue by thesayyn** [google/go-containerregistry#1579]
Currently, go-containerregistry has its own registry implementation which is mostly used for testing. It would be useful to expose this functionality for others to use via `crane serve` command.

**Comment by thesayyn** [comment]
Ref: https://github.com/google/go-containerregistry/pull/1211/files

**Comment by alexeagle** [comment]
Note, this is needed for the Bazel OCI rules to be able to host a registry as a Bazel toolchain, so that OCI-format and Docker-format images can both be used.

**Comment by thesayyn** [comment]
Cross-ref: https://github.com/bazel-contrib/rules_oci/pull/71

**Comment by imjasonh** [comment]
I'm fine with it. There's also [`cmd/registry`](https://github.com/google/go-containerregistry/tree/main/cmd/registry) as a separate binary, in case that's helpful. This is used by [`chainguard-dev/setup-registry`](https://github.com/chainguard-dev/actions/tree/main/setup-registry), which we use in some e2e tests. But I think it could be useful to have this just included in `crane`.

**Comment by alexeagle** [comment]
@imjasonh we don't have the funding to devote to an on-disk storage for the registry. Would you accept a PR that literally adds a `serve` command that's identical to https://github.com/chainguard-dev/actions/blob/main/setup-registry/action.yaml#L21 and only stores in-memory?

**Comment by mering** [comment]
Has there been any work towards an on disk implementation?

The memory one crashes our Bazel RBE workers for large images.
