### ISSUE TITLE
question: crane auth logout

### ISSUE THREAD

**Issue by Danielku15** [google/go-containerregistry#1587]
We plan to use `crane auth login` in our CI pipeline (filled via secrets) and want to remove after further actions those credentials again. 
I don't see a `crane auth logout` in the docs. How can we remove these credentials again?

**Comment by imjasonh** [comment]
This has been requested before (recently, https://github.com/google/go-containerregistry/pull/1459) and it's something I think would be useful. If you're interested in sending a PR I'd be happy to review it. If not, I can throw something together when I have some time.
