### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by testwill** [google/go-containerregistry#1588]
Can the decompression layer be optimized to reduce memory usage

**Comment by imjasonh** [comment]
```
 ScanImage err:scan error: scan failed: failed analysis: analyze error: failed to analyze layer:    : unable to get uncompressed layer sha256:3e2f8db7fa513d9c70b9b6778e182f9cb816a9442472cbdf748550feff7d853b: failed to get the layer (sha256:3e2f8db7fa513d9c70b9b6778e182f9cb816a9442472cbdf748550feff7d853b):   unable to populate: unable to open: failed to copy the image: write /tmp/fanal-2118041723: cannot allocate memory
```

**Comment by imjasonh** [comment]
Can you elaborate on what you're trying to do, and what caused this error?

How large is the image you're pulling and decompressing, and how as it compressed?

**Comment by testwill** [comment]
I use trivy to scan software packages and vulnerabilities. The reason for this error is that we put a 2.2g file in this layer. This image has 2.63GB, I don't know why to decompress and compress, I use the local image of docker

**Comment by imjasonh** [comment]
This sounds like an issue with Trivy.

The error in question seems to come from here: https://github.com/aquasecurity/trivy/blob/57904c0f975b9957323ac362c604db057c904aa2/pkg/fanal/artifact/image/image.go#L420

It's certainly possible for go-containerregistry to fetch and extract a large layer without buffering it all into memory (try `crane pull <large-image> out.tar`), it seems that Trivy has implemented things so they buffer it all into memory, and you run out of memory.
