### ISSUE TITLE
gcrane: --platform option/flag does not have any effect when copying images

### ISSUE THREAD

**Issue by phong2tran** [google/go-containerregistry#1591]
### Describe the bug

We're using a GitLab pipeline with **gcrane** to copy third-party images from public registries like DockerHub into our private Artifactory registry for vulnerability scanning and then uploading these images to private repos in Google Artifact Registry (GAR) for deploying into GKE clusters.  As these images are built with multi-platform support (https://hub.docker.com/r/newrelic/nri-kubernetes/tags) and we're still using an old version of Artifactory (6.2) which does not have the support for multi-platform images (https://jfrog.atlassian.net/browse/RTFACT-13975), so we're running into an issue with accessing these images on our Artifactory because by default gcrane retains and copies images with all platforms. 

As a temporary workaround, we're trying to use "--platform=linux/amd64" option with gcrane to copy images with only one platform selected, so these images can be used on our old version of Artifactory, however, this option seemed to be ignored by gcrane and has no effect as images are still copied with all platforms.  

Is this a bug with gcrane or something we we could have missed on its usage?

### To Reproduce
`$ gcrane --platform=linux/amd64 copy dockerhub.${ARTIFACTORY_HOST}/newrelic/nri-kubernetes:3.6.0 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes:3.6.0`
2023/03/09 14:48:46 Copying from dockerhub.${ARTIFACTORY_HOST}/newrelic/nri-kubernetes:3.6.0 to ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes:3.6.0
2023/03/09 14:48:46 existing blob: sha256:d94ef9ff347125cf4ba7f3549eb2ec55f5465a9e63457701c32d82a8576cd605
2023/03/09 14:48:46 existing blob: sha256:2893e0c76346bf9990f44daa683fa63f8b09b81a90371b40bfcd36978fbba2ed
2023/03/09 14:48:46 existing blob: sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
2023/03/09 14:48:46 existing blob: sha256:215c6eb4952e4ca09c6f4d5d4c0749de2ad779228431a6a0622d3c37fc414821
2023/03/09 14:48:46 existing blob: sha256:a7578d550498c87c4c39054f16ec5d73500c20d281a9a08667b876ead10484ef
2023/03/09 14:48:46 existing blob: sha256:b49669421b457babe1779bb7cd698749604b90f031ae65dbe81bd1c9136de2df
2023/03/09 14:48:47 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes@sha256:0ed938c08d7d1c5449c6433ebc3b3afe13445a52f5e82680a8cdf128ae81f6c2: digest: sha256:0ed938c08d7d1c5449c6433ebc3b3afe13445a52f5e82680a8cdf128ae81f6c2 size: 1371
2023/03/09 14:48:47 existing blob: sha256:9b18e9b68314027565b90ff6189d65942c0f7986da80df008b8431276885218e
2023/03/09 14:48:47 existing blob: sha256:da9e44ce749a40ea7f74cb899a5b9103ab05399073aad9be6cd5e51a090863db
2023/03/09 14:48:47 existing blob: sha256:5f33a213efff6ad9f47b4b77c83f6462001c5130c4e3c2228d1f2737afdf9af1
2023/03/09 14:48:47 existing blob: sha256:81c71b1f15f9f58e12efe543f1ee5c286a75b36c5614f29f0badcc19597bb51c
2023/03/09 14:48:47 existing blob: sha256:b4cbc8c48bda27a69410935a28ecd508507070b5cce37688440ebde0e5af0394
2023/03/09 14:48:47 existing blob: sha256:f73418aeaf6a32b1040c0acd0db36336cd88bab4f866d943cd6a9f78aee8eee2
2023/03/09 14:48:47 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes@sha256:8405f7dc6b04afb38609b0f2c952279c3d456dbbe2e94779a4366f4dd974c839: digest: sha256:8405f7dc6b04afb38609b0f2c952279c3d456dbbe2e94779a4366f4dd974c839 size: 1371
2023/03/09 14:48:48 existing blob: sha256:2a821605f88742aced2ae99a07d93a1fbf518136048a1090966be89b149ad41b
2023/03/09 14:48:48 existing blob: sha256:8fb8eae73ab0cac2fc77efeecfaeee8357702c56309f04ca8622c0d69c23c448
2023/03/09 14:48:48 existing blob: sha256:296ac8dd435cc7ad6f521430529949916efa572128572e2beb34b72e88ea1e99
2023/03/09 14:48:48 existing blob: sha256:c6556b3b6858c6fa1e328377cc2c4becdc9cd1bc3e7302aa7299936522cf93ba
2023/03/09 14:48:48 existing blob: sha256:c0d893ccefa7843aa008427a2dddd00c6afc4ad07d918b6002004df9000dc353
2023/03/09 14:48:48 existing blob: sha256:20de6338772d1ca7efd663e07c93ac997af5ab64fec9d5bbc5bb7666e864a968
2023/03/09 14:48:48 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes@sha256:69dca2ff72a77091075d7da490f399787ea39b3f95a0c76225271fa4da1bd52d: digest: sha256:69dca2ff72a77091075d7da490f399787ea39b3f95a0c76225271fa4da1bd52d size: 1371
2023/03/09 14:48:48 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes:3.6.0: digest: sha256:6c05a62483c1edc8911d491619a7c7029443708d3c871f4f0304aa543e0f5fbb size: 1079

### Expected behavior
The images should be copied with only the "linux/amd64" platform selected in gcrane platform option. 

### Additional context
However when using the other tool "**crane**" with the same platform option, it copied images with the single selected platform as expected:

`$ crane --platform=linux/amd64 copy dockerhub.${ARTIFACTORY_HOST}/newrelic/nri-kubernetes:3.6.0 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes:3.6.0`
2023/03/09 14:51:12 Copying from dockerhub.${ARTIFACTORY_HOST}/newrelic/nri-kubernetes:3.6.0 to ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes:3.6.0
2023/03/09 14:51:12 existing blob: sha256:a7578d550498c87c4c39054f16ec5d73500c20d281a9a08667b876ead10484ef
2023/03/09 14:51:12 existing blob: sha256:2893e0c76346bf9990f44daa683fa63f8b09b81a90371b40bfcd36978fbba2ed
2023/03/09 14:51:12 existing blob: sha256:d94ef9ff347125cf4ba7f3549eb2ec55f5465a9e63457701c32d82a8576cd605
2023/03/09 14:51:12 existing blob: sha256:215c6eb4952e4ca09c6f4d5d4c0749de2ad779228431a6a0622d3c37fc414821
2023/03/09 14:51:12 existing blob: sha256:b49669421b457babe1779bb7cd698749604b90f031ae65dbe81bd1c9136de2df
2023/03/09 14:51:12 existing blob: sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
2023/03/09 14:51:12 ${ARTIFACTORY_HOST}/csdpaas-docker/testing/nri-kubernetes:3.6.0: digest: sha256:0ed938c08d7d1c5449c6433ebc3b3afe13445a52f5e82680a8cdf128ae81f6c2 size: 1371

- Output of `crane version`
$ gcrane version
0.13.0

$ crane version
0.13.0

- Registry used (e.g., GCR, ECR, Quay)
Artifactory/GAR

**Comment by jonjohnsonjr** [comment]
This probably does what you want: https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#filter-irrelevant-platforms-from-a-multi-platform-image

We could make copy respect the platform if copying by tag, though...
