### ISSUE TITLE
question: how to use TLS for client code

### ISSUE THREAD

**Issue by Skarlso** [google/go-containerregistry#1613]
Hi. This is probably a silly question, but I'm using an internal registry and would like to setup TLS for the client side code.

How do I do that? As far as I can see I have to use a Custom Transport with TLS Config while I'm calling something like this:

```go
// pushBlob pushes a blob to the repository. It accepts a v1.Layer interface.
func (r *Repository) pushBlob(layer v1.Layer) error {
	return remote.WriteLayer(r.Repository, layer, r.remoteOpts...)
}
```

So, here I would have a `WithTransport` and a client that has TLSConfig properly configured. Do I see that right? And there is no option like WithCertificate or something like that?

What I'm trying to do is, that I've setup a registry using TLS and now I would like to actually call it with HTTPS.

But even though I don't use `insecure` anywhere, the push or the write or the get, still try it with HTTP.

```
failed to get resource: failed to fetch resource: failed to fetch blob: failed to fetch layer: GET http://registry.ocm-system.svc.cluster.local:5000/v2/: unexpected status code 400 Bad Request: Client sent an HTTP request to an HTTPS server.
```

The repository looks like this: `registry.ocm-system.svc.cluster.local:5000` the `http` is put there by this SDK. I thought it should be secure by default so why isn't it trying HTTPS?

**Comment by Skarlso** [comment]
I did something like this:

```go
	// Create a new certificate pool and add the self-signed certificate
	certPool := x509.NewCertPool()
	certPool.AppendCertsFromPEM([]byte(tlsCrt))

	// Create a new TLS configuration with the self-signed certificate and private key
	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{{
			Certificate: [][]byte{[]byte(tlsCrt)},
			PrivateKey:  []byte(tlsKey),
		}},
		// InsecureSkipVerify should be set to true to disable
		// verification of the server's certificate chain
		InsecureSkipVerify: true,
	}
	// Create a new HTTP transport with the TLS configuration
	transport := &http.Transport{
		TLSClientConfig: tlsConfig,
	}

	return remote.Layer(ref, remote.WithTransport(transport))
```

Should do the trick, once I extract it into a helper.

**Comment by jonjohnsonjr** [comment]
If you are able to configure your environment with the custom cert, things should "just work" because golang's default tls config uses [`x509.SystemCertPool`](https://pkg.go.dev/crypto/x509#SystemCertPool), which looks at all the normal locations for custom certs.

**Comment by Skarlso** [comment]
@jonjohnsonjr this has to be self-contained. The thing runs inside a cluster and I'm looking to use a cert in a cluster running controller.

**Comment by Skarlso** [comment]
Yeah, so if I remove the custom transport ( even if it's set with just ignore certificates ) it will immediately switch to plain HTTP.

**Comment by Skarlso** [comment]
I think this can be closed. I got my answer. :)
