### ISSUE TITLE
question: crane: Unable tp push image to registry even after crane auth login successfull

### ISSUE THREAD

**Issue by ravinjhajharia** [google/go-containerregistry#1617]
I am not able to push the image to docker hub registry even after the crane auth login succeeded. It fails with below error:
`
Error: POST https://index.docker.io/v2/library/nginx/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/nginx Type:repository] map[Action:push Class: Name:library/nginx Type:repository]] `

I don't understand why it says unauthorized even the crane auth succeeded.
```
crane auth login -u <user_name> registry.docker.io
2023/03/28 09:59:29 logged in via /root/.docker/config.json
```
Would appreciate if anyone can provide suggestions?

**Comment by imjasonh** [comment]
I think you might need to `crane auth login` to `docker.io`, instead of `registry.docker.io`. I think we could do some work to make this act more like `docker login`, to avoid this confusion.

**Comment by akhilesh2410** [comment]
@imjasonh I am also getting same issue with my local harbor registry
`./crane auth login IP:30003 -u <username> -p <password>
2023/04/03 08:54:12 logged in via /root/.docker/config.json
./crane copy alpine:latest IP:30003/spectro-images/alpine-test:latest --insecure
2023/04/03 08:54:18 Copying from alpine:latest to IP:30003/spectro-images/alpine-test:latest
2023/04/03 08:54:22 retrying without mount: POST https://IP:30003/v2/spectro-images/alpine-test/blobs/uploads/?from=library%2Falpine&mount=sha256%3A9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e&origin=REDACTED: UNAUTHORIZED: unauthorized to access repository: spectro-images/alpine-test, action: push: unauthorized to access repository: spectro-images/alpine-test, action: push
Error: failed to copy index: POST https://IP:30003/v2/spectro-images/alpine-test/blobs/uploads/: UNAUTHORIZED: unauthorized to access repository: spectro-images/alpine-test, action: push: unauthorized to access repository: spectro-images/alpine-test, action: push`


This looks like some bug.

Same is working fine if my host has docker installed, but on another where I have containerd it is not working. Not sure if crane has some dependency on docker ?

**Comment by imjasonh** [comment]
@akhilesh2410 your issue sounds different from the original one, because you're logging in to an IP:PORT and not docker.io.

One important difference between `crane auth login` and `docker login` is that `docker login` sends the creds to the server to check that they're accepted before writing them to the Docker config, and `crane auth login` just writes them directly. This means that `crane` will accept invalid credentials and not tell you they're invalid until you try to use them. Do your credentials work when you `docker login IP:30003 -u ... -p ...`?
