### ISSUE TITLE
Add type which could check for layers locally before pulling remotely

### ISSUE THREAD

**Issue by priyawadhwa** [google/go-containerregistry#163]
We've been thinking about adding [caching](https://github.com/GoogleContainerTools/kaniko/issues/102) for base image layers to kaniko, and it seems like storing the layers in a persistent volume is probably the best way to do it.

To help with that, we were thinking of adding another type in go-containerregistry which could check to see which layers of an image are already present at a given path, and then pull any remaining layers. We could use it in kaniko to see which cached layers are present in the PV and then get any additional ones. Just wondering if anybody had any thoughts about feasibility/implementation?

cc @dlorenc

**Comment by ImJasonH** [comment]
This could be an option passed to `remote.Image` (especially with new functional options (#161) !), something like `remote.Image(ref, authn, t, ..., remote.WithCache(cache))` where `cache` implements some interface like:

```go
type Cache interface {
  Load(v1.Hash) (io.ReadCloser, error)
  Store(io.ReadCloser) error
}
```

Then if passed, `remote.Image` could check the cache before fetching blobs and `Load` them, otherwise fetch and `Store`.

WDYT?

**Comment by priyawadhwa** [comment]
Sounds good to me, is there anything I can do to help out?

**Comment by dlorenc** [comment]
You could get started implementing the layer cache itself inside remote.Image. The eventual merge with functional options should be easy.

**Comment by priyawadhwa** [comment]
I think @ImJasonH got started on that already! (#164)

**Comment by ImJasonH** [comment]
@priyawadhwa Is there anything else you think you'll need from layer caching? Eviction, for instance?

The discussion in https://github.com/GoogleContainerTools/kaniko/issues/102 hints at some other things worth considering on your end, like how you attach and populate the PDs that back the cache. That probably/hopefully won't have to leak into this library's implementation, but it might be worth settling before we go further.

How urgent is this request? I'd personally probably wait for the functional options change to land, but if you're in a hurry you can take what's started in #164 and expand on it in a fork.

**Comment by priyawadhwa** [comment]
We're thinking kaniko could call a separate service which would be responsible for reading from and writing to the PD that backs the cache, so I don't think anything related to the PD has to spill over into this library's implementation.  For kaniko specifically I also don't think we need to worry about eviction. 

I'm good with waiting for the functional options, for now I'll probably start testing with the changes in #164 and do some benchmarking!

**Comment by jonjohnsonjr** [comment]
@priyawadhwa does https://github.com/google/go-containerregistry/pull/458 satisfy your needs?

**Comment by priyawadhwa** [comment]
Yup, thanks! I'll go ahead and close this issue.
