### ISSUE TITLE
ggcr: validate does not support windows images

### ISSUE THREAD

**Issue by matthewrobertson** [google/go-containerregistry#1639]
The `github.com/google/go-containerregistry/pkg/v1/validate` package does not support windows images.

### To Reproduce

Try to run the `crane validate` command on a windows image. Note the validation always fails with a message about the index not containing a "child with platform linux/amd64"

```
crane validate --remote mcr.microsoft.com/windows/nanoserver:1809 --fast 
Error: failed to read image mcr.microsoft.com/windows/nanoserver:1809: no child with platform linux/amd64 in index mcr.microsoft.com/windows/nanoserver:1809
```

### Expected behavior

The image is valid so I would expect to see:

```
PASS: mcr.microsoft.com/windows/nanoserver:1809
```

### Additional context

The manifest of the image above is:

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 574,
      "digest": "sha256:534e38583dfa4ab78b76d5b8dd31da8db589d981cf1c0eb3c7b34fd6b69b1bbe",
      "platform": {
        "architecture": "amd64",
        "os": "windows",
        "os.version": "10.0.17763.4131"
      }
    }
  ]
}
```

**Comment by imjasonh** [comment]
This is due to how `crane` (and go-containerregistry in general, and most tools) tends to default to `linux/amd64`. Most images have a `linux/amd64` platform, but not this one.

If you pass `--platform=windows/amd64` it should work:

```
crane validate --remote mcr.microsoft.com/windows/nanoserver:1809 --fast --platform=windows/amd64
PASS: mcr.microsoft.com/windows/nanoserver:1809
```

**Comment by matthewrobertson** [comment]
@imjasonh I see what I am doing wrong here. In my case I am actually using ggcr as a library, but I have a remote reference and I don't know if it points to an image manifest or an index. I can do something like:

```go
desc, _ := remote.Head(ref)
// check if the ref is pointing to an index
if desc.MediaType == types.OCIImageIndex || desc.MediaType == types.DockerManifestList {
  index, _ := remote.Index(ref, remote.WithAuth(auth), remote.WithTransport(http.DefaultTransport))
  return validate.Index(index, validate.Fast)
}
// otherwise assume it an image
img, _ := remote.Image(ref, remote.WithAuth(auth), remote.WithTransport(http.DefaultTransport))
return validate.Image(img, validate.Fast)
```

How would you feel about a PR that adds a "smarter" validate that fetches the reference, parses the MediaType and calls the corresponding validate method? Something like:

```go
validate.Ref("mcr.microsoft.com/windows/nanoserver:1809", remote.WithAuth(x))
```

**Comment by imjasonh** [comment]
That sounds reasonable.

We also have `remote.Get` with `.Image()` and `.Index()` that would let you do what you described without doing two requests.

**Comment by imjasonh** [comment]
Thinking about this a bit more, I think we'd like to avoid a dependency from validate to remote, so as much as it kinda sucks to have to spell it out I think I'd recommend doing remote.Get and passing the result to whichever validate flavor is relevant.

If you only care about validating the windows image, you can `remote.Image(..., remote.WithPlatform("windows/amd64"))`, and avoid knowing about the index at all.

**Comment by jonjohnsonjr** [comment]
> Thinking about this a bit more, I think we'd like to avoid a dependency from validate to remote

Definitely, but it would not be an unreasonable thing to put into `pkg/crane`.
