### ISSUE TITLE
Rebasing always downloads layers to the host

### ISSUE THREAD

**Issue by sclevine** [google/go-containerregistry#166]
When rebasing with all repositories on GCR or all repositories on Docker Hub, I observe that layers are unexpectedly downloaded to the host, but not re-uploaded. I observe this with both `crane rebase` and via direct usage of `mutate.Rebase`.

The culprit appears to be the first execution of this line:
https://github.com/google/go-containerregistry/blob/7f1e66edb3a89174cb95bbc9ab5324449cd80d69/v1/mutate/mutate.go#L82

Coming from:
https://github.com/google/go-containerregistry/blob/7f1e66edb3a89174cb95bbc9ab5324449cd80d69/v1/mutate/rebase.go#L80

I'm guessing that `DiffID` requires an uncompressed image which must be downloaded from the registry before decompressing and calculating a SHA.

For me, this eats up more time when rebasing on Docker Hub than #165 does. On GCR, over 80% of  real time appears to be spent in the `DiffID` method.

**Comment by jonjohnsonjr** [comment]
@sclevine can you try patching this in and see if it fixes you?

https://github.com/jonjohnsonjr/go-containerregistry/commit/d9e30031b9015b04effafe166823202611786839

This seems to work in my testing -- dropped rebase time from 17s to 6s.

**Comment by sclevine** [comment]
Patch works for me! Also seeing ~6s on GCR.

**Comment by jonjohnsonjr** [comment]
Improvement on dockerhub too? Or just GCR?

**Comment by sclevine** [comment]
It's ~25s faster on Docker Hub for me, but #165 makes it take much longer than 6s. Still a great improvement. 😄

**Comment by mattmoor** [comment]
@sclevine See the linked PR.  I've proposed an alternative to Jon's change that *should* avoid recomputing `DiffIDs` (and a model for augmenting the bare minimum we currently allow the base to provide to `partial`).  I've based this on the PR that fixes mounting against DockerHub, so I'd appreciate it if you could take it for a spin and confirm it fixes all the problems you were seeing.

**Comment by sclevine** [comment]
Sounds great. I'll test both issues against 8eeff01c82cf64317009e4067f14791288ba2678 and report back.

**Comment by sclevine** [comment]
@mattmoor Can confirm that this works. Docker Hub rebases are now ~6s for me. Thanks again!
