### ISSUE TITLE
ggcr: Unable to copy into Docker Hub when origin image has "3 part" name

### ISSUE THREAD

**Issue by njhale** [google/go-containerregistry#1687]
### Describe the bug

Copying a private remote image with a name consisting of more than two slash delimited components -- e.g. `ghcr.io/njhale/foo/bar:latest` -- into a Docker Hub repository with a standard "2 part" name -- `docker.io/njhale/bar:latest` -- fails with: `unexpected status code 400 Bad Request: {"details":"invalid repository name"}`.

### To Reproduce

1. Build, tag, and push a private image with a "3 part" name into a registry that supports it, such as GHCR
2. Use `crane copy`, setting the destination to a repo in `docker.io`

```bash
$ crane copy ghcr.io/njhale/foo/bar:latest docker.io/njhale/bar:latest

2023/05/04 14:14:37 Copying from ghcr.io/njhale/foo/bar:latest to docker.io/njhale/bar:latest
Error: failed to copy index: Post "https://index.docker.io/v2/njhale/bar/blobs/uploads/?from=njhale%2Ffoo%2Fbar&mount=sha256%3A493e4c0237bba932cb727098a2e21827b39e361ea2795b1b4598752d769a1d7b&origin=ghcr.io": GET https://auth.docker.io/token?scope=repository%3Anjhale%2Fbar%3Apull%2Cpush+repository%3Anjhale%2Ffoo%2Fbar%3Apull&scope=repository%3Anjhale%2Fbar%3Apush%2Cpull&service=registry.docker.io: unexpected status code 400 Bad Request: {"details":"invalid repository name"}
```

### Expected behavior

The image is successfully copied into the target Docker Hub repo.

### Additional context

- Copying the same image to both GHCR and ECR works
- [acorn-io/acorn](https://github.com/acorn-io/acorn) first encounters this issue [while calling `remote.WriteIndex`](https://github.com/acorn-io/acorn/blob/1fc80f7d020e1ee9938d43395f3e5271aac49806/pkg/server/registry/apigroups/acorn/images/push.go#L167) using module version `v0.13.0`
- Reproduced with `crane` version `0.14.0`

**Comment by jonjohnsonjr** [comment]
Can you confirm that this is fixed at HEAD?

https://github.com/google/go-containerregistry/pull/1681 should resolve this.

We can cut a release that includes it.

**Comment by njhale** [comment]
> Can you confirm that this is fixed at HEAD?

Yup, just checked and this is fixed at HEAD.

> We can cut a release that includes it.

That would be awesome, thanks!

**Comment by jonjohnsonjr** [comment]
Enjoy: https://github.com/google/go-containerregistry/releases/tag/v0.15.1
