### ISSUE TITLE
question: can crane do the same as docker manifest create?

### ISSUE THREAD

**Issue by abo-abo** [google/go-containerregistry#1689]
I'm currently doing the following with `docker`, while already using `crane` commands:
```
docker manifest create project/image:latest \
       --amend project/image:sha1 \
       --amend project/image-arm64:sha1
docker manifest push project/image:latest;
```
I'd like to remove the dependency on `docker` and instead use `crane` for everything. Is it possible for `crane` to create a manifest that forwards to two other images?

**Comment by jonjohnsonjr** [comment]
The `crane index` commands should be able to do what you want (if not, file a bug).

[This](https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#create-a-multi-platform-image-from-scratch) and [this](https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#filter-irrelevant-platforms-from-a-multi-platform-image) are similar examples.

I believe an equivalent command to that `docker` invocation would be:

```
crane index append -m project/image:sha1 -m project/image-arm64:sha1 -t project/image:latest
```

But it might be easier to express that in terms of platforms you want to extract from an existing index using `crane index filter`?
