### ISSUE TITLE
ggcr: Pass retryBackoff to transport.NewRetry in the remote pkg

### ISSUE THREAD

**Issue by somtochiama** [google/go-containerregistry#1692]
### Describe the feature

Not a bug report but a feature request.

It would be great if the `remote.BackOff` set in options gets passed now to the created transport in https://github.com/google/go-containerregistry/blob/a927d7c995a991edeb54e840f66d8cfffcf30d62/pkg/v1/remote/options.go#L165.

This would enable people to configure some parts of the retry operation without providing our own transport.

### Expected behavior

The retry transport is created with the `remote.BackOff` set in option.

### Additional context

- Version of the module
- Registry used (e.g., GCR, ECR, Quay)

**Comment by somtochiama** [comment]
@jonjohnsonjr @imjasonh Sorry for labelling this as a bug, it's really a question.
Is it a reasonable ask/feature request to have the  retry transport configured with remote backoff 
e.g 
```
o.transport = transport.NewRetry(o.transport, transport.WithRetryPredicate(defaultRetryPredicate), transport.WithRetryStatusCodes(o.retryStatusCodes...), transport.WithRetryBackoff(o.retryBackoff)))
```

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/pull/1628#issuecomment-1499536861

**Comment by somtochiama** [comment]
@jonjohnsonjr does this mean the remote backoff isn't intended for configuring retries on the transport?

If so, will you consider adding an option that is? Configuring a new transport when you only want to modify a backoff means copying some parts of the code in crane (like the default predicate and some other parts from the internal retry package)  and isn't the best experience
