### ISSUE TITLE
ggcr: Error while using `crane.Manifest`

### ISSUE THREAD

**Issue by Vishal-Chdhry** [google/go-containerregistry#1697]
### Describe the bug
I get this error when I fetch manifest with mediatype `application/vnd.oci.artifact.manifest.v1+json`
```
GET https://jimnotarytest.azurecr.io/v2/jim/net-monitor/manifests/sha256:10c0b24faa551466b708d1677694eb65bbe4679ba10c3a5290ecec2e4f0af6c8: MANIFEST_UNKNOWN: OCI artifact found, but accept header does not support OCI artifacts
```

### To Reproduce
Call the following function: 
```
crane.Manifest(`jimnotarytest.azurecr.io/jim/netmonitor@sha256:10c0b24faa551466b708d1677694eb65bbe4679ba10c3a5290ecec2e4f0af6c8`)
```
### Expected behavior

The manifest should be fetched as shown in Additional Context

### Additional context

Manifest:
```bash
oras manifest fetch jimnotarytest.azurecr.io/jim/net-monitor@sha256:10c0b24faa551466b708d1677694eb65bbe4679ba10c3a5290ecec2e4f0af6c8 | jq .
{
  "mediaType": "application/vnd.oci.artifact.manifest.v1+json",
  "artifactType": "vuln-scan",
  "blobs": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:bf9500c04c507cc5074cd4b174aa0a1d78009b3d71c6d487257017da1bd01700",
      "size": 178782,
      "annotations": {
        "org.opencontainers.image.title": "scan.json"
      }
    }
  ],
  "subject": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "digest": "sha256:ba7000206594c2d72c3ab550453004c0dc50961157e5ebd2fb8ea1890099d02d",
    "size": 528
  },
  "annotations": {
    "org.opencontainers.artifact.created": "2023-04-19T15:46:25Z"
  }
}
```

I might be happening because the `Accept` header doesnt have `application/vnd.oci.artifact.manifest.v1+json` media type in it.
Regclient also had the similar issue: https://github.com/regclient/regclient/issues/417

### Cause
I believe the issue is happening because, `crane.Manifest` calls `get` function, which takes a list of mediatypes as input
https://github.com/google/go-containerregistry/blob/0b12f56b375240c8534672bb356391ef9a5d8316/pkg/v1/remote/descriptor.go#L80-L82

The list of media type does not include `application/vnd.oci.artifact.manifest.v1+json`
https://github.com/google/go-containerregistry/blob/0b12f56b375240c8534672bb356391ef9a5d8316/pkg/v1/remote/descriptor.go#L28-L31

### Add any other context about the problem here.

- Version of the module: `github.com/google/go-containerregistry v0.14.1-0.20230425172351-b7c6e9dc3944`
- Registry used: ACR

**Comment by imjasonh** [comment]
> They are using `application/vnd.oci.artifact.manifest.v1+json` which is no longer part of the OCI spec, and I need to add some headers since there's still support for reading this data in regclient. 

https://github.com/regclient/regclient/issues/417#issuecomment-1533076643

Unlike `regclient`, crane has never had support for the artifact manifest, and I don't think we should add it since (as mentioned) it's not expected to be part of future OCI specs in that form at least.
