### ISSUE TITLE
question: why crane append without base image always set created to "0001-01-01T00:00:00Z"

### ISSUE THREAD

**Issue by baydakov-tn** [google/go-containerregistry#1703]
reproduce: use example from cmd/crane/recipes.md   
```crane config ${IMAGE}```

this is affect on many registries where image sorted by date in default

trouble in https://github.com/google/go-containerregistry/blob/b7ad3f13a62ce40366707a1347ab4bf33d5cd0d9/pkg/v1/empty/index.go#L51 because returned index is not filled with datetime

**Comment by imjasonh** [comment]
This is generally done for reproducibility. If you append the same file to an empty base image, today or tomorrow or a week from now, you'll get the same image digest.

**Comment by prestonvanloon** [comment]
Is there any way to set the default to `1970-01-01T00:00:00Z`? `0001-01-01 00:00:00 +0000 UTC` looks terrible in some UIs 

![Screenshot_2023-12-15_11-55-46](https://github.com/google/go-containerregistry/assets/7246818/d7bf1f26-164d-47bb-897b-be942583d19f)
