### ISSUE TITLE
question: why does `gcrane cp` fail with MANIFEST_INVALID

### ISSUE THREAD

**Issue by rafibarash** [google/go-containerregistry#1725]
Howdy @jonjohnsonjr! Miss u man, hope life and the baby have been good.

I recently got a customer support bug from a customer copying images from GCR->AR, and I wasn't sure if it was an issue with the customer's image or with `gcrane`.

The customer was able to pull the image from GCR and push to AR with the docker CLI without any issues, but when using gcrane ran into a `MANIFEST_INVALID: config file size (3106 bytes) does not match the config descriptor size (311 bytes)` error.

We somewhat recently added these config file size checks to GCR (Sep 2021) and AR (March 2021), so my original thinking was the GCR image the customer is trying to copy has issues but was pushed before we added these checks, but I can't figure out why the `docker` cli push would succeed when the `gcrane cp` command would fail.

I was wondering:

1. How to verify if the config size specified in the manifest actually matches the config blob size? I know we can get the config size in the manifest with `gcrane manifest <img> | jq .`, but I wasn't sure how to calculate the config blob size?
2. Do you think there's any chance this is a bug with gcrane? And if not, do you have any theories for how the `docker` cli could pull/push without issue but `gcrane cp` failed?

**Comment by jonjohnsonjr** [comment]
> Howdy jonjohnsonjr!  Miss u man, hope life and the baby have been good.

🤠 ❤️ 

> How to verify if the config size specified in the manifest actually matches the config blob size? I know we can get the config size in the manifest with gcrane manifest <img> | jq ., but I wasn't sure how to calculate the config blob size?

```
crane config <img> | wc -c
```

> Do you think there's any chance this is a bug with gcrane? And if not, do you have any theories for how the docker cli could pull/push without issue but gcrane cp failed?

Possibly, but I doubt it...

 My guess for why you don't see `docker push` fail is that `docker pull` throws away the manifest and `docker push` re-generates a new manifest with the correct config file size. Compare the manifest before to what it looks like after you `docker push` it.

Another theory is maybe this is a multi-platform image and one of the manifests is right but the other has an invalid config blob size?

I assume the image isn't public? Otherwise I could take a look.

**Comment by rafibarash** [comment]
Thanks Jon!! I haven't heard back from the customer yet so I'm guessing this helped confirm their issue. I'll go ahead and close this

**Comment by mfractal** [comment]
@jonjohnsonjr hi 

experiencing a similar issue with a public image.

any chance you could take a look ?

```
crane cp  public.ecr.aws/karpenter/controller:0.35.2 .... 

Error: PUT https://url/karpenter/controller/manifests/sha256:f61c026bcec3f25b3b0ba117559246c71d2e6d3b6e82d8b72885bcc71f78167c: MANIFEST_INVALID: manifest invalid; map[]
```
