### ISSUE TITLE
Does Crane support something equivalent to Docker Content Trust (DCT) ?

### ISSUE THREAD

**Issue by cbf123** [google/go-containerregistry#1738]
Just wondering if crane supports a mechanism to validate the image contents, similar to Docker Content Trust as documented at https://docs.docker.com/engine/security/trust/

Thanks!

**Comment by imjasonh** [comment]
Crane doesn't have something like this itself. You may be interested in Sigstore's [`cosign`](https://github.com/sigstore/cosign) though, which allows anyone to sign and verify and apply policy to container images and more. The [policy controller](https://docs.sigstore.dev/policy-controller/overview/) project lets you define policies about what kinds of signatures are required to pull and run images in a cluster, for example.
