### ISSUE TITLE
question: any plan to cut 0.15.2/0.16.0 soon?

### ISSUE THREAD

**Issue by phisco** [google/go-containerregistry#1753]
Hi! 
As per the title, is there any time to cut a new release any time soon? Release `0.15.2` was cut on the 16th of May, while `0.15.1` and `0.15.0` on the 5th of the same month and `0.14.0` before that was cut two months earlier, so I feel like we could be close to a new release.

The reason I'm asking is that, we are approaching the end of the development cycle for a new minor release of Crossplane, 1.13, and we would like to bump the dependency to get a few commits that were merged since `0.15.2` without having to point to `main`.

Thanks 🙏

**Comment by artem-panchenko** [comment]
@jonjohnsonjr @imjasonh folks, you cut new releases here before. Is there maybe a schedule / roadmap we could check to know future release dates? Thank you in advance!

**Comment by phisco** [comment]
I see 1.16.0 and 1.16.1 were cut yesterday! 🎉 thanks, I'll close this issue 🙏
