### ISSUE TITLE
ggcr: name functionally discards tags when a reference has both tag and digest

### ISSUE THREAD

**Issue by mxmeinhold** [google/go-containerregistry#1768]
### Describe the bug

When `name.ParseReference` is passed a reference that has both tag and digest, such as `registry.example.com/repo:tag@sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c`, it parses as a Digest.

This becomes noticeable when using `remote.Write`, which does not write the tag to the registry, as it uses the references `Identifier()` 
https://github.com/google/go-containerregistry/blob/a54d64203cffcbf94146e04069aae4a97f228ee2/pkg/v1/remote/write.go#L577

This behavior is well and good for pulling an image, where the digest is the most specific reference, but since `name.ParseReference` appears to discard the tag. I believe this occurs because `NewTag` splits on `:`, which would result in the sha256sum in the digest being read as the tag.
https://github.com/google/go-containerregistry/blob/a54d64203cffcbf94146e04069aae4a97f228ee2/pkg/name/tag.go#L77-L83

The `base` of our example reference is then considered as `registry.example.com/repo:tag`, which is parsed to a repo of `repo:tag`, which of course is not a valid repository name, so this reference can't be parsed with a tag
https://github.com/google/go-containerregistry/blob/a54d64203cffcbf94146e04069aae4a97f228ee2/pkg/name/repository.go#L78-L91

It looks like `NewDigest` actually does parse out the tag, but only uses this to get the repository https://github.com/google/go-containerregistry/blob/a54d64203cffcbf94146e04069aae4a97f228ee2/pkg/name/digest.go#L80-L83

This parsing is masked by `Digest.String()`, as it returns the unparsed reference https://github.com/google/go-containerregistry/blob/a54d64203cffcbf94146e04069aae4a97f228ee2/pkg/name/digest.go#L57-L60

### To Reproduce

```go
package refs

import (
	"testing"

	"github.com/google/go-containerregistry/pkg/name"
)

func TestGoContainerRegistryRef(t *testing.T) {

	t.Run("tag only", func(t *testing.T) {
		ref, err := name.ParseReference("registry.example.com/repo:tag")
		if err != nil {
			t.Error(err)
		}

		if ref.Identifier() != "tag" {
			t.Error("ref id:", ref.Identifier(), "expected:", "tag")
		}
	})

	t.Run("digest only", func(t *testing.T) {
		ref, err := name.ParseReference("registry.example.com/repo@sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")
		if err != nil {
			t.Error(err)
		}

		if ref.Identifier() != "sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c" {
			t.Error("ref id:", ref.Identifier(), "expected:", "sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")
		}
	})

	// this test will fail, as identifier only contains the digest
	t.Run("both", func(t *testing.T) {
		ref, err := name.ParseReference("registry.example.com/repo:tag@sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")
		if err != nil {
			t.Error(err)
		}

		if ref.Identifier() != "tag" {
			t.Error("ref id:", ref.Identifier(), "expected:", "tag")
		}
	})
}

```

### Expected behavior

A reference that contains both a tag and a digest should parse both components. When pulling the image, the digest should be used for specificity. When pushing the image, the tag should be used to ensure the tag is being created.

### Additional context

I believe this also impacts `crane`

Version: `github.com/google/go-containerregistry v0.16.1`
Registry: N/A, this is evident with reference parsing, and can be further validated with `net/http/httptest`

**Comment by imjasonh** [comment]
This has been reported before, and I've definitely had some attempts at fixing it, but nothing has stuck yet.

https://github.com/google/go-containerregistry/issues/702
https://github.com/google/go-containerregistry/issues/540

The handling of `name.Tag` and `name.Digest` makes this a bit difficult, since if we introduce a third `name.TagAndDigest` interface then code that handles typecasting one or the other needs to be careful to handle this new third case where it's a tag _and_ a digest.

That being said, I think it's worth trying to do again, and if you have ideas about how to do it, I'd gladly review a code change and give feedback.

**Comment by mxmeinhold** [comment]
With the current implementation, the API implies:
* `name.Tag`: this only has a tag
* `name.Digest`: this only has a digest

If one were to be extended, my inclination is to extend `name.Digest`, if only because the model is a series of wrappings (`Registry` within a `Repository` within a `Tag` or a `Digest), and since a full reference is `registry.example.com/repository:tag@digest`, I think it follows that a `Digest` could contain a `Tag`.

I see a couple models in the older issues,
* `name.Digest.AsTag() (name.Tag, bool)`: convert `name.Digest` to `name.Tag`
* `name.Reference.Target() string`: counterpart to `Identifier()` which exposes the read reference, this would expose the write reference (by which I mean `<reference>` as in `/v2/<name>/manifests/<reference>`)

A caveat with `AsTag`, it is probably worth being careful to carry over the original full reference string so that we aren't dropping information.

Another caveat I think I saw in other issues was to check, given a digest and tag when pushing, that the digest matches the provided push content?

Supplemental option: adding a backref to the `name.Digest` in the created `name.Tag` and exposing `name.Tag.AsDigest() (name.Digest, bool)`, though I don't think this is _necessary_, a user could maintain the original `Digest` or reparse it

I think a `name.TagAndDigest` would require expanding the `name.Reference` API for purposes like `Target()` anyways.

Not sure I can dig to much more into this today, but I will keep it in mind
