### ISSUE TITLE
image tags for v0.16.* are missing from gcr.io

### ISSUE THREAD

**Issue by joemiller** [google/go-containerregistry#1772]
The latest release is v0.16.1 - https://github.com/google/go-containerregistry/releases - which says the following tags are available to pull:

```console
docker pull gcr.io/go-containerregistry/crane:v0.16.1
docker pull gcr.io/go-containerregistry/gcrane:v0.16.1
```

But the tags are not available:
```
Error response from daemon: manifest for gcr.io/go-containerregistry/crane:v0.16.1 not found: manifest unknown: Failed to fetch "v0.16.1"
```

It looks like tags after 0.15.2 are not being pushed:

```console
$ crane ls gcr.io/go-containerregistry/crane | grep -E '^v'
v0.10.0
v0.11.0
v0.12.0
v0.12.1
v0.13.0
v0.14.0
v0.15.0
v0.15.1
v0.15.2
v0.5.0
v0.5.1
v0.6.0
v0.7.0
v0.8.0
v0.9.0
```

**Comment by madrisan** [comment]
image tags for `v0.16.*` are still missing :/

**Comment by bobdoah** [comment]
doesn't seem to be an image tag for `v0.17.0` either

**Comment by sankalp-khare** [comment]
[x-post](https://github.com/google/go-containerregistry/issues/1851#issuecomment-1829027514) for visibility
