### ISSUE TITLE
question: pass 2 sets of credentials to crane.CopyRepository

### ISSUE THREAD

**Issue by bangiopicher2** [google/go-containerregistry#1774]
My source and destination registries are different and I have 2 sets of credentials that I need to pass to crane.CopyRepository via the option crane.withAuth
Is this possible at all?

**Comment by imjasonh** [comment]
This is possible with https://pkg.go.dev/github.com/google/go-containerregistry@v0.16.1/pkg/authn#NewMultiKeychain

**Comment by bangiopicher2** [comment]
@imjasonh Thanks for your response!
I don't want to rely on keychains and external credential stores or configuration files.
I am trying to simply pass 2 sets of credentials to crane.withAuth(). With 1 set of credentials, this works perfectly by defining an AuthConfig with only username and password, building an authenticator with authn.fromConfig(authconfig) and passing the authenticator to crane.withAuth().
The problem is that many functions (including copyRepository) deal with 2 registries (most likely they will have 2 different sets of credentials), but the withAuth option only allow you to pass 1 authenticator with 1 set of credentials.
Is what I am trying to do possible at all?

**Comment by imjasonh** [comment]
`crane.WithAuth` only deals with one set of credentials, unfortunately: it overwrites any existing auth with the provided auth: https://github.com/google/go-containerregistry/blob/v0.16.1/pkg/crane/options.go#L132

If you use

```
var auth1, auth2 authn.AuthConfig
crane.WithAuthFromKeychain(authn.NewMultiKeychain(
  staticKeychain{"reg1", auth1},
  staticKeychain{"reg2", auth2},
))
```

where `staticKeychain` is defined as:

```
type staticKeychain struct {
  registry string
  auth authn.AuthConfig
}

func (s staticKeychain) Resolve(rs authn.Resource) (Authenticator, error) {
  if rs.RegistryStr() != s.registry {
    return authn.Anonymous, nil
  }

  return staticAuthenticator{s.auth}
}

type staticAuthenticator struct {
  auth authn.Authenticator
}

func (s staticAuthenticator) Authorization() (*authn.AuthConfig, error) {
  return &s.auth, nil
}
```

(phew that's a lot! 😮‍💨)

Anyway, what that does is configure a single auth source, which delegates to one of two auth sources based on the registry string (you could also switch based on the repo, if copying between two repos in the same registry with different credentials, but this is rare).

When pulling from the source repo you'll use the appropriate creds, likewise when pushing to the destination repo.

**Comment by bangiopicher2** [comment]
Hi @imjasonh, I made this small change to make it work:

`type staticAuthenticator struct {
  auth authn.AuthConfig
}`

This is great, thanks for pointing me in the right direction!
