### ISSUE TITLE
question: Does the rust language have a library like Crane

### ISSUE THREAD

**Issue by mark0-cn** [google/go-containerregistry#1777]
Does the rust language have a library like Crane? Thank you.

**Comment by imjasonh** [comment]
Sorry for the delay.

The closest thing I'm aware of is https://github.com/krustlet/oci-distribution/ but I'm not sure how actively developed it is. I tried to [add support](https://github.com/krustlet/oci-distribution/pull/39) for an equivalent to ggcr's `authn.DefaultKeychain` a while ago, but ended up giving up (my fault, not theirs).
