### ISSUE TITLE
Allow `ko apply -L` to be configurable

### ISSUE THREAD

**Issue by scothis** [google/go-containerregistry#179]
I work on a team where some develop against GKE and others against minikube. When targeting minikube, the `-L` flag is needed, while when targeting GKE using `-L` will cause image pull errors. This makes scripting `ko` more difficult as script needs to distinguish between the two environments and configure each `ko apply` command correctly.

It would be nice if the `-L` flag could be applied uniformly with an environment variable.

We attempt to [hack around this issue](https://github.com/scothis/stream-spike/blob/227b3999c09389ea1dad86297bbc564f77cabc24/Makefile#L69-L78) by detecting `KO_REPO_OVERRIDE` and setting the `-L` flag if the override is not set.

**Comment by jonjohnsonjr** [comment]
WDYT about making this the default behavior, e.g. something like:

```
if os.Getenv("KO_DOCKER_REPO") == "" {
  log.Println("KO_DOCKER_REPO unset, falling back to local mode (-L/--local).")
  lo.Local = true
}
```

/cc @mattmoor

**Comment by scothis** [comment]
I like that, but it also makes it easy to apply a resource with an image that a remote cluster will be unable to pull.

**Comment by mattmoor** [comment]
I like `KO_DOCKER_REPO=ko.local` == `-L`, WDYT?

**Comment by scothis** [comment]
@mattmoor Unless you hit this tonight, I would enjoy taking a crack at it in the morning. Feel free to assign me.

**Comment by mattmoor** [comment]
I'm about to send a PR :)
