### ISSUE TITLE
question: Docker Media Type versus OCI Media Type

### ISSUE THREAD

**Issue by joaopapereira** [google/go-containerregistry#1793]
Is there any particular reason for us to be using the Docker Manifest media type in places like https://github.com/google/go-containerregistry/blob/main/pkg/v1/empty/image.go#L32 instead of using the MediaType defined in the OCI Image Spec?

**Comment by django1194** [comment]
Additionally, this causes issues with certain platforms such as OpenShift that will report `unsupported media type dockerv2s2`. I'm having to convert everything to OCI format but it super annoying having to do it with this too.

Perhaps as a way of keeping backwards compatability we could add a constructor that allows us to specify the media type?

**Comment by codingben** [comment]
I opened PR to modify it: https://github.com/google/go-containerregistry/pull/1905
