### ISSUE TITLE
question: add multiple tags to target image

### ISSUE THREAD

**Issue by rgrzesk** [google/go-containerregistry#1797]
I am currently copying images by adding a new tag:
`gcrane cp europe-west3-docker.pkg.dev/project-a/a-registry/main:latest europe-west3-docker.pkg.dev/project-b/b-registry/main:newTag`

Is it possible to add multiple tags to the target? So that in project-b my main has eg. tags: newTag, newTag1, newTag2?

**Comment by ericsmalling** [comment]
I have a use case where someone is wanting to copy an image with all of the same tags it has in the origin registry.  We can get a list of all tags pointing to the digest through other means but would like to avoid a looping shell script to recreate them if possible.

**Comment by ericsmalling** [comment]
Would we want to have this be atomic, rolling back any applied tags if any of them fail to be added, or simply warn that not all of them were applied?
