### ISSUE TITLE
ko should allow images to be tagged with other tags (not just :latest)

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#181]
`ko apply`, `resolve`, `publish` all publish to `$KO_DOCKER_REPO/$importpath:latest` due to code [here](https://github.com/google/go-containerregistry/blob/36637b11473b5be14cc7271b034e098a9b572529/ko/publish/default.go#L47-L49).

Some users might want to tag these images with something other than `:latest`, possibly with multiple tags. Where that is configured is up for debate (in `.ko.yaml` or in another env var? How to specify multiple tags?).

**Comment by jonjohnsonjr** [comment]
I think if we start down this path, it makes more sense to have a skaffold builder that leverages `ko` (or implements its ideas) rather than building this into `ko`. IMO, the biggest selling point of `ko` is that it "just works".

/cc @ahmetb

**Comment by mattmoor** [comment]
+1 on the relevance to release management.  cc @adrcunha 

Right now in Knative we have some scripts that extract and tag image references from the resolved yaml, but ideally we could just make this:
```yaml
# Nightly releases
ko resolve --tag={commit} -f config/

# Release tags
ko resolve --tag=vX.Y.Z -f config/
```

The tags are cosmetic from the standpoint of the yaml, but are certainly helpful when trying to determine the release for a given image.

**Comment by mattmoor** [comment]
We should also consider making it `--tags` since I know some folks will want to do something like `--tags=latest,{commit},vX.Y.Z`

**Comment by adrcunha** [comment]
+1 for `--tags`

**Comment by paivagustavo** [comment]
I like the idea to add custom tags to this as well. Any reasons why #277 was closed? Can I reuse it and finish the implementation?

**Comment by adrcunha** [comment]
@markusthoemmes ^^

**Comment by markusthoemmes** [comment]
@paivagustavo sure go ahead. I was just lacking time finishing it and it was lying around.
