### ISSUE TITLE
crane: Deleting image by tag not working

### ISSUE THREAD

**Issue by iFrozenPhoenix** [google/go-containerregistry#1822]
### Describe the bug
Deleting a tag, i.e. the manifest and the blob, is not working when using crane delete registry.domain/repo/image:tag

### To Reproduce
crane delete registry.domain/repo/image:tag

### Expected behavior
when the delete command is specified with a tag instead of a digest the tag is automatically resolved to the digest value and the delete command is executed with the digest. 

### Additional context

Registry: Distribution

**Comment by megamorf** [comment]
I'm also facing this issue. I ran `crane ls`, did some grep magic and piped the output to xargs `... | xargs -I % crane delete "${REGISTRY}/${NAMESPACE}/${PROJECT}:%"` but get `invalid checksum digest format`.

The help text does not indicate that a digest is expected and just like OP said I'd expect crane to resolve the tag accordingly:

```
▶ crane delete --help
Delete an image reference from its registry

Usage:
  crane delete IMAGE [flags]

Flags:
  -h, --help   help for delete

Global Flags:
      --allow-nondistributable-artifacts   Allow pushing non-distributable (foreign) layers
      --insecure                           Allow image references to be fetched without TLS
      --platform platform                  Specifies the platform in the form os/arch[/variant][:osversion] (e.g. linux/amd64). (default all)
  -v, --verbose                            Enable debug logs

```

**Comment by sankalp-khare** [comment]
@iFrozenPhoenix could you share the output when you try this? thanks!

**Comment by iFrozenPhoenix** [comment]
@sankalp-khare the error was something that the hash couldn't be found. Actually I can't reproduce it anymore.
Deleting a tag is now actually working. Can't say if it was a problem of the registry (distributon) or crane.

**Comment by megamorf** [comment]
> @sankalp-khare the error was something that the hash couldn't be found. Actually I can't reproduce it anymore.
> Deleting a tag is now actually working. Can't say if it was a problem of the registry (distributon) or crane.

Can you add the crane version that you tested with so that I can check as well :-)

**Comment by iFrozenPhoenix** [comment]
Sure, 0.19.0
