### ISSUE TITLE
crane: `--platform` does nothing?

### ISSUE THREAD

**Issue by slonopotamus** [google/go-containerregistry#1839]
### Describe the bug

I'm trying to create an image with non-empty platform string by passing `--platform` to various crane command, but none of them seem to respect it

### To Reproduce

What I've tried:

1. `crane append --oci-empty-base --platform darwin/arm64 -t <tag> -f <tarball>` - nope, manifest doesn't have platform in it
2. `crane tag --platform darwin/arm64 <image from previous step> <new tag>` - nope
3. `crane copy --platform darwin/arm64 <image from first step> <new tag>` - still nope

### Expected behavior

There is _some_ way to produce platform-specific image via crane

### Additional context

- Output of `crane version`: 0.16.1
- Registry used: ghcr.io

**Comment by slonopotamus** [comment]
Never understood stalebots... Issues do not magically fix themselves.

**Comment by pvillaverde** [comment]
Same here, trying to get a list of image from a repo for a platform does not seems to work. i.e.

```bash
docker run -ti --entrypoint "" gcr.io/go-containerregistry/crane:debug sh
/ # crane ls --platform linux/amd64 registry.k8s.io/defaultbackend-amd64
1.1
1.2
1.3
1.4
1.5
/ # crane ls --platform linux/arm64 registry.k8s.io/defaultbackend-amd64
1.1
1.2
1.3
1.4
1.5
```
In theory this repository should not have images for arm64, and viceversa with this other one:

```bash
/ # crane ls --platform linux/arm64 registry.k8s.io/defaultbackend-arm64
1.1
1.2
1.3
1.4
1.5
/ # crane ls --platform linux/amd64 registry.k8s.io/defaultbackend-arm64
1.1
1.2
1.3
1.4
1.5
```

**Comment by slonopotamus** [comment]
https://nostalebots.xyz/

**Comment by stereobutter** [comment]
This issue is still relevant.
