### ISSUE TITLE
How to get just the image name from the oci repo url 

### ISSUE THREAD

**Issue by PuneetPunamiya** [google/go-containerregistry#1841]
### Cannot get the name of image

Let's say I have an image 

`docker.io/puneet2147/kaniko-chains@sha256:bc4f7468f87486e3835b09098c74cd7f54db2cf697cbb9b824271b95a2d087ff`

As of today is there any method, where I can get just the imageName i.e. expected output will be `kaniko-chains`

Because, I tried this function 

```golang
digest, err := name.NewDigest(test.testImageName)

if err != nil {
	t.Error(err)
}

t.Logf("this is digest: %s and repository: %s and registry: %s", digest.DigestStr(), digest.RepositoryStr(), digest.RegistryStr())
```

and the output of the above code is 

```bash= 
this is digest: sha256:bc4f7468f87486e3835b09098c74cd7f54db2cf697cbb9b824271b95a2d087ff and repository: puneet2147/kaniko-chains and registry: index.docker.io
```

**Comment by imjasonh** [comment]
The repo name is the entire path section of that reference, including the Dockerhub username, so `puneet2147/kaniko-chains`.

Other registry implementations might let you push to `example.com/foo` without the username part. The requirement that repos are under usernames is just an implementation detail of Dockerhub. For example, you can push to an image to `ttl.sh/puneet`.

If you want only the last segment of the path component, you can do that using [`strings.Split`](https://pkg.go.dev/strings#Split), [`strings.Cut`](https://pkg.go.dev/strings#Cut), [`path.Split`](https://pkg.go.dev/path#Split), or other Go stdlib methods, depending on what you're trying to achieve and what inputs you expect.

**Comment by PuneetPunamiya** [comment]
Yeah I was using  [strings.Split](https://pkg.go.dev/strings#Split) but I got your point regarding the repo name and it's path. Thanks :)
