### ISSUE TITLE
RFC: Support adding data to images in ko

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#185]
cc @dprotaso 

## Question: How do I add static assets to images produced by `ko`?

This is a question that's come up at least a handful of times. This is trivial with `Dockerfile`. This is doable with Bazel. So how do you add static assets to the container image produced by `ko`?

My guiding principle with `ko` is to bias heavily towards Go idioms, so I found myself asking: **"How would a Go *binary* do this?"**

Turns out that Go has no special provisions for including data into Go binaries.  The method I come across most often seems to be `go-bindata` ([e.g.](https://mlafeldt.github.io/blog/embedding-assets-in-go/)), which effectively generates a Go package that inlines the data, and exposes an API for accessing that data.  **This solution should work fine with `ko` as-is.**  However, it feels like overkill to include data into a binary only to expand it into a filesystem that we are synthesizing ourselves anyways.  The DevX of requiring `go generate` or `go-bindata` invocations before `ko apply` also leaves something to be desired.

The next Go idiom that occurred to me was the `testdata/` idiom for exposing test data to Go tests.  This path is [special cased](https://github.com/golang/go/issues/14715) by the Go tool to expose certain data to tests.

**What if, leaning on this idiom as precedent, we special cased our own directory, e.g. `kodata/`?**  We could mount this data into some fixed path on the container filesystem (e.g. `/var/run/ko/...`) and expose that path to the user binary via an environment variable (e.g. `KO_DATA_PATH=/var/run/ko`).  This enables the user to use: `KO_DATA_PATH=$PWD/cmd/foo/kodata go run ./cmd/foo/*.go ...` to run without `ko` too.

This is intended as a "request for comments", so I'd love to hear thoughts.

**Comment by dprotaso** [comment]
When chatting about this I realize that k8s ConfigMaps solved my needs

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume

This was because the executable I'm invoking allowed me to pass arguments (ie. path to a TLS cert)

**Comment by mattmoor** [comment]
Sure, but what's not clear to me is whether that's the common case or the exceptional case.

Part of my interest in writing this up was to document existing options as well, and the reasoning around all of it.  Unless there's a major outpouring of support for something like this, I expect we should just direct folks to `go-bindata` (or direct them to options like `ConfigMap`) and be done with it.
