### ISSUE TITLE
crane: running image as non-root UID fails

### ISSUE THREAD

**Issue by kuwv** [google/go-containerregistry#1852]
### Describe the bug

Currently, the GCR crane image runs as root and mounts the root directory. Software factories often downgrade CI/CD images to a unprivileged user to improve security. This will cause crane to attempt creating credentials at `/.docker/config.json` and fail.

### To Reproduce

Run crane as UID 1000.

### Expected behavior

Run crane as non-root user and/or from a dedicated `/workspace` directory. Additionally, set the proper linux capabilities if running crane as non-root user.

### Additional context

- GitLab used as CI/CD environment
- gcr.io/go-containerregistry/crane:debug

**Comment by kuwv** [comment]
Bump

**Comment by Prieschl** [comment]
this is still a problem

**Comment by Prieschl** [comment]
I found a workaround for now: You can set the environment variable HOME=/tmp/
Then it will write to /tmp/.docker/config.json, where non-root user has permissions.
