### ISSUE TITLE
question: How can i push a compressed image tar (gzip compressed) using crane push command.

### ISSUE THREAD

**Issue by SanadhyaLakshya** [google/go-containerregistry#1859]
Current behavior: when using command  **crane push push.tar test.iem.svc:5000/devicefeatureapp/nginx:1.10.0 --insecure**  i am getting the error "invalid tar header" error

* The push.tar is image tar ball which is compressed using gzip

Expected Behavior: the image blob should be pushed successfully on the registry.

Any workaround possible.?

**Comment by ashpect** [comment]
gzip the tar file using flag -czvf (explicitly mentioning the z flag) { eg : tar -czvf ... }, in case the system zips it up using something else. It might work.
