### ISSUE TITLE
question: append with an empty base and  environment vars?

### ISSUE THREAD

**Issue by jordan-da** [google/go-containerregistry#1881]
I know it's possible to `append` over an empty base _or_ `mutate` an existing base with environment vars or append layers to it, but is it possible to append layers and environment vars over an empty base?

For example, something like:

```
crane mutate --oci-empty-base -e foo=bar --append tarball.tgz -t someregistry/someimage:sometag 
```

or 

```
crane append --oci-empty-base -e foo=bar -f tarball.tgz -t someregistry/someimage:sometag 
```

**Comment by jordan-da** [comment]
Slightly related but I noticed that even Ko doesn't really support this?

https://github.com/ko-build/ko/issues/800

Is there is technical reason this is so tricky?

**Comment by jordan-da** [comment]
maybe what i am asking for is for this to work?

```
crane mutate scratch --append tarball.tgz -t  us.gcr.io/my-images/my-image:image
Error: pulling scratch: GET https://index.docker.io/v2/library/scratch/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; unknown tag=latest
```

**Comment by thesayyn** [comment]
You can combine  crane append with crane mutate.  That's what we do in rules_oci
