### ISSUE TITLE
Auth issue in kaniko -- Unrecognized challenge: BASIC

### ISSUE THREAD

**Issue by priyawadhwa** [google/go-containerregistry#189]
This [issue](https://github.com/GoogleContainerTools/kaniko/issues/196) was opened in kaniko, and it seems like it's hitting an auth error from [here](https://github.com/google/go-containerregistry/blob/0ff1db03aaaabc9820e8a13353f61d8474814abd/v1/remote/transport/transport.go#L82) (I think it's happening when kaniko is trying to push the final image). It could have something to do with the docker config, just wondering if anyone knew why this might be happening?

**Comment by jonjohnsonjr** [comment]
@dekkagaijin didn't you solve this in the python library?

**Comment by mattmoor** [comment]
@priyawadhwa I suspect the problem may be that `strings.Title` [here](https://github.com/google/go-containerregistry/blob/0ff1db03aaaabc9820e8a13353f61d8474814abd/v1/remote/transport/ping.go#L78) isn't WAI.

**Comment by jonjohnsonjr** [comment]
```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.Title("BASIC"))
	fmt.Println(strings.Title(strings.ToLower("BASIC")))
}
```
```
BASIC
Basic
```

**Comment by priyawadhwa** [comment]
Thank you! :)
