### ISSUE TITLE
ggcr: `mutate.Extract` does not handle whiteouts of directories properly

### ISSUE THREAD

**Issue by tri-adam** [google/go-containerregistry#1897]
### Describe the bug

When the source image contains a layer with an opaque whiteout, the output of `mutate.Extract` seems to contain unexpected content.

### To Reproduce

I've implemented a reproducer in the form of a test in https://github.com/tri-adam/go-containerregistry/commit/062c74e0d745d850e89a62512c32edd924ce9310.

In the test, an image whose base layer is:

```
a/
a/b/
a/b/foo
```

.. with a layer that deletes `a/b/` using an opaque whiteout on `a/`:

```
a/
a/.wh..wh..opq
```

... results in a (squashed) layer that contains `a/b/`:

```
a/
a/b/
a/b/foo
```

### Expected behavior

I believe the expected output would be:

```
a/
```

### Additional context

- Version of the module: v0.19.1

**Comment by ssst0n3** [comment]
Did this issue has been fixed?
