### ISSUE TITLE
question: Consider distributing crane on conda-forge

### ISSUE THREAD

**Issue by matthewfeickert** [google/go-containerregistry#1899]
:wave: `crane` is [already installable](https://github.com/google/go-containerregistry/tree/8b3c3036d612bcb3c1147fe11c2d1818dc432329/cmd/crane#installation) from a collection of different methods, which is great. However, it would be nice if it was also distributed on [conda-forge](https://conda-forge.org/), as this would make it accessible to a wide collection of ecosystems and tools.

Would the team be open to the idea of adding `crane` as a PR to https://github.com/conda-forge/staged-recipes and then managing the automated release PRs that would come up with its associated [conda-forge feedstock](https://github.com/conda-forge/feedstocks)?

**Comment by matthewfeickert** [comment]
While I appreciate that there are `go` specific package registries, given that `go` itself is on conda-forge (https://github.com/conda-forge/go-feedstock) it doesn't seem unreasonable to have `crane` be there too.

**Comment by benmoss** [comment]
I created one here https://github.com/conda-forge/crane-feedstock

**Comment by matthewfeickert** [comment]
> I created one here https://github.com/conda-forge/crane-feedstock

Amazing! Thank you so much @benmoss!

I can now use [`pixi`](https://pixi.sh/) to get the latest release of `crane` for my system. :) 

```console
$ pixi search crane
Using channels from global config: conda-forge

crane ha8f183a_0
----------------

Name                crane              
Version             0.20.1
Build               ha8f183a_0         
Size                3578432            
License             Apache-2.0         
Subdir              linux-64           
File Name           crane-0.20.1-ha8f183a_0.conda
URL                 https://conda.anaconda.org/conda-forge/linux-64/crane-0.20.1-ha8f183a_0.conda
MD5                 40a6b978252d250f50eee352931a6349
SHA256              d18578b595535ada37dd675d5feed686b2e6e79cbf21985772ee4a56add1b002

Dependencies:
$ pixi global install crane
✔ Installed package crane 0.20.1 ha8f183a_0 from conda-forge
  These executables are now globally available:
   -  crane
$ command -v crane
/home/feickert/.pixi/bin/crane
$ crane version
0.20.1
```
