### ISSUE TITLE
ko publish should support relative import paths

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#190]
I'd love to be able to say `ko publish ./cmd/foo` like I can say `go build ./cmd/foo`.

cc @ImJasonH

**Comment by jonjohnsonjr** [comment]
What about `ko publish ./...` ?

**Comment by ImJasonH** [comment]
If we support that we should probably only build `package main` packages, otherwise you're going to build a lot of useless images.

**Comment by mattmoor** [comment]
I think this is done.

**Comment by ImJasonH** [comment]
The only thing we don't have is `./...`, I'm not sure how important that is or if it's just nice-to-have. If somebody wants it we can open a new issue
