### ISSUE TITLE
crane: cannot push or validate .tar.gz format

### ISSUE THREAD

**Issue by a-h** [google/go-containerregistry#1908]
### Describe the bug

`crane` doesn't support working with `.tar.gz` files, requiring that Docker container images that are gzipped are first untarred.

Attempting to run `crane validate --tarball <filename>.tar.gz` results in the error:

```
Error: failed to read image <filename>.tar.gz: archive/tar: invalid tar header
```

### To Reproduce

- Create an empty directory.
- Initialize a git repo in it with `git init`.
- Create  a `flake.nix` file containing this content and add it with `git add flake.nix`:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/23.11";
  };

  outputs = { self, nixpkgs }:
    let
      allSystems = [
        "x86_64-linux" # 64-bit Intel/AMD Linux
        "aarch64-linux" # 64-bit ARM Linux
      ];
      forAllSystems = f: nixpkgs.lib.genAttrs allSystems (system: f {
        system = system;
        pkgs = import nixpkgs {
          inherit system;
        };
      });

      # Build Docker container.
      dockerImageTools = system: pkgs: pkgs.dockerTools.buildImage {
        name = "tools";
        tag = "latest";
        copyToRoot = [
          pkgs.coreutils
          pkgs.bash
          pkgs.jq
        ];
        config = {
          Cmd = [ "bash" ];
        };
      };
    in
    {
      packages = forAllSystems ({ system, pkgs }: {
        docker-image-tools = dockerImageTools system pkgs;
      });
    };
}
```

- Run `nix build ./#packages.x86_64-linux.docker-image-tools` which outputs a `result` file, which is a `.tar.gz` file.
- Run `crane validate --tarball /nix/store/8cix3l8fwpz7m5v7cggmk0467s9s7naj-docker-image-tools.tar.gz` to see the error. 

### Expected behavior

Expected it to work without additional steps.

**Comment by a-h** [comment]
This issue would be fixed by merging https://github.com/google/go-containerregistry/pull/1858

I've tested the PR and confirm it works well.

This also probably fixes https://github.com/google/go-containerregistry/issues/1838

**Comment by zhangguanzhang** [comment]
@jonjohnsonjr PTAL

**Comment by zhangguanzhang** [comment]
@imjasonh cc
