### ISSUE TITLE
crane: requesting 1000 tags from quay.io reports that max of 100 tags is exceeded

### ISSUE THREAD

**Issue by khrisrichardson** [google/go-containerregistry#1963]
### Describe the bug

quay.io just started reporting the following error when using crane

> TOO_MANY_TAGS_REQUESTED: Too many tags requested; requested limit 1000 is too high, max is 100

### Expected behavior

The following shouldn't fail, but instead produces the above error.

```shell
crane ls quay.io/prometheus-operator/prometheus-config-reloader
```

**Comment by jamesbarnett91** [comment]
We are also hitting this issue. Seems like it's linked to a recent change to Quay which must have just been rolled out to quay.io: https://github.com/quay/quay/pull/2884 
>There is a small wrinkle though: as per the OCI spec, a client is still allowed to request an arbitrarily high number of tags to be returned in a single API call, which we so far silently ignored and returned the configured maximum. Now we return an HTTP 413 response, which technically is against the spec but needed in order to protect the registry against rogue clients and also return a clear error signal instead of less tags than the client asked for

So their limit always was 100 but was being silently ignored before, whereas now they throw an error.

Seems like there is already logic to set the current 1000 limit for non-Google registries, maybe this now needs an extra check for quay.io to set to n=100? https://github.com/google/go-containerregistry/blob/1b4e4078a545f2b6f96766a064b45ee77cdbefdd/pkg/v1/google/list.go#L98-L102

**Comment by khrisrichardson** [comment]
It looks like quay fixed this on their end: https://github.com/fluxcd/image-reflector-controller/issues/585#issuecomment-2183332064
