### ISSUE TITLE
ko apply shouldn't need to be run inside GOPATH

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#197]
It doesn't make sense to say:

```yaml
image: ./cmd/foo
```

It only makes sense IMO to include full importpaths in YAML, at which point we can run `ko apply` outside of GOPATH and have it assume importpaths are at `$GOPATH/src/$importpath`

For `ko publish` it probably makes sense to be less strict (#190), and if given a relative path, assume it's being run inside GOPATH.

This also allows `ko` (excluding `publish` with relative importpaths) to be run outside of `GOPATH`, which would enable us to easily produce a builder image for use in GCB.

[My fork's `kobin` branch](https://github.com/ImJasonH/go-containerregistry/tree/kobin?files=1) has this change, and also excludes building images from non-`package main` packages, but is broken by some interaction of the `go/build.Default.GOPATH` and Bazel. If we dropped Bazel for tests (#198) I believe we could merge it (relevant tests pass with `go test`).

**Comment by jonjohnsonjr** [comment]
> but is broken by some interaction of the go/build.Default.GOPATH and Bazel

I wonder if this is fixed by #217

**Comment by ImJasonH** [comment]
Closed in #229
