### ISSUE TITLE
Drop Bazel

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#198]
Bazel is only necessary for tests, and tests really don't like to be run without Bazel (panics, failures, spurious files created).

I don't think Bazel really buys us anything, and can make it harder for people to contribute.

**Comment by jonjohnsonjr** [comment]
I think we can close out https://github.com/google/go-containerregistry/issues/24 easily when this lands, too?

**Comment by mattmoor** [comment]
I had to install Bazel on my new machine for this repo :(
