### ISSUE TITLE
question: why are version tagged crane images no longer being pushed to gcr.io/go-containerregistry even though the docs specifically say to use that

### ISSUE THREAD

**Issue by sflanker** [google/go-containerregistry#1988]
The latets tag for `gcr.io/go-containerregistry/crane` is way back on ea19b579661d99bc753c92e93730b8aab6ecd31b which was from July of last year and corresponds with [v0.16.0](https://github.com/google/go-containerregistry/releases/tag/v0.16.0) even though no versioned labels have been pushed. since v0.15.2!

It would be really great if this project would either maintain these container images, or update the documentation to reflect that they are deprecated and should not be used.

**Comment by laurivosandi** [comment]
Same question here. Please add GitHub actions pipeline to build and upload it
