### ISSUE TITLE
crane append should accept flags, not positional args

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#200]
Cobra's generated docs for positional args are bad, and flags make it harder to mess up "src vs dst" ordering bugs anyway. 

Check with existing users whether they'll be broken by this change and whether we should support both for some period while they migrate.

Also document that crane is experimental and likely to change in breaking ways until an official release is cut.

**Comment by ImJasonH** [comment]
@sclevine you might be the only real crane user at this point?

**Comment by sclevine** [comment]
I only use the `crane` binary to report issues with the underlying library in a way that's easy to reproduce. Definitely support this change though.

**Comment by jonjohnsonjr** [comment]
Hello I am the other user :)

For the things I use a lot (`ls`, `copy`, `manifest`, `config`, `digest`), I feel that adding flags would be additional overhead that I'd like to avoid. Some commands are difficult to understand without flags (e.g. `rebase`), so I agree with you there, but if we just want to avoid bad cobra docs I'd rather just hand-craft the READMEs myself :)
