### ISSUE TITLE
question: crane cp  support multiple `--platform`

### ISSUE THREAD

**Issue by zirain** [google/go-containerregistry#2016]
use golang as example, I just want copy `linux/amd64` and `linux/arm64`, can I use following command?
```shell
crane cp "golang:1.23.1" "${MIRROR_REGISTRY}/[${imageName}](golang:1.23.1)" --platform linux/arm64 --platform linux/amd64
```

**Comment by ameir** [comment]
I have a PR out that adds support for this (https://github.com/google/go-containerregistry/pull/1939). If you know that your source image is multi-arch, you can alternatively use `crane index filter`.

**Comment by zirain** [comment]
closed as https://github.com/google/go-containerregistry/pull/1939
