### ISSUE TITLE
Support foreign/restricted layers

### ISSUE THREAD

**Issue by dekkagaijin** [google/go-containerregistry#207]
This is mostly an issue when naively attempting to pull layers. 

Docker V2 Schema2 media type: `application/vnd.docker.image.rootfs.foreign.diff.tar.gzip`

OCI NonDistributable: https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/mediatype.go

Tagging @jonjohnsonjr for others that I missed

**Comment by dekkagaijin** [comment]
I'll be doing this for the python lib, and will do the work for ggcr, as well, if it isn't picked up beforehand.

**Comment by genevieve** [comment]
Hey @jonjohnsonjr! Are you looking for someone to make a PR for this functionality? Are you interested in this library supporting this functionality?

**Comment by dekkagaijin** [comment]
@genevieve all the love this lib gets is a good thing, most likely.

I only updated the Python lib to support remote -> remote registry pushes before leaving the team, and don't know if it's been updated internally or externally to support local pulls or pushes.

**Comment by jonjohnsonjr** [comment]
@genevieve yeah we're definitely interested in supporting this, I just haven't found the time to add it.

At one point I started working on it but got distracted: https://github.com/google/go-containerregistry/compare/master...jonjohnsonjr:foreign

I'm not sure how far behind that branch is -- rebasing might be harder than starting from scratch :)

**Comment by genevieve** [comment]
@dekkagaijin @jonjohnsonjr Thank you both for your quick responses! I'm going to try working on it now and I'll get back to you if I find myself in over my head!
