### ISSUE TITLE
Move the libraries under pkg

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#21]

**Comment by mattmoor** [comment]
Should wait until fewer PRs are outstanding.

**Comment by dekkagaijin** [comment]
Wouldn't this consolidate everything into `pkg` and `tools`?
Given that this is primarily a library package, seems like it would be fine to skip the 'pkg' part...?

**Comment by mattmoor** [comment]
`tools` => `cmd`

**Comment by dekkagaijin** [comment]
Wouldn't this consolidate everything under `cmd` and `package`? Given that this is primarily a set of libraries, and secondarily a set of binary tools which are fairly thin wrappers of the libs, would it not make sense to have `cmd` and leave the libs as-is? I don't think we're ever going to get as big as k8s, and probably won't have much beyond the library and tools, as in google/containerregistry.

**Comment by mattmoor** [comment]
I understand your sentiment, but I'm not sure I understand the relevance of size to clarity of code organization?

**Comment by dekkagaijin** [comment]
The benefit from such organization is primarily based on how much non-library code there is in your repo, right? As in, it doesn't make sense to put the contents of [small, focused, repos](https://github.com/toqueteos/webbrowser) into `pkg`, but has obvious organizational advantages for larger repos, like k8s. Where's the line where adding the layer of organization makes sense?
