### ISSUE TITLE
ko: Should lower case import paths

### ISSUE THREAD

**Issue by evanj** [google/go-containerregistry#212]
Go import paths are case sensitive, and many Github user names contain upper case letters. It is not possible to use "ko publish" with these import paths since Docker does not permit upper case letters:

```
2018/06/13 17:53:04 error publishing github.com/TriggerMail/...: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: ...
```

Interestingly, at least on Mac OS X `ko publish` will work if I manually lower case the import path, but `ko apply` will not recognize the import in the .yaml.

**Comment by jonjohnsonjr** [comment]
@evanj can you try out #224 to confirm that it fixes this for you? 😄

**Comment by evanj** [comment]
Sorry for the delay: Yes it certainly does thanks!
