### ISSUE TITLE
ko should check IsCommand on import paths

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#215]
See [here](https://golang.org/pkg/go/build/#Package.IsCommand).

Something like:
```go
import "go/build"

p, err := build.Import(importpath, srcDir, 0)
// check err
if !p.IsCommand() {
  // Return error.
}

```

**Comment by ImJasonH** [comment]
I have this in my [`kobin`](https://github.com/ImJasonH/go-containerregistry/blob/kobin/pkg/ko/build/gobuild.go) branch in my fork. It fails under Bazel tests only. Let's remove Bazel.
