### ISSUE TITLE
Remote should dedupe scopes for token handshake

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#221]
@everpeace pointed this out in #219 

We append a scope for each layer, which might be a bit too much. Many registries handle multiple scopes poorly, but others (chiefly dockerhub) require multiple scopes for cross-repo mounting to work.

See here: https://github.com/google/go-containerregistry/blob/3f6471078a9661a9a439bd5e71a371aff429566a/pkg/v1/remote/write.go#L45-L49

**Comment by mattmoor** [comment]
Use a Go "set": `map[string]struct{}`
