### ISSUE TITLE
ko fails to build images if config is under a different directory path

### ISSUE THREAD

**Issue by scothis** [google/go-containerregistry#228]
This works as expected:

    ko apply -f ./config

This find and applies the configuration, but does not build/publish containers:

    ko apply -f ../some-other-dir/config

**Comment by jonjohnsonjr** [comment]
I wonder if we need to call `filepath.Abs` here:
https://github.com/google/go-containerregistry/blob/f02501e1d74bff68d6e2d8962ea61277ea628b5d/cmd/ko/filestuff.go#L41

**Comment by scothis** [comment]
Using an absolute path doesn't help. The applied directory has to be under the working directory.

**Comment by mattmoor** [comment]
I wonder, was this fixed by @ImJasonH's recent change to our handling of import paths?

**Comment by scothis** [comment]
Yep, it works now
