### ISSUE TITLE
Add go coverage tracking.

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#24]

**Comment by mattmoor** [comment]
@dekkagaijin Do you know how to get us a Go coverage badge? :D

**Comment by dekkagaijin** [comment]
I think it involves another CI pipeline, but I'll see if there's a free tier for the one that Docker uses...

**Comment by dekkagaijin** [comment]
Now that bazel is required for the tests to work, going to be difficult to get coverage :/
Seems like this is an area of active development for rules_go, tho, so I'll keep this in the back of my mind.

**Comment by mattmoor** [comment]
Oh mighty Bazel slayer @jonjohnsonjr.  Wanna add gocov?

**Comment by jonjohnsonjr** [comment]
@dekkagaijin thanks!
