### ISSUE TITLE
Proposal: Did you mean? error messages

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#246]
@mattmoor had a crazy idea:

> What if our keychain resolution (when falling back on `Anonymous`) looked at the delta of the input and registered domains and printed out "did you mean"?

We can look at the minimum [edit distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) of entries during keychain resolution, and suggest the closest matching domain if it is under some threshold and none matched exactly.

**Comment by mattmoor** [comment]
I think you meant:
> @mattmoor has a crazy *good* idea

**Comment by dekkagaijin** [comment]
I was also thinking of creating a OSS debugging tool, but I couldn't think of any tool other than `docker` itself that would make a good home for the feature, so...

**Comment by dekkagaijin** [comment]
Debugging e.g. `tool pull example.com/repo/image --debug` which would do a 'dry run' and tell users what went wrong

**Comment by mattmoor** [comment]
Maybe:
```shell
$ crane check-access registry.io/repo/image:label
Success!
```

**Comment by dekkagaijin** [comment]
But also disambiguating push & pulls

**Comment by mattmoor** [comment]
How about:
```shell
$ crane check-access registry.io/repo/image:label
Checking read: Success!
Checking write: Success!
```

We can simply roundtrip the tag :)

**Comment by dekkagaijin** [comment]
... and blob POSTs, PATCHes, HEADs...
but I can't withstand Impact of that magnitude...

Credential resolution and manifest push/pull token exchanges seem like they'd cover 99% of issues, though.

**Comment by mattmoor** [comment]
@dekkagaijin I'd characterize anything beyond those basic checks as registry-side image corruption and out of scope.  Those checks should cover 100% of client-side issues.

**Comment by mattmoor** [comment]
`crane diagnose`?

**Comment by jonjohnsonjr** [comment]
I don't think we'll end up doing this, and the `-v` flag in crane and gcrane is useful for debugging any issues.
