### ISSUE TITLE
HEAD checks for pushing remote images

### ISSUE THREAD

**Issue by siddharthab** [google/go-containerregistry#249]
In my experiments, I am reasonably certain that my ECR registry does not support mounted blobs, with or without the from param.

It will be nice to have HEAD checks when uploading blobs to remote registries. They are fairly cheap, and almost everyone supports them.

I can send a pull request if you think this is a good idea.

**Comment by jonjohnsonjr** [comment]
Wow this sounds familar 😄  https://github.com/moby/moby/pull/31720

SGTM, will look at your PR soon. It might be worth bugging the ECR folks to see if it's feasible for them to implement mounting, as well.
