### ISSUE TITLE
Split v1.Image

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#25]
In the Python client, we provided base implementations (in our ABC) for things like `UncompressedBlob` that simply decompressed the result of its sibling.

To achieve the same for Go, my thinking was that we'd split apart the `v1.Image` interface into:
1. Common accessors,
1. Accessors for natively uncompressed image forms (e.g. `tarball.Image`),
1. Accessors for natively compressed image forms (e.g. `remote.Image`),

... and then provide functions for turning `v1.{Foo,Bar}Image` => `v1.Image`, which would implement the remaining methods in terms of its available sibling methods.

WDYT?

**Comment by mattmoor** [comment]
@ImJasonH @dlorenc @jonjohnsonjr @dekkagaijin Does that explanation even make sense to you?

**Comment by dekkagaijin** [comment]
As in, abstract the push/pull file descriptor separate from compressed/uncompressed layers? +1

**Comment by mattmoor** [comment]
I don't understand what you just said :)
