### ISSUE TITLE
Define minimum golang version

### ISSUE THREAD

**Issue by dekkagaijin** [google/go-containerregistry#27]
Add validation to travis:
```yaml
go:
  - ${MINIMUM_VERSION}
  - tip
```

**Comment by jonjohnsonjr** [comment]
How does one determine the minimum golang version?

**Comment by dekkagaijin** [comment]
Whatever the minimum version for the set of features you want to use is. Honestly picking something arbitrary for now is fine, like `"1.10" ` (you have to add quotes, or travis parses it as `1.1`)

**Comment by jonjohnsonjr** [comment]
> (you have to add quotes, or travis parses it as 1.1)

Lovely!
