### ISSUE TITLE
crane cannot push compressed image tarballs

### ISSUE THREAD

**Issue by aduong** [google/go-containerregistry#284]
`crane` pushes all blobs to the remote registry but fails on the config blob. Manually decompressing the layers in the image tarball (and changing `manifest.json`) allows crane to successfully push.

The problem seems to boil down to a difference in implementation of `LayerByDigest`. In the `uncompressedImageExtender`, the digest is checked against the config name and a config layer is returned. In `compressedImageExtender`, no such branch exists and the code iterates on the true image layers instead.

**Comment by ImJasonH** [comment]
Thanks for the bug report! Some clarifying questions:

1. Which `crane` command(s) specifically exhibit this behavior?
1. Which registry(s) specifically? I've had no trouble pushing/pulling/etc to/from `gcr.io` or Dockerhub, but there are other registries which might have varying support for different registry operations.
1. Are there specific image(s) that exhibit this behavior?

In short, it might be helpful to demonstrate the bug with some example `crane` commands which fail when they should succeed.

**Comment by aduong** [comment]
Happy to answer those questions. Here's something that we can run to demonstrate the issue:

```bash
docker_repo=us.gcr.io/PROJECT_ID/test/postgres # your favourite registry+repo here
docker pull postgres:alpine
docker save -o postgres.tar postgres:alpine # should be uncompressed layers
mkdir postgres
tar -C postgres -xvf postgres.tar
cd postgres
for f in */*.tar; do
  gzip -v "$f"
done
perl -i -pe 's/\.tar/.tar.gz/g' manifest.json
tar -cvf ../postgres.compressed.tar *
cd ..

crane push postgres.compressed.tar $docker_repo # this will fail with blob not found
crane push postgres.tar $docker_repo # this will succeed
```

**Which `crane` command(s) specifically exhibit this behavior?**

`crane push` in particular, although I imagine this may happen to any command that requests the "config layer" by hash on an image with compressed layers.

**Which registry(s) specifically?**

I specifically tried with us.gcr.io, but I think that this isn't an issue with the registry so much as it is crane.

**Are there specific image(s) that exhibit this behavior?**

My example constructs a postgres image (which loads fine with docker `docker load -i postgres.compressed.tar`), but it can be applied to any image tarball. I specifically ran into this when building images using [GoogleContainerTools/kaniko](https://github.com/GoogleContainerTools/kaniko) which produces image tarballs with compressed layers using go-containerregistry itself.

Hope that's clear.

**Comment by ImJasonH** [comment]
Thanks for that detailed description, that's very helpful. I've approved your PR and unless @jonjohnsonjr has any comments I'll make sure we merge it soon.
