### ISSUE TITLE
Usage & help messages for various commands don't include details about positional arguments

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#286]
```
crane pull
Error: accepts 2 arg(s), received 0
Usage:
  crane pull [flags]

Flags:
  -h, --help   help for pull

accepts 2 arg(s), received 0
```

```
crane pull  -h
Pull a remote image by reference and store its contents in a tarball

Usage:
  crane pull [flags]

Flags:
  -h, --help   help for pull
```

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/go-containerregistry/pulls?q=is%3Apr+is%3Aclosed

**Comment by dprotaso** [comment]
solved by all the closed PRs!

**Comment by jonjohnsonjr** [comment]
😠 GitHub recently started doing this incredibly obnoxious thing (at least for me) where when I click a PR link, it will start loading that page, update the URL bar to the correct URL, then reset it to the URL of the page I was just on, then finally fix go to the right place.
