### ISSUE TITLE
Treat 10.x.x.x registry addresses as local/insecure

### ISSUE THREAD

**Issue by berndtj** [google/go-containerregistry#289]
10.x.x.x registries should be considered insecure in the same manor registries suffixed with .local are.  This is needed to pull from in cluster insecure registries:

Needed for: https://github.com/GoogleContainerTools/kaniko/issues/405

**Comment by jonjohnsonjr** [comment]
Fixing this actually exacerbates another issue: https://github.com/google/go-containerregistry/issues/279

We probably want the behavior to first attempt https and fallback to http only for things that match the heuristic... (really, we need a flag or env var or something).

**Comment by berndtj** [comment]
Yeah, it does.  I think the real problem is that we don't have a distinction between source and destination within Kaniko, so the insecure flag only applies to destination.  Fallback actually sounds like a pretty good solution that would "just work".

**Comment by berndtj** [comment]
I've got another fix which should fix both my issue and #279.  If we just do a fallback in the ping, it seems to work.  I'm still evaluating this.

**Comment by jonjohnsonjr** [comment]
Essentially yes, but I don't like it :(

I think what I'd really want is for our behavior to just be the same as this: https://docs.docker.com/registry/insecure/

I don't love how we implicitly assume certain endpoints are safe to be insecure, but it's harder to plumb these flags/configs around, so I'm not sure what to do 🙃

/cc @mattmoor what do you think?

**Comment by jonjohnsonjr** [comment]
@berndtj I haven't forgotten about this, just pondering still what the best path forward would be.

I think I'm fine with this PR going in as-is if we followup with the fallback.

re: the fallback proposal, I think it would be cleaner to pull the retry into the bearer transport's [Roundtrip](https://github.com/google/go-containerregistry/blob/0a6b857c44c4f1f33da0a8c8286bfaf830013d86/pkg/v1/remote/transport/bearer.go#L48).

I'm not sure if it's easy (or even possible) to discriminate TLS-related errors from other connection-related errors, but perhaps retrying anything is a good idea.

In the bearer transport we could add something like:
```go
	res, err := sendRequest()
	if err != nil {
                if bt.registry.Scheme() == "http" {
                        in.URL.Scheme = "http"
                        return sendRequest()
                }
		return nil, err
	}
```

And use "https" for *every* request first. It might make sense to split that logic out into an insecureFallbackTransport or something and wrap the bearerTransport's inner transport with it [here](https://github.com/google/go-containerregistry/blob/0a6b857c44c4f1f33da0a8c8286bfaf830013d86/pkg/v1/remote/transport/transport.go#L70).

**Comment by berndtj** [comment]
I can clean it up.  I'm not thrilled with this methodology either.  I think long-term it needs to be explicitly settable.
