### ISSUE TITLE
Support targeting custom namespaces with ko

### ISSUE THREAD

**Issue by greghaynes** [google/go-containerregistry#295]
As a developer on a project I may want to define the resources for that project in a namespace of my choosing. This may be because I have a restricted account which forces me to use a specific namespace. Currently, a project can only provide static namespace definitions and as such a user has no easy way to chose where namespace-scoped resources are defined.

**Comment by mattmoor** [comment]
I *believe* what you want is the ability to pass-thru `-nfoo` to `kubectl` in `ko apply`?

**Comment by greghaynes** [comment]
Ah good point - this seems a lot like https://github.com/google/go-containerregistry/issues/288 then.

**Comment by jonjohnsonjr** [comment]
FWIW my fix will only work if you haven't already specified a namespace in the target yaml. Apparently kubectl doesn't support overriding a namespace in that way, e.g.:
```
$ ko apply -f service.yaml -n foo
error: the namespace from the provided object "default" does not match the namespace "foo". You must pass '--namespace=default' to perform this operation.
```

So you'd either have to leave namespace blank or use something like [kustomize](https://github.com/kubernetes-sigs/kustomize).
