### ISSUE TITLE
Consider adding a utility to validate Images

### ISSUE THREAD

**Issue by dlorenc** [google/go-containerregistry#30]
This could be used in testing or by derived tools to validate the constraints imposed by Docker on an image. It could cover things like:

- relationship between config file history and layers
- layer sizes in the manifest match actual layer sizes
- config digest in the manifest matches the actual config digest

etc.

**Comment by dekkagaijin** [comment]
* Validate that the images produced by `tarball` work with `docker load`

**Comment by mattmoor** [comment]
See: https://github.com/google/go-containerregistry/pull/88

We should validate that the digest we have for the config in `Manifest` matches `ConfigName`.
