### ISSUE TITLE
Clone Succeeded, Checkout Failed

### ISSUE THREAD

**Issue by gkgkgkgk** [google/go-containerregistry#305]
When using `RUN go get -d -v ./...` in my docker file, I get the following error:

```
github.com/google/go-containerregistry (download)
# cd .; git clone https://github.com/google/go-containerregistry /go/src/github.com/google/go-containerregistry
Cloning into '/go/src/github.com/google/go-containerregistry'...
error: unable to create file pkg/v1/mutate/testdata/whiteout/.wh.foo.txt: Operation not permitted
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Any Fixes? Thanks.

**Comment by jonjohnsonjr** [comment]
Oh that's terrible. We use a whiteout file as part of a test and it looks like creating whiteout files is forbidden inside the container, so the git clone fails. A possible fix would be to create that whiteout file as part of the setup for the test so we don't have to check it in.

**Comment by gkgkgkgk** [comment]
@jonjohnsonjr Thanks so much for the response.
> Alternatively, using [`dep`](https://github.com/golang/dep) will prune tests (which is why I didn't catch this myself).
I use glide as my package manager for go, an I get the same error when using Glide in the Dockerfile. 
How can I prevent the whiteout file from being checked in? Thanks.

**Comment by jonjohnsonjr** [comment]
@gkgkgkgk this should work now (I think) 👍

**Comment by gkgkgkgk** [comment]
@jonjohnsonjr thanks, I'll test it out asap!
