### ISSUE TITLE
Wrong Timestamp of image

### ISSUE THREAD

**Issue by surajnarwade** [google/go-containerregistry#316]
`CREATED` timestamp of generated image using `ko` sounds like time travel :laughing: 
it says created 48 years ago

```
ko.local/webapp-99a8320c12098e79d5aecf6dbe16e649   b8759c094879831fd0e66ea1b56cf53f6298c5d4d6b57565e36d13318552437c   3af1d69ab1ca        48 years ago        23.3MB
```

**Comment by jonjohnsonjr** [comment]
This is intentional to get reproducible builds, see: https://github.com/google/go-containerregistry/issues/273

FWIW https://github.com/google/go-containerregistry/pull/146 added the ability to set this via the `SOURCE_DATE_EPOCH` environment variable.
