### ISSUE TITLE
Docker can't parse our created times

### ISSUE THREAD

**Issue by dlorenc** [google/go-containerregistry#35]
Not sure where exactly the issue is, but Docker can't parse an empty creation time. Trying to docker load a saved tarball gives:

```shell
parsing time """" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "2006"
```

**Comment by dekkagaijin** [comment]
Looks like it's not fully RFC 3339 compliant, dunno what the numbers after the `Z` are supposed to be (was it supposed to be `-07:00`?)

Also what's with all the extra quotes?

**Comment by dekkagaijin** [comment]
Anyway, looking into it

**Comment by dekkagaijin** [comment]
ah- the zero values for `time.Time` and `string` are different:
https://play.golang.org/p/VyI03LHSmSa

Made a fix...
