### ISSUE TITLE
Parsing image references with both tag and sha fails

### ISSUE THREAD

**Issue by martin-sucha** [google/go-containerregistry#351]
[name.ParseReference](https://github.com/google/go-containerregistry/blob/efb7e1b888e142e2c66af20fd44e76a939b2cc3e/pkg/name/ref.go#L41) does not handle Docker image references like `ubuntu:latest@sha256:868fd30a0e47b8d8ac485df174795b5e2fe8a6c8f056cc707b232d65b8a1ab68` (which Docker supports). This causes GoogleContainerTools/kaniko#535.

This could probably be fixed by adding some logic to `ParseReference` or implementing #78.

**Comment by scothis** [comment]
In my local tests with `docker pull` the tag is ignored. Haven't looked at the spec yet.

**Comment by briandealwis** [comment]
I've hit this with [Skaffold](https://github.com/GoogleContainerTools/skaffold/), which catenates an image reference (like `xxx:latest`) with the sha256 digest.  This is then passed along in a Kubernetes manifest which is happily accepted.

```
      containers:
        image: gcr.io/gcp-dev-tools/bdealwis/xxx/microservices-kubernetes-demo-customer:02e6676@sha256:852935558bef6251c18c0c69c79eafa002d1e24cff3599dd499e6e33a201f58d
        name: microservices-kubernetes-demo-customer
```
