### ISSUE TITLE
configurable EntryPoint for `ko` built containers

### ISSUE THREAD

**Issue by xtreme-andrew-su** [google/go-containerregistry#385]
After the changes for https://github.com/google/go-containerregistry/issues/375 the path to the app produced by `ko` changed from `/ko-app` to `/ko-app/<app_name>`. It'd be great to be able to specify a stable path for the binary. Perhaps a configuration within `.ko.yaml`

For example:
```yaml
ApplicationEntryPoint: /my/path/to/app_name
```

**Comment by jonjohnsonjr** [comment]
Oh no, what did #375 break? I would think you could get the binary path from `os.Args[0]`.

**Comment by xtreme-andrew-su** [comment]
I was working on a [PR for knative](https://github.com/knative/serving/pull/3347). The binary created by `ko` was to be used as an exec for readiness and liveness probes.

**Comment by xtreme-andrew-su** [comment]
After re-evaluating the changes for the PR, this isn't actually needed anymore. Closing.

**Comment by kfox1111** [comment]
Was something like this ever implemented? Migrating from not ko -> ko will break existing things that expect binary path to be where it was before switching to ko. This is a showstopper for some projects.
