### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#390]
We currently use the standard library's `log` package, but that has some issues:

https://github.com/google/go-containerregistry/issues/266
https://github.com/google/go-containerregistry/pull/352

There are some messages we'd like to get to users because traditionally they've been very useful in diagnosing problems. The way we're using `log` means that there's no way to turn that off.

One approach would be to log nothing, but expose issues through some diagnose command:
https://github.com/google/go-containerregistry/issues/246

We could also use a no-op logger by default that just discards messages, and register a real logger in our own binaries: https://golang.org/pkg/log/#New

We could also have a verbose logger that is useful for debugging that gets turned on via some flag.

**Comment by ekcasey** [comment]
+1

For consumers of this library it would be nice to have control over the output without having to mess with the standard logger.
