### ISSUE TITLE
Decouple pkg/crane from command line flags

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#407]
The original intention for `pkg/crane` was to be a library that `cmd/crane` consumes, but we ended up consolidating a lot of code because we were adding a lot of boilerplate for no reason.

I'd like to expose these high-level crane operations into easy to consume libraries, for example, someone who wants to copy an image basically has to re-implement all the code under `pkg/crane/copy.go`. Ideally, we'd expose a function:

```
package crane

func Copy(src, dst string, options ...Option) {
  // Do the copying.
}
```

And have sane defaults that can be overridden with options.

**Comment by marekschwarz** [comment]
Is someone working on this? If not I would like to give it a try.
