### ISSUE TITLE
Return better error when pulling schema 1

### ISSUE THREAD

**Issue by glyn** [google/go-containerregistry#411]
The error returned is `Error: MANIFEST_UNKNOWN ...` which doesn't give much of a clue about schema 1.

See https://github.com/google/go-containerregistry/pull/344#issuecomment-473006868

**Comment by jonjohnsonjr** [comment]
Added this in https://github.com/google/go-containerregistry/pull/408

```
$ crane pull ruby:2.1.2 ruby.tar
2019/03/18 12:33:18 Pulling index.docker.io/library/ruby:2.1.2
2019/03/18 12:33:18 No matching credentials were found, falling back on anonymous
2019/03/18 12:33:19 reading image "index.docker.io/library/ruby:2.1.2": unsupported MediaType: https://github.com/google/go-containerregistry/issues/377
```

Reopen if you don't like the exact error, but linking to the discussion seemed like the most useful information.

**Comment by glyn** [comment]
@jonjohnsonjr I don't mind the error message linking to an issue for background, but I would like the error message to include the MediaType. The current messages reads as if issue 377 _is_ the unsupported MediaType.

How do I re-open this issue?

**Comment by jonjohnsonjr** [comment]
Oh sorry I might have to reopen it.
