### ISSUE TITLE
Problems authenticating to Azure ACR

### ISSUE THREAD

**Issue by tjk** [google/go-containerregistry#421]
I've been trying to solve an issue with https://github.com/GoogleContainerTools/skaffold in which fetching a remote image digest from Azure Container Registry (ACR) returns a 401.

Turns out the `docker-credential-acr-*` returns a username of `<token>` and secret representing a refresh_token (rather than a username + password). 

https://github.com/google/go-containerregistry/blob/master/pkg/v1/remote/transport/transport.go determines it must use bearer auth strategy and when it tries to refresh the `bearerTransport`, it performs a GET request with `Basic` username+password auth. I have a patch that instead performs a POST with the refresh_token that the docker-credential helper returns which fixes the 401 but I need advice on how to more properly fix this.

Please let me know if seeing my patch would be more helpful.

**Comment by jonjohnsonjr** [comment]
Thanks for filing an issue!

To make sure I understand, from looking at the registry docs, it looks like:
* we **only** support the [token authentication specification](https://docs.docker.com/registry/spec/auth/token/),
* whereas ACR **only** supports the [oauth authentication specification](https://docs.docker.com/registry/spec/auth/oauth/).

Reading through the oauth docs:
> Note: Not all token servers implement oauth2. If the request to the endpoint returns 404 using the HTTP POST method, refer to Token Documentation for using the HTTP GET method supported by all token servers.

So I'm thinking for an actual fix, we'd want to first attempt to do the oauth exchange, then do the token exchange if that fails. Ideally, ACR would just support token authentication, given (emphasis mine) this snipper:
> refer to Token Documentation for using the HTTP GET method supported by **all** token servers

It's probably more likely we could land a fix here than against ACR, but it might be worth pursuing that as well. I'm wondering if this is a bug in the cred helper, or how it's configured or something? cc @shhsu who seems to have written most of it. Is this expected?

Is there anything in the [challenge](https://docs.docker.com/registry/spec/auth/token/#how-to-authenticate) that indicates we should use oauth?

Seeing your patch would definitely be helpful, as well as the responses from ACR and from their credential helper (with any sensitive information or secrets redacted).

Do you happen to know if there are docs somewhere for how [the credential helper response](https://godoc.org/github.com/docker/docker-credential-helpers/credentials#Credentials) is supposed to work with the oauth exchange? I guess we just use the `Secret` as a `refresh_token`?

**Comment by tjk** [comment]
Sorry got a busy, some responses --

> Reading through the oauth docs:

>> Note: Not all token servers implement oauth2. If the request to the endpoint returns 404 using the HTTP POST method, refer to Token Documentation for using the HTTP GET method supported by all token servers.

This page seems relevant and doesn't mention any GET routes? https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md

> Is there anything in the challenge that indicates we should use oauth?

```
< HTTP/1.1 401 Unauthorized
< Server: nginx
< Date: Wed, 27 Mar 2019 03:17:17 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 134
< Connection: keep-alive
< Access-Control-Expose-Headers: Docker-Content-Digest
< Access-Control-Expose-Headers: WWW-Authenticate
< Access-Control-Expose-Headers: Link
< Access-Control-Expose-Headers: X-Ms-Correlation-Request-Id
< Docker-Distribution-Api-Version: registry/2.0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Www-Authenticate: Bearer realm="https://***.azurecr.io/oauth2/token",service="***.azurecr.io",scope="registry:catalog:*"
< X-Content-Type-Options: nosniff
< X-Ms-Correlation-Request-Id: 0f31144e-f94d-428f-b4b6-a979d5c9f4dc
< Strict-Transport-Security: max-age=31536000; includeSubDomains
<
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}
```

>  as well as the responses from ACR and from their credential helper (with any sensitive information or secrets redacted)

```
% echo '***.azurecr.io' | /usr/local/bin/docker-credential-acr-darwin get
{"ServerURL":"","Username":"\u003ctoken\u003e","Secret":"***dq2hGP5Tm1w"}
```

**Comment by tjk** [comment]
Here is the *awful* patch that at least makes things work (for ACR):

```
diff --git a/vendor/github.com/google/go-containerregistry/pkg/authn/helper.go b/vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
index c8ba4e6e..3ee8d01d 100644
--- a/vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
+++ b/vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
@@ -97,6 +97,11 @@ func (h *helper) Authorization() (string, error) {
 		return "", fmt.Errorf("invoking %s: %v", helperName, cmdErr)
 	}

+	// we have refresh_token in ho.Secret and passing it via POST data
+	if ho.Username == "<token>" {
+		return Anonymous.Authorization()
+	}
+
 	b := Basic{Username: ho.Username, Password: ho.Secret}
 	return b.Authorization()
 }
diff --git a/vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go b/vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
index f72ab276..59a35843 100644
--- a/vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
+++ b/vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
@@ -23,6 +23,10 @@ import (

 	"github.com/google/go-containerregistry/pkg/authn"
 	"github.com/google/go-containerregistry/pkg/name"
+
+	"bytes"
+	"os/exec"
+	"strings"
 )

 type bearerTransport struct {
@@ -83,6 +87,53 @@ func (bt *bearerTransport) RoundTrip(in *http.Request) (*http.Response, error) {
 	return res, err
 }

+// from vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
+type helperOutput struct {
+	Username string
+	Secret   string
+}
+
+func getRefreshToken(_helperName, domain string) string {
+	helperName := fmt.Sprintf("docker-credential-%s", _helperName)
+	// We want to execute:
+	//   echo -n {domain} | docker-credential-{name} get
+	cmd := exec.Command(helperName, "get")
+
+	// Some keychains expect a scheme:
+	// https://github.com/bazelbuild/rules_docker/issues/111
+	cmd.Stdin = strings.NewReader(fmt.Sprintf("https://%v", domain))
+
+	var out bytes.Buffer
+	cmd.Stdout = &out
+	cmdErr := cmd.Run()
+
+	// If we see this specific message, it means the domain wasn't found
+	// and we should fall back on anonymous auth.
+	output := strings.TrimSpace(out.String())
+	magicNotFoundMessage := "credentials not found in native keychain"
+	if output == magicNotFoundMessage {
+		return ""
+	}
+
+	// Any other output should be parsed as JSON and the Username / Secret
+	// fields used for Basic authentication.
+	ho := helperOutput{}
+	if err := json.Unmarshal([]byte(output), &ho); err != nil {
+		if cmdErr != nil {
+			// If we failed to parse output, it won't contain Secret, so returning it
+			// in an error should be fine.
+			return ""
+		}
+		return ""
+	}
+
+	if cmdErr != nil {
+		return ""
+	}
+
+	return ho.Secret
+}
+
 func (bt *bearerTransport) refresh() error {
 	u, err := url.Parse(bt.realm)
 	if err != nil {
@@ -95,14 +146,27 @@ func (bt *bearerTransport) refresh() error {
 	}
 	client := http.Client{Transport: b}

-	u.RawQuery = url.Values{
+	uVals := url.Values{
 		"scope":   bt.scopes,
 		"service": []string{bt.service},
-	}.Encode()
+	}

-	resp, err := client.Get(u.String())
-	if err != nil {
-		return err
+	// TODO this part http.Client ends up calling helper.Authorization() which only then determines we have a refresh token already
+	refreshToken := getRefreshToken("acr-darwin", u.Host) // TODO get helper name here
+	if refreshToken == "" {
+		u.RawQuery = uVals.Encode()
+		resp, err := client.Get(u.String())
+		if err != nil {
+			return err
+		}
+	} else {
+		uVals.Add("client_id", "SOME_CLIENT_ID") // TODO what clientID
+		uVals.Add("grant_type", "refresh_token")
+		uVals.Add("refresh_token", secret)
+		resp, err := client.PostForm(u.String(), uVals)
+		if err != nil {
+			return err
+		}
 	}
 	defer resp.Body.Close()
```

**Comment by yuwaMSFT2** [comment]
@tjk we just came across this issue. ACR supports both the token auth spec and oauth spec mentioned above:
https://github.com/Azure/acr/blob/master/docs/Token-BasicAuth.md

What credential you were getting from the credential manager? If it's a refresh token, and you want to get access token on GET /token endpoint, can you try use the following as user/pwd:
user: 00000000-0000-0000-0000-000000000000
pwd: {refreshToken}

**Comment by tjk** [comment]
@yuwaMSFT2 that worked!

**Comment by jonjohnsonjr** [comment]
@tjk is there something we can do in this library to fix that? Or can we document something better?

**Comment by tjk** [comment]
@jonjohnsonjr I'm not sure... I ended up moving on. I think @yuwaMSFT2 should be able to provide direction?

**Comment by yuwaMSFT2** [comment]
As mentioned earlier, both GET and POST token paths are supported by ACR.
1. GET /token
Authorization: Basic {base64("00000000-0000-0000-0000-000000000000:token)"}

2. POST /token
Authorization: bearer {token}

So if the credential manager returns user name as <token>, you can user either approach to get an access token.

Let me know there is anything we can do. Thanks!

**Comment by jonjohnsonjr** [comment]
> So if the credential manager returns user name as ,

Assuming that `<token>` got parsed out here?

Probably a stretch, but is it possible to have the credential manager return `00000000-0000-0000-0000-000000000000` for the token username instead of `<token>`? Or even Have ACR accept `<token>` as a username instead of `00000000-0000-0000-0000-000000000000` for basic auth? I don't see a way to get around this without hard-coding some ACR knowledge here, which I'd like to avoid.

**Comment by yuwaMSFT2** [comment]
@jonjohnsonjr We are working on a server side fix on ACR. It would be a hack on ACR but a reasonable one to maintain backward compatibility:) Will update here once it's done.

**Comment by jonjohnsonjr** [comment]
@yuwaMSFT2 that's great to hear, thank you so much 😄

**Comment by yuwaMSFT2** [comment]
@jonjohnsonjr Just FYI, we noticed that recently you fixed the same issue in jib tool:
https://github.com/GoogleContainerTools/jib/issues/1490

According to docker's credential helper protocol, if the secret is a token, username will always be <token>. So it will be safer if you can also handle this case in your tools as well:
https://github.com/docker/cli/blob/master/docs/reference/commandline/login.md#credential-helper-protocol
_If the secret being stored is an identity token, the Username should be set to <token>._

**Comment by jonjohnsonjr** [comment]
Ah, I missed that - looks like we can just fix this on our side. Thanks!
