### ISSUE TITLE
Gcrane: unrecognized HTTP status: 429 Too Many Requests

### ISSUE THREAD

**Issue by paulros** [google/go-containerregistry#424]
I'm trying to migrate a large number of data (over 38000) to a new GCR. Gcrane fails with a following error:
"failed to copy image: reading image "XXXXX": unrecognized HTTP status: 429 Too Many Requests" that means a Cloud Storage JSON API usage limit was exceeded.

Command executed: 
gcrane cp -r [old_GCR] [new_GCR]

How can it be fixed?

**Comment by jonjohnsonjr** [comment]
Oh wow that's a lot of images. My implementation was pretty naive, and for that number of images probably hits some quota for GCR/GCS.

I can hack together something that does throttling to stay under [GCR's posted limits](https://cloud.google.com/container-registry/quotas).

Sorry about that! I'll post back here when I've put something together.

**Comment by jonjohnsonjr** [comment]
@paulros sorry this took so long, let me know if that doesn't help things.
