### ISSUE TITLE
-bash: ko: command not found, after running go get -u github.com/google/go-containerregistry/cmd/ko

### ISSUE THREAD

**Issue by houshengbo** [google/go-containerregistry#427]
After I ran the command "go get -u github.com/google/go-containerregistry/cmd/ko" to install ko, I tried to run the ko command, it popped up with 
```
-bash: ko: command not found
```

I am using Mac. What am I missing?

**Comment by jonjohnsonjr** [comment]
It's probably installed under [`$GOPATH/bin`](https://golang.org/doc/code.html#GOPATH), which you'd have to put on your path via:
```
export PATH=$PATH:$(go env GOPATH)/bin
```

**Comment by houshengbo** [comment]
i have already done the path setting.

**Comment by ImJasonH** [comment]
Ko has moved, `go get -u github.com/google/ko/cmd/ko`

**Comment by jonjohnsonjr** [comment]
That's odd, what version of go is this?

cc @dprotaso you use `ko` on macos right? any ideas?

**Comment by houshengbo** [comment]
I am still getting "-bash: ko: command not found", after I run "go get -u github.com/google/ko/cmd/ko".

**Comment by dprotaso** [comment]
I'm on Mojave 10.14.2 and have no problems.

What version of Mac are you on?
What version of Go are you using?

**Comment by houshengbo** [comment]
Mojave 10.14.3. 
go version go1.12.1 darwin/amd64

**Comment by houshengbo** [comment]
This is something wrong with my local go environment. I remove go and reinstall it. This issue is gone.
