### ISSUE TITLE
why setting in.URL.Scheme = bt.scheme ?

### ISSUE THREAD

**Issue by 0xtyls** [google/go-containerregistry#428]
https://github.com/google/go-containerregistry/blob/f1df91a4a813cbc183527dc7b9a31ea6454557b5/pkg/v1/remote/transport/bearer.go#L66

We have a private docker registry "http://reg.docker.xxx" and the Bearer realm is "https://dockerauth.xxx". If everything is right, a http get to "http://reg.docker.xxx" will finally be redirected to "http://storage.docker.xxx". However, with "in.URL.Scheme = bt.scheme", the final url will be "https://storage.docker.xxx" and this url is wrong. 

So I wonder why we need this line here? How about removing it?

**Comment by ImJasonH** [comment]
That was added in https://github.com/google/go-containerregistry/pull/360

Specifically in https://github.com/google/go-containerregistry/pull/360/commits/82312b1f7df0d8ffd2b56f08b6fd0d9fde7a24da after [this comment](https://github.com/google/go-containerregistry/pull/360#pullrequestreview-200313987).

@mattmoor @jonjohnsonjr

**Comment by jonjohnsonjr** [comment]
I wonder if it's sufficient to move this line [up to here](https://github.com/google/go-containerregistry/blob/f1df91a4a813cbc183527dc7b9a31ea6454557b5/pkg/v1/remote/transport/bearer.go#L62). We are probing the registry in the `ping()` to determine if we should use https or http. That check is only really valid for the registry, so it shouldn't apply to other domains (token server or blob service) -- we should just trust the URLs we get from the registry.

**Comment by jonjohnsonjr** [comment]
@0xtyls I believe that should fix things for you, but let me know if it doesn't.

**Comment by 0xtyls** [comment]
@jonjohnsonjr Thank you
