### ISSUE TITLE
Handling BLOB_UPLOAD_INVALID?

### ISSUE THREAD

**Issue by tbarrella** [google/go-containerregistry#431]
Hello,

This is to try to address https://github.com/GoogleContainerTools/kaniko/issues/607, in which BLOB_UPLOAD_INVALID is happening seemingly because of the following situation:

1. Kaniko tries to upload blob X
2. Somehow, Kaniko is told to retry blob X, but actually the upload succeeds
3. Kaniko tries to upload blob X again -> "BLOB_UPLOAD_INVALID" because blob X + 1 is expected, or more specifically
>BLOB_UPLOAD_INVALID: “First byte of the layer part is {position of first byte of X} instead of {position of first byte of X + 1}”

When this happens, the push fails completely

I know ideally step 2 wouldn't happen, but would it make sense to have some way to handle this from the client (uploader) side?

**Comment by jonjohnsonjr** [comment]
Seems like a transient ECR error. On the client side I think the best thing we could do is retry, but since it's a 4xx error instead of a 5xx error, we'll need to parse the error, look for this error code, and retry the entire upload.

Alternatively we could just retry the layer upload if we encounter any errors. That seems less elegant but would require a lot less code 🤔

**Comment by tbarrella** [comment]
Hello, thank you! I'm not very knowledgeable about what's best for here, or if other libraries have a standard way of handling 4xx errors (the [spec](https://docs.docker.com/registry/spec/api/#pushing-an-image) is a bit vague on that). From https://github.com/docker/distribution/blob/master/docs/spec/api.md#on-failure-bad-request-4, maybe it makes sense to parse the "code" because there are a few different 400 errors for blob upload

**Comment by tbarrella** [comment]
I've been looking into this more because I'm still encountering this frequently (retrying the layer upload would be more preferable for me than retrying the whole build since some builds take a while). The registry API [lists possible failure responses](https://github.com/docker/distribution/blob/3226863cbcba6dbc2f6c83a37b28126c934af3f8/registry/api/v2/descriptors.go#L1254) for blob upload including specifying when they should be retried.

For how containerregistry handles this, a [push](https://github.com/google/containerregistry/blob/da03b395ccdc4e149e34fbb540483efce962dc64/tools/docker_pusher_.py#L105) seems to be [retried up to twice](https://github.com/google/containerregistry/blob/da03b395ccdc4e149e34fbb540483efce962dc64/transport/retry_.py#L72) for some [hard-coded](https://github.com/google/containerregistry/blob/da03b395ccdc4e149e34fbb540483efce962dc64/transport/retry_.py#L29) exception types.

For how moby handles this, it appears that a layer upload is [retried up to 5 times](https://github.com/moby/moby/blob/69c5ea328d750d31bec85036babe08596748bb3d/distribution/xfer/upload.go#L143) unless the error is [wrapped with DoNotRetry](https://github.com/moby/moby/blob/69c5ea328d750d31bec85036babe08596748bb3d/distribution/errors.go#L148).

Is there a clean way that you think might be reasonable for handling this when [running uploadOne](https://github.com/google/go-containerregistry/blob/1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7/pkg/v1/remote/write.go#L83
), even if it doesn't fully address all possible errors/errors for all methods? Though I'm not experienced with this repo, I may be able to make a PR if the scope is small enough, but I wouldn't want to make one with an approach that maintainers aren't ok with

**Comment by jonjohnsonjr** [comment]
I think we can fix your problem by wrapping [this code](https://github.com/google/go-containerregistry/blob/1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7/pkg/v1/remote/write.go#L310-L339) in some retry logic. We can check if the error is a [`transport.Error`](https://github.com/google/go-containerregistry/blob/1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7/pkg/v1/remote/transport/error.go#L27) and look through the contained [error codes](https://github.com/google/go-containerregistry/blob/1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7/pkg/v1/remote/transport/error.go#L74) to see if it's retryable.

It's possible that retrying [this](https://github.com/google/go-containerregistry/blob/1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7/pkg/v1/remote/write.go#L322) could fail for streaming uploads, but that shouldn't be a problem.

I'm pretty swamped for the next couple weeks with kubecon coming up, but It's not too big a change if you're familiar with go.

The easiest thing would probably be to wrap that code in a closure, call it, check the error, and call it again if it can be retried, kind of similar to [`Roundtrip`](https://github.com/google/go-containerregistry/blob/1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7/pkg/v1/remote/transport/bearer.go#L49-L88).

**Comment by tbarrella** [comment]
Thank you! I'm not super experienced but also not entirely unfamiliar. I'm definitely up for trying, hopefully some time in the next couple weeks!
