### ISSUE TITLE
Could you add the installation doc?

### ISSUE THREAD

**Issue by rc3097** [google/go-containerregistry#444]
I have no idea how to install the tool.

**Comment by jonjohnsonjr** [comment]
Which tool do you mean? E.g. for crane you can run:

`go get github.com/google/go-containerregistry`

This isn't ideal though! It requires that you are familiar with go conventions and have the entire go toolchain installed, which we shouldn't assume 😄 

I'll use this issue to track:
1. Building and publishing crane/gcrane releases.
2. Updating the docs with installation instructions.

**Comment by ImJasonH** [comment]
For crane it's `go get github.com/google/go-containerregistry/cmd/crane`

We should definitelydo releases though 👍

**Comment by mgreau** [comment]
> Building and publishing crane/gcrane releases.

+1
I really like crane, it's powerful and easy to use for managing the container artifacts in a k8s environment. Thanks for your work on this.
I'd love to have releases for tracking the features/bugs/improvements before upgrading the image version in my cluster.

**Comment by jonjohnsonjr** [comment]
Thanks for your kind words 😄 I'll try to put something together tomorrow.

**Comment by jonjohnsonjr** [comment]
Fixed in https://github.com/google/go-containerregistry/pull/585
