### ISSUE TITLE
Crane fails to push to localhost running https

### ISSUE THREAD

**Issue by fxdgear** [google/go-containerregistry#451]
I'm trying to test crane on a local registry and I'm getting failures for crane to communicate to  my registry: 

```
~/go/bin/crane push image-name-tag-linux-amd64-docker-image.tar localhost:5000/namespace/name:tag
2019/04/30 16:49:15 Pushing localhost:5000/namespace/name:tag
2019/04/30 16:49:15 writing image "localhost:5000/namespace/image:tag": Get http://localhost:5000/v2/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

my local registry is running https. how do I force this to use https?

**Comment by jonjohnsonjr** [comment]
That's really surprising, it should try https first.

What do you see if you:
```
$ curl -v https://localhost:5000/v2/
```

**Comment by fxdgear** [comment]
using `-vk` I get

```
curl -vk https://localhost:5000/v2/                                                                                                                                                                                                                                                                                                                               
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Colorado; L=Pine; O=Elastic; OU=Infra; CN=registry; emailAddress=infra@elastic.co
*  start date: Apr 30 16:48:16 2019 GMT
*  expire date: Apr 29 16:48:16 2020 GMT
*  issuer: C=US; ST=Colorado; L=Pine; O=Elastic; OU=Infra; CN=registry; emailAddress=infra@elastic.co
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a84135af30)
> GET /v2/ HTTP/2
> Host: localhost:5000
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 401
< content-type: application/json; charset=utf-8
< docker-distribution-api-version: registry/2.0
< www-authenticate: Bearer realm="https://localhost:7000/auth",service="Docker registry"
< x-content-type-options: nosniff
< content-length: 87
< date: Tue, 30 Apr 2019 23:06:08 GMT
<
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
* Connection #0 to host localhost left intact
* Closing connection 0
```

**Comment by jonjohnsonjr** [comment]
Are you using custom certificates?

**Comment by fxdgear** [comment]
yes I am.

**Comment by jonjohnsonjr** [comment]
Ah, probably hitting this? https://github.com/google/go-containerregistry/issues/211

You could work around that with [`SSL_CERT_DIR`](https://golang.org/pkg/crypto/x509/#pkg-overview) but we really need to fix that 😅

**Comment by fxdgear** [comment]
Ahh great, I’ll give it a go in a bit.

**Comment by Ian2020** [comment]
/reopen
/remove-lifecycle stale

Hello I've hit this bug and believe it's not the same as or fixed by #211. The error as originally reported:

```
2019/04/30 16:49:15 writing image "localhost:5000/namespace/image:tag": Get http://localhost:5000/v2/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

...is the result of hitting an HTTPS endpoint with an HTTP request - not (yet!) a problem with trusting self-signed certs as in #211. 

I believe this is caused by the logic around [line 82 of registry.go](https://github.com/google/go-containerregistry/blob/f937abdc5c9af165a6921363fb49da3fe6cef421/pkg/name/registry.go#L82):

```golang
	if strings.HasPrefix(r.Name(), "localhost:") {
		return "http"
	}
```

...which means any localhost registry connection's scheme will be forced to HTTP. When I remove this if statement I am successful in using HTTPS against my HTTPS localhost registry.

I note there are further if statements after this that try various forms of regex to detect local addresses and force HTTP:

```golang
	if reLocal.MatchString(r.Name()) {
		return "http"
	}
	if reLoopback.MatchString(r.Name()) {
		return "http"
	}
	if reipv6Loopback.MatchString(r.Name()) {
		return "http"
	}
```

They may also need to allow for possibility that a localhost registry is HTTPS.

**Comment by jonjohnsonjr** [comment]
@Ian2020 it's possible that you're hitting https://github.com/google/go-containerregistry/issues/738 and we're just showing a terrible error.

**Comment by jonjohnsonjr** [comment]
@Ian2020 can you take a look at https://github.com/google/go-containerregistry/pull/859 to see if that returns a better error for you?

**Comment by Ian2020** [comment]
@jonjohnsonjr Hi, thanks for pointing me at your changes. I am using skaffold so rebuilt it with your branch. I now get this when I do a skaffold run:

```
failed to build: getting digest: getting image: Get "https://localhost:5000/v2/": x509: certificate signed by unknown authority; Get "http://localhost:5000/v2/": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

As you can see I now get two errors reported instead of one: (1) unknown authority and (2) HTTP can't understand an HTTPS endpoint as before. However when I supply the correct certificate to skaffold it is successful and reports no errors. So it seems (1) is the real problem, I don't know how (2) ends up being reported as well?

**Comment by jonjohnsonjr** [comment]
> I don't know how (2) ends up being reported as well?

There's a precedent for allowing non-https traffic to localhost (and some other hardcoded things). Unfortunately, this can cause issues if localhost is expecting https traffic. To work around this, we always try to use https and fall back to http in certain situations. Unfortunately, it's hard to know which error (https or http) is the actual issue, so we'll return both.

**Comment by Ian2020** [comment]
Thanks for the info, makes sense and I see your work is now merged. That should be enough for anyone to troubleshoot who hits this problem in future :+1:

**Comment by cbf123** [comment]
I've just run into this as well.  I have run "crane auth  registry.local:9001" with my username and password and it was successful, but I hit the following trying to "crane cp" to my local registry:

[sysadmin@controller-0 ~(keystone_admin)]$ crane cp  centos:latest registry.local:9001/centos:latest
2023/06/13 16:43:12 Copying from centos:latest to registry.local:9001/centos:latest
Error: Get "https://registry.local:9001/v2/": x509: certificate signed by unknown authority; GET http://registry.local:9001/v2/: unexpected status code 400 Bad Request: Client sent an HTTP request to an HTTPS server.
