### ISSUE TITLE
Support Content Trust with registry?

### ISSUE THREAD

**Issue by SimonXming** [google/go-containerregistry#461]
Could we support content trust with a remote Docker registry server?
Just like https://github.com/docker/cli/blob/master/cli/trust/trust.go, I think it would be very helpful for us.

**Comment by jonjohnsonjr** [comment]
Is there a spec somewhere for how clients are expected to behave? I've never used notary myself, so I'm not sure what is needed to support this.

**Comment by SimonXming** [comment]
> Is there a spec somewhere for how clients are expected to behave? I've never used notary myself, so I'm not sure what is needed to support this.

I think there already have a package implements everything required for interacting with a Notary repository. We only need to integrate with it.
Ref: https://github.com/theupdateframework/notary/blob/master/client/client.go

**Comment by jonjohnsonjr** [comment]
Just skimmed through some of that code and it seems like this could be done at a higher level, e.g. with a different concourse resource for notary operations. I'd be reluctant to add notary integration directly.
