### ISSUE TITLE
Is it legit to send empty Authorization header for anonymous request?

### ISSUE THREAD

**Issue by yolo3301** [google/go-containerregistry#468]
I noticed that when anon authn is used, requests to the registry will be sent with empty `Authorization` header (instead of dropping the Authorization header). However, it doesn't seem comply with http spec.

According to https://tools.ietf.org/html/rfc7235#appendix-C:

> credentials = auth-scheme [ 1*SP ( token68 / [ ( "," / auth-param )
    *( OWS "," [ OWS auth-param ] ) ] ) ]

Then

> auth-scheme = token

And

> token = <token, see [RFC7230], Section 3.2.6>

And 

> token          = 1*tchar

This essentially means the Authorization header cannot be empty. Any thoughts on this?

Related code: https://github.com/google/go-containerregistry/blob/master/pkg/v1/remote/transport/bearer.go#L62

**Comment by jonjohnsonjr** [comment]
Yeah that's definitely a bug, this is actually causing https://github.com/knative/serving/issues/4355
