### ISSUE TITLE
library prints annoying logs

### ISSUE THREAD

**Issue by dgageot** [google/go-containerregistry#480]
When used in Skaffold, the library prints annoying logs to the console and we have no simple way to hide them.

For example:
 + https://github.com/google/go-containerregistry/blob/9c974872bc17b108ff910a5c97eaa676e3dfab2e/pkg/authn/keychain.go#L103
 + https://github.com/google/go-containerregistry/blob/9c974872bc17b108ff910a5c97eaa676e3dfab2e/pkg/authn/keychain.go#L109
 + https://github.com/google/go-containerregistry/blob/46a3528b82270ecea7c731c14e698ea24aa0bbca/pkg/v1/google/auth.go#L65

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/issues/390

I'm surprised you're hitting the gcloud error ever.

This has been annoying for a while. In my head the best fix for this would be to revamp how we pass around credentials and defer that log statement until the point where using the credentials actually fails (e.g. you're trying to use anonymous auth against a private registry).

In the short term we could just introduce indirection between ggcr and the `log` package by adding our own `log` package that lets you override the logger (to ioutil.Discard or something). Eventually we should actually invest in real logging.

**Comment by dgageot** [comment]
@jonjohnsonjr I've started using the cloud authenticator directly. (not yet merged in master)

**Comment by pre** [comment]
The annoying error still exists. 

We recently introduced a publicly available container image dependency in our local development environment from the Google container registry. 

Now `ERRO[0003] gcloud binary not found` is coming from skaffold as a false alarm.
