### ISSUE TITLE
Feature: add the ability to mutate MediaType

### ISSUE THREAD

**Issue by joaopapereira** [google/go-containerregistry#491]
We have a use case where we want to create a docker image and save it in the registry with a specific  MediaType.

Why MediaType: this image is not going to be a runnable image but a storage image. The idea is also that we will have an application that will do some validation to ensure the image is consumable by the app an not a "random" image.

The proposal is to extend the `mutable` package to allow the ggcr user to update a given image MediaType.

**Comment by jonjohnsonjr** [comment]
Sounds good to me. Do you just care about the manifest media type or layer media types too?

In general we're lacking a good way to mutate manifests, e.g. adding annotations (related: https://github.com/google/go-containerregistry/issues/474).

**Comment by joaopapereira** [comment]
At this point in time I think that changing the media type of the manifest will fulfill our use case.
