### ISSUE TITLE
Please stop importing k8s.io/kuberneretes

### ISSUE THREAD

**Issue by fejta** [google/go-containerregistry#496]
Kubernetes only wants people to import things like k8s.io/api k8s.io/client-go, not k8s.io/kubernetes directly. This is why a bunch of k8s.io/kubernetes deps are [pinned to version v0.0.0](https://github.com/kubernetes/kubernetes/blob/39724859b524e345881eb8ef458f0d5a2f25bd9a/go.mod#L148-L173) to discourage its use.

See https://github.com/kubernetes/kubernetes/issues/81878 

Example usage: https://github.com/google/go-containerregistry/blob/31e00cede111067bae48bfc2cbfc522b0b36207f/pkg/authn/k8schain/k8schain.go#L25

**Comment by jonjohnsonjr** [comment]
In the meantime, we could just fork off the pkg/credentialprovider package? Anyone interested in doing that? 😄

**Comment by jonjohnsonjr** [comment]
@glyn I think most of your problems caused by this could be resolved by just forking the k8schain package off into its own project, but that would still leave knative and tekton broken, so it's not a panacea :(

**Comment by glyn** [comment]
Wouldn't a k8schain project still need something like the following in its `go.mod` and in the `go.mod` of all its users (transitively)?
```
replace (
	k8s.io/api => k8s.io/api v0.15.7
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.15.7
	k8s.io/apimachinery => k8s.io/apimachinery v0.15.8-beta.1
	k8s.io/apiserver => k8s.io/apiserver v0.15.7
	k8s.io/cli-runtime => k8s.io/cli-runtime v0.15.7
	k8s.io/client-go => k8s.io/client-go v0.15.7
	k8s.io/cloud-provider => k8s.io/cloud-provider v0.15.7
	k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.15.7
	k8s.io/code-generator => k8s.io/code-generator v0.15.8-beta.1
	k8s.io/component-base => k8s.io/component-base v0.15.7
	k8s.io/cri-api => k8s.io/cri-api v0.15.7
	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.15.7
	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.15.7
	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.15.7
	k8s.io/kube-proxy => k8s.io/kube-proxy v0.15.7
	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.15.7
	k8s.io/kubelet => k8s.io/kubelet v0.15.7
	k8s.io/kubernetes => k8s.io/kubernetes v1.15.7
	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.15.7
	k8s.io/metrics => k8s.io/metrics v0.15.7
	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.15.7
)
```

**Comment by jonjohnsonjr** [comment]
Yes, but AFAICT you don't actually use k8schain in https://github.com/pivotal/image-relocation right?

**Comment by glyn** [comment]
Correct, forking the k8schain package off into its own project would solve the problem for https://github.com/pivotal/image-relocation.

**Comment by jonjohnsonjr** [comment]
Fixed in https://github.com/google/go-containerregistry/pull/649

I'll leave this open to track https://github.com/kubernetes/enhancements/pull/1406

**Comment by jonjohnsonjr** [comment]
The KEP got merged :tada:
