### ISSUE TITLE
Option to not inject defaults in objects defined in the pkg/name package

### ISSUE THREAD

**Issue by smukherj1** [google/go-containerregistry#527]
For `Tag` and `Reference` created in the pkg/name package using [NewTag](https://github.com/google/go-containerregistry/blob/bb2eda47dcc0c4cb5d554415f786c8fbe45e42fb/pkg/name/tag.go#L74) and [ParseReference](https://github.com/google/go-containerregistry/blob/bb2eda47dcc0c4cb5d554415f786c8fbe45e42fb/pkg/name/ref.go#L40), for image strings that don't specify the registry name or name the repository in a certain way, some default values defined [here](https://github.com/google/go-containerregistry/blob/bb2eda47dcc0c4cb5d554415f786c8fbe45e42fb/pkg/name/registry.go#L26) and [here](https://github.com/google/go-containerregistry/blob/bb2eda47dcc0c4cb5d554415f786c8fbe45e42fb/pkg/name/repository.go#L23) get injected into the generated objects. I would like the ability to specify an option to the Tag & Reference creator functions such that they never insert any defaults. So if an image name like `foo/bar:latest` is specified, I would prefer the Registry entry in the created object to be left blank instead of defaulting it to `docker.io`. The default behavior of these functions can still be inserting these values if necessary.

**Comment by smukherj1** [comment]
This is currently blocking https://github.com/bazelbuild/rules_docker/issues/580

**Comment by jonjohnsonjr** [comment]
A couple options:
1. Add a `name.Option` to *not* add the defaulted values when we call `String()`
2. Expose something like `func Original() string` on `Reference` that returns the input string, so you can avoid throwing away the input.

Either one of these should also apply to references of the form `<repo>:<tag>@<digest>`. These are currently transformed into just `<repo>@<digest>` (the tag is thrown away), but we should be able to pass through the tag.

**Comment by smukherj1** [comment]
> A couple options:
> 
> 1. Add a `name.Option` to _not_ add the defaulted values when we call `String()`
> 2. Expose something like `func Original() string` on `Reference` that returns the input string, so you can avoid throwing away the input.
> 
> Either one of these should also apply to references of the form `<repo>:<tag>@<digest>`. These are currently transformed into just `<repo>@<digest>` (the tag is thrown away), but we should be able to pass through the tag.

If we decide to go with 2, the v1.tarball package will need an option to use the `Original` function instead of the `String` function when generating the image manifest for the image tarball.

**Comment by jonjohnsonjr** [comment]
> If we decide to go with 2, the v1.tarball package will need an option to use the Original function instead of the String function when generating the image manifest for the image tarball.

I think that's reasonable default behavior, since we should be able to parse either form.

**Comment by jonjohnsonjr** [comment]
Alright, so looking at the interface for `name.Reference`:
```go
// Reference defines the interface that consumers use when they can
// take either a tag or a digest.
type Reference interface {
	fmt.Stringer

	// Context accesses the Repository context of the reference.
	Context() Repository

	// Identifier accesses the type-specific portion of the reference.
	Identifier() string

	// Name is the fully-qualified reference name.
	Name() string

	// Scope is the scope needed to access this reference.
	Scope(string) string
}
```

It seems like `Name` should be the defaulted thing, and `String` should be the original input. Right now `Name` and `String` are just the same thing. We could add a new method that preserves the input or just change `String` to return the original input. We might be able to fix [this](https://github.com/google/go-containerregistry/blob/650bcbc276f32fe9e40263635bbf4a61a7837739/pkg/name/repository.go#L53) as a happy side-effect.
