### ISSUE TITLE
google.WalkFunc should be able to be parallelized

### ISSUE THREAD

**Issue by klauern** [google/go-containerregistry#556]
Looking at the implementation of the [`google.WalkFunc`](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/google#WalkFunc) it should be possible to implement a FastWalk function that parallelizes work across a parameterized set of goroutines and WaitGroups.

There's a few examples of doing this with `filepath.Walk`, so if this version is implemented in the same spirit, it should be able to benefit from prior work:

* [`fastwalk`](https://github.com/golang/tools/blob/19e2aca3fdf9724feacb8701307db6fb35055030/internal/fastwalk/fastwalk.go) (Golang internal tools)
* https://blog.golang.org/pipelines
* [Parallelizing Golang File IO](https://medium.com/@timhigins/parallelizing-golang-file-io-7c5d0cacfe5a)

**Comment by jonjohnsonjr** [comment]
Definitely agree. I've been trying to think of the right way to do this. We could add an `Option` to 
the existing `google.Walk` to configure a number of workers without having to making any breaking changes (as in fastwalk), which would be great, so we should probably just do that.

I feel like a better signature would be something that returns `(<-chan google.Tags, <-chan error)` (from the pipelines blogpost). We could possibly use that pattern for [catalog](https://github.com/google/go-containerregistry/pull/548) as well to handle pagination.

I'm not a huge go expert, though, so I might be missing a better pattern for this.
