### ISSUE TITLE
Layer digests don't match pushed digests using `docker`

### ISSUE THREAD

**Issue by jromero** [google/go-containerregistry#572]
It seems like there have been a few issues regarding Digest and compression (#150, #153, #158) yet I've come here with an unexpected issue brought on by the current compression. 

It seems like the current compression used is great in regards of performance but our expectation was that it would produce a layer digest which resembles that of what `docker` would produce when pushing to a registry. That is not the case. [`docker` uses default compression](https://sourcegraph.com/github.com/moby/moby@4866f5139a0b0bc026aa4b0c916ee1071c695134/-/blob/distribution/push.go#L155) making calls to `layer.Digest()` unusable in our case and requires us to compress the layers yet again to get the appropriate and expected layer digest.

This issue appears affects both [`tarball.Layer`](https://github.com/google/go-containerregistry/blob/master/pkg/v1/tarball/layer.go#L124:6) and [`stream.Layer`](https://github.com/google/go-containerregistry/blob/master/pkg/v1/stream/layer.go#L124).

**Proposal:** Allow configuration of compression used at digest computation but default to `gzip.DefaultCompression`.

**Comment by jonjohnsonjr** [comment]
> our expectation was that it would produce a layer digest which resembles that of what docker would produce when pushing to a registry

I don't think matching exactly what docker produces is something we are interested in trying to maintain, given that any changes to docker would break this assumption.

> Proposal: Allow configuration of compression used at digest computation but default to gzip.DefaultCompression.

On the other hand, this is completely reasonable and something we should definitely have :smile:.

I haven't looked into it much, so I'm not sure how hard it would be to plumb this through everywhere. Do you have an idea of how you'd want to implement this?

**Comment by jromero** [comment]
There was a PR that was going to address part of this #155 for images and the discussions revolved around using functional options. It seems like most agreed on that strategy. (https://github.com/google/go-containerregistry/pull/155#issuecomment-391126592)

On the plus side would maintain the method signatures backwards compatible.

Here's a quick prototype of what that would look like.
[layer-compress.patch.txt](https://github.com/google/go-containerregistry/files/3735625/layer-compress.patch.txt)

**Comment by jonjohnsonjr** [comment]
Sorry I didn't think of this before, but I'm wondering if we can solve https://github.com/google/go-containerregistry/issues/531 at the same time? If we're already making the compression level pluggable, perhaps we should make the entire compression algorithm pluggable?

We would need some way to synthesize the appropriate mediaType for the given compression algorithm as well. Perhaps something like:

```go
func defaultCompressor(rc io.ReadCloser, mt types.MediaType) (io.ReadCloser, types.MediaType) {
  // TODO: map docker media types and OCI media types to the right compressed versions
  mt = convertMediaType(mt, "gzip")
  return v1util.GzipReadCloser(rc), mt
}

func WithCompressor(c Compressor) LayerOption {
  return func(l *layer) error {
    l.compressor = c
  }
}

type Compressor func(io.ReadCloser, types.MediaType) (io.ReadCloser, types.MediaType)
```

Maybe returning the whole mediatype is the wrong thing here and we should just return "gzip" -- some generic interface would be useful.

Somewhat related are https://github.com/containerd/containerd/pull/3649 and https://github.com/opencontainers/image-spec/issues/791
