### ISSUE TITLE
Is go-containerregistry only supporting sending requests to a server that accepts HTTP and not HTTPS?

### ISSUE THREAD

**Issue by kovkev** [google/go-containerregistry#597]
https://github.com/google/go-containerregistry/blob/bf040943242e7fcc301d126fb6760e039395c2a6/pkg/v1/remote/transport/logger.go#L21

**Comment by jonjohnsonjr** [comment]
This works for both HTTP and HTTPS. The logger is only enabled if `logs.Debug` is set, which is done with the `--verbose` flag in `crane` and `gcrane` for debugging purposes.

Is your concern that it doesn't work? Or that we shouldn't be logging requests that will be encrypted on the wire?

**Comment by jonjohnsonjr** [comment]
Closing this, feel free to reopen if you have more questions!
