### ISSUE TITLE
Cannot get image

### ISSUE THREAD

**Issue by hougangliu** [google/go-containerregistry#601]
When I tried to get image info of a Kubernetes Pod container as below,  `remote.Image` always return error with message `Get https://index.docker.io/v2/: x509: certificate signed by unknown authority` no matter the image is private or public (for a private image, the Pod can pull the image successfully with same  pod.Spec.ImagePullSecrets)

```
	for _, s := range pod.Spec.ImagePullSecrets {
		imagePullSecrets = append(imagePullSecrets, s.Name)
	}
	kc, err := k8schain.NewInCluster(k8schain.Options{
		Namespace:          namespace,
		ServiceAccountName: pod.Spec.ServiceAccountName,
		ImagePullSecrets:   imagePullSecrets,
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to create k8schain: %v", err)
	}

	mkc := authn.NewMultiKeychain(kc)
	img, err := remote.Image(ref, remote.WithAuthFromKeychain(mkc))
```

In Gopkg.toml
```
[[override]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2019-03-20
  revision = "8d4083db9aa0d2fae6588c1acdbe6a1f5db461e3"
```

**Comment by jonjohnsonjr** [comment]
Interesting -- are you using a proxy for dockerhub?

**Comment by hougangliu** [comment]
> Interesting -- are you using a proxy for dockerhub?

no, we can access docker hub directly in my kubernetes cluster

**Comment by jonjohnsonjr** [comment]
I would guess that the container that's running this code needs to update the certs, e.g.:
```
apt-get update && apt-get install -y ca-certificates
```

**Comment by hougangliu** [comment]
@jonjohnsonjr cool, it works by `apt-get update && apt-get install -y ca-certificates`. thank you
