### ISSUE TITLE
Oauth grant_type=password is inaccessible

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#629]
Before https://github.com/google/go-containerregistry/pull/628 we would fall back to the oauth flow for username/password if the token flow failed. This is not great behavior, since it almost always will fail, so we removed that fallback. As a result, there's actually no way to use username/password with the oauth flow.

Docker has a similar codepath that is reachable if the [`ForceOAuth`](https://github.com/docker/distribution/blob/84f47e7bb3bb3521d7d20615d42078df306fb01d/registry/client/auth/session.go#L196) option is set in their `TokenHandlerOptions`, but as far as I can tell there's no existing code that actually exercises that path in the docker client.

It's unclear to me if any registries support this or any clients need it, and there's no easy way to tell if we should take that path from the registry response.

**Comment by splucs** [comment]
@jonjohnsonjr friendly ping on the PR for this: https://github.com/google/go-containerregistry/pull/1740
