### ISSUE TITLE
FYI som problems running crane Ubuntu 18.04 with docker installed with snap

### ISSUE THREAD

**Issue by phluks** [google/go-containerregistry#632]
I think. 

docker was listed with "snap list".

At the beginning my docker version was 18.09.9

I got this error:
```
crane pull cnbs/sample-builder:bionic builder.tar
2019/12/14 01:21:43 unsupported status code 401
```

I removed the apt get installed docker and downloaded a .deb package instead. Then it ran without errors.

Now my version was 19.03.5

However docker was still listed with "snap list". I then snap remove'd docker and reinstalled the .deb package.

And it still works. It might be the upgrade or the "un-snapped" docker.

I'm sorry that my debugging did not provide a clear picture.

**Comment by jromero** [comment]
Related to: https://github.com/buildpacks/docs/issues/96

**Comment by jonjohnsonjr** [comment]
Possibly related to docker mutating your config file on upgrade? `crane` shouldn't have any dependency on what docker version you have installed, but it does rely on `~/.docker/config.json` for credential configuration. It would be hard to debug without more info, but inspecting that file and maybe throwing around the `-v` flag could help.

**Comment by jromero** [comment]
Will keep `-v` in mind if we run into the issue again.

<hr />

FWIW, this additional information was provided via slack:

> jromero  19 hours ago
> Some things to look at are:
```
echo $DOCKER_CONFIG
ls ~/.docker/config.json
```

> Olav Cleemann  19 hours ago
> I'm in the process of downloading .deb packages for docker. Here's the config so far:
```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "<I dont know if this is safe to publish>"
    }   
  },  
  "HttpHeaders": {
    "User-Agent": "Docker-Client/18.09.1 (linux)"
  }
}
```

Olav Cleemann  19 hours ago
> I don't have a $DOCKER_CONFIG

**Comment by jonjohnsonjr** [comment]
> `<I dont know if this is safe to publish>`

FWIW, definitely not. This should be your basic auth (i.e. the base64 encoded string `$USERNAME:$PASSWORD`).

I'm not at all familiar with snap, so I wouldn't know where to start debugging this.

**Comment by phluks** [comment]
Good news. I tried to see if I could get back to the broken state by removing the .deb installed version of docker and re-install with snap.

I could not. In fact crane worked with and without docker installed in either version.

I suspect that my docker install was broken somehow and that removing and re-installing docker solved the problem.

Case closed. Thanks for your assistance. I'm sorry for the inconvenience. Please feel free to rock-on with what ever else requires your attention 8-)

**Comment by jonjohnsonjr** [comment]
> Case closed. Thanks for your assistance. I'm sorry for the inconvenience. Please feel free to rock-on with what ever else requires your attention 8-)

No problem, thanks for the closure!
