### ISSUE TITLE
Force Crane to use http instead of https

### ISSUE THREAD

**Issue by erbesharat** [google/go-containerregistry#633]
I went through the code and documentation but couldn't find any option to force Crane to use http instead of https.
We've decided to use Crane inside our E2E tests and since every service is using http, when we want to pull an image from the testing server, Crane returns a connection refused error since it tries to lookup :443.
```
2019/12/14 12:54:26 Get https://pull.dockerv2.dockerv2.example.com/v2/: dial tcp 172.20.10.2:443: connect: connection refused
```

Is there any option to use http instead or we have to serve the services on https too?

**Comment by erbesharat** [comment]
I found out that using HTTP is possible by using Insecure Option within NewRegistry. But can't find any options to pass it to Crane with a flag or something like. Is there anything that I'm missing or passing insecure isn't implemented in cmd and it's only available inside the pkg?
No option is being passed to ParseReference in here:
https://github.com/google/go-containerregistry/blob/1fcfcf2f6866ccdd4f686421b2de0d99c8f0514f/pkg/crane/pull.go#L34

Let me know if it's ok to add the `-insecure` flag to the crane cli. I can take care of it and create a PR for it :)

**Comment by stp-ip** [comment]
This would be really helpful to use crane within testing or local environments.

**Comment by ImJasonH** [comment]
+1 to a PR. If there are other surfaces that support an insecure option they should probably all support it and with the same semantics.

**Comment by jonjohnsonjr** [comment]
I guess it's time for crane to have options :P 

+1 to a PR.
