### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by spursy** [google/go-containerregistry#648]
**I have encounter the followed issue:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ecd70f]

goroutine 39 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc0007aa060, 0xa, 0xc0007aa06b, 0xa, 0xc0007aa076, 0x7, 0x0, 0x0, 0xc00081fc68, ...)
	/private/tmp/minikube-20191220-77113-wmp8w9/.brew_home/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc0007aa060, 0x1d, 0xc0006e6140, 0x40, 0x0, 0x0)
	/private/tmp/minikube-20191220-77113-wmp8w9/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc000746f68, 0x1)
	/private/tmp/minikube-20191220-77113-wmp8w9/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0007ac120, 0xc0007ac150)
	/private/tmp/minikube-20191220-77113-wmp8w9/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/private/tmp/minikube-20191220-77113-wmp8w9/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/e
```

**My GO version is :**

```
go version go1.13.5 darwin/amd64
```

**Comment by jonjohnsonjr** [comment]
Interesting!

This is suspicious looking to me: https://github.com/kubernetes/minikube/blame/cc82b4a81f16bf27894d940fe34854b7eef14875/pkg/minikube/machine/cache_images.go#L350-L368

I wonder if the logs produce anything useful, but the mix of checking for nil err or non-nil err seems bug-prone @priyawadhwa any ideas?

It's failing here per the logs: https://github.com/google/go-containerregistry/blob/697ee0b3d46eff19ed2b30f86230377061203f79/pkg/v1/tarball/write.go#L57

Which makes me think minikube is calling `tarball.Write` with a nil `v1.Image`.

**Comment by priyawadhwa** [comment]
Yup this looks like it's probably a minikube error --

@spursy would you mind [opening an issue](https://github.com/kubernetes/minikube/issues) in the minikube repo and we can continue this discussion there?

**Comment by jonjohnsonjr** [comment]
Going to close this, since I believe it's an issue in minikube.
