### ISSUE TITLE
Convert a v1 tar to a legacy tar?

### ISSUE THREAD

**Issue by deitch** [google/go-containerregistry#650]
Is there a way to convert a v1 tar to a legacy tar? I am using the API, not the CLI, usually something like this (ignoring error handling and a lot of the logic):

```go
ref, err := name.ParseReference(image)
desc, err := remote.Get(ref, options...)
img, err := desc.Image()
tag, ok := ref.(name.Tag)
switch writeFormat {
case FORMATV1:
    err = v1tarball.WriteToFile(savePath, tag, img)
case FORMATLEGACY:
    w, err := os.Create(savePath)
    defer w.Close()
    err = legacytarball.Write(tag, img, w)
}
```

Is there any way to take the file output of `v1tarball.Write()` (i.e. a file) and convert it to a legacy tar file? I always could do:

```go
img, err := v1tarball.ImageFromPath(v1Path, tag)
w, err := os.Create(legacyPath)
defer w.Close()
err = legacytarball.Write(tag, img, w)
```

But would the second write not go back to the registry over the network (which may not be available at the time)? I just want to convert it using my already available data in the local v1 tarball, which is a true and hash-validated representation of the image in the registry.

**Comment by jonjohnsonjr** [comment]
> But would the second write not go back to the registry over the network (which may not be available at the time)? I just want to convert it using my already available data in the local v1 tarball, which is a true and hash-validated representation of the image in the registry.

I don't think your second snippet would go back over the network. `ImageFromPath` just reads from disk to access images/blobs, so this *should* work like you expect.

**Comment by deitch** [comment]
Thanks @jonjohnsonjr i will run an experiment and check. 

I did understand correctly for the first part, though, that `remote.Get()` just fetches the manifest (potentially resolving the index, I’d present), while the `tarball.Write()` does the fetching of layers?

**Comment by deitch** [comment]
@jonjohnsonjr my experiment succeeded, you are write. I did a `Pull()` while on network to save to a v1 tarball, then turned off network and did a convert as described above. It all works as expected. 

May I suggest the documentation be updated to indicate that when you get a `v1.Image()` from an existing downloaded structure, whether `v1.tarball`, `legacy.tarball` or `layout.Path`, that it reads the data structures locally?

In the meantime, I will close this issue.

**Comment by jonjohnsonjr** [comment]
> It all works as expected.

:tada: 

> May I suggest the documentation be updated to indicate that when you get a v1.Image() from an existing downloaded structure, whether v1.tarball, legacy.tarball or layout.Path, that it reads the data structures locally?

It's a bit complicated, because we try to access things as lazily as possible. When you `Write()` something to disk, though, you essentially force the package to download everything and serialize it to disk. It's been on my TODO list for a while to update the README to describe the structure and philosophy behind this package, so I'll try to sit down and write something once I'm caught up from vacation :)
