### ISSUE TITLE
Requires authentication even for public registries

### ISSUE THREAD

**Issue by samos123** [google/go-containerregistry#666]
Currently when using a public image from GCR it will fail with trying to authenticate with Google Cloud. However for public images that shouldn't be needed.

Steps to reproduce:
1. Remove any authentication with gcloud. E.g. `mv ~/.config/gcloud{,.bak}` 
2. Use go-containerregistry to pull an image from a public GCR repo
```
crane pull gcr.io/distroless/base-debian10 test.tgz
WARNING: Could not open the configuration file: [/home/stoelinga/.config/gcloud/configurations/config_default].
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2020/01/29 16:40:05 error getting credentials - err: exit status 1, out: ``
```

Current result:
Failure telling you to authenticate with google cloud

Expected result:
Successfully pull down the image

**Comment by jonjohnsonjr** [comment]
Seems like you've configured a [credential helper](https://github.com/google/go-containerregistry/tree/master/pkg/authn#credential-helpers) in ~/.docker/config.json (or $DOCKER_CONFIG) but it isn't set up properly.

We do eagerly get credentials for a registry, which is the cause of this error. If we deferred fetching creds until we actually got a 401, we could avoid this... which is definitely something we should do.

**Comment by tejal29** [comment]
@samos123, i ended up removing `~/.docker/config.json and `~/.config/gcloud`
```
$mv ~/.config/gcloud ~/Desktop

$ls ~/.config/
configstore	gbackup		hub
$ls ~/.config/gbackup/
exclude		exclude.d	include

 $crane pull gcr.io/distroless/base-debian10 test.tgz
2020/01/29 16:59:55 No matching credentials were found, falling back on anonymous

$ls -alh test.tgz 
-rw-r--r--  1 tejaldesai  primarygroup   8.3M Jan 29 17:02 test.tgz

```

**Comment by samos123** [comment]
interesting then it must be something in Kaniko that we're doing incorrectly in relation to this library since on Travis CI, i did not configure the gcloud config helper but it would still fail with a similar message that authentication with gcloud was needed.

**Comment by filesnate** [comment]
In the kaniko image, there exists the file `/kaniko/.docker/config.json` with the following contents.
```
/kaniko/.docker # more config.json 
{
        "auths": {},
        "credHelpers": {
                "asia.gcr.io": "gcr",
                "eu.gcr.io": "gcr",
                "gcr.io": "gcr",
                "staging-k8s.gcr.io": "gcr",
                "us.gcr.io": "gcr"
        }
}
```
If this file is replaced with a blank json file contents of `{}`, then kaniko works properly. This default configuration files is causing issues with any registry listed above, as it causes them to REQUIRE credentials that are not setup in the default case.  IMO, the contents of config.json should be replaced with a blank json file.

**Comment by filesnate** [comment]
```Dockerfile
FROM gcr.io/kaniko-project/executor:debug
```

```config.json
{}
```
```
% docker run -v `pwd`/config.json:/kaniko/.docker/config.json:ro -v `pwd`:/workspace gcr.io/kaniko-project/executor:debug --context=/workspace --no-push
INFO[0000] Resolved base name gcr.io/kaniko-project/executor:debug to gcr.io/kaniko-project/executor:debug 
INFO[0000] Resolved base name gcr.io/kaniko-project/executor:debug to gcr.io/kaniko-project/executor:debug 
INFO[0000] Retrieving image manifest gcr.io/kaniko-project/executor:debug 
INFO[0000] Retrieving image manifest gcr.io/kaniko-project/executor:debug 
INFO[0001] Built cross stage deps: map[]                
INFO[0001] Retrieving image manifest gcr.io/kaniko-project/executor:debug 
INFO[0002] Retrieving image manifest gcr.io/kaniko-project/executor:debug 
INFO[0002] Skipping unpacking as no commands require it. 
INFO[0002] Taking snapshot of full filesystem...        
INFO[0002] Resolving paths                              
INFO[0002] Skipping push to container registry due to --no-push flag 
```

**Comment by tejal29** [comment]
Thanks a lot @filesnate for debugging this.
I agree, we should replace config.json with empty file and other users who use private images can add their config as a volume mount inside cluster like [this](https://github.com/GoogleContainerTools/kaniko/blob/master/examples/pod.yaml#L13)
or on the `docker run` command like you mentioned


Would you up for submitting a PR to remove credentials helper in from the executor image ?

**Comment by filesnate** [comment]
See https://github.com/GoogleContainerTools/kaniko/pull/1125
