### ISSUE TITLE
Default namespace for repository

### ISSUE THREAD

**Issue by antechrestos** [google/go-containerregistry#668]
In a previous [issue](https://github.com/google/go-containerregistry/issues/600), I had issue using kaniko as it used to ask scopes to target registry for both target image and parent image.
As I used a jfrog docker proxy for an official image, my parent image looked like

```
FROM my-docker-proxy.io/ubuntu:latest
```

When [the ParseReference function](https://github.com/google/go-containerregistry/blob/aec8da010de25d23759d972d7896629d6ae897d8/pkg/name/ref.go#L40)  is called , it builds a new tag object.

My question is: why `hasImplicitNamespace` used for [Repository objects](https://github.com/google/go-containerregistry/blob/aec8da010de25d23759d972d7896629d6ae897d8/pkg/name/repository.go#L36) only limits the prefixing of `library` to images hosted on `docker.io`? 

Doesn't all the registries respect this convention?

Thanks

**Comment by jonjohnsonjr** [comment]
> Doesn't all the registries respect this convention?

Not to my knowledge. E.g. [docker/distribution](https://github.com/docker/distribution/blob/411d6bcfd2580d7ebe6e346359fa16aceec109d5/reference/normalize.go#L107-L127) only does this for `docker.io` as well. I think you'd have to explicitly reference this image as `my-docker-proxy.io/library/ubuntu:latest`.

**Comment by antechrestos** [comment]
@jonjohnsonjr thank you for your reply.
