### ISSUE TITLE
crane ls failed with AWS ECR

### ISSUE THREAD

**Issue by alexey-igrychev** [google/go-containerregistry#681]
> https://github.com/google/go-containerregistry/blob/master/pkg/v1/remote/list.go#L56
```
uri := &url.URL{
	Scheme:   repo.Registry.Scheme(),
	Host:     repo.Registry.RegistryStr(),
	Path:     fmt.Sprintf("/v2/%s/tags/list", repo.RepositoryStr()),
	RawQuery: "n=10000",
}
```

The number of tags is hardcoded. What do you think about adding the option with default value instead?

### Error

2020/03/03 13:01:43 reading tags for 659236497016.dkr.ecr.eu-central-1.amazonaws.com/test/a: GET https://659236497016.dkr.ecr.eu-central-1.amazonaws.com/v2/test/a/tags/list?n=10000: UNSUPPORTED: Invalid parameter at 'maxResults' failed to satisfy constraint: 'Member must have value less than or equal to 1000'

**Comment by jonjohnsonjr** [comment]
Interesting! That's surprising behavior given the spec (added in https://github.com/docker/distribution/pull/1774):

>  The implementation may impose a maximum limit and return a partial set with pagination links.

Granted, that's for catalog pagination, but tags pagination is supposed to have the same behavior. FYI @samuelkarp for ECR, but it also looks like we dropped this when removing catalog from the distribution spec, which should probably be added back: https://github.com/opencontainers/distribution-spec/commit/b4e98332eccaf51d1974c9136caf67317bd99104#diff-958e7270f96f5407d7d980f500805b1bL4682 

I don't have a problem with exposing this as an option, but for now let's just drop it down to 1000 by default. FYI @dsbrng25b

**Comment by jonjohnsonjr** [comment]
Hm, looking at this now, the section I quoted is specifically for requests where `n` isn't set, so ECR may be doing the right thing. I'll open a PR against the distribution spec to see what folks think.

**Comment by samuelkarp** [comment]
It doesn't look like the distribution spec currently specifies behavior around a maximum page size.

**Comment by jonjohnsonjr** [comment]
I've opened https://github.com/opencontainers/distribution-spec/issues/106 to start a discussion for the spec. I'm curious if ECR returns as much as it permits (i.e. 1000 tags) if `n` is unspecified, or if it defaults to a lower number.

**Comment by samuelkarp** [comment]
> I'm curious if ECR returns as much as it permits (i.e. 1000 tags) if `n` is unspecified, or if it defaults to a lower number.

The current default page size is 100.

> Is there an upper limit on the allowed number of tags in an image?

Yep, 100 as described by the page you linked.

> [What] happens if someone does a non-paginated tag list in a repo with > 1000 tags?

They'll get a result of the default page size, 100.  They can make paginated requests to see the full set of tags.

**Comment by jonjohnsonjr** [comment]
Thanks for digging all that up :)

**Comment by alexey-igrychev** [comment]
Thank you for your prompt action
