### ISSUE TITLE
push to local docker

### ISSUE THREAD

**Issue by lshamis** [google/go-containerregistry#688]
I'm trying to push/pull images from the local docker daemon (not a registry running at localhost:5000).

I'm coming in from bazelbuild/rules_docker which gives limited interaction.
It requires a `registry` and `repository` https://github.com/bazelbuild/rules_docker/blob/4949635b4d315641a91e950c935308903a61286f/container/push.bzl#L151

which gets assembled into a destination `dst={registry}/{repository}:{tag}` https://github.com/bazelbuild/rules_docker/blob/4949635b4d315641a91e950c935308903a61286f/container/push.bzl#L82

which executes `ref, err := name.ParseReference(dst)` and `remote.Write(ref, ...)` here
https://github.com/bazelbuild/rules_docker/blob/ce4da69d74945cf28e2d2aed5b3a3c2c565dbc87/container/go/cmd/pusher/pusher.go#L149

What value of `dst` can I set such that `ParseReference` and `Write` talk to the local machine?
I've tried setting the `registry` to the empty string and to `/var/run/docker.sock`, neither work.

I'm running stock Ubuntu with the latest docker.

**Comment by jonjohnsonjr** [comment]
I believe you can just `bazel run <target>` a `container_image` target (from [here](https://github.com/bazelbuild/rules_docker#using-with-docker-locally)).

**Comment by lshamis** [comment]
Thanks @jonjohnsonjr!

**Comment by lshamis** [comment]
Sorry to reopen. Seems I can't directly use the name of a local image as base in a `cc_image` rule. Is there a `container_pull` equivalent to `container_image`? (or a `registry` value)

**Comment by jonjohnsonjr** [comment]
I think the closest is [`container_load`](https://github.com/bazelbuild/rules_docker#container_load), but you'd have to `docker save` the image first... I might be wrong though, cc @smukherj1

**Comment by lshamis** [comment]
Ping @smukherj1
