### ISSUE TITLE
Determine if v1.Image is compressedLayerExtender or uncompressedLayerExtender

### ISSUE THREAD

**Issue by knqyf263** [google/go-containerregistry#701]
Is there any way to determine if v1.Image is compressedLayerExtender or uncompressedLayerExtender? If it is compressedLayerExtender, I want to call `Digest()`. If it is uncompressedLayerExtender, I want to call `DiffID()`. This is because the hash calculation of a compressed layer for uncompressedLayerExtender is a high cost.
https://github.com/google/go-containerregistry/blob/6950943e71a1805ce590c2b5ee50d761c09acc02/pkg/v1/partial/uncompressed.go#L72-L82

I tried type assertion, but I couldn't do it since `compressedLayerExtender` and `uncompressedLayerExtender` are not exposed. If you don't have the way, can I add a function like `func IsCompressed() bool`?

**Comment by jonjohnsonjr** [comment]
I wouldn't mind exposing `uncompressedLayerExtender` and `compressedLayerExtender` if you want to send a PR and test that it solves your issue.
