### ISSUE TITLE
Copying images from dockerhub to amazon aws ecr fails - 'imageTag' failed to satisfy constraint

### ISSUE THREAD

**Issue by markus7811** [google/go-containerregistry#704]
Hi, 

i discovered crane one week ago and like it. But while using the cli and the package i discovered one issue and have no clue at the moment why crane behaves like this. I think it hast to do with aws implementation of a docker registry ...

If i trie to copy images from the docker hub, crane (cli and pkg) fail with the following error message:

_failed to copy index: PUT https://xxxxx.dkr.ecr.an-aws-region.amazonaws.com/v2/library/ubuntu/manifests/sha256:e5dd9dbb37df5b731a6688fa49f4003359f6f126958c9c928f937bec69836320: UNSUPPORTED: Invalid parameter at 'imageTag' failed to satisfy constraint: 'must satisfy regular expression '[a-zA-Z0-9-_.]+''_

or

failed to copy index: PUT https://xxx.dkr.ecr.eu-central-1.amazonaws.com/v2/.../alpine-test/manifests/sha256:cb8a924afdf0229ef7515d9e5b3024e23b3eb03ddbba287f4a19c6ac90b8d221: UNSUPPORTED: Invalid parameter at 'ImageTag' failed to satisfy constraint: 'You must specify the image tag for this image type'

But it only happens if i use the docker.io hub as source (tried ubuntu:latest, hello-world:latest and some other tags)

But using images from gcr and other private registries works fine. 

One difference i found in the verbose output of the crane cli is the following:

works: 

_--> PUT https://xxxxx.dkr.ecr.an-aws-region.amazonaws.com/v2/gcr.io/kaniko-project/executor/manifests/latest_

doesn't work:
_--> PUT https://xxxxx.dkr.ecr.an-aws-region.amazonaws.com/v2/library/ubuntu/manifests/sha256:e5dd9dbb37df5b731a6688fa49f4003359f6f126958c9c928f937bec69836320_

So it looks to me as if crane uses the sha to create the manifest for the image if the image source is dockerhup - i think aws things sha256:e5.... is the image tag and refuses this, as it is not matching the regex.

So, is it possible to make crane using the tag for pushing, not the sha?

Is this issue linked with: https://github.com/google/go-containerregistry/issues/540 ?

**Comment by jonjohnsonjr** [comment]
ECR didn't seem to [support manifest lists](https://aws.amazon.com/about-aws/whats-new/2020/05/ecr-now-supports-manifest-lists-for-multi-architecture-images/) until after you filed this issue, have you tried again since then?

> So, is it possible to make crane using the tag for pushing, not the sha?

We might have to do this, but for manifest lists like this, we'd be writing multiple images using the same tag, which might have some unintended consequence depending on registry behavior (around quota, immutable tag policies, etc...).
