### ISSUE TITLE
Support a "login" flow

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#718]
This came up in the context of `ko` (https://github.com/google/ko/issues/155), but I think it would also be valuable to have `crane login` and supporting libraries upstream here.

I think we need work to:
1. Support interfacing with mutable keychains to write credentials through (not all will implement this, so we need a new interface, e.g. `MutableKeychain` that the default keychain implements)

2. In a perfect world we'd just have a `login` cobra command that both `crane` and `ko` can simple link in.  I could also see this being useful for downstream tooling like `tkn`, `kn`, `packs`, ...

3. Link it into `crane`

**Comment by ImJasonH** [comment]
Is the idea to generate the ~/.docker/config.json that has auth set up (e.g., credential helpers)? Or to replace credential helpers for crane etc.?

What's the CLI surface you imagine? `crane login gcr.io`?

**Comment by mattmoor** [comment]
I wasn’t imagining a lot of design here.  I’d mimic the docker CLI surface and semantics.  I wouldn’t set up cred helpers, but it one is configured I’d implement the write protocol.

**Comment by mattmoor** [comment]
Wait...  Is this already done? 🤣 

https://github.com/google/go-containerregistry/pull/672

**Comment by mattmoor** [comment]
I was able to link this into another command group and it worked great.  I think the key thing that needs to be fixed is the usage, which still prints `crane auth login`.  I have solved this in other tools by using `%[1]s` for the command name in usage and then `fmt.Sprintf` with `filepath.Base(os.Args[0])`.

Then we can have `ko auth login` 🤩
