### ISSUE TITLE
k8schain doesn't work with multiple Secrets

### ISSUE THREAD

**Issue by zuzzas** [google/go-containerregistry#723]
I'm trying to build an image checking operator for Kubernetes. Everything works perfectly except the auth part if multiple `imagePullSecrets` are specified. The authentication provider selects only the first one from keyring: https://github.com/google/go-containerregistry/blob/5cbd060f5c92/pkg/authn/k8schain/k8schain.go#L145. Is it by design?

**Comment by ImJasonH** [comment]
@mattmoor was this an intentional restriction?

**Comment by hasheddan** [comment]
@mattmoor is this something that you are looking for someone to work on?

**Comment by mattmoor** [comment]
I think that'd be awesome.  This likely affects Knative's multi-container support as well 🤔 

cc @markusthoemmes @savitaashture @dprotaso

**Comment by bonifaido** [comment]
It bit us as well: https://github.com/banzaicloud/bank-vaults/issues/1269

Is this something that is being worked on? If not, I'm happy to help.

**Comment by jonjohnsonjr** [comment]
I don't think anyone is actively working on k8schain. There has been some discussion in https://github.com/knative/serving/issues/10259 about outstanding issues that are nearly unsolvable given the current structure, and the packages we rely on are likely going to go away as part of KEP-541, which means we'll either need to have a very divergent fork or rethink how k8schain should work.

Of course, I'm happy to review small changes that fix bugs, but the package will probably need to be rewritten or deprecated after a few more k8s releases.

**Comment by dkulchinsky** [comment]
Hey folks 👋🏼 just wanted to know if someone's planning to look into this specific issues?

**Comment by jonjohnsonjr** [comment]
@hasheddan might be interested still?

**Comment by hasheddan** [comment]
Yep! Let me take a look here and see if we can support this in the near-term with the current state of the package 👍

**Comment by dprotaso** [comment]
woot!

**Comment by dkulchinsky** [comment]
Hey @hasheddan, any update you can share with us? hoping there's a chance this could be resolved to unblock a painful issue this is causing (https://github.com/banzaicloud/bank-vaults/issues/1269)

Thanks!

**Comment by jonjohnsonjr** [comment]
I am curious how we'd expect this to work -- any pointers to how the kubelet handles this?

**Comment by jonjohnsonjr** [comment]
Found this: https://github.com/kubernetes/kubernetes/blob/2e93b3924ae6eb2b6a2b914fe400a006bd676308/pkg/kubelet/kuberuntime/kuberuntime_image.go#L45-L76

Doesn't exactly fit into how we expect auth to work (we really only expect one authconfig).

I can imagine plumbing this around and doing some typechecking in [here](https://github.com/google/go-containerregistry/blob/5cbd060f5c9218eea992d3246fe51d7794dd6cd3/pkg/v1/remote/transport/bearer.go#L91) to look for a magic method that returns multiple authconfigs instead of one... maybe:

```go
// MultiAuthenticator is used to authenticate Docker transports.
type MultiAuthenticator interface {
	// Authorizations returns the values to use in an http transport's Authorization header.
	Authorizations() ([]AuthConfig, error)
}
```

Then we can drop into a loop on refresh until it works?

**Comment by bonifaido** [comment]
Looks like a feasible solution to me!

**Comment by realshuting** [comment]
Hi, we are also encountering the same issue in Kyverno https://github.com/kyverno/kyverno/issues/4536, only the first secret specified in the keychain is used.

Any updates on this issue?

**Comment by zuzzas** [comment]
Fixed by https://github.com/google/go-containerregistry/pull/1234
