### ISSUE TITLE
`crane push` doesn't support OCI image tarballs

### ISSUE THREAD

**Issue by jspawar** [google/go-containerregistry#726]
One of the first actions `crane push` undertakes is to obtain the image manifest as such: https://github.com/google/go-containerregistry/blob/a873a21aff2360d401b48410e63edbdc3c97bc8c/pkg/v1/tarball/image.go#L155

However, `manifest.json` is not defined in the OCI image-layout spec and this command should instead be opening up `index.json` and following its contents to eventually obtain the manifest in the image tarball to be pushed per the OCI spec: https://github.com/opencontainers/image-spec/blob/master/image-layout.md#oci-image-layout-specification

I then discovered you all have a helpful readme for that package which states:

> This package produces tarballs that can consumed via `docker load`

So I see this implementation is indeed Docker-specific and wondering if y'all are open to accepting changes which would allow `crane push` to support pushing OCI image tarballs? Perhaps behind a flag to the push command using your `layout` package implementation? 

Don't know if there are any issues with pushing to certain registries such as GCR or Docker Hub (i.e. they don't support pushing/pulling OCI images), so would be good to know that as well as any other context I might be missing if you don't mind. 

Thank you!

**Comment by ImJasonH** [comment]
I'd definitely be in support of adding this. What CLI flags were you thinking exactly?

**Comment by jspawar** [comment]
@ImJasonH perhaps something simple on the push command like `--layout` which would accept some enum value to indicate what type of tarball layout your input is in? 

E.g. `crane push --layout docker` or `crane push --layout oci`

Not really picky and can even leave Docker as the default layout to mitigate introducing a breaking change.

**Comment by ImJasonH** [comment]
A new `--layout` flag which defaults to `docker` for compatibility sgtm, @jonjohnsonjr any objection?

**Comment by jonjohnsonjr** [comment]
That seems reasonable to me, though I'd probably go with `--format` over `--layout` since [we already have that for pull](https://github.com/google/go-containerregistry/blob/2a1a46d929f8e396080340669edf5456a67493b5/cmd/crane/cmd/pull.go#L65).

**Comment by jspawar** [comment]
@jonjohnsonjr @ImJasonH Great! Also like the sound of `--format` over `--layout`.

Would you all prefer a contribution for this or is there some sort of public backlog y'all will add this into?

**Comment by jonjohnsonjr** [comment]
We'll take any contributions we can get 😄

**Comment by t0rr3sp3dr0** [comment]
Any updates on this?
