### ISSUE TITLE
github.com/google/subcommands isn't very user friendly

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#73]
Should consider using another library or patching it.

Biggest issue is if your subcommand returns `ExitUsageError` during `Execute` it doesn't actually print the usage. 

```bash
$ d8s append
$ # Nothing was printed!
```

Additionally, when performing `d8s [subcommand] -h` or `d8s [subcommand] -non-existent-flag` the output is confusing. See the weird `-o string ...` output below

```bash
$ d8s append -h
append [-o output-file] <src-reference> <dest-tag> <tarball>  -o string
    	output the resulting image to a new tarball
```

**Comment by ImJasonH** [comment]
Yeah it looks like all the cool kids use github.com/spf13/cobra so we'll probably move to that.

Don't let that block adding `append` though I'll move it along with the rest.

**Comment by dekkagaijin** [comment]
+1 to corba command, for obvious reasons
