### ISSUE TITLE
Docker API version negotiation happens too late

### ISSUE THREAD

**Issue by afbjorklund** [google/go-containerregistry#734]
After the change in 4336215636f7ace860f1e499cf5033d12073a44b, it now happens _after_ the open:

```go
	if i.buffered {
		opener, err = i.bufferedOpener(i.ref)
	} else {
		opener, err = i.unbufferedOpener(i.ref)
	}
	if err != nil {
		return nil, err
	}

	i.client.NegotiateAPIVersion(context.Background())
```

pkg/v1/daemon/image.go

This means that it tries to run without first determining the highest version supported by the docker daemon:

`Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40`

So it (`i.client.NegotiateAPIVersion`) needs to happen **before** the `i.client.ImageSave` (in the opener)

We get this error in minikube.

**Comment by jonjohnsonjr** [comment]
Thanks -- sorry about that.
