### ISSUE TITLE
crane copy can not be used to copy from insecure registry to secure

### ISSUE THREAD

**Issue by Omar007** [google/go-containerregistry#738]
Crane defines `--insecure` as "Allow image references to be fetched without TLS" but it's not so much an 'Allow' as it is enforcing the use of HTTP instead of HTTPS.  

When you attempt to copy from an insecure to a secure registry (or vice versa) you have to supply `--insecure` to be able to pull it from the source registry. 
Because the flag globally forces the use of HTTP and completely forgoes any attempt to use HTTPS at all, it causes the push to the target registry to be done with HTTP as well and thus fail.

**Comment by jonjohnsonjr** [comment]
This isn't intentional -- we try to always use https first, falling back to http is --insecure is supplied:

https://github.com/google/go-containerregistry/blob/72edbad9993e722466d28ff308cf2cdba4b675c5/pkg/v1/remote/transport/ping.go#L71-L77

If you can narrow down the sequence of requests where this is still failing (`crane cp -v` is useful), that would help debug why this doesn't work as expected.

> Because the flag globally forces the use of HTTP...

I do think this is less than ideal, and it might make sense to add some feature where you could specify that an image ref is insecure, e.g. `crane cp http://foo.example.com/my/image secure.example.com/my/image`

**Comment by Omar007** [comment]
I'll have to provide more specifics tomorrow when I get back in. What I can give you now is that I've gotten a few other job results that went successfully with a similar setup (insecure to secure but different secure target) so it might be some other mechanism within crane that flips on HTTP over HTTPS which I'm not aware (I have not look into the code yet and `--insecure` was the only documented flag for this)

**Comment by Omar007** [comment]
You were completely right. Using `-v` it showed a single line log message stating that the certificate was signed by an unknown authority before it continued on its merry way with HTTP.  

It seems the combination of that unknown authority and `--insecure` causes crane to fall back to HTTP even though it did in fact hit an HTTPS endpoint. As a result, when not using `-v`, it ends up only showing the HTTP connection error as the failure reason at the end even though that was not the actual cause in this case.  

That does bring up a question I'd like to pose here; should `--insecure` just accept unknown certs instead of falling back to HTTP? HTTPS is present so why fall back to HTTP? 
Having it accept unknown certs when using `--insecure` basically makes the flag work the same as Docker's insecure_registries setting;
- If HTTPS is available but the certificate is invalid, ignore the error about the certificate.
- If HTTPS is not available, fall back to HTTP.

Anyway, at the moment that means we are basically hitting issue #211 for the given registries. Providing the certs for those registries through `SSL_CERT_DIR=...` as mention in issue #451 did the trick and resolved the problem for now.

**Comment by jonjohnsonjr** [comment]
> As a result, when not using -v, it ends up only showing the HTTP connection error as the failure reason at the end even though that was not the actual cause in this case.

We should probably fix this to show the first error (or both) on that code path.

> That does bring up a question I'd like to pose here; should --insecure just accept unknown certs instead of falling back to HTTP? HTTPS is present so why fall back to HTTP?

This is a great question -- we don't do any kind of investigation of the error we get back when we try HTTPS -- we just assume trying HTTP is the right thing to do. I don't have any problem with setting [`InsecureSkipVerify`](https://golang.org/pkg/crypto/tls/#Config.InsecureSkipVerify) when `--insecure` is set (PRs welcome, of course).

> ... resolved the problem for now.

Glad you're unblocked -- I'll keep this open to track the two things I mentioned above.
