### ISSUE TITLE
errors returned via cli aren't user friendly

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#74]
Currently errors in this library don't provide much context. Thus errors in the resulting cli suffer from poor UX

We should use [github.com/pkg/errors](https://github.com/pkg/errors) and wrap errors with more context.

**Comment by dekkagaijin** [comment]
making up for Go's misguided opinionatedness, I love it
+1 until they give in and realize that `error` is `exception` with 10x the boilerplate and relent

**Comment by shimmerjs** [comment]
agree, getting this error myself:

```
./crane manifest ubuntu
2018/04/27 10:27:23 Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: exit status 1
```

i have no current auth for docker and shouldn't need any for a public image... looks like other credentials (for a private registry) may be getting used but can't be sure with current error message.

**Comment by ImJasonH** [comment]
FWIW, I'm not able to reproduce this from HEAD.

```
$ bazel run //cmd/crane:crane -- manifest ubuntu
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
...
```

This is with both a valid `~/.docker/config.json` and with one broken by invalid JSON.

**Comment by mattmoor** [comment]
Is this fixed?

**Comment by jonjohnsonjr** [comment]
I think we should do another pass over any of the errors to add some context.
