### ISSUE TITLE
Unauthorized when calling remote.Delete

### ISSUE THREAD

**Issue by jpreese** [google/go-containerregistry#746]
When calling `remote.Delete` I'm getting an authorized error when attempting to delete a remote image that is hosted on Docker Hub. I have used `remote.Get` in the past with a private registry, so I've seen this functionality work when auth is required.

```golang
	image, err := name.ParseReference("plexsystems/busybox:1.25.0", name.WeakValidation)
	if err != nil {
		t.Fatal("parse reference:", err)
	}
	if err := remote.Delete(image, remote.WithAuthFromKeychain(authn.DefaultKeychain)); err != nil {
		t.Fatal("delete image:", err)
	}
```

```text
delete image: DELETE https://index.docker.io/v2/plexsystems/busybox/manifests/1.25.0: UNAUTHORIZED: authentication required; [map[Action:delete Class: Name:plexsystems/busybox Type:repository]]
```

Potentially related, I have `https://index.docker.io/v1/` in my `.docker/config.json`, but do not have a reference to `../v2`. Not sure if that could be the root cause.

**Comment by jonjohnsonjr** [comment]
Unfortunately Docker Hub doesn't allow deleting images via the registry API, for whatever reason, see https://github.com/google/go-containerregistry/issues/136#issuecomment-530543423

**Comment by jpreese** [comment]
ah.. yes. That could be it. Let me see if I can grab the scopes to get a better idea of whats going on, but seems promising.

**Comment by jpreese** [comment]
Glancing at the registry package from distribution, I do see a method for `DELETE`.

https://github.com/docker/distribution/blob/master/registry/handlers/app.go#L930

**Comment by jonjohnsonjr** [comment]
Right, the registry spec has it, and docker/distribution has it, but last I checked _Docker Hub_ had specifically disabled it (see the comment I linked to).

I think there's a potential bug here to fix re: the delete scope, but even if that gets fixed, you'll still hit a 405:

```
$ crane delete -v jonjohnson/test:nonroot

# ...

2020/07/20 15:33:23 DELETE /v2/jonjohnson/test/manifests/latest HTTP/1.1
Host: index.docker.io
User-Agent: go-containerregistry
Authorization: Bearer <REDACTED>
Accept-Encoding: gzip


2020/07/20 15:33:24 <-- 405 https://index.docker.io/v2/jonjohnson/test/manifests/nonroot
2020/07/20 15:33:24 HTTP/1.1 405 Method Not Allowed
Content-Length: 78
Content-Type: application/json
Date: Mon, 20 Jul 2020 22:33:25 GMT
Docker-Distribution-Api-Version: registry/2.0
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}

2020/07/20 15:33:24 deleting jonjohnson/test: DELETE https://index.docker.io/v2/jonjohnson/test/manifests/nonroot: UNSUPPORTED: The operation is unsupported.
```

**Comment by jpreese** [comment]
Oooh, Ok I understand the root issue then. Seems.. strange, but hey that's what we've got. Thanks for the clarification! Will have to figure something else out.

**Comment by jonjohnsonjr** [comment]
It looks like it's possible to hack around (from comments in https://github.com/docker/hub-feedback/issues/1759) but I'm not too keen on implementing that in here, since it doesn't follow the spec.
