### ISSUE TITLE
Rename d8s

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#75]
`d8s` is a placeholder name, we should find a better name before this one sticks.

`imgctl` and `regctl` seem to be the current leaders. Your ideas welcome.

**Comment by dprotaso** [comment]
koutí is greek for box

**Comment by ImJasonH** [comment]
Current leading idea is `crane`, like something you use to move containers around.

Unless anybody has strong objections, after #106 is merged I'll send a PR to rename `d8s` to `crane`.

(I do like `kouti` though, I pronounce it like "cutie" in my head which is nice :smile: )
