### ISSUE TITLE
Not include docker manifest schema v1 in "Accept" header

### ISSUE THREAD

**Issue by knqyf263** [google/go-containerregistry#754]
Can we have an option not to include DockerManifestSchema1 and DockerManifestSchema1Signed in the "Accept" header?
https://github.com/google/go-containerregistry/blob/a84993334b277818146f48584a1ad748e1b53859/pkg/v1/remote/descriptor.go#L82-L83

If a registry supports v1 schema, it replies with v1 schema and occurs an error since go-containerregistry doesn't support it.
https://github.com/google/go-containerregistry/blob/a84993334b277818146f48584a1ad748e1b53859/pkg/v1/remote/descriptor.go#L123-L126

This is the issue we have.
https://github.com/aquasecurity/trivy/issues/591

If you agree to such an option and tell me how to fix it, I can open the PR.

**Comment by jonjohnsonjr** [comment]
Interesting -- we used to have this behavior but would get 404s for schema1 images: https://github.com/google/go-containerregistry/pull/557

I wonder if we can use [content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) or just ordering to indicate which media type we prefer.

**Comment by knqyf263** [comment]
According to his comment, there is an issue with an old version of docker-distribution.
https://github.com/aquasecurity/trivy/issues/591#issuecomment-677765463

**Comment by jonjohnsonjr** [comment]
I would be okay with adding an option that allowed overriding the acceptable media type headers for GET/HEAD requests, but it appears that the linked issue has a workaround.

@sukhinin is this still an issue for you?

**Comment by sukhinin** [comment]
It seems to be an issue with the old version of docker-registry we use, and there is a workaround so we can handle that. 

Nevertheless, it's a little bit strange to include in Accept header something that is not supported. It's probably not worth fixing for our particular case alone, but it could benefit other users.
