### ISSUE TITLE
Add tagged versions to gcr.io

### ISSUE THREAD

**Issue by guyguy333** [google/go-containerregistry#755]
Currently, there is only latest tag available on gcr.io registry for crane. Can you add tagged versions to gcr.io for crane ? 

It would be great to retrieve docker image with a fixed version for more determinism.

Thanks

**Comment by jonjohnsonjr** [comment]
I think all we need to do is update this to add `$TAG_NAME` to our tag flags if it's set:
https://github.com/google/go-containerregistry/blob/3904ad806ff1c30cb12e7d41f78a5702bf7e176d/cloudbuild.yaml#L25-L32

PR's are welcome if this is easy to test for you (i.e. you have a GCP project and can run cloud build easily).

**Comment by max-wittig** [comment]
any plans for this? [kaniko](https://github.com/GoogleContainerTools/kaniko) already has tagged images.
