### ISSUE TITLE
Semantic difference between v1.Image.Layers & serialization format forces people to think

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#76]
`v1.Image.Layers()` returns the layers with the most recent being first.

In contrast, the serialization format ([OCI Image Spec](https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions)) orders layers with the base being first. Similarly in the [config spec](https://github.com/opencontainers/image-spec/blob/master/config.md#properties) `rootfs.diff_ids` are ordered to match the manifest layers.

This difference led to some bugs: [pull/63/commits/bc06df7c5dc16c72b9f1968a3e46a8aedfd4a878](https://github.com/google/go-containerregistry/pull/63/commits/bc06df7c5dc16c72b9f1968a3e46a8aedfd4a878)

I think we should ~~change the OCI Image Spec~~ be consistent and have`v1.Image.Layers()` return the base layer first.

**Comment by dekkagaijin** [comment]
+1 I, too, hate thinking
@jonjohnsonjr

**Comment by mattmoor** [comment]
I can live with that :)
