### ISSUE TITLE
crane auth: Registries must be valid RFC 3986 URI authorities

### ISSUE THREAD

**Issue by wwchen21227** [google/go-containerregistry#766]
It seem crane wasn't supported private registry with IP address. 

Any plan to have it support in future, that will be great for company who were using on prem and without a domain name.

**Comment by jonjohnsonjr** [comment]
I'm surprised I haven't run into this before.

> Any plan to have it support in future

Definitely, this seems like a bug. Happy to review a PR if you have the time to contribute, otherwise I will try to get to this eventually.

**Comment by wwchen21227** [comment]
I dig a little deeper, and found the following function. Because i'm using e.g. https://1.1.1.1:5000, therefore it failed the checking due to Parse prefix the **//**. However i could by-pass that by removing the prefix **https://**, but it fallback to http which failed the push command  to the self-signed registry with the following push error: 

Maybe could have additional checking for // exist before prepend it to the url.

func checkRegistry(name string) error {
	// Per RFC 3986, registries (authorities) are required to be prefixed with "//"
	// url.Host == hostname[:port] == authority
	if url, err := url.Parse("//" + name); err != nil || url.Host != name {
		return NewErrBadName("registries must be valid RFC 3986 URI authorities: %s", name)
	}
	return nil
}

Push error
_net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"_

**Comment by jonjohnsonjr** [comment]
So we first try https and fall back to http -- I suspect we are swallowing whatever the first error is and returning the http error.

If you're using self-signed certs, you're probably running into https://github.com/google/go-containerregistry/issues/211, but we should probably return both errors when we fall back to http to make this easier to debug.

**Comment by AaronLuo3296** [comment]
I also have the issue while trying to login to gcr: 
```
> crane auth login -u oauth2accesstoken -p "${TOKEN}" "https://gcr.io/${GCP_PROJECT_ID}"
Error: registries must be valid RFC 3986 URI authorities: https://gcr.io/my-gcp-project-id
```

**Comment by jonjohnsonjr** [comment]
You probably want:

```
crane auth login -u oauth2accesstoken -p "${TOKEN}" "gcr.io"
```

**Comment by AaronLuo3296** [comment]
> You probably want:
> 
> ```
> crane auth login -u oauth2accesstoken -p "${TOKEN}" "gcr.io"
> ```

I got another error "Error: error storing credentials - err: exit status 1, out: \`add is unimplemented\`" after I change it to "gcr.io". This error message might not be related to crane (I used docker-credential-gcr as docker credential helper).

My gcr login scripts is as follows.

```gcr-login.sh
#!/usr/bin/env bash
set -euo pipefail

docker-credential-gcr config --token-source="env" > /dev/null 2>&1 && docker-credential-gcr configure-docker > /dev/null 2>&1
TOKEN=$(echo "gcr.io" | docker-credential-gcr get | jq -r .Secret)

crane auth login -u oauth2accesstoken -p "${TOKEN}" "gcr.io"
```

Docker login works if I replace the last line to `docker login -u oauth2accesstoken -p "${TOKEN}" "https://gcr.io/${GCP_PROJECT_ID}"`.

Any idea on how to login to gcr with crane?

**Comment by jonjohnsonjr** [comment]
If you're using `docker-credential-gcr`, you don't need to use `crane login`, but you might need to `gcloud login` if your environment doesn't have application default credentials available e.g through the GCE metadata server.

FWIW if you're trying to use `crane login` to make crane work with GCR, you could also just use `gcrane`, which is effectively the same as crane but with docker-credential-gcr built into it.

**Comment by AaronLuo3296** [comment]
> If you're using `docker-credential-gcr`, you don't need to use `crane login`, but you might need to `gcloud login` if your environment doesn't have application default credentials available e.g. through the GCE metadata server.
> 
> FWIW if you're trying to use `crane login` to make crane work with GCR, you could also just use `gcrane`, which is effectively the same as crane but with docker-credential-gcr built into it.

You are right. Once I run `docker-credential-gcr configure-docker`, `crane copy` works without need of `crane login`. Thanks for your help.

**Comment by sanmai-NL** [comment]
@jonjohnsonjr Can you please reopen this? There's still a defect: to spec, repositories needn't be valid RFC 3986 URI authorities.

**Comment by sanmai-NL** [comment]
See also https://github.com/google/go-containerregistry/issues/1729

**Comment by sanmai-NL** [comment]
See also https://github.com/GoogleContainerTools/kaniko/pull/1794
