### ISSUE TITLE
Ability to send a HEAD request to get a manifest's digest

### ISSUE THREAD

**Issue by vito** [google/go-containerregistry#769]
With Docker soon [enforcing pretty strict rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) we're scrambling a bit to prevent Concourse's image polling from grinding to a halt on November 1.

The `registry-image` resource `check` call currently uses `remote.Image` to fetch an image's digest. However this results in a `GET` request, which counts towards the rate limit.

Given that we only need the `sha256:...` digest string, which is available as the `Docker-Content-Digest` response header, would it be possible to add a `go-containerregistry` API which just sends a `HEAD` request and returns the hash? Something like `remote.ImageDigest(name.Reference, ...Option) (v1.Hash, error)`?

Happy to put together a PR if you've got any guidance.

**Comment by jonjohnsonjr** [comment]
Hah, I was just thinking of doing something like this.

Given that we already have `remote.Get` that sends a GET request, I'd propose perhaps `remote.Head`? Maybe also `remote.Stat`. We should have enough from the headers to produce an entire `v1.Descriptor` to make this more generally useful than just a digest, too.

Roughly:

```go
func Head(name.Reference, ...Option) (*v1.Descriptor, error) {
  // send head request, get resp, error handling, etc...
  return &v1.Descriptor{
    MediaType: resp.Header.Get("Content-Type"),
    Size: resp.Header.Get("Content-Length"),
    Digest: resp.Header.Get("Docker-Content-Digest"),
  }, nil
}
```

> Happy to put together a PR if you've got any guidance.

I would gladly review one!

**Comment by jonjohnsonjr** [comment]
cc @ImJasonH @mattmoor please bikeshed naming

**Comment by ImJasonH** [comment]
`remote.Head` sgtm
