### ISSUE TITLE
Support pushing to legacy repository which not support manifest list

### ISSUE THREAD

**Issue by ydcool** [google/go-containerregistry#771]
Crane does not support push image to legacy harbor repository which not support Manifest.List，but using `docker push` will be ok. So could we import a new flag like `--legacy-manifest` to avoid this? 

```
root@vm:/home/dominic# crane cp the-new-registry/the-image:1.0 the-legacy-registry/the-image:1.0 --insecure
2020/09/24 10:27:48 Copying from the-new-registry/the-image:1.0 to the-legacy-registry/the-image:1.0
2020/09/24 10:27:49 existing manifest: sha256:a048003b20060b3c1b9d3e7967d6d6f7d1bd20359adc5c762e6f73d7d9817057
2020/09/24 10:27:49 existing manifest: sha256:52579266cadcac899c8f9bfbae9223e651de2c57354db1b65cfd9cda48c333e7
2020/09/24 10:27:49 existing manifest: sha256:4b14dbf2a0a2db3ce352e56e403432bdfa39bd964714430ef5cd0f734aa11be3
2020/09/24 10:27:49 failed to copy index: PUT http://the-legacy-registry/v2/the-image/manifests/1.0: UNSUPPORTED_MEDIA_TYPE: Manifest.list is not supported.; Manifest.list is not supported.
```

**Comment by jonjohnsonjr** [comment]
There are a couple ways to deal with this:

1. Add a flag to pick a specific platform to copy. https://github.com/google/go-containerregistry/pull/742 adds support for this, but I think the PR got stalled?
2. You can also do this manually by looking at the source image (e.g. with `crane manifest the-new-registry/the-image:1.0`) and copying a specific image, by digest, to the legacy registry. This isn't as nice, but it works today.

**Comment by ydcool** [comment]
@jonjohnsonjr  Thank you for reply! I'll try the both solutions. And the first looks nice and I'll keep eyes on it, thank you.

**Comment by dsbrng25b** [comment]
@ydcool #742 is merged now

**Comment by ydcool** [comment]
> @ydcool #742 is merged now

Nice work , thank you!
