### ISSUE TITLE
Release builds for Windows

### ISSUE THREAD

**Issue by mterrel** [google/go-containerregistry#778]
I'd like to use crane in one of my open source projects, [AdaptJS](https://github.com/unboundedsystems/adapt), which deploys and manages containers and other app infrastructure. But we'd like to ensure Adapt can continue to run on Windows platforms. Would it be possible to build and release official Windows binaries for crane?

I have built crane from source on Windows 10 and so far, I haven't run into any issues. But our users would be downloading the binaries directly onto their own systems and so we'd prefer to have them do that from the official releases.

If you'd like, I'm willing to look into creating a pull request to enable Windows builds.

**Comment by jonjohnsonjr** [comment]
> Would it be possible to build and release official Windows binaries for crane?

I am totally fine with that, I just don't have any experience doing so or ability to test the binaries.

> If you'd like, I'm willing to look into creating a pull request to enable Windows builds.

This would be wonderful, please do! Thanks!
