### ISSUE TITLE
Add default registry option in pkg/name

### ISSUE THREAD

**Issue by hasheddan** [google/go-containerregistry#805]
Currently, if a hostname is omitted in name parsing, registry is [assumed to be `index.docker.io`](https://github.com/google/go-containerregistry/blob/5040388aee43ce720902e720f929de5a56c32a0c/pkg/name/registry.go#L25). It would be nice if this behavior was configurable via an [`Option`](https://github.com/google/go-containerregistry/blob/5040388aee43ce720902e720f929de5a56c32a0c/pkg/name/options.go#L31). This should be able to be introduced without a breaking API change by adding a private field to the `Registry` struct (will also necessitate adding to parent `Reference` / `Tag` / `Digest` / `Repository` as well I believe).

**Comment by jonjohnsonjr** [comment]
I think this is a fine change to make. I would be careful to make sure we aren't assuming `index.docker.io` is the default anywhere else in the project.

In terms of naming, the `name.Option` isn't too important -- something like `WithDefaultRegistry` would be fine.

Exposing this via CLI flags and stuff to consumers of the package is going to be more delicate. I'd love to find a precedent we can steal, but if there isn't one we can just bikeshed on this issue for a while until we achieve consensus.

This issue makes me think we should start worrying about mirroring soon. If I have time I will write up an issue with my thoughts, unless someone else beats me to it.
