### ISSUE TITLE
Unhelpful error message when 403 is returned from the registry

### ISSUE THREAD

**Issue by vagababov** [google/go-containerregistry#825]
Using knative I've tried to deploy an image I have no access to.
The resulting error is far from being helpful

```
'Unable to fetch image "gcr.io/<prj>/<img>": failed
      to resolve image to digest: HEAD https://gcr.io/v2/<prj>/<img>/manifests/latest:
      unsupported status code 403'
```
I'd expect `permission denied` kind of message there, rather than this.

/cc @mattmoor @julz

**Comment by jonjohnsonjr** [comment]
Likely because HEAD does not have a body... sigh.

**Comment by vagababov** [comment]
Yeah... should there be canned responses? e.g. 403 - permission denied is miles better than `403 unrecognized response code`

**Comment by jonjohnsonjr** [comment]
We could change this to `unexpected status code: 403 Forbidden` or something?

**Comment by jonjohnsonjr** [comment]
We could also say something about the fact that it is a HEAD request so there is no error body?

**Comment by vagababov** [comment]
"HEAD URL: 403 permissions denied"
"HEAD URL: 404 not found"
etc would probably be helpful, yes

**Comment by vagababov** [comment]
for 404, I get the same
```
failed to resolve image to digest: HEAD URL: unsupported status code 404.
```

**Comment by jonjohnsonjr** [comment]
In the linked PR...

```
HEAD https://gcr.io/v2/<prj>/<img>/manifests/latest: unsupported status code 403
```

becomes

```
HEAD https://gcr.io/v2/<prj>/<img>/manifests/latest: unsupported status code 403 Forbidden (HEAD responses have no body)
```

@vagababov WDYT?

**Comment by vagababov** [comment]
I'd just avoid `unsupported status code` and instead went for
`status code 403 Forbidden ((HEAD responses have no body or detailed reason)` or along those lines.
