### ISSUE TITLE
Encourage consumers to set a user agent

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#830]
Right now, this is hardcoded to `go-containerregistry`: https://github.com/google/go-containerregistry/blob/d4a7f2f35a2f035df4da27331a91321a863ac158/pkg/v1/remote/transport/useragent.go#L20

This isn't very useful when looking at registry logs, so:

1. Do what [we do in `ko`](https://github.com/google/ko/blob/79beb3b01539afa4c2fdb83e6dce4811c6409447/pkg/commands/resolver.go#L41-L58) to include version info, e.g. `go-containerregistry/0.1.4`.
2. Add a `remote.WithUserAgent` option that appends the supplied string in accordance with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.5.3). Kaniko does something weird here where [they join `UPSTREAM_CLIENT_TYPE` with a comma](https://github.com/GoogleContainerTools/kaniko/blob/2f8d939b3fd667882466baf148699bf6be295647/pkg/executor/push.go#L91), which doesn't look like it follows the grammar, but I also don't really understand the grammar. For example, if `ko` dropped their transport and used this option instead, we would produce `ko/0.6.2 go-containerregistry/0.1.4`.
3. Optionally, ~~annoy consumers via stderr requesting that they set this option. Not sure how reasonable that is -- we could also just~~ document it, put it in all the samples, and slowly send PRs.

Note that consumers currently work around this by just passing something that sets the header via `remote.WithTransport`.

**Comment by ImJasonH** [comment]
+1 on (1) and (2), and -100 on (3). This library is used by a number of tools and we shouldn't spam their users with our request to set a useragent, which doesn't benefit the end user or really the tool author that much either.

But I'm all for `WithUserAgent` and recommending in docs that consumers of the package should set a useragent.

**Comment by jonjohnsonjr** [comment]
ACK. Edited description accordingly.
