### ISSUE TITLE
Unable to use "crane ls" with registry with port

### ISSUE THREAD

**Issue by benmoss** [google/go-containerregistry#840]
```
$ crane ls localhost:5000/foo
2020/11/23 17:52:45 reading tags for localhost:5000: parsing repo "localhost:5000": repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: localhost:5000
```

Related to #762

**Comment by jonjohnsonjr** [comment]
Sorry about that :/ this package definitely needs some love.

cc @hasheddan -- you were poking around here recently if you're interested in taking a look.

**Comment by hasheddan** [comment]
@jonjohnsonjr yep I can take this one 👍

**Comment by jonjohnsonjr** [comment]
I can't reproduce this:

```
$ crane ls localhost:1338/ubuntu
latest
```

**Comment by coryrc** [comment]
Same here, no reproduce.

**Comment by benmoss** [comment]
I think I misidentified the issue, I only see this error when I do `crane ls localhost:5000`.
