### ISSUE TITLE
We should disallow accessing the config through LayerBy*

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#87]
Especially now that we have `v1.Layer`, it is awkward to reason about `ConfigFile` as a layer.

This has been the source of multiple bugs, we should just eliminate this and require that `LayerBy*` be used exclusively to access something from `Layers()`.

The history here is that since the config is stored as a blob in the registry, we had incorporated it into concepts like `blob_set()` (but not `fs_layers()`!)...

**Comment by jonjohnsonjr** [comment]
Should we just close this? https://github.com/google/go-containerregistry/pull/285 😆
