### ISSUE TITLE
Doesn't GCR support pagination?

### ISSUE THREAD

**Issue by nakabonne** [google/go-containerregistry#897]
Hi, thanks for making the quite useful package. I love this one.

The `v1/remote` looks to implements the client that always uses the Link header value when proceeding through results linearly.
https://github.com/google/go-containerregistry/blob/3584fa0df9f1bd51a7cf559c97126a20212fa7cd/pkg/v1/remote/list.go#L52-L59

Wheres the `v1/google` package seems to not have any option to do that.

https://github.com/google/go-containerregistry/blob/3584fa0df9f1bd51a7cf559c97126a20212fa7cd/pkg/v1/google/list.go#L79-L106

It means Google Container Registry doesn't implement it, or just this client hasn't implemented it yet? Sorry if this sounds dumb, but it would be great if you could let me know.

**Comment by jonjohnsonjr** [comment]
> Hi, thanks for making the quite useful package. I love this one.

Thanks! I really appreciate it.

> It means Google Container Registry doesn't implement it, or just this client hasn't implemented it yet?

GCR doesn't implement this pagination, mostly for historical reasons. If you look at the response, GCR adds a bunch of non-standard fields, [including a map from image digest to some metadata](https://github.com/google/go-containerregistry/blob/d1ffc8b82b61910dbcabfb07fdc0b6cb96fb3d66/pkg/v1/google/list.go#L188). This makes the response a lot more useful, but also makes pagination troublesome...

It's hard to know if clients actually care about _only_ tags, or if they also care about that manifest map. We could paginate just the tags and not populate the manifest map for paginated requests, but that would break clients that care about the manifest map.

In theory, we could paginate both the manifest map and the tags list, but that would make the http handler a lot more complicated, so we just settled on returning the whole response until someone complains.

Out of curiosity, what would you expect to happen for a paginated request? Also, why would it be useful to you?

> Sorry if this sounds dumb, but it would be great if you could let me know.

Not dumb at all, it's a very reasonable question.

**Comment by nakabonne** [comment]
>In theory, we could paginate both the manifest map and the tags list, but that would make the http handler a lot more complicated

That makes sense!

>Out of curiosity, what would you expect to happen for a paginated request? Also, why would it be useful to you?

As you may know, I currently implement a program that periodically calls `google.List()` to determine the latest tag. Then I'm now worried about that the result could be quite a large size if there are a lot of tags. The document of [Docker Registry API V2](https://docs.docker.com/registry/spec/api/#listing-image-tags) also says:

>For repositories with a large number of tags, this response may be quite large. If such a response is expected, one should use the pagination.
>
>https://docs.docker.com/registry/spec/api/#listing-image-tags

I haven't actually measured the response size to see if it is realistic, but if possible, I would like to avoid a single response size that is unexpected.

(Btw, my problem will be solved, if there is another way to detect the latest tags for a specific image other than listing all tags)
