### ISSUE TITLE
crane digest does not work with specific platform on v1 schema

### ISSUE THREAD

**Issue by dvob** [google/go-containerregistry#906]
crane digest does not work with the platform option on v1 schema images. It returns the following error:
```
unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
```

Code to reproduce:
```
crane.Digest("nginx:1.10.0", crane.WithPlatform(&v1.Platform{OS: "linux", Architecture: "amd64"}))
```

Context:
I use crane to sync images from external registries to a local registry. For that I call `crane.Digest(src)` and `crane.Digest(dst)` and if the values differ I do a `crane.Copy` and after the copy trigger some pipelines. I used to use `Copy` and `Digest` without the platform option which worked for v1 schema but this way it did not work for indexes which contain images with non-distributable layers.

**Comment by jonjohnsonjr** [comment]
> crane digest does not work with the platform option on v1 schema images. It returns the following error:

Definitely a bug, thanks for the fix.

> For that I call crane.Digest(src) and crane.Digest(dst) and if the values differ I do a crane.Copy 

It would not be completely unreasonable for us to do these `HEAD` checks within `crane.Copy` (or even `remote.Write`).

> but this way it did not work for indexes which contain images with non-distributable layers.

I'd like to know more about this. Do you need something like [`--allow-nondistributable-artifacts`](https://docs.docker.com/engine/reference/commandline/dockerd/)?

**Comment by dvob** [comment]
> It would not be completely unreasonable for us to do these `HEAD` checks within `crane.Copy` (or even `remote.Write`) ourselves, if you have any interest in sending a PR.

Isn't there already such a check in `remote.Write`? I do the check that I no if `crane.Copy` will change something and depending on that start further processing after the `Copy`. Since `crane.Copy` only does return err i have to do it somewhere else either way I guess.

> I'd like to know more about this. Do you need something like --allow-nondistributable-artifacts?

My main problem was that `crane.Copy` did not work for images with non-distributable layers (see #741).  The platform option is good enough for me since I only need the `amd64/linux` images.

**Comment by jonjohnsonjr** [comment]
> Isn't there already such a check in remote.Write?

Only for blobs. We will always PUT the manifest.

> I do the check that I no if crane.Copy will change something and depending on that start further processing after the Copy.

Ah, I can see this being frustrating. We'd need some way to indicate whether the write was skipped or not. We could expose something like:
```go
ok, err := crane.MaybeCopy(src, dst)
if err != nil {
  return err
}
if ok {
  // Image was actually written
} else {
  // Skipped
}
```

But we can punt on that for now, since nobody is asking for it.

> (see #741)

Ah yeah, I forgot about that issue.
