### ISSUE TITLE
Add crane to homebrew?

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#914]
My limited understanding of homebrew is that you can either add a formula to homebrew/core or maintain a tap.

It seems like less over head if we can get into core (we don't have to maintain a separate repo), but from [their guidelines](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff):

> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.
> 
> We frown on authors submitting their own work unless it is very popular.

I'm not sure if `[g]crane` is "very popular", but it seems like it's more likely to be accepted if _someone else_ submits it...

Also, we need a homepage.

**Comment by chenrui333** [comment]
Filed a PR for `crane`

**Comment by ImJasonH** [comment]
It looks like goreleaser doesn't support publishing releases to homebrew-core, it wants us to own the tap.

<img width="797" alt="Screen Shot 2021-01-18 at 9 20 52 PM" src="https://user-images.githubusercontent.com/210737/104979784-1d54cb80-59d3-11eb-9719-37e03b22daed.png">

(https://goreleaser.com/customization/homebrew/)

**Comment by chenrui333** [comment]
yeah, goreleaser would only do the tap release.

**Comment by chenrui333** [comment]
After the homebrew PR review and merge, you can do `https://github.com/mislav/bump-homebrew-formula-action` as part of the github action release flow.

**Comment by ImJasonH** [comment]
`brew install crane` works now, thanks for the PR @chenrui333 🎉 

I'll keep this issue open to track automatically updating Homebrew when we do a release.

**Comment by jonjohnsonjr** [comment]
https://github.com/Homebrew/homebrew-core/pull/69310/files#diff-2fde799ce0afb71c82d5f35c03725c6c02b0b86bb65250eb91e23b017c27d835R17

I worry a bit that this test will hit dockerhub rate limits, but I'm not sure how often that test gets run?
