### ISSUE TITLE
Proposal: annotation to signal a rebase seam

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#937]
`crane rebase`, and other tools that want to rebase images, like [kpack's `rebase`](https://github.com/pivotal/kpack/blob/master/cmd/rebase/main.go), take as input information about what image had previously provided the base layers, and what new image should provide them in the rebased image.

As an alternative to explicit inputs, tooling to produce rebaseable images (buildpacks, kaniko, crane, etc.) could annotate images with this information, so that rebase tooling can infer the rebase seam. **edit:** [`pack rebase`](https://buildpacks.io/docs/concepts/operations/rebase/) seems to be able to rebase without explicit inputs.

To accomplish this, images would need to note what the original base image was by digest, and the image-by-tag where new base images should be found. This information can be encoded into one image reference, since image references can include both the tag and the digest.

As an example, consider an image based on an OS image, `ubuntu:latest`. To be able to rebase the image to pick up updates to the `ubuntu:latest` image, we'd signal that seam in an annotation, e.g.,

```
some.annotation.base-image: ubuntu:latest@sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
```

This annotation effectively states, "I am currently based on `ubuntu@sha256:...` (the digest portion of the ref), and if you'd like to rebase me in the future, by default, rebase me on the image tagged `ubuntu:latest` (the tag portion of the ref).

Rebase tooling would be able to look for this annotation, resolve the image-by-tag value to its digest, and if it's different than the digest in the annotation, perform a rebase, and annotate the new image with the new base image-by-tag-and-digest accordingly. If the base image hasn't changed, no rebase is necessary and no new image will be produced.

In any case, explicitly requesting a rebase with `--original` or `--new_base` would override the annotation and perform the requested rebase, and annotate resulting images accordingly. If `--original` is provided and it conflicts with `base-image`-by-digest, this should be considered an error. If `--new_base` is provided, it will be used instead of the image-by-tag portion of the `base-image`.

I'd like to get some consensus about this proposal before proceeding, since to be successful it will require some buy-in and adoption from image building and rebase tooling to really make this successful.

# Open Questions

* Annotation naming: `some.annotation.base-image` is catchy but ultimately not very descriptive. 😄  Perhaps this should be an RFC to the OCI spec to make this a [pre-defined annotation key](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys), perhaps `org.opencontainers.image.base-image`?

(This issue derives from discussion in https://github.com/google/go-containerregistry/issues/659)

**Comment by jonjohnsonjr** [comment]
Not exactly sure what I want to do, but to capture my thoughts for posterity... 

`ubuntu:latest@sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715` serves three purposes:

1. `ubuntu` locates the registry and repository from which we pulled the base image.
2. `sha256:...` serves as an immutable reference to exactly which base image we pulled.
3. `latest` identifies the tag, which we might want to use as a default for updating the base image to a newer digest (if changed).

One drawback of this is that `ubuntu` and `latest` aren't content-addressable, so the output of the build would be dependent on the repo and tag where your base image is stored. That's a shame.

It would be nice if we could get the same benefit without sacrificing the location-independence of our artifacts. So perhaps the annotation could be two forms. The first, above, the second just the digest:

```
sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
```

This loses the ability to auto-update to follow a tag, but at least the artifact remains location-independent. It might make sense for this to be a separate annotation, but spec language could just call out the two forms of values.

re: `some.annotation.base-image`, I don't love the hyphen, but that's not a huge deal.

**Comment by ImJasonH** [comment]
New proposal, two annotations:

```
something.something.base.digest: sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
something.something.base.ref.name: ubuntu:latest
```

This puts all content-addressed information in one annotation, and all other information in the other.

There's no guarantee that the image referenced by `base.ref.name` exists now, or ever did, or that it ever pointed to the digest in `base.digest` (there never was anyway).

**Comment by jonjohnsonjr** [comment]
> two annotations

I think one annotation would be nicer, aesthetically, but this seems like a good middle ground. This also avoids some issues around client support and semantics of `foo:tag@digest` style references.

Just to head off the question: how should I represent a base image that doesn't have a tag?\

```
something.something.base.digest: sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
something.something.base.ref.name: ubuntu
```

or

```
something.something.base.digest: sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
something.something.base.ref.name: ubuntu@sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
```

if the latter, does it make sense to just drop the first annotation?

```
something.something.base.ref.name: ubuntu@sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
```

I think it probably makes sense to explicitly call out the first one being preferable because client implementations can always map one annotation to one meaning; however, I can see some confusion around defaulting. Does the first one mean `ubuntu:latest` and the tag was just omitted? How likely is it that we'll get this wrong with name parsing and defaulting?

Let's think through the semantics of:

1. just `digest` present.
2. just `ref.name` present
3. both present
4. interpretations of `ref.name`, also does how we interpret it depend on if the other annotation is present?
    1. `ubuntu`
    2. `ubuntu:latest`
    3. `ubuntu:latest@sha256:...`
    4. `ubuntu@sha256...`

What is the expected behavior if `ref.name` is not found (tag or digest), if the digest doesn't exist in the `ref.name` repo, etc...

**Comment by ImJasonH** [comment]
> Just to head off the question: how should I represent a base image that doesn't have a tag?

If you're using an untagged image as a base, that's fine, but you aren't the target audience, and will not be able to take advantage of rebasing tools, because there's no signal of where to look for new bases. In that case, you're welcome to set `base.digest` to signal to...something... that you're based on an image with that digest, and maybe you can figure out where to find new versions of that image...somehow.

Is there a use case for untagged base images you're interested in supporting?

`base.ref.name` including a digest feels like a bad idea to me, because it duplicates information from `base.digest` at best, and causes confusion if they differ. I think I'd prefer to say that `base.ref.name` must be parseable as an image reference by tag, and not include a digest.

> 1. just `digest` present

This is informational. You've decided to signal that you're based on something with that digest, but I don't know of anything useful we can do with that information in a vacuum.

> 2. just `ref.name` present

Likewise, this is informational. You've signalled that you're based on an image that was at one point tagged `ubuntu:latest`, but absent information about what specific layers of yours represent that image, it's impossible to know how to rebase you.

> 3. both present

The golden zone. The world feels good, like nice warm socks.

> interpretations of ref.name, also does how we interpret it depend on if the other annotation is present?
> i. ubuntu

Assume this means `ubuntu:latest`, or (my preference) document the expectation that the value of `base.ref.name` must explicitly includes the tag.

> ii. ubuntu:latest

Warm socks. 🧦 🤗 

> iii. ubuntu:latest@sha256:...
> iv. ubuntu@sha256:...

I'd rather not support either of these as valid at all, but if we do, document the expectation that the digest is ignored, and `:latest` is assumed. It's not great, but that's why I don't like supporting it at all.

**Comment by jonjohnsonjr** [comment]
> Is there a use case for untagged base images you're interested in supporting?

Imagine I want to rebase an existing image onto an completely unrelated new base image. I think it's not unreasonable for some other person to use a non-tagged base image without any regard for my ability to rebase it, but I should be able to come along afterwards and rebase it regardless... does that make sense?

> but I don't know of anything useful we can do with that information in a vacuum

I think this is useful for people who want to have reproducible builds that are independent of where their base images were stored e.g. if you want to run `ko` but can't talk to GCR for \<insert any valid reason\>, you might mirror distroless into a different registry, or maybe your base image doesn't come from a registry but a local image store (https://github.com/google/ko/issues/295).

**Comment by ImJasonH** [comment]
> Imagine I want to rebase an existing image onto an completely unrelated new base image.

You can do this today, without this annotation. You just need to figure out somehow somewhere what the digest of the base image was. Technically you could make up any image you want so long as the layer digests match your base image, `crane rebase` doesn't care. I don't think we need to optimize for this use case.

> if you want to run ko but can't talk to GCR for <insert any valid reason>, you might mirror distroless into a different registry

`defaultBaseImage: my.registry.dev/distroless/static:nonroot` in my `.ko.yaml`, problem solved.

I can't stop anybody from annotating their images however they want, I can only tell them how I'll be able to do anything useful with it. Maybe over time Magic Rebasing™️ will learn more tricks and be able to make anything useful out of a base image digest annotation by itself. For now, I'd just like images to signal what they're based on (both specifically, and in general) and rebase them slightly more easily.

**Comment by dlorenc** [comment]
I have a couple questions:

- Where would this annotation live? At the "image" level or at the "layer" level?
- If at the image level:
  - we still have to actually find the "seam", it's not trivial to figure out which layer switches from base to derived.
  - there can be multiple "seams" - a base image itself can have a base image. Is that handled, or would the "seam" for that base image be expected to be found, well, in that base image?

**Comment by ImJasonH** [comment]
> * Where would this annotation live? At the "image" level or at the "layer" level?

I had been imagining it at the image level. I'm open to other ideas though, if annotating the layer makes more sense.

If we annotated layers instead, it would effectively be annotating, "[this layer] is the topmost layer of my base image, which I got from [image-by-tag]", and we could avoid having to annotate the base image-by-digest at all. Jon probably doesn't like this idea. 😄 

The [OCI spec for common annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md) doesn't mention any specific examples of layer annotations, but they're Descriptors, so it's possible.

> * If at the image level:
>   
>   * we still have to actually find the "seam", it's not trivial to figure out which layer switches from base to derived.

It's not trivial, but it's also not terribly hard. `crane rebase` compares the layers in `original` and `old_base` to make sure they're the same, and immediately above that is the seam. If they're not the same, the `old_base` value must be incorrect and rebasing isn't possible.

>   * there can be multiple "seams" - a base image itself can have a base image. Is that handled, or would the "seam" for that base image be expected to be found, well, in that base image?

Yeah, I had toyed with having multiple seams annotated, but I think it's easier to describe it as "this is _my_ base image", and if that base image also has a base, it can annotate it, and so on.

In a world where rebasing is common and automated, an OS image update could trigger an image rebase, which would trigger other rebases, etc. This feels safer to me than having a top-layer image watching for updates to multiple base images.

Annotating layers instead makes it a bit easier to signal multiple seams, which is kinda nice. 🤔

**Comment by dlorenc** [comment]
OK, I think I'm convinced on just having one seam.

I do still sort of prefer putting it on the layer itself, just to save the calculation/computation to try to find the seam. Not a huge/strong preference either way though.

**Comment by ImJasonH** [comment]
Thinking about how it would work to annotate the label, if we go that way, I wonder if it's easier to annotate the layer _above_ the seam, i.e., the bottom-most new layer above the base. That would make it easier to, for example:

```go
mutate.Append(base, mutate.Addendum{
  Layer: newLayer,
  Annotations: map[string]string{
    "blah.blah.based-on": "my-base-image",
  },
})
```

...instead of having to append a layer, then modify the layer descriptor under it to mark it as the top of the base. I don't know if it's worth compromising the cleanliness of the design just to make appending easier for ggcr though. Other clients in other languages might be just fine with modifying lower layers.

**Comment by jonjohnsonjr** [comment]
Having _something_ on the layer seems reasonable to me for a couple reasons:
1. Re-fetching the original base might be slow or impossible.
2. Clients might put the digest of an index here, which would make finding the right platform a bit involved (though not impossible, if we assume the config file is set properly).

I'm a little worried about having multiple seams. The UX kind of falls over if you want to rebase a multi-seam image because you have to specify which one.

Also, I'm not sure about the logic/validation for what we would do if you rebase a lower-level base image and then want to rebase the higher-level base image later. Example:

`widget-server:1` is based on `ubuntu:1`, which is based on `debian:1`

If I want to rebase `ubuntu:1` -- that's easy, we should now have:

`widget-server:2` is based on `ubuntu:2`, which is based on `debian:2`

But what happens if I rebase `debian:2` now?

`widget-server:3` is based on `ubuntu:2`, which is based on `debian:3`

If later I want to rebase `ubuntu:2`, we're in a weird spot. I would check the layers in `ubuntu:2` and see that they _don't_ match what I have in `widget-server:3`. Maybe you just `--force` it, but I'd want to think through this more.

I think it makes sense for an image to have a single base image with an additional layer annotation just for convenience. I'm not sure if putting it on layer[n] or layer[n+1] makes more sense. Leaning towards layer[n+1] because the "based-on" relationship is easy to understanding.

**Comment by jonjohnsonjr** [comment]
We should consider https://github.com/google/go-containerregistry/issues/753

**Comment by ImJasonH** [comment]
Closing in favor of https://github.com/opencontainers/image-spec/issues/821

If that lands, I'll open issues here to use the annotations.

If it doesn't land, I'll reopen this to make a ggcr-specific annotation 😄
