### ISSUE TITLE
zsh: command not found: gcrane

### ISSUE THREAD

**Issue by tiny-tinker** [google/go-containerregistry#941]
I'm on MacOS Catalina v 10.15.7 and after installing go, I ran this command to install gcrane:
```bash
GO111MODULE=on go get -u github.com/google/go-containerregistry/cmd/gcrane
```
Then, I attempted to copy an image to my project's repo, but got this result:

```bash
jo@supapro Downloads % gcrane cp docker.io/hello-world:latest gcr.io/jos-box/hello-world:latest
zsh: command not found: gcrane
```

Re-running the `go get` command produces no output. There was output on the original install, but I closed the terminal in an attempt to troubleshoot. 

(I was able to get around this by running the command in the cloud shell, but thought I'd post here in case anyone else ran into it)

**Comment by jonjohnsonjr** [comment]
What version of go are you using? I know the go tool recently changed to make `go install` work better with go modules, which might explain this: https://golang.org/doc/go1.16#go-command

If that's the case, we need to update the documentation.

The other explanation might be that go is installing the binary somewhere that is not on your `PATH`. If you look under:

```
# Default
ls $(go env GOPATH)/bin

#  If you over-rode this with GOBIN
ls $(go env GOBIN)
```

And see `gcrane`, you just need to [add that to your path](https://golang.org/doc/code).
