### ISSUE TITLE
Add `WithProgress` option for `remote.Write`

### ISSUE THREAD

**Issue by tydra-wang** [google/go-containerregistry#952]
As the title.

**Comment by DennisDenuto** [comment]
+1

I would find this also useful for `remote.MultiWrite`

**Comment by DennisDenuto** [comment]
Would it be correct to assume that `WithProgress` would work very similar to how it works for `tarball.WriteToFile`? 

https://github.com/google/go-containerregistry/blob/77421d5c5906d1a567ed0193787cac3db8b4a4e4/pkg/v1/progress.go#L21

i.e. `MultiWrite` would send progress information to the `v1.Update` channel?

**Comment by ImJasonH** [comment]
Yeah, I'd like to have them behave similarly. The difference with `MultiWrite` is that there are multiple things having progress made, does it make sense for the update to include information about which things are progressing how?

MultiWrite already doesn't support streaming layers, so we can know ahead of time how many total bytes we anticipate writing. In theory we'd like to support streaming layers though, in which case the `Total` might not be known ahead-of-time.

I think we've also talked about it taking a chan of things to write, so the update's `Total` could increase as new things were requested. I don't know if that breaks any assumptions.

**Comment by DennisDenuto** [comment]
Thanks that is pretty helpful!

I would like to volunteer to work on this (This Friday will probably be the day I work on it). 

wrt MultiWrite and streaming layers: 
I will calculate the total bytes ahead-of-time before any blobs are uploaded (when / if streaming layers are supported, the implementation can be changed)

**Comment by ImJasonH** [comment]
Sounds good @DennisDenuto, thanks!

Let us know if you have any questions or problems, we'd be happy to help.

**Comment by jonjohnsonjr** [comment]
> The difference with MultiWrite is that there are multiple things having progress made, does it make sense for the update to include information about which things are progressing how?

The equivalent in [docker land](https://github.com/moby/moby/blob/40d9e2aff130b42ba0f83d5238b9b53184c8ab3b/pkg/progress/progress.go#L9) partitions upload progress by ID. I think that's usually layers.

I'm honestly not sure what to do here. A lot of the time, I want a single progress bar, and that's an easy model to program against... but folks might want to display more complex things than a single bar (e.g. per-layer progress), but making that change actually seems nontrivial, and I'm not sure how much it makes sense for MultiWrite (there can be hundreds of layers)...

> I think we've also talked about it taking a chan of things to write, so the update's Total could increase as new things were requested. I don't know if that breaks any assumptions.

Yes, for tarball we take a channel: https://github.com/google/go-containerregistry/blob/efb2d62d93a7705315b841d0544cb5b13565ff2a/pkg/v1/tarball/write.go#L396

I imagine we want a uniform API.

**Comment by ImJasonH** [comment]
I think we should start with `WithProgress(chan<- v1.Update)` for now. In the future if we decide we want a more granular progress option we can add `WithGranularProgress(chan<- v1.GranularUpdate)` or whatever makes sense then.

It sounds like that's sufficient for @DennisDenuto 's immediate use case, and I imagine it'll be good enough for most users at least for now.

**Comment by ImJasonH** [comment]
There are some notable differences between tarball and remote wrt writing layer contents, that we should be careful to handle:

- `remote.Write` retries failed uploads, so a progress update might go back and forth if a partial upload fails and then succeeds on retry.
- `remote.Write` can also mount layer contents, and performs an existence check before writing layers, so a whole layer might get "uploaded" without involving any `Write`s.

I think we should try to get this landed in `remote.Write` first with tests, then extending it to `remote.MultiWrite` should be relatively straightforward.

**Comment by DennisDenuto** [comment]
Thanks for raising these differences.

I was thinking of writing an [Example test](https://github.com/google/go-containerregistry/blob/51f01e739161bf35d663240a8ca404777d7d9378/pkg/v1/tarball/progress_test.go#L29) similar to what `tarball.Write` does. But I'm leaning towards having tests with assertions for remote Writing, and having cases for the above might be a better approach.
