### ISSUE TITLE
Make MustParseReference only accept consts

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#963]
The [recently added `MustParseReference`](https://github.com/google/go-containerregistry/issue/962) takes a string, and returns its successfully parsed `name.Reference` if it's successfully parsed, and panics otherwise. This is mainly useful for tests, where a value is known/expected to be valid at authoring time.

What if `MustParseReference` only accepted const strings, to make it clearer that it's not intended to accept user-defined values.

```
type stringConst string

func MustParseReference(s stringConst) Reference {
  ...
}
```

Since the `stringConst` type isn't exported, external callers can't make one themselves. Go's type coercion is able to automatically convert a string-typed const to the correct type.

[Playground link](https://play.golang.org/p/cYcrTjpdxAI)

This would prevent people from using `MustParseReference` with dynamically-constructed strings, and wouldn't stop them from using it in test setups like `const ref = name.MustParseReference("valid")`.

**Comment by jonjohnsonjr** [comment]
@dekkagaijin what do you think about this

**Comment by jonjohnsonjr** [comment]
You're an odd duck.

**Comment by dekkagaijin** [comment]
A compile-time check is nice and `constString` is descriptive enough to get the point across. I'd like to see what the usability is like in practice, and I'll have concrete examples if I'm opinionated, but this change would be safe to reverse anyway if so
