### ISSUE TITLE
Arch Package

### ISSUE THREAD

**Issue by ulrichSchreiner** [google/go-containerregistry#968]
hi,

just wanted you to know that i created an ARCH package 

https://aur.archlinux.org/packages/go-crane-bin/

so users of arch linux can simply do a `yay -S go-crane-bin` to install crane/gcrane

**Comment by jonjohnsonjr** [comment]
Awesome! Thanks!

Want to send a PR to add it to the [install instructions](https://github.com/google/go-containerregistry/tree/main/cmd/crane#installation)?

**Comment by ulrichSchreiner** [comment]
PR created

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/go-containerregistry/pull/969
