### ISSUE TITLE
`crane label` and `crane annotate`

### ISSUE THREAD

**Issue by ImJasonH** [google/go-containerregistry#974]
```
crane label my-image \
  --label a=b \
  --label b=c
  --new_ref=my-image:labeled
```

The `--new_ref` flag is optional, and if omitted, `crane label` would tag over `my-image`.

This would necessitate a new `mutate.Labels(v1.Image)` method to mirror `mutate.Annotations(v1.Image)` being proposed in https://github.com/google/go-containerregistry/pull/960

This would add or overwrite existing labels/annotations only, and wouldn't facilitate unsetting existing values. I'm not sure whether that's a priority. Perhaps we could interpret `--label a=` to mean "unset", or `--label a=<unset>` as a sentinel value. Setting the value to an empty string and unsetting the value are notably separate things.

**Comment by jonjohnsonjr** [comment]
Something dumb like `--unable a`?

**Comment by jonjohnsonjr** [comment]
One concern I have is an explosion of top-level commands that do various things. Maybe not a huge deal, but small mutations like this might be lump-able under `crane mutate` or something?

**Comment by jonjohnsonjr** [comment]
>  This would necessitate a new `mutate.Labels(v1.Image)` method

We can do this today with `mutate.Config`.

**Comment by ImJasonH** [comment]
> Something dumb like `--unlabel a`?

Love it.

> One concern I have is an explosion of top-level commands that do various things. Maybe not a huge deal, but small mutations like this might be lump-able under `crane mutate` or something?

I'm fine that. Were you imagining `crane mutate` as a subcommand for other subcommands (`crane mutate label` and `crane mutate annotations`) or as a place to do a bunch of mutations (`crane mutate --label a=b --annotation b=c`) ?

> We can do this today with `mutate.Config`.

Yep, good call.

**Comment by jonjohnsonjr** [comment]
> Were you imagining crane mutate as a subcommand for other subcommands

Yeah this one seems easiest but there's a lot of interesting things we could do with a generic mutate command.

**Comment by otaviof** [comment]
Hello 👋🏼 !

What do you think about a mixed approach? I like the ability to `crane mutate ...` labels and annotations at once. So, my suggestion is the following:

```sh
# add or remove labels, using "label" and "unlabel" sub-commands
crane label image a=b c=d
crane unlabel image a c
```

The same goes for annotations, with:

```sh
crane annotate image e=f
crane unannotate image e
```

As for `mutate`, I think we should let users inform the behavior by inspecting the actual flags, as in `--[un]label` and `--[un]annotate`. For instance:

```sh
# setting both labels and annotations with "mutate" sub-command:
crane mutate --label a=b --label c=d --annotate e=f
crane mutate --unlabel a --unlabel c --unannotate e
```

**Comment by ImJasonH** [comment]
I think I'd prefer to have one way to label/annotate, to reduce code/docs/tests needed.

A CLI that can set multiple labels can also be used to set one, if you want to do it in multiple calls for whatever reason.

**Comment by ImJasonH** [comment]
Closing in favor of the older #281
