### ISSUE TITLE
Log messages get sent to STDOUT, polluting command output like 'crane config'

### ISSUE THREAD

**Issue by jcmcken** [google/go-containerregistry#976]
If I run ``crane config`` on an image name from a public image (no auth required), STDOUT contains a mix of log messages and JSON output, making it awkward to pipe to other shell tools. For example:

```
$ crane config foo.example.com/someimage
2021/03/29 13:03:49 No matching credentials were found for "foo.example.com/someimage", falling back on anonymous
{"architecture": "amd64", ...etc...}
```

The 'No matching credentials' log message is not sent to STDERR, but STDOUT, so I can't pipe this output to ``jq`` without stripping out log messages. This makes the command a little brittle, since I don't necessarily know how many of these log messages might get printed.

**Comment by ImJasonH** [comment]
This seems to work for me:

```
$ crane config ubuntu | jq
2021/03/29 10:28:17 No matching credentials were found for "index.docker.io/library/ubuntu", falling back on anonymous
{
  "architecture": "amd64",
  "config": {
    "Hostname": "",
    "Domainname": "",
...
```

Seems like `No matching credentials` logs are going to stderr:

```
$ crane config ubuntu > /dev/null
2021/03/29 10:29:38 No matching credentials were found for "index.docker.io/library/ubuntu", falling back on anonymous
```

Is it possible you're on an older version of `crane`? Upgrading might fix this.

**Comment by jcmcken** [comment]
Sorry, looks like the problem is Docker not ``crane``.

**Comment by jonjohnsonjr** [comment]
To be fair, I have really wanted to get rid of that warning for a while. It's unnecessary most of the time!
