### ISSUE TITLE
GCrane fails to list all tags available on Quay.io registries

### ISSUE THREAD

**Issue by davidalger** [google/go-containerregistry#984]
Run the following two commands and compare the output. The former returns all 147 tags, the latter only 50 randomly ordered tags.

* `docker run --rm gcr.io/go-containerregistry/crane ls quay.io/prometheus/prometheus`
* `docker run --rm gcr.io/go-containerregistry/gcrane ls quay.io/prometheus/prometheus`

The verbose output reveals crane is passing `n=1000` to the Quay API and GCrane is not. Both appear to possibly be making paginated calls, although apparently not successfully.

**Comment by jonjohnsonjr** [comment]
I think I'm OK with this behavior. `gcrane` is specifically for google container registries, whereas `crane` is meant to be a generic client.

There are a couple ways to fix this, but I'm not sure if it's worth fixing...

**Comment by jonjohnsonjr** [comment]
> we're using gcrane to copy images from Quay to GCR so that Quay outages won't affect the node-exporter daemonset we have running. So we have a daily Gitlab job which basically runs gcrane ls on a set of images, and then copies all tags to us.gcr.io/myimagemirror/quay.io/image/name allowing us to then update chart values to use our registry and/or use a mutating webhook controller for enforcement.

I see. In theory we could make `gcrane cp -r` work for this use case, but I'm happy to just fix `gcrane ls` to do pagination.

> I haven't tested it, but I have a sneaking suspicion that the same issue may exist in crane for registries which have more than 1k tags.

The `crane` implementation does pagination as you might expect. The `gcrane` implementation doesn't, because GCR doesn't do pagination, but it just so happens to return the tags you would expect anyway.

**Comment by ImJasonH** [comment]
> `gcrane` implements a superset of crane commands and it's ls provides enriched output (even when working with non-GCR repositories, it's useful when mirroring images). An ls shouldn't simply be redacted just because I listed a non-GCR registry.

Could we solve this by having `crane` provide the features you need from `gcrane`?

We could add `crane ls --full` or something, that outputs the full names of images, instead of just tags.

I think in general we should discourage (maybe even disallow?) using `gcrane` against anything but GCR.

**Comment by davidalger** [comment]
> We could add crane ls --full or something, that outputs the full names of images, instead of just tags.

This would be useful, and would would resolve the primary reason I'm using `gcrane` for mirroring images rather than using `crane` (which is to have the full names in the response, making it simpler to mirror the images regardless of where they come from given docker.io images can be referenced by 4 different less-than-qualified names).

It would also resolve the issue I have to workaround when mirroring images from one GCR repository to another, as `crane` doesn't include the image digests in the `ls` output as `gcrane` does. Could be useful to add an `--no-digest` flag to `gcrane ls` but that's outside the scope of this request.

What using `crane` doesn't do is provide authentication with GCR "for free" when running with Compute Metadata or GKE Metadata available. Although at this point, I'm already building my own docker image with `gcrane`, `docker-credential-gcr` and a `/root/.docker/config.json` because `gcrane` fails to authenticate with GCR when doing `gcrane cp quay.io/some/image gcr.io/project/some/image` (it seems to get stuck attempting to do anonymous auth with both instead of only with Quay).

I'm happy to build my own `crane` images to add the credential helper as well if I could use it to fetch full image names with the tags as one can with `gcrane`.

I do still believe it would be better to fix pagination for `ls`, but blocking use with other registries would at least prevent discrepancies from tripping others up. If this is the route taken, at least consider emitting some sort of messaging pointing the user to `crane` for non-GCR registries.

**Comment by jonjohnsonjr** [comment]
> Could be useful to add an --no-digest flag to gcrane ls but that's outside the scope of this request.

I've been just doing `... | grep - v @ | xargs ...` for that, but I do understand the mismatch can be frustrating.

> because gcrane fails to authenticate with GCR when doing gcrane cp quay.io/some/image gcr.io/project/some/image 

This worked for me, so that's surprising. Might be worth filing a separate bug.

> if I could use it to fetch full image names with the tags as one can with gcrane.

I've thought about this as a cross-cutting flag. It could be useful for `crane digest` as well.

We can solve a lot of this to make what you're doing slightly easier, or we could try to tackle the actual problem directly... you want to copy all the tags from SRC to DST, yeah?

To borrow from [`docker pull`](https://docs.docker.com/engine/reference/commandline/pull/), we add a `-all-tags` flag that could work with both `crane` and `gcrane`:

```
# Copy all the tags from SRC to DST.
crane cp --all-tags $SRC $DST
```

```
# Copy all the tags from SRC
gcrane cp --all-tags $SRC $DST
```

With `gcrane`, we currently have a way to copy a single image or the entire repository (including recursively) with all the non-tagged images as well.

 I'm wondering what the expected behavior for this would be:

```
gcrane cp --all-tags -r $SRC $DST
```

Recurse, but only copy the tags? Does that sound reasonable?

**Comment by davidalger** [comment]
> you want to copy all the tags from SRC to DST

In most cases, that is correct. There are edge cases where the upstream registry has literally thousands of commit sha tags, presumably for nightly or dev builds, and which we have no desire to copy.

Basically my job script (one per image) looks like this at the moment:

```
  script:
    - IMAGE_LIST="$(gcrane ls "${IMAGE_NAME}" | sed 's/^index\.docker\.io/docker.io/' | perl -ne "${FILTER_EXPR} and print")"
    - echo "${IMAGE_LIST}"
    - test "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" && exit
    - for IMAGE in ${IMAGE_LIST}; do gcrane cp "${IMAGE}" "${GCR_REGISTRY}/${IMAGE}"; done
```

By default `FILTER_EXPR='/:(?!(@sha256:)?[a-z0-9]{64}).+$/'` (likely a bit more complex than is required, but I like to be specific) to exclude digests using a negative lookahead on the filter.

In cases where the upstream has thousands of tags for each git commit, it's replaced with `'/:(v?([0-9]+\.?){1,3}|latest)$/'` to only copy `X.Y.Z`, `vX.Y.Z` and `latest` tags.

> # Copy all the tags from SRC to DST.
> crane cp --all-tags $SRC $DST

I do like this a lot. It would make copy jobs for 99% of image mirroring operations very simple and easy to accomplish (with rare exceptions such as the one case I noted above where there are literally thousands of images we wouldn't want to copy)


With gcrane, we currently have a way to copy a single image or the entire repository (including recursively) with all the non-tagged images as well.

> I'm wondering what the expected behavior for this would be:
> 
> gcrane cp --all-tags -r $SRC $DST
> 
> Recurse, but only copy the tags? Does that sound reasonable?

Could they be mutually exclusive? Having `--all-tags` change the behavior of `-r` to only copy tags might be confusing, but I can see the use-case. When used in combination with `-r` an `--only-tags` flag might make the most sense.

**Comment by jonjohnsonjr** [comment]
I've edited your response to be more legible, as the `#` comment got interpreted as a heading.

> There are edge cases where the upstream registry has literally thousands of commit sha tags, presumably for nightly or dev builds, and which we have no desire to copy.

Ok, so we could merge https://github.com/google/go-containerregistry/pull/985 for that or introduce some flag that prints the whole ref for `crane ls`, e.g. `crane ls --full-ref`?

> When used in combination with `-r` an `--only-tags` flag might make the most sense.

Sure, so:

```
# Copy single image
crane cp SRC DST

# Copy all tags from SRC
crane cp --all-tags SRC DST

# Copy single image
gcrane cp SRC DST

# Copy all tags from SRC
gcrane cp --all-tags SRC DST

# Copy everything, recursively
gcrane cp -r SRC DST

# Return an error, maybe someone can complain.
gcrane cp -r --all-tags SRC DST
```

I think I'm ok with this, as it is the least surprising and doesn't get into any grey areas. I'm fine with returning an error and being convinced later that we should allow both flags.

**Comment by davidalger** [comment]
> Ok, so we could merge #985 for that or introduce some flag that prints the whole ref for crane ls, e.g. crane ls --full-ref?

I would vote for merging this now, maybe keep the other for some point in the future, especially seeing as how the PR for the fix is both already put together and as was pointed out [in your comment here](https://github.com/google/go-containerregistry/pull/985) it does resolve something for an intentionally existing behavior.

Regarding all-tags and recursive copies, I like it. Appreciate the dialog.

**Comment by jonjohnsonjr** [comment]
> Appreciate the dialog.

No problem, thanks for reporting the issue.

Closing this because I believe the original issue is resolved, but feel free to file a follow-up issue around `crane cp --all-tags` if it's something you would use.
