### ISSUE TITLE
Crane: No possibility to delete tag / untag only

### ISSUE THREAD

**Issue by MoeRT09** [google/go-containerregistry#999]
Hello,

maybe I am I am missing something here, but at the moment, it does not seem to be possibile to "delete a tag" only without removing the underlaying image. Issuing `crane delete <image>:<tag>@<digest>` will remove all other tags based on the same digest as well so this is unsuitable.

A use case for this scenario is, in GitLab CI, after I build an Image, I tag it with the commit SHA using Kaniko. After Verifying the image, I use Crane to tag it "latest" (or whatever tag is specified). After that, I want to be able to simply remove the tag referring to the commit SHA, so that repository does not get garbaged with those "intermediary" images. Untagging those images would allow the garbage collector on our GitLab server (which runs once per week) to clean up those images not referred to by  a tag anymore (images still having a reference like "latest" tag will be kept of course).
Right now, issuing `crane delete ...` will remove the tag "latest" as well. `crane tag <image>:<tag> ""` does not work unfortunately.

Untagging was mentioned in #136  once. From my understanding untagging in this way is against the spec but maybe there is some workaround.

**Comment by jonjohnsonjr** [comment]
Support for "untagging" is probably not widespread yet. I know this works for GCR, but the spec was only recently updated to add tag deletion: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#deleting-tags

`crane delete` will just delete whatever ref you specify, so to untag, you'd just do:

```
crane delete <image>:<tag>
```

The `<image>:<tag>@<digest>` syntax is somewhat ambiguous, and it's unclear exactly what we should do, so in most cases  we just ignore the tag.

`crane delete <image>:<tag>@<digest>` is equivalent to `crane delete <image>@<digest>`.

Does that help?

**Comment by MoeRT09** [comment]
@jonjohnsonjr thank your for the tip. This is the first thing I tried but issuing the command in the form `crane delete <image>:<tag>` resulted in the following error:
```
Error: DELETE <image>/manifests/<tag>: DIGEST_INVALID: provided digest did not match uploaded content
```
This is why I appended the digest later on. So this is probably an issue with the GitLab container registry not supporting tag deletion for now. So I should open an issue at GitLab then.

**Comment by jonjohnsonjr** [comment]
> So this is probably an issue with the GitLab container registry not supporting tag deletion for now. So I should open an issue at GitLab then.

Sounds reasonable! The 1.0 spec is being voted on right now, if they need some justification for the change: https://github.com/opencontainers/distribution-spec/pull/274

In the past, the GitLab folks have been pretty good about landing fixes to their registry, so I have high hopes.

**Comment by fgreinacher** [comment]
> @jonjohnsonjr thank your for the tip. This is the first thing I tried but issuing the command in the form `crane delete <image>:<tag>` resulted in the following error:
> 
> ```
> Error: DELETE <image>/manifests/<tag>: DIGEST_INVALID: provided digest did not match uploaded content
> ```
> 
> This is why I appended the digest later on. So this is probably an issue with the GitLab container registry not supporting tag deletion for now. So I should open an issue at GitLab then.

@MoeRT09 Have you already opened a GitLab issue?

**Comment by MoeRT09** [comment]
> I'm running into this as well - anyone talk to gitlab on this one yet?

Unfortunately no, I gave up because of the amount of information that is required to file a feature request at GitLab.
